Repository elastic/apm-server, pull requests merged in 2018-04, with the labels that each got.

#787 [6.x] handle large integers in json (#783)
  decoder/decoder.go
  decoder/decoder_test.go
  docs/data/intake-api/generated/transaction/minimal_span.json
  processor/error/event.go
  processor/transaction/package_tests/TestProcessTransactionMinimalSpan.approved.json
  tests/data/valid/transaction/minimal_span.json
  tests/loader/loader.go
  utility/data_fetcher.go
  utility/map_str_enhancer.go
Labels: backport

#798 [6.x] Clarify semantics of request.url.raw (#785)
  docs/spec/request.json
  processor/error/schema.go
  processor/transaction/schema.go
Labels: backport

#802 [6.x] target for clean and docs together (make docs without removing '/build' first behaves in a unexpected way) (#624)
  Makefile
Labels: backport

#804 Change bucket size of open source dashboards to 1 minute (or greater) for 6.0 and above
  _meta/kibana/6/dashboard/apm-dashboards.json
Labels: bug, v6.3

#808 [6.x] Fixes #532 - Limit the resolution of the charts to 1 minute to prevent users from zooming in past the resolution of the data
  _meta/kibana/6/dashboard/apm-dashboards.json
Labels: backport

#812 [6.x] update description used in packaging (#807)
  Makefile
Labels: backport

#822 [6.x] reduce ExtractIP allocations (#821)
  utility/ip.go
  utility/ip_test.go
Labels: backport

#780 [6.x] limit number of new connections to accept simultaneously (#751)
  _meta/beat.reference.yml
  apm-server.reference.yml
  beater/config.go
  beater/server.go
  beater/server_test.go
  vendor/golang.org/x/net/netutil/listen.go
  vendor/vendor.json
Labels: backport

#824 [6.2] Update beats framework to 1122568
  Makefile
  NOTICE.txt
  _beats/dev-tools/generate_notice.py
  _beats/dev-tools/set_docs_version
  _beats/vendor/vendor.json
  script/generate_notice_overrides.py
  script/update_beats.sh
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics_common.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/metrics_other.go
  vendor/github.com/elastic/beats/libbeat/common/cli/cli.go
  vendor/github.com/elastic/beats/libbeat/common/file/file_other.go
  vendor/github.com/elastic/beats/libbeat/common/file/file_windows.go
  vendor/github.com/elastic/beats/libbeat/metric/system/process/process.go
  vendor/vendor.json
Labels: backport, v6.2

#746 Early return to caller.
  beater/beater.go
  beater/handlers.go
  beater/onboarding.go
  beater/onboarding_test.go
  beater/pub.go
  beater/pub_test.go
  beater/server.go
  beater/server_test.go
  processor/error/benchmark_test.go
  processor/error/package_tests/json_schema_test.go
  processor/error/package_tests/processor_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/error/processor_test.go
  processor/healthcheck/processor.go
  processor/healthcheck/processor_test.go
  processor/processor.go
  processor/sourcemap/package_tests/json_schema_test.go
  processor/sourcemap/package_tests/processor_test.go
  processor/sourcemap/payload.go
  processor/sourcemap/payload_test.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/benchmark_test.go
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/package_tests/processor_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/processor_test.go
  script/output_data/output_data.go
  tests/approvals.go
  tests/fields.go
Labels: review

#823 [6.x] listen on unix domain socket (#768)
  CHANGELOG.asciidoc
  _meta/beat.reference.yml
  apm-server.reference.yml
  beater/beater.go
  beater/beater_test.go
  beater/server_test.go
  docs/guide/index.asciidoc
  model/system.go
  model/system_test.go
Labels: [zube]: Backlog, backport

#817 Documents how to handle 503s
  docs/troubleshooting.asciidoc
Labels: docs, review

#825 [6.x] Early return to caller. (#746)
  beater/beater.go
  beater/handlers.go
  beater/onboarding.go
  beater/onboarding_test.go
  beater/pub.go
  beater/pub_test.go
  beater/server.go
  beater/server_test.go
  processor/error/benchmark_test.go
  processor/error/package_tests/json_schema_test.go
  processor/error/package_tests/processor_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/error/processor_test.go
  processor/healthcheck/processor.go
  processor/healthcheck/processor_test.go
  processor/processor.go
  processor/sourcemap/package_tests/json_schema_test.go
  processor/sourcemap/package_tests/processor_test.go
  processor/sourcemap/payload.go
  processor/sourcemap/payload_test.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/benchmark_test.go
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/package_tests/processor_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/processor_test.go
  script/output_data/output_data.go
  tests/approvals.go
  tests/fields.go
Labels: backport

#827 [6.x] makes timestamp optional (#819)
  CHANGELOG.asciidoc
  docs/data/intake-api/generated/error/minimal_payload_exception.json
  docs/data/intake-api/generated/error/minimal_payload_log.json
  docs/data/intake-api/generated/transaction/minimal_payload.json
  docs/spec/errors/error.json
  docs/spec/transactions/transaction.json
  processor/error/event.go
  processor/error/package_tests/TestProcessErrorMinimalPayloadException.approved.json
  processor/error/package_tests/TestProcessErrorMinimalPayloadLog.approved.json
  processor/error/package_tests/processor_test.go
  processor/error/schema.go
  processor/transaction/event.go
  processor/transaction/package_tests/TestProcessTransactionAugmented.approved.json
  processor/transaction/package_tests/TestProcessTransactionAugmentedMerge.approved.json
  processor/transaction/package_tests/TestProcessTransactionFrontend.approved.json
  processor/transaction/package_tests/TestProcessTransactionMinimalPayload.approved.json
  processor/transaction/package_tests/processor_test.go
  processor/transaction/schema.go
  tests/data/invalid/error/no_timestamp.json
  tests/data/invalid/transaction/no_timestamp.json
  tests/data/valid/error/minimal_payload_exception.json
  tests/data/valid/error/minimal_payload_log.json
  tests/data/valid/transaction/augmented_payload_frontend.json
  tests/data/valid/transaction/augmented_payload_frontend_no_context.json
  tests/data/valid/transaction/frontend.json
  tests/data/valid/transaction/minimal_payload.json
  tests/json_schema_test.go
  utility/data_fetcher.go
  utility/data_fetcher_test.go
Labels: backport

#829 [6.x] Fix link to beats platform reference (#614)
  docs/setting-up-and-running.asciidoc
Labels: backport

#820 Update docs copied from beats.
  Makefile
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/keystore.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/tls.asciidoc
  docs/copied-from-beats/security/user-access.asciidoc
  docs/copied-from-beats/shared-directory-layout.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-env-vars.asciidoc
  docs/copied-from-beats/shared-path-config.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/setting-up-and-running.asciidoc
  script/copy-docs.py
Labels: [zube]: Ready, docs

#832 [6.x] Log additional request info in error case. (#811)
  beater/handlers.go
Labels: backport

#843 [6.x] Update docs copied from beats. (#820)
  Makefile
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/keystore.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/tls.asciidoc
  docs/copied-from-beats/security/user-access.asciidoc
  docs/copied-from-beats/shared-directory-layout.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-env-vars.asciidoc
  docs/copied-from-beats/shared-path-config.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/setting-up-and-running.asciidoc
  script/copy-docs.py
Labels: backport

#847 [6.x] Allow system tests to be run from any directory (#835) | Allow other tests to be run from any directory (#837)
  tests/system/apmserver.py
  tests/system/test_integration.py
  tests/system/test_requests.py
Labels: backport

#846 [6.x] Remove flaky test for goroutine consumers. (#845)
  beater/pub_test.go
Labels: backport

#853 [6.x] Update monitoring data to changed handling. (#852)
  processor/error/payload.go
  processor/error/processor.go
  processor/sourcemap/processor.go
  processor/transaction/payload.go
  processor/transaction/processor.go
Labels: backport

#851 Backport script for updating beats docs.
  Makefile
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/getting-help.asciidoc
  docs/copied-from-beats/keystore.asciidoc
  docs/copied-from-beats/loggingconfig.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/shared-directory-layout.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-env-vars.asciidoc
  docs/copied-from-beats/shared-path-config.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/setting-up-and-running.asciidoc
  script/copy-docs.py
Labels: [zube]: In Progress, docs, review

#864 [6.x] Expose apm-server metrics via expvar (#861)
  beater/handlers.go
  processor/error/processor.go
  processor/sourcemap/processor.go
  processor/transaction/processor.go
Labels: backport

#869 [6.x] Add monitoring for agents and all response codes and reasons (#862)
  CHANGELOG.asciidoc
  beater/handlers.go
  beater/handlers_test.go
  processor/error/processor.go
  processor/transaction/processor.go
Labels: backport

#870 Add metrics for stacktrace.
  processor/error/payload.go
  processor/transaction/payload.go
Labels: review

#871 [6.x] Monitor req sizes (#868)
  decoder/decoder.go
Labels: backport

#875 [6.x] Move common problems section up (#826)
  docs/common-problems.asciidoc
  docs/troubleshooting.asciidoc
Labels: backport

#876 [6.x] docs/guide: Added docs (#770)
  docs/guide/index.asciidoc
Labels: backport

#889 [6.3] do not start the HTTP server twice in tests (#879)
  beater/server_test.go
Labels: backport

#890 [6.x] rotate changelog (#877)
  CHANGELOG.asciidoc
Labels: backport

#888 [6.x] do not start the HTTP server twice in tests (#879)
  beater/server_test.go
Labels: backport

#891 [6.x] listen on default port 8200 if unspecified (#886)
  CHANGELOG.asciidoc
  beater/beater.go
  beater/config.go
  beater/server_test.go
Labels: backport
