Repository elastic/apm-server, pull requests merged in 2018-06, with the labels that each got.

#989 [6.2] Update beats framework to 4fb9286
  NOTICE.txt
  vendor/github.com/elastic/beats/libbeat/dashboards/importer.go
  vendor/github.com/elastic/beats/libbeat/publisher/pipeline/processor.go
  vendor/vendor.json
Labels: [zube]: In Review

#983 document curator tips useful for APM data
  docs/common-problems.asciidoc
  docs/index.asciidoc
Labels: [zube]: In Progress

#1002 [6.x] Add clarification on 503 error due to full disk (#999)
  docs/common-problems.asciidoc
Labels: backport

#1004 [6.x] Move section on APM Server to the APM Server docs folder (#998)
  docs/guide/index.asciidoc
  docs/overview.asciidoc
Labels: backport

#976 [6.3] clarify root cause for 403 errors, fixes #973 (#974)
  beater/handlers.go
  beater/handlers_test.go
Labels: backport

#995 [6.3] document curator tips useful for APM data, fixes #954 (#983)
  docs/common-problems.asciidoc
  docs/index.asciidoc
Labels: backport

#1003 [6.3] Add clarification on 503 error due to full disk (#999)
  docs/common-problems.asciidoc
Labels: backport

#1005 [6.3] Move section on APM Server to the APM Server docs folder (#998)
  docs/guide/index.asciidoc
  docs/overview.asciidoc
Labels: backport

#915 store navigationTiming marks as scaled floats
  docs/data/elasticsearch/transaction.json
  docs/data/intake-api/generated/transaction/payload.json
  docs/fields.asciidoc
  include/fields.go
  processor/transaction/_meta/fields.yml
  processor/transaction/package_tests/TestProcessTransactionFull.approved.json
  processor/transaction/package_tests/json_schema_test.go
  tests/data/valid/transaction/payload.json
  tests/fields.go
  tests/system/test_integration.py
  tests/system/transaction.approved.json
Labels: [zube]: In Review

#1023 Add change log entry for #972
  CHANGELOG.asciidoc
Labels: [zube]: In Review

#1022 Add release notes
  CHANGELOG.asciidoc
  docs/index.asciidoc
  docs/release-notes.asciidoc
Labels: [zube]: In Review, docs

#859 Prevent automatically inheriting configs from beats. (#578)
  CHANGELOG.asciidoc
  _beats/libbeat/_meta/config.reference.yml
  _beats/libbeat/_meta/config.yml
  _meta/beat.reference.yml
  _meta/beat.yml
  apm-server.reference.yml
  apm-server.yml
  script/update_beats.sh
Labels: [zube]: In Review, backport

#1028 [6.x] Update beats framework to 575c675
  NOTICE.txt
  _beats/libbeat/docs/version.asciidoc
  vendor/vendor.json
Labels: backport

#1027 [6.3] Update beats framework to 4de74bd
  NOTICE.txt
  _beats/libbeat/docs/version.asciidoc
  _beats/libbeat/scripts/Makefile
  _beats/testing/environments/Makefile
  _beats/testing/environments/args.yml
  _beats/testing/environments/latest.yml
  _beats/vendor/vendor.json
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/libbeat/autodiscover/autodiscover.go
  vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go
  vendor/github.com/elastic/beats/libbeat/common/docker/client.go
  vendor/github.com/elastic/beats/libbeat/common/docker/watcher.go
  vendor/github.com/elastic/beats/libbeat/common/file/helper_other.go
  vendor/github.com/elastic/beats/libbeat/dashboards/importer.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/extract_field.go
  vendor/github.com/elastic/beats/libbeat/publisher/queue/spool/spool.go
  vendor/vendor.json
Labels: backport

#1024 Move generated schemas into sub-folders
  processor/error/generated/schema/payload.go
  processor/error/package_tests/json_schema_test.go
  processor/error/processor.go
  processor/sourcemap/generated/schema/payload.go
  processor/sourcemap/package_tests/json_schema_test.go
  processor/sourcemap/processor.go
  processor/transaction/generated/schema/payload.go
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/processor.go
  script/inline_schemas/inline_schemas.go
Labels: [zube]: In Progress

#1045 catch errors when starting the beater
  beater/beater_test.go
  beater/server_test.go
Labels: [zube]: In Review

#1043 [6.x] Move "Why is APM Server a separate component?" under "Overview"." (#1040)
  docs/overview.asciidoc
Labels: [zube]: In Review, backport

#1044 [6.3] Move "Why is APM Server a separate component?" under "Overview"." (#1040)
  docs/overview.asciidoc
Labels: [zube]: In Review, backport

#1051 update go-structform dependency
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/go-structform/CHANGELOG.md
  vendor/github.com/elastic/go-structform/json/visitor.go
  vendor/vendor.json
Labels: [zube]: In Review

#1000 Metrics
  CHANGELOG.asciidoc
  Makefile
  _meta/beat.yml
  apm-server.yml
  beater/beater_test.go
  beater/config.go
  beater/handlers.go
  docs/data/elasticsearch/metric.json
  docs/data/intake-api/generated/metric/payload.json
  docs/fields.asciidoc
  docs/spec/metrics/metric.json
  docs/spec/metrics/payload.json
  docs/spec/metrics/sample.json
  include/fields.go
  processor/metric/_meta/fields.yml
  processor/metric/counter.go
  processor/metric/event.go
  processor/metric/gauge.go
  processor/metric/generated/schema/payload.go
  processor/metric/package_tests/TestProcessMetric.approved.json
  processor/metric/package_tests/TestProcessMetricMinimal.approved.json
  processor/metric/package_tests/TestProcessMetricMultipleSamples.approved.json
  processor/metric/package_tests/TestProcessMetricNull.approved.json
  processor/metric/package_tests/json_schema_test.go
  processor/metric/package_tests/processor_test.go
  processor/metric/payload.go
  processor/metric/payload_test.go
  processor/metric/processor.go
  processor/metric/summary.go
  script/inline_schemas/inline_schemas.go
  testdata/metric/minimal.json
  testdata/metric/multiple-samples.json
  testdata/metric/null.json
  testdata/metric/payload.json
  tests/json_schema.go
  tests/json_schema_test.go
  tests/set.go
  tests/set_test.go
  tests/system/apmserver.py
  tests/system/test_integration.py
  utility/data_fetcher.go
  utility/data_fetcher_test.go
  utility/map_str_enhancer.go
Labels: [zube]: In Progress
