Repository elastic/apm-server, pull requests merged in 2018-02, with the labels that each got.

#661 Resolve attrs in docs example.
  docs/copied-from-beats/loggingconfig.asciidoc
Labels: backport, docs, review

#660 docs: fix missing app -> service renames
  docs/guide/index.asciidoc
Labels: bug, v6.2

#645 [6.x] Send sourcemap docs to own index by default. (#582)
  CHANGELOG.asciidoc
  _meta/beat.reference.yml
  _meta/beat.yml
  apm-server.reference.yml
  apm-server.yml
  beater/beater.go
  beater/beater_test.go
  beater/config.go
  beater/config_test.go
  beater/handlers.go
  beater/onboarding_test.go
  beater/server_test.go
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
Labels: backport

#617 [6.2] Update docs copied from beats to use variables. (#591)
  docs/copied-from-beats/getting-help.asciidoc
  docs/index.asciidoc
  docs/troubleshooting.asciidoc
Labels: backport

#653 Remove duplicate changelog entry.
  CHANGELOG.asciidoc
Labels: v6.2

#662 [6.x] docs: fix missing app -> service renames (#660)
  docs/guide/index.asciidoc
Labels: backport

#663 [6.2] docs: fix missing app -> service renames (#660)
  docs/guide/index.asciidoc
Labels: backport

#648 Add note to docs for dashboard loading.
  docs/copied-from-beats/dashboardsconfig.asciidoc
Labels: docs

#679 [6.x] Enrich processing with additional data generated within the APM Server. (#393)
  Makefile
  _meta/fields.common.yml
  beater/beater_test.go
  beater/handlers.go
  beater/handlers_test.go
  beater/server_test.go
  decoder/decoder.go
  decoder/decoder_test.go
  docs/data/intake-api/generated/error/frontend_app.e2e-bundle.json
  docs/data/intake-api/generated/error/frontend_app.e2e-bundle.min.json
  docs/data/intake-api/generated/error/minimal_process.json
  docs/data/intake-api/generated/error/null_values.json
  docs/data/intake-api/generated/transaction/frontend.json
  docs/data/intake-api/generated/transaction/minimal_process.json
  docs/data/intake-api/generated/transaction/null_values.json
  docs/data/intake-api/generated/transaction/process_null.json
  docs/data/intake-api/generated/transaction/system_null.json
  docs/fields.asciidoc
  model/system.go
  model/system_test.go
  processor/error/benchmark_test.go
  processor/error/event.go
  processor/error/package_tests/TestProcessErrorAugmentedIP.approved.json
  processor/error/package_tests/TestProcessErrorAugmentedUserAgentAndIP.approved.json
  processor/error/package_tests/TestProcessErrorUserAgentAndIP.approved.json
  processor/error/package_tests/fields_test.go
  processor/error/package_tests/processor_test.go
  processor/error/payload.go
  processor/sourcemap/decoder.go
  processor/sourcemap/decoder_test.go
  processor/sourcemap/package_tests/processor_test.go
  processor/sourcemap/payload_test.go
  processor/sourcemap/processor_test.go
  processor/transaction/benchmark_test.go
  processor/transaction/event.go
  processor/transaction/package_tests/TestProcessTransactionAugmented.approved.json
  processor/transaction/package_tests/TestProcessTransactionAugmentedIP.approved.json
  processor/transaction/package_tests/TestProcessTransactionAugmentedMerge.approved.json
  processor/transaction/package_tests/TestProcessTransactionIP.approved.json
  processor/transaction/package_tests/fields_test.go
  processor/transaction/package_tests/processor_test.go
  processor/transaction/payload.go
  script/output_data/output_data.go
  tests/approvals.go
  tests/common.go
  tests/common_test.go
  tests/data/valid/error/augmented_payload_backend.json
  tests/data/valid/error/augmented_payload_frontend.json
  tests/data/valid/transaction/augmented_payload_backend.json
  tests/data/valid/transaction/augmented_payload_frontend.json
  tests/data/valid/transaction/augmented_payload_frontend_no_context.json
  tests/fields.go
  tests/json_schema.go
  tests/loader/loader.go
  tests/system/test_integration.py
  utility/common.go
  utility/common_test.go
  utility/ip.go
  utility/ip_test.go
Labels: backport

#681 [6.x] accept application/json; charset=UTF-8 as contentType in the request, fixes #676
  decoder/decoder.go
  decoder/decoder_test.go
Labels: backport

#682 [6.x] "Rotate" changelog and add new entry
  CHANGELOG.asciidoc
Labels: backport

#684 [6.x] Update changelog
  CHANGELOG.asciidoc
Labels: backport

#641 Use type integer instead of number where applicable
  CHANGELOG.asciidoc
  docs/spec/context.json
  docs/spec/errors/error.json
  docs/spec/process.json
  docs/spec/stacktrace_frame.json
  docs/spec/transactions/span.json
  docs/spec/transactions/transaction.json
  docs/spec/user.json
  processor/error/schema.go
  processor/transaction/schema.go
  tests/json_schema_test.go
Labels: enhancement

#652 [6.x] Keep original values when transforming. (#647)
  CHANGELOG.asciidoc
  docs/data/intake-api/generated/error/frontend.json
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  processor/error/package_tests/TestProcessErrorFrontend.approved.json
  processor/error/package_tests/TestProcessErrorFrontendMinifiedSmap.approved.json
  tests/data/valid/error/frontend.json
Labels: backport

#690 [6.x] Use type integer instead of number where applicable
  CHANGELOG.asciidoc
  docs/spec/context.json
  docs/spec/errors/error.json
  docs/spec/process.json
  docs/spec/stacktrace_frame.json
  docs/spec/transactions/span.json
  docs/spec/transactions/transaction.json
  docs/spec/user.json
  processor/error/schema.go
  processor/transaction/schema.go
  tests/json_schema_test.go
Labels: backport, v6.3

#692 [6.x] Set array item types to string
  CHANGELOG.asciidoc
  docs/spec/process.json
  docs/spec/stacktrace_frame.json
  processor/error/schema.go
  processor/transaction/schema.go
Labels: backport, v6.3
