Repository elastic/apm-server, pull requests merged in 2018-03, with the labels that each got.

#705 [6.x] Add a config option to opt out from data augmentation, fixes #694
  CHANGELOG.asciidoc
  _meta/beat.reference.yml
  apm-server.reference.yml
  beater/beater_test.go
  beater/config.go
  beater/handlers.go
  decoder/decoder.go
  decoder/decoder_test.go
Labels: backport

#697 [6.x] Refactor Event creation and enhancer utility method. (#673)
  model/process.go
  model/service.go
  model/stacktrace_frame.go
  model/system.go
  processor/error/event.go
  processor/error/package_tests/TestProcessErrorNullValues.approved.json
  processor/error/payload.go
  processor/error/processor.go
  processor/processor.go
  processor/sourcemap/payload.go
  processor/sourcemap/processor.go
  processor/transaction/event.go
  processor/transaction/event_test.go
  processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/span.go
  utility/doc_mapping.go
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
Labels: backport

#713 [6.x] Add integration test for ES documents. (#709)
  docs/data/elasticsearch/error.json
  docs/data/intake-api/generated/error/payload.json
  docs/data/intake-api/generated/transaction/payload.json
  processor/error/package_tests/TestProcessErrorFull.approved.json
  processor/transaction/package_tests/TestProcessTransactionFull.approved.json
  tests/data/valid/error/payload.json
  tests/data/valid/transaction/payload.json
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/test_integration.py
  tests/system/transaction.approved.json
Labels: backport

#716 [6.x] Enhance utility methods and get rid of normalization processor in beats.
  beater/pub.go
  docs/data/elasticsearch/transaction.json
  docs/data/intake-api/generated/transaction/payload.json
  model/context.go
  model/context_test.go
  model/process.go
  model/process_test.go
  model/service.go
  model/service_test.go
  model/system.go
  processor/error/event.go
  processor/error/package_tests/TestProcessErrorNullValues.approved.json
  processor/error/payload.go
  processor/transaction/event.go
  processor/transaction/package_tests/TestProcessTransactionFrontend.approved.json
  processor/transaction/package_tests/TestProcessTransactionFull.approved.json
  processor/transaction/package_tests/TestProcessTransactionNullValues.approved.json
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/payload.go
  processor/transaction/span_context.go
  processor/transaction/span_context_test.go
  tests/data/valid/transaction/payload.json
  tests/system/transaction.approved.json
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
  utility/rfc3399decoder.go
Labels: backport

#725 [6.x] Remove enum for error.log.level (#712)
  CHANGELOG.asciidoc
  docs/data/intake-api/generated/error/payload.json
  docs/spec/errors/error.json
  processor/error/package_tests/TestProcessErrorFull.approved.json
  processor/error/schema.go
  tests/data/valid/error/payload.json
  tests/system/error.approved.json
Labels: backport

#726 [6.x] Push transactions and errors to different indices, fixes #279
  _meta/beat.yml
  apm-server.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
Labels: backport

#729 [6.x] graceful shutdown of apm server (#704)
  CHANGELOG.asciidoc
  beater/beater.go
  beater/beater_test.go
  beater/pub.go
  beater/server.go
  beater/server_test.go
Labels: backport

#730 Use manual decoding for performance improvements.
  CHANGELOG.asciidoc
  NOTICE.txt
  _meta/fields.common.yml
  beater/handlers.go
  decoder/decoder.go
  decoder/decoder_test.go
  docs/fields.asciidoc
  model/context.go
  model/context_test.go
  model/process.go
  model/process_test.go
  model/service.go
  model/service_test.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/system.go
  model/system_test.go
  model/user.go
  model/user_test.go
  processor/error/event.go
  processor/error/event_test.go
  processor/error/package_tests/fields_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/healthcheck/processor.go
  processor/processor.go
  processor/sourcemap/payload.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/event.go
  processor/transaction/event_test.go
  processor/transaction/package_tests/fields_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/span.go
  processor/transaction/span_test.go
  tests/fields.go
  tests/system/test_integration.py
  utility/data_fetcher.go
  utility/data_fetcher_test.go
  utility/rfc3399decoder.go
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/vendor.json
Labels: review, v6.3

#744 [6.x] Use manual decoding for performance improvements. (#730)
  CHANGELOG.asciidoc
  NOTICE.txt
  _meta/fields.common.yml
  beater/handlers.go
  decoder/decoder.go
  decoder/decoder_test.go
  docs/fields.asciidoc
  model/context.go
  model/context_test.go
  model/process.go
  model/process_test.go
  model/service.go
  model/service_test.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/system.go
  model/system_test.go
  model/user.go
  model/user_test.go
  processor/error/event.go
  processor/error/event_test.go
  processor/error/package_tests/fields_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/healthcheck/processor.go
  processor/processor.go
  processor/sourcemap/payload.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/event.go
  processor/transaction/event_test.go
  processor/transaction/package_tests/fields_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/span.go
  processor/transaction/span_test.go
  tests/fields.go
  tests/system/test_integration.py
  utility/data_fetcher.go
  utility/data_fetcher_test.go
  utility/rfc3399decoder.go
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/vendor.json
Labels: backport

#749 [6.x] update/sync configuration defaults (#748)
  CHANGELOG.asciidoc
  _meta/beat.reference.yml
  apm-server.reference.yml
  beater/config.go
Labels: backport

#753 [6.x] repair config test (#752)
  CHANGELOG.asciidoc
  beater/beater_test.go
Labels: backport

#755 [6.x] generally available (#658)
  README.md
Labels: backport

#756 [6.x] Add security note (#700)
  _meta/fields.common.yml
  docs/fields.asciidoc
  utility/ip.go
Labels: backport

#758 [6.x] Add note to docs for dashboard loading. (#648) Describe that `setup.dashboards.index` only works for >= 6.0 closes #519
  docs/copied-from-beats/dashboardsconfig.asciidoc
Labels: backport

#759 [6.x] Resolve attrs in docs example. (#661)
  docs/copied-from-beats/loggingconfig.asciidoc
Labels: backport

#760 [6.x] more security documentation (#546) * add X-Pack configuration documentation * expand on TLS configuration
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/tls.asciidoc
  docs/copied-from-beats/security/user-access.asciidoc
  docs/security.asciidoc
Labels: backport

#761 Removing duplicate entries from Changelog.
  CHANGELOG.asciidoc
Labels: review, v6.3

#767 [6.x] use libbeat version (#659)
  Makefile
  beater/server.go
Labels: backport

#765 Enable index pattern in config for separating indices.
  _meta/beat.yml
  apm-server.yml
Labels: bug, review, v6.3

#769 [6.x] Change index pattern description. (#765)
  _meta/beat.yml
  apm-server.yml
Labels: backport

#772 [6.x] Improve sourcemap docs (#771)
  docs/sourcemaps.asciidoc
Labels: backport

#745 Use config.Config over processor.Config.
  beater/handlers.go
  config/config.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  processor/error/benchmark_test.go
  processor/error/event.go
  processor/error/event_test.go
  processor/error/package_tests/json_schema_test.go
  processor/error/package_tests/processor_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/error/processor_test.go
  processor/healthcheck/processor.go
  processor/healthcheck/processor_test.go
  processor/processor.go
  processor/sourcemap/package_tests/json_schema_test.go
  processor/sourcemap/package_tests/processor_test.go
  processor/sourcemap/payload.go
  processor/sourcemap/payload_test.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/benchmark_test.go
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/package_tests/processor_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/processor_test.go
  processor/transaction/span.go
  processor/transaction/span_test.go
  script/output_data/output_data.go
  tests/approvals.go
  tests/fields.go
Labels: review

#774 Split indices by `processor.event` instead of `name`.
  CHANGELOG.asciidoc
  _meta/beat.yml
  apm-server.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
Labels: review

#778 [6.x] Use config.Config over processor.Config. (#745)
  beater/handlers.go
  config/config.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  processor/error/benchmark_test.go
  processor/error/event.go
  processor/error/event_test.go
  processor/error/package_tests/json_schema_test.go
  processor/error/package_tests/processor_test.go
  processor/error/payload.go
  processor/error/payload_test.go
  processor/error/processor.go
  processor/error/processor_test.go
  processor/healthcheck/processor.go
  processor/healthcheck/processor_test.go
  processor/processor.go
  processor/sourcemap/package_tests/json_schema_test.go
  processor/sourcemap/package_tests/processor_test.go
  processor/sourcemap/payload.go
  processor/sourcemap/payload_test.go
  processor/sourcemap/processor.go
  processor/sourcemap/processor_test.go
  processor/transaction/benchmark_test.go
  processor/transaction/package_tests/json_schema_test.go
  processor/transaction/package_tests/processor_test.go
  processor/transaction/payload.go
  processor/transaction/payload_test.go
  processor/transaction/processor.go
  processor/transaction/processor_test.go
  processor/transaction/span.go
  processor/transaction/span_test.go
  script/output_data/output_data.go
  tests/approvals.go
  tests/fields.go
Labels: backport

#779 [6.x] Split indices by `processor.event` instead of `name`. (#774)
  CHANGELOG.asciidoc
  _meta/beat.yml
  apm-server.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
Labels: backport

#788 [6.x] bump go to 1.9.4 (#786)
  .go-version
  .travis.yml
  CHANGELOG.asciidoc
  Dockerfile
  README.md
  docs/version.asciidoc
  script/jenkins/ci.ps1
  script/jenkins/ci.sh
  script/jenkins/intake.sh
  script/jenkins/update-beats.sh
  tests/Dockerfile
Labels: backport
