Repository elastic/apm-server, pull requests merged in 2018-09, with the labels that each got.

#1346 [6.4] docs(node): update Node.js code snippet (#1344)
  docs/guide/index.asciidoc
Labels: backport

#1345 [6.4] docs(node): list support for Restify framework (#1343)
  docs/guide/index.asciidoc
Labels: backport

#1357 docs: fix grammar, overwrite -> override
  docs/guide/index.asciidoc
Labels: docs

#1342 maintain changelog per minor release
  CHANGELOG.asciidoc
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.4.asciidoc
  changelogs/head.asciidoc
Labels: discuss

#1349 Add basic ES rally track for APM.
  rally/README.md
  rally/challenges/default.json
  rally/fetch_data.py
  rally/index.json
  rally/operations/default.json
  rally/requirements.txt
  rally/track.json
Labels: [zube]: In Review, review

#1382 apm-server monitoring
  _meta/beat.yml
  apm-server.yml
  changelogs/head.asciidoc
  cmd/root.go
  docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/security/beats-system.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/index.asciidoc
Labels: [zube]: In Review

#1391 [v2] Clean up required fields for distributed tracing.
  CHANGELOG.asciidoc
  docs/spec/spans/v2_span.json
  docs/spec/transactions/v2_transaction.json
  model/span/generated/schema/transaction.go
  model/transaction/generated/schema/transaction.go
  processor/stream/approved-es-documents/testV2IntakeIntegrationMixedMinimalProcess.approved.json
  processor/stream/approved-es-documents/testV2IntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/approved-es-documents/testV2IntakeIntegrationSpans.approved.json
  testdata/intake-v2/minimal_process.ndjson
  testdata/intake-v2/optional-timestamps.ndjson
  testdata/intake-v2/spans.ndjson
Labels: review

#1339 [6.4] Add APM release notes for 6.4.1 (#1335)
  docs/guide/index.asciidoc
Labels: [zube]: Blocked, backport

#1384 Require and change description for `error.id`
  CHANGELOG.asciidoc
  docs/spec/errors/v2_error.json
  model/error/generated/schema/error.go
Labels: [zube]: In Review

#1402 [6.4] docs: fix grammar, overwrite -> override (#1357)
  docs/guide/index.asciidoc
Labels: backport, docs

#1403 [v2] Increase metrics counter in v2 responses.
  beater/common_handlers.go
  beater/v2_handler.go
  beater/v2_handler_test.go
  processor/stream/result.go
  processor/stream/result_test.go
  processor/stream/stream_processor.go
  processor/stream/stream_processor_test.go
Labels: [zube]: In Review

#1400 [docs] Note for changing index, adapt dashboard desc.
  docs/copied-from-beats/outputconfig.asciidoc
Labels: [zube]: In Review

#1367 1299 event rate limit per ip
  CHANGELOG.asciidoc
  _meta/beat.yml
  apm-server.yml
  beater/approved-stream-result/TestRequestIntegrationRumRateLimit.approved.json
  beater/beater.go
  beater/beater_test.go
  beater/common_handlers.go
  beater/config.go
  beater/config_test.go
  beater/rl_cache.go
  beater/rl_cache_test.go
  beater/route_config.go
  beater/v2_handler.go
  beater/v2_handler_test.go
  processor/sourcemap/package_tests/attrs_test.go
  processor/stream/approved-es-documents/testV2IntakeIntegrationEvents.approved.json
  processor/stream/approved-stream-result/testIntegrationResultEvents.approved.json
  processor/stream/approved-stream-result/testIntegrationResultLimiterAllowAll.approved.json
  processor/stream/approved-stream-result/testIntegrationResultLimiterDeny.approved.json
  processor/stream/approved-stream-result/testIntegrationResultLimiterDenyAll.approved.json
  processor/stream/approved-stream-result/testIntegrationResultLimiterPartiallyUsedLimitAllow.approved.json
  processor/stream/approved-stream-result/testIntegrationResultLimiterPartiallyUsedLimitDeny.approved.json
  processor/stream/approved-stream-result/testIntegrationResultNoLimiter.approved.json
  processor/stream/benchmark_test.go
  processor/stream/result.go
  processor/stream/stream_processor.go
  processor/stream/stream_processor_test.go
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/metadata-null-values.ndjson
  testdata/intake-v2/minimal-service.ndjson
  testdata/intake-v2/only-metadata.ndjson
  testdata/intake-v2/ratelimit.ndjson
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_access.py
  tests/system/test_requests.py
Labels: [zube]: In Review, review
