Repository elastic/apm-server, pull requests merged in 2019-03, with the labels that each got.

#1969 [7.x] Make Ingest pipeline path explicit (#1963)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config.go
Labels: [zube]: In Review, backport

#1966 Setting user_agent as root key for all events, and canonicalize http headers.
  _meta/ecs-migration.yml
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/7.0.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/context.json
  docs/spec/request.json
  include/fields.go
  ingest/pipeline/definition.json
  model/context.go
  model/context_test.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/ecs_migration_test.go
  tests/system/error.approved.json
  tests/system/transaction.approved.json
  utility/data_fetcher.go
Labels: [zube]: In Review, bug, v7.0

#1974 [7.0] Setting user_agent as root key for all events and canonicalize http headers. (#1966)
  _meta/ecs-migration.yml
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/7.0.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/context.json
  docs/spec/request.json
  include/fields.go
  ingest/pipeline/definition.json
  model/context.go
  model/context_test.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/ecs_migration_test.go
  tests/system/error.approved.json
  tests/system/transaction.approved.json
  utility/data_fetcher.go
Labels: backport

#1973 [7.x] Setting user_agent as root key for all events and canonicalize http headers. (#1966)
  _meta/ecs-migration.yml
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/7.0.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/context.json
  docs/spec/request.json
  include/fields.go
  ingest/pipeline/definition.json
  model/context.go
  model/context_test.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/ecs_migration_test.go
  tests/system/error.approved.json
  tests/system/transaction.approved.json
  utility/data_fetcher.go
Labels: backport

#1942 Update config yml to reflect proper default vals.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: [zube]: In Review

#1975 [7.x] Update beats framework to 70d813d
  NOTICE.txt
  _beats/libbeat/processors/add_host_metadata/_meta/fields.yml
  docs/fields.asciidoc
  include/fields.go
  vendor/github.com/elastic/beats/libbeat/autodiscover/providers/kubernetes/kubernetes.go
  vendor/github.com/elastic/beats/libbeat/kibana/index_pattern_generator.go
  vendor/github.com/elastic/beats/libbeat/publisher/testing/testing.go
  vendor/vendor.json
Labels: [zube]: In Review

#1978 Optional transaction_id for span and error.
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/spec/errors/error.json
  docs/spec/spans/span.json
  model/error/generated/schema/error.go
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/minimal.ndjson
  testdata/intake-v2/spans.ndjson
Labels: [zube]: Done

#1986 [7.x] Specify minimal events on Intake API and ES level. (#1941)
  beater/integration_test.go
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  docs/spec/metadata.json
  model/metadata/generated/schema/metadata.go
  testdata/intake-v2/minimal.ndjson
Labels: backport

#1987 [7.0] Specify minimal events on Intake API and ES level. (#1941)
  beater/integration_test.go
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  docs/spec/metadata.json
  model/metadata/generated/schema/metadata.go
  testdata/intake-v2/minimal.ndjson
Labels: backport

#1988 [7.x] Update config yml to reflect proper default vals. (#1942)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: backport

#1989 [7.0] Update config yml to reflect proper default vals. (#1942)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: backport

#1985 [6.7] Remove ilm-policy from export and setup cmd.
  cmd/root.go
Labels: [zube]: In Review

#1991 [docs] Add 6.6.2 release notes
  changelogs/6.6.asciidoc
Labels: docs

#1992 [docs] Update stack version to 6.6.2
  docs/version.asciidoc
Labels: docs

#1990 [6.7] Update beats framework to 065ccc4
  NOTICE.txt
  _beats/libbeat/processors/add_host_metadata/_meta/fields.yml
  _beats/vendor/vendor.json
  docs/fields.asciidoc
  include/fields.go
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/libbeat/common/cli/password.go
  vendor/github.com/elastic/beats/libbeat/common/field.go
  vendor/github.com/elastic/beats/libbeat/common/seccomp/policy_linux_amd64.go
  vendor/github.com/elastic/beats/libbeat/kibana/fields_transformer.go
  vendor/github.com/elastic/beats/libbeat/kibana/index_pattern_generator.go
  vendor/github.com/elastic/beats/libbeat/publisher/pipeline/processor.go
  vendor/github.com/elastic/beats/libbeat/publisher/queue/spool/codec.go
  vendor/github.com/elastic/beats/libbeat/template/load.go
  vendor/github.com/elastic/beats/libbeat/template/processor.go
  vendor/vendor.json
Labels: [zube]: In Review

#2004 [APM-CI] allow disable the kibana update check stage
  Jenkinsfile
Labels: automation

#1921 [Docs] Document APM Server sizing
  docs/storage-management.asciidoc
Labels: docs

#2009 [docs] Update install instructions
  docs/guide/install-and-run.asciidoc
Labels: docs

#2024 [docs] Update index prefix in output config
  docs/copied-from-beats/outputconfig.asciidoc
Labels: docs

#2011 [docs] Backport docs 7.0
  changelogs/6.6.asciidoc
  docs/common-problems.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/storage-management.asciidoc
Labels: docs

#2012 [docs] Backport docs 7.x
  changelogs/6.6.asciidoc
  docs/common-problems.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/storage-management.asciidoc
Labels: docs

#2013 [docs] Backport docs 6.7
  changelogs/6.6.asciidoc
  docs/common-problems.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: docs

#2014 [docs] Backport docs 6.6
  docs/common-problems.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: docs

#2025 [docs] Backport docs 6.5
  docs/common-problems.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
Labels: docs

#2015 [docs] add 6.6.2 release notes (#1991)
  changelogs/6.6.asciidoc
Labels: docs

#2020 [7.0] enable pipeline registration for setup --pipelines (#2010)
  _beats/libbeat/tests/system/beat/beat.py
  beater/beater.go
  beater/beater_test.go
  beater/config.go
  tests/system/test_setup.py
Labels: backport

#2019 [APM-CI] Run package stage on new conditions
  Jenkinsfile
Labels: automation

#2034 [docs] Fix release notes: 7.7.0 -> 7.0.0
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport, docs

#2035 [docs] fix release notes links
  changelogs/7.0.asciidoc
Labels: backport, docs

#2033 [docs] Add manual ILM instructions
  docs/configuring.asciidoc
  docs/ilm-setup.asciidoc
Labels: backport, docs

#2038 [7.0] expect UTC indices (#2027)
  idxmgmt/supporter_test.go
Labels: backport

#2041 [7.0] Doc clarifications (#2032)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  package-README.md.tmpl
Labels: backport

#2044 [docs] 6.7 release-state
  changelogs/6.7.asciidoc
  docs/version.asciidoc
Labels: docs

#2042 [docs] Fix confusing beats reference
  docs/copied-from-beats/repositories.asciidoc
  docs/index.asciidoc
  docs/version.asciidoc
Labels: docs

#2043 [docs] Add deb/rpm running instructions
  docs/setting-up-and-running.asciidoc
Labels: docs

#2048 [docs][7.0] Backport docs
  changelogs/6.7.asciidoc
  changelogs/7.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuring.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/version.asciidoc
Labels: docs

#2049 [docs][7.x] Backport docs
  changelogs/6.7.asciidoc
  changelogs/7.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuring.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/version.asciidoc
Labels: docs

#2050 [docs][6.7] Backport docs
  docs/configuring.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/version.asciidoc
Labels: docs

#2051 [docs] 7.0.0-rc1 release notes
  changelogs/7.0.asciidoc
  docs/version.asciidoc
Labels: docs

#2053 [docs] Remove old attributes
  docs/configuring-ingest.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/https.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/security/linux-seccomp.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/shared-configuring.asciidoc
  docs/copied-from-beats/shared-ssl-logstash-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/step-test-config.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
Labels: docs

#2054 [docs] Add 7.0 upgrading guide with deb/RPM instructions
  docs/upgrading-to-70.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#2002 [APM-CI] use current as pipeline shared library version
  Jenkinsfile
Labels: [zube]: In Progress, automation
