Repository elastic/apm-server, pull requests merged in 2019-07, with the labels that each got.

#2340 [TLS] Align client_auth handling to beats changes and add description for verification_mode
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config.go
  beater/config_test.go
  changelogs/head.asciidoc
  tests/system/config/apm-server.yml.j2
  tests/system/test_access.py
Labels: [zube]: In Review

#2360 [7.x] Sourcemap only log info for correct log level (#2358)
  sourcemap/cache.go
Labels: [zube]: In Review, backport

#2361 [7.x] [TLS] Align client_auth handling to beats changes and add description for verification_mode (#2340)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config.go
  beater/config_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_access.py
Labels: [zube]: In Review, backport

#2337 Add caching to Agent Remote Configuration handling
  _meta/beat.yml
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  apm-server.docker.yml
  apm-server.yml
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/beater_test.go
  beater/config.go
  beater/route_config.go
  changelogs/head.asciidoc
  convert/convert.go
Labels: [zube]: In Review

#2363 [7.x] Add caching to Agent Remote Configuration handling (#2337)
  _meta/beat.yml
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  apm-server.docker.yml
  apm-server.yml
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/beater_test.go
  beater/config.go
  beater/route_config.go
  convert/convert.go
Labels: backport

#2356 [ILM] Enable ILM by default when supported by configured ES output.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/head.asciidoc
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/ilm/supporter_factory_test.go
  idxmgmt/indices.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  idxmgmt/supporter.go
  idxmgmt/supporter_factory.go
  idxmgmt/supporter_factory_test.go
  idxmgmt/supporter_test.go
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_integration.py
  tests/system/test_pipelines.py
  tests/system/test_setup_index_management.py
Labels: [zube]: In Review, review

#2365 [7.x] [ILM] Enable ILM by default when supported by configured ES output. (#2356)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/ilm/supporter_factory_test.go
  idxmgmt/indices.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  idxmgmt/supporter.go
  idxmgmt/supporter_factory.go
  idxmgmt/supporter_factory_test.go
  idxmgmt/supporter_test.go
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_integration.py
  tests/system/test_pipelines.py
  tests/system/test_setup_index_management.py
Labels: backport

#2364 [7.x] Update beats framework and backports sync config via mage #2320
  Makefile
  NOTICE.txt
  _beats/CHANGELOG-developer.asciidoc
  _beats/CHANGELOG-developer.next.asciidoc
  _beats/CHANGELOG.asciidoc
  _beats/CHANGELOG.next.asciidoc
  _beats/dev-tools/cmd/module_include_list/module_include_list.go
  _beats/dev-tools/generate_notice.py
  _beats/dev-tools/packaging/package_test.go
  _beats/dev-tools/packaging/templates/windows/install-service.ps1.tmpl
  _beats/libbeat/_meta/fields.common.yml
  _beats/libbeat/magefile.go
  _beats/libbeat/processors/script/javascript/module/processor/chain.go
  _beats/libbeat/processors/script/javascript/module/processor/processor.go
  _beats/libbeat/scripts/Makefile
  _beats/libbeat/scripts/generate_fields_docs.py
  _beats/script/build_docs.sh
  _beats/testing/environments/latest.yml
  _beats/vendor/vendor.json
  _meta/beat.yml
  docs/fields.asciidoc
  include/fields.go
  magefile.go
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/dev-tools/generate_notice.py
  vendor/github.com/elastic/beats/dev-tools/mage/config.go
  vendor/github.com/elastic/beats/dev-tools/mage/pkg.go
  vendor/github.com/elastic/beats/libbeat/autodiscover/builder/helper.go
  vendor/github.com/elastic/beats/libbeat/cfgfile/reload.go
  vendor/github.com/elastic/beats/libbeat/common/docker/watcher.go
  vendor/github.com/elastic/beats/libbeat/common/seccomp/seccomp.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/copy_fields.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/decode_base64_field.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/rename.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/truncate_fields.go
  vendor/vendor.json
Labels: [zube]: In Review, backport

#2372 [7.x] Fix failing system-test (#2370)
  tests/system/test_integration.py
Labels: backport

#2373 [7.3] Fix failing system-test (#2370)
  tests/system/test_integration.py
Labels: backport

#2382 [7.3] Fix flaky tests, default value for agent config cache. (#2376)
  beater/beater_test.go
  beater/config.go
  tests/system/test_integration.py
  tests/system/test_pipelines.py
Labels: backport

#2381 [7.x] Fix flaky tests, default value for agent config cache. (#2376)
  beater/beater_test.go
  beater/config.go
  tests/system/test_integration.py
  tests/system/test_pipelines.py
Labels: backport

#2171 [docs] APM Overview structure and content improvements
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/images/kibana-geo-data.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: discuss, docs

#2384 ci: set sync stage to unstable on failure
  Jenkinsfile
Labels: [zube]: In Review, automation, backport, ci

#2378 ci: add labels to script commands
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#2377 ci: notify on cleanup stage
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#2374 fix: ignore fails on tar test results files
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#2379 fix: release stage should not be triggered always
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#2375 fix: build inside a Golang Docker container
  .ci/docker/golang-mage/Dockerfile
  Jenkinsfile
  script/jenkins/build.sh
Labels: [zube]: In Review, automation, ci

#2386 Fix config handler
  agentcfg/fetch.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/common_handler_test.go
  beater/route_config.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_logging.py
Labels: [zube]: In Review

#2390 [7.x] Update kibana endpoint and introduce a killer switch to disable the (#2386)
  agentcfg/fetch.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/common_handler_test.go
  beater/route_config.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_logging.py
Labels: backport

#2388 feat(ci): use isGitRegionMatch step
  Jenkinsfile
Labels: automation, ci

#2368 build just the default packages
  script/jenkins/package.sh
Labels: [zube]: In Review

#2369 [7.x] Update beats framework to cecb997
  NOTICE.txt
  _beats/CHANGELOG.next.asciidoc
  _beats/dev-tools/generate_notice.py
  _beats/dev-tools/packaging/templates/windows/install-service.ps1.tmpl
  _beats/libbeat/docs/version.asciidoc
  _beats/libbeat/processors/script/javascript/module/processor/chain.go
  _beats/libbeat/processors/script/javascript/module/processor/processor.go
  _beats/libbeat/scripts/Makefile
  _beats/vendor/vendor.json
  script/update_beats.sh
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/dev-tools/generate_notice.py
  vendor/github.com/elastic/beats/dev-tools/mage/integtest.go
  vendor/github.com/elastic/beats/libbeat/outputs/kafka/config.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/decompress_gzip_field.go
  vendor/github.com/elastic/beats/libbeat/processors/communityid/communityid.go
  vendor/github.com/elastic/beats/libbeat/processors/communityid/config.go
  vendor/github.com/golang/protobuf/LICENSE
  vendor/github.com/golang/protobuf/proto/Makefile
  vendor/github.com/golang/protobuf/proto/clone.go
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/discard.go
  vendor/github.com/golang/protobuf/proto/encode.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_merge.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/proto/text.go
  vendor/github.com/golang/protobuf/proto/text_parser.go
  vendor/vendor.json
Labels: [zube]: In Review

#2405 [7.x] Fix timing issue for pipeline system test (#2403)
  tests/system/apmserver.py
  tests/system/test_pipelines.py
Labels: [zube]: In Review, backport

#2406 [7.3] Fix timing issue for pipeline system test (#2403)
  tests/system/apmserver.py
  tests/system/test_pipelines.py
Labels: [zube]: In Review, backport

#2397 Remove unused properties from metricset Intake API
  changelogs/7.3.asciidoc
  docs/spec/metricsets/metricset.json
  model/metricset/generated/schema/metricset.go
Labels: [zube]: In Review

#2402 [7.3] Update kibana endpoint and introduce a killer switch to disable the (#2386)
  agentcfg/fetch.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/common_handler_test.go
  beater/route_config.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_logging.py
Labels: [zube]: In Review, backport

#2409 [7.3] Remove unused properties from metricset Intake API (#2397)
  docs/spec/metricsets/metricset.json
  model/metricset/generated/schema/metricset.go
Labels: backport

#2401 [7.x] Refactor http header strings. Add "X-Content-Type-Options: nosniff" header (#2387)
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/common_handler.go
  beater/headers/keys.go
  beater/intake_handler.go
Labels: [zube]: In Review, backport

#2408 [7.x] Remove unused properties from metricset Intake API (#2397)
  docs/spec/metricsets/metricset.json
  model/metricset/generated/schema/metricset.go
Labels: backport

#2398 [7.x] Fix changelog from 7.2 on. (#2396)
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
Labels: [zube]: In Review, backport

#2399 [7.3] Fix changelog from 7.2 on. (#2396)
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
Labels: [zube]: In Review, backport

#2407 Enclose etag and IfNoneMatch header in double quotes.
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
Labels: [zube]: In Review

#2392 feat(ci): enable check changelogs pipeline
  .ci/check-changelogs.groovy
  .ci/jobs/apm-server-check-changelogs-mbp.yml
  Makefile
  script/check_changelogs.py
  script/jenkins/check-changelogs.sh
Labels: [zube]: In Progress, automation, ci

#2411 [7.x] Enclose etag and IfNoneMatch header in double quotes. (#2407)
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
Labels: backport

#2412 [7.3] Enclose etag and IfNoneMatch header in double quotes. (#2407)
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  changelogs/7.3.asciidoc
Labels: backport

#2424 [docs] APM Overview structure and content improvements (#2171)
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/images/kibana-geo-data.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport, docs

#2423 [docs] APM Overview structure and content improvements (#2171)
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/images/kibana-geo-data.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport, docs

#2422 [docs] APM Overview structure and content (#2171)
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/images/kibana-geo-data.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport, docs

#2425 [docs] APM Overview structure and content improvements (#2171)
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport, docs

#2426 [docs] APM Overview structure and content improvements (#2171)
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-architecture.png
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/distributed-tracing.jpg
  docs/guide/images/apm-architecture-cloud.png
  docs/guide/images/apm-architecture-diy.png
  docs/guide/images/apm-distributed-tracing.png
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/kibana-dashboard.png
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport, docs

#2366 [docs] Agent configuration documentation
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/agent-configuration.asciidoc
  docs/configure-kibana-endpoint.asciidoc
  docs/configuring.asciidoc
  docs/intake-api.asciidoc
  docs/redirects.asciidoc
Labels: docs

#2431 [docs][7.x] Fix documentation build errors
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
Labels: docs

#2432 [docs][7.3] Fix documentation build errors
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
Labels: docs

#2433 [docs] Add links to release notes
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
Labels: docs

#2430 [docs][7.x] Agent configuration documentation (#2366)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/agent-configuration.asciidoc
  docs/configure-kibana-endpoint.asciidoc
  docs/configuring.asciidoc
  docs/intake-api.asciidoc
  docs/redirects.asciidoc
Labels: backport, docs

#2429 [docs][7.3] Agent configuration documentation (#2366)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/agent-configuration.asciidoc
  docs/configure-kibana-endpoint.asciidoc
  docs/configuring.asciidoc
  docs/intake-api.asciidoc
  docs/redirects.asciidoc
Labels: backport, docs

#2414 ci(jenkins): 7d is not allowed but 1w instead
  .ci/check-changelogs.groovy
  .ci/jobs/apm-server-check-changelogs-mbp.yml
Labels: automation, bug, ci

#2410 fix: use fixed dependencies on golang Docker container
  .ci/docker/golang-mage/Dockerfile
Labels: [zube]: In Progress, automation, ci

#2421 Ensure Kibana client reconnects.
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/beater.go
  beater/common_handler.go
  beater/onboarding_test.go
  beater/route_config.go
  beater/server.go
  changelogs/7.3.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  log/selectors.go
  tests/kibana.go
  tests/system/test_integration_logging.py
Labels: [zube]: In Review

#2436 [7.3] Ensure Kibana client reconnects. (#2421)
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/beater.go
  beater/common_handler.go
  beater/onboarding_test.go
  beater/route_config.go
  beater/server.go
  changelogs/7.3.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  log/selectors.go
  tests/kibana.go
  tests/system/test_integration_logging.py
Labels: backport

#2435 [7.x] Ensure Kibana client reconnects. (#2421)
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  beater/beater.go
  beater/common_handler.go
  beater/onboarding_test.go
  beater/route_config.go
  beater/server.go
  changelogs/7.3.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  log/selectors.go
  tests/kibana.go
  tests/system/test_integration_logging.py
Labels: backport

#2391 ci: move benchmark stage to run in a tool Docker container
  Jenkinsfile
  script/jenkins/bench.sh
Labels: [zube]: In Progress, automation, ci

#2439 Agent configuration integration tests
  docker-compose.yml
  tests/docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_integration_logging.py
  tests/system/test_pipelines.py
Labels: [zube]: In Review

#2415 feat: backport pipeline from #2260 [7.3]
  .ci/check-changelogs.groovy
  Makefile
  script/check_changelogs.py
  script/jenkins/check-changelogs.sh
Labels: [zube]: In Review, automation, backport, ci

#2443 [ACM] Only allow cache expiration values in full seconds.
  beater/config.go
  beater/config_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: [zube]: In Review

#2448 [7.x] Agent configuration integration tests (#2439)
  docker-compose.yml
  tests/docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_integration_logging.py
  tests/system/test_pipelines.py
Labels: backport

#2449 [7.3] Agent configuration integration tests (#2439)
  docker-compose.yml
  tests/docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_integration_logging.py
  tests/system/test_pipelines.py
Labels: backport

#2444 [7.x] build just the default packages (#2368)
  script/jenkins/package.sh
Labels: [zube]: In Review, backport

#2445 [7.3] build just the default packages (#2368)
  script/jenkins/package.sh
Labels: [zube]: In Review, backport

#2451 [7.3] [ACM] Only allow cache expiration values in full seconds. (#2443)
  beater/config.go
  beater/config_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: [zube]: In Review, backport

#2450 [7.x] [ACM] Only allow cache expiration values in full seconds. (#2443)
  beater/config.go
  beater/config_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: [zube]: In Review, backport

#2452 Disable overwriting ingest pipelines by default.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/beater_test.go
  beater/config.go
  beater/config_test.go
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  tests/system/test_pipelines.py
Labels: [zube]: In Review

#2455 [7.3] Disable overwriting ingest pipelines by default. (#2452)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/beater_test.go
  beater/config.go
  beater/config_test.go
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  tests/system/test_pipelines.py
Labels: backport

#2454 [7.x] Disable overwriting ingest pipelines by default. (#2452)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/beater_test.go
  beater/config.go
  beater/config_test.go
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  tests/system/test_pipelines.py
Labels: backport

#2437 [docs] Update ILM enabled to “auto”
  docs/ilm.asciidoc
Labels: docs

#2456 [7.2] Disable overwriting ingest pipelines by default. (#2452)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/beater_test.go
  beater/config.go
  beater/config_test.go
  changelogs/7.2.asciidoc
  tests/system/test_pipelines.py
Labels: [zube]: In Review, backport

#2458 [ACM] Return 200 instead of 404 for missing config.
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  tests/system/test_integration_acm.py
Labels: [zube]: In Review

#2463 [7.3] [ACM] Return 200 instead of 404 for missing config. (#2458)
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  tests/system/test_integration_acm.py
Labels: backport

#2462 [7.x] [ACM] Return 200 instead of 404 for missing config. (#2458)
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  tests/system/test_integration_acm.py
Labels: backport

#2465 [7.x] Update changelog for 7.2.1 (#2464)
  changelogs/7.2.asciidoc
Labels: backport

#2466 [7.3] Update changelog for 7.2.1 (#2464)
  changelogs/7.2.asciidoc
Labels: backport

#2467 [7.2] Update changelog for 7.2.1 (#2464)
  changelogs/7.2.asciidoc
Labels: backport

#2473 [ILM] change auto disabled message
  idxmgmt/manager.go
Labels: [zube]: In Review

#2479 [7.x] ignore unavailable agent configuration index during setup. (#2475)
  tests/system/apmserver.py
  tests/system/test_integration_acm.py
Labels: backport

#2480 [7.3] ignore unavailable agent configuration index during setup. (#2475)
  tests/system/apmserver.py
  tests/system/test_integration_acm.py
Labels: backport

#2476 [7.x] [ILM] change auto disabled message (#2473)
  idxmgmt/manager.go
Labels: backport

#2477 [7.3] [ILM] change auto disabled message (#2473)
  idxmgmt/manager.go
Labels: backport

#2441 [ACM] Create Etag from settings struct.
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  agentcfg/query.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: [zube]: In Review

#2482 [7.3] [ACM] Create Etag from settings struct. (#2441)
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  agentcfg/query.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: backport

#2481 [7.x] [ACM] Create Etag from settings struct. (#2441)
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  agentcfg/query.go
  beater/agent_config_handler.go
  beater/agent_config_handler_test.go
  changelogs/7.3.asciidoc
  tests/system/test_integration_acm.py
Labels: backport

#2485 [docs] Update ILM enabled to “auto” (#2437)
  docs/ilm.asciidoc
Labels: docs

#2487 [7.x] Upgrade Go to 1.12.7 (#2483)
  .go-version
  Dockerfile
  README.md
  changelogs/7.4.asciidoc
  docs/version.asciidoc
  tests/Dockerfile
Labels: backport

#2490 ci: remove the documentation stage
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#2501 [7.x] Add service.environment to spans. (#2500)
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/spans.json
  model/metadata/service.go
  model/span/event_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  tests/system/spans.approved.json
Labels: backport

#2468 [docs][6.8] 6.8.2 release notes and version
  changelogs/6.8.asciidoc
  docs/version.asciidoc
Labels: docs

#2460 [docs][7.2] 7.2.1 release bump
  docs/version.asciidoc
Labels: docs

#2503 ci: move to use new windows-2019-immutable workers
  Jenkinsfile
Labels: automation, ci

#2513 [6.7] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2512 [6.8] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2511 [7.0] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2510 [7.1] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2509 [7.2] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2508 [7.3] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2507 [7.x] ci: move to use new windows-2019-immutable workers (#2503)
  Jenkinsfile
Labels: automation, backport, ci

#2469 [docs][7.3] 7.3.0 release version bump
  docs/version.asciidoc
Labels: docs

#2515 [DOCS] Adds 7.3.0 breaking changes
  docs/guide/apm-breaking-changes.asciidoc
Labels: docs, v7.3.0

#2516 [DOCS] Adds 7.3.0 release highlights
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/apm-highlight-breakdown-charts.png
  docs/guide/images/apm-highlight-rum-maps.png
  docs/guide/images/apm-highlight-sample-rate.png
Labels: docs, v7.3.0
