Repository elastic/apm-server, pull requests merged in 2019-10, with the labels that each got.

#2748 [7.4][docs] 7.4.0 release state
  docs/version.asciidoc
Labels: docs

#2751 [docs] Fix Homebrew instructions
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: docs

#2752 [7.x] [docs] Fix Homebrew instructions (#2751)
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2753 [7.4] [docs] Fix Homebrew instructions (#2751)
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2754 [7.3] [docs] Fix Homebrew instructions (#2751)
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2755 [7.2] [docs] Fix Homebrew instructions (#2751)
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2756 [7.1] [docs] Fix Homebrew instructions (#2751)
  docs/brew.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2757 [7.0] [docs] Fix Homebrew instructions (#2751)
  docs/getting-started-apm-server.asciidoc
  docs/installing.asciidoc
Labels: backport

#2746 Add service.node.configured_name to Intake API and transform into service.node.name for ES
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/service.json
  include/fields.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/metadata/generated/schema/metadata.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/span/event.go
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/metricsets.ndjson
  testdata/intake-v2/only-metadata.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: review

#2759 [7.4] [docs] Break outputconfig.asciidoc into multiple files (#2744)
  _beats/script/build_docs.sh
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/outputs/change-output-codec.asciidoc
  docs/copied-from-beats/outputs/output-cloud.asciidoc
  docs/copied-from-beats/outputs/output-console.asciidoc
  docs/copied-from-beats/outputs/output-elasticsearch.asciidoc
  docs/copied-from-beats/outputs/output-file.asciidoc
  docs/copied-from-beats/outputs/output-kafka.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/outputs/output-redis.asciidoc
  docs/copied-from-beats/shared-securing-beat.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  script/build_apm_docs.sh
Labels: backport

#2760 [7.x] [docs] Fix typos (#2690)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#2761 [7.4] [docs] Fix typos (#2690)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#2762 [7.3] [docs] Fix typos (#2690)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#2738 [7.x] [docs] make rum-allow-origins format clear (#2716)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/configuration-rum.asciidoc
Labels: backport

#2768 [7.x] use real agent name for rum events (#2763)
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  testdata/intake-v2/errors_rum.ndjson
  testdata/intake-v2/transactions_spans_rum.ndjson
  testdata/intake-v2/transactions_spans_rum_2.ndjson
Labels: backport

#2769 ci(codecov): resolve PR coverage measures errors
  codecov.yml
Labels: automation, ci

#2771 Copy `client.ip` to `source.ip`
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  include/fields.go
  model/error/event.go
  model/error/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: [zube]: In Review, review

#2772 Parse IP and only store valid IPs in client.ip
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/transactions.json
  model/context.go
  model/context_test.go
  model/error/event.go
  model/metadata/user.go
  model/metadata/user_test.go
  model/transaction/event.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/transactions.ndjson
  utility/ip.go
  utility/ip_test.go
Labels: [zube]: In Review

#2786 [7.x] Copy `client.ip` to `source.ip` (#2771)
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  include/fields.go
  model/error/event.go
  model/error/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: backport

#2779 docs: update agent server compatibly for Node.js
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: docs

#2783 [7.x][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2782 [7.4][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2785 [7.3][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2780 [7.2][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2781 [7.1][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2784 [7.0][docs] Updates to Agent compat and links
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport, docs

#2774 ci(jenkins): reuse top level agent
  .ci/check-changelogs.groovy
  Jenkinsfile
Labels: automation, ci

#2787 [7.x] Add service.node.configured_name to Intake API and transform into service.node.name for ES (#2746)
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/service.json
  include/fields.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/metadata/generated/schema/metadata.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/span/event.go
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/metricsets.ndjson
  testdata/intake-v2/only-metadata.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: backport

#2764 Make ILM policies configurable.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/head.asciidoc
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/policy.go
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/ilm/supporter_factory_test.go
  idxmgmt/ilm/template.go
  idxmgmt/ilm/template_test.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  idxmgmt/supporter.go
  idxmgmt/supporter_factory.go
  idxmgmt/supporter_factory_test.go
  idxmgmt/supporter_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_setup_index_management.py
Labels: [zube]: In Review, review

#2797 [7.x] Make ILM policies configurable. (#2764)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/policy.go
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/ilm/supporter_factory_test.go
  idxmgmt/ilm/template.go
  idxmgmt/ilm/template_test.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  idxmgmt/supporter.go
  idxmgmt/supporter_factory.go
  idxmgmt/supporter_factory_test.go
  idxmgmt/supporter_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_setup_index_management.py
Labels: [zube]: In Review, backport

#2800 [7.x] agent config GA
  agentcfg/cache.go
  agentcfg/cache_test.go
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/api/intake/handler.go
  beater/api/intake/handler_test.go
  beater/api/mux.go
  beater/middleware/cors_middleware.go
  beater/middleware/rate_limit_middleware.go
  beater/middleware/rum_middleware.go
  beater/request/context.go
  kibana/connecting_client.go
  sourcemap/mapper.go
  tests/system/apmserver.py
  tests/system/test_integration_acm.py
Labels: backport

#2798 [ILM] Change default policies to 30day rollover
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/head.asciidoc
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/policy.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_setup_index_management.py
Labels: [zube]: In Review, review, v7.5.0

#2801 [7.x] [ILM] Change default policies to 30day rollover (#2798)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/policy.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_setup_index_management.py
Labels: backport

#2812 [7.5] Mark agent config tests as integration. (#2810)
  tests/system/test_integration_acm.py
Labels: backport

#2811 [7.x] Mark agent config tests as integration. (#2810)
  tests/system/test_integration_acm.py
Labels: backport

#2808 [7.5] Pin 7.5 in stack versions for integration tests
  _beats/testing/environments/snapshot-oss.yml
  _beats/testing/environments/snapshot.yml
Labels: backport

#2822 Add 7.5 changelog
  CHANGELOG.asciidoc
  changelogs/7.5.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#2790 fix: discard to check changelogs before 7.3
  script/check_changelogs.py
Labels: automation, ci

#2819 [7.x] [CI] Fix flaky ILM setup system test (#2816)
  tests/system/test_setup_index_management.py
Labels: backport

#2820 [7.5] [CI] Fix flaky ILM setup system test (#2816)
  tests/system/test_setup_index_management.py
Labels: backport

#2826 [7.x] Adds support for global labels in spans.
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/spans.json
  model/metadata/metadata.go
  model/span/event.go
  model/span/event_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport

#2829 [docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2833 [7.x][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2834 [7.5][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2835 [7.4][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2830 [7.3][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2831 [7.2][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2832 [7.0][docs] update link to ruby docs
  docs/guide/install-and-run.asciidoc
Labels: docs

#2838 [DOCS] Bump docs for 6.8.4 release
  docs/version.asciidoc
Labels: docs

#2837 [DOCS] Bump docs for 7.4.1 release
  docs/version.asciidoc
Labels: docs

#2851 Revert "[DOCS] Bump docs to 6.8.4 release (#2838)"
  docs/version.asciidoc
Labels: docs

#2850 Revert "[DOCS] Bump docs to 7.4.1 release (#2837)"
  docs/version.asciidoc
Labels: docs

#2853 [DOCS] Bump docs for 7.4.1 release
  docs/version.asciidoc
Labels: docs

#2852 [DOCS] Bump docs for 6.8.4 release
  docs/version.asciidoc
Labels: docs

#2855 [Docs] Improve testdata used for docs example
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  docs/data/intake-api/generated/events.ndjson
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  testdata/intake-v2/events.ndjson
Labels: [zube]: In Review, docs, review

#2775 [DOCS] Fixes link to role mapping
  docs/copied-from-beats/https.asciidoc
  docs/copied-from-beats/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/users.asciidoc
  docs/copied-from-beats/template-config.asciidoc
Labels: docs

#2859 [7.x] [Docs] Improve testdata used for docs example (#2855)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  docs/data/intake-api/generated/events.ndjson
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  testdata/intake-v2/events.ndjson
Labels: [zube]: In Review, backport

#2860 [7.5] [Docs] Improve testdata used for docs example (#2855)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  docs/data/intake-api/generated/events.ndjson
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  testdata/intake-v2/events.ndjson
Labels: [zube]: In Review, backport

#2869 Clarify messages on 403 errors for each endpoint.
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json
  beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/mux.go
  beater/middleware/kill_switch_middleware.go
  beater/middleware/kill_switch_middleware_test.go
  tests/system/test_integration_acm.py
Labels: [zube]: In Review

#2870 [7.x] Clarify messages on 403 errors for each endpoint. (#2869)
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json
  beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/mux.go
  beater/middleware/kill_switch_middleware.go
  beater/middleware/kill_switch_middleware_test.go
  tests/system/test_integration_acm.py
Labels: backport

#2871 [7.5] Clarify messages on 403 errors for each endpoint. (#2869)
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/OffSourcemap.approved.json
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json
  beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/OffRum.approved.json
  beater/api/mux.go
  beater/middleware/kill_switch_middleware.go
  beater/middleware/kill_switch_middleware_test.go
  tests/system/test_integration_acm.py
Labels: backport

#2861 [7.4] [Docs] Improve testdata used for docs example (#2855)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  docs/data/intake-api/generated/events.ndjson
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  testdata/intake-v2/events.ndjson
Labels: [zube]: In Review, backport

#2879 [docs] 7.4.2 changelog
  changelogs/7.4.asciidoc
Labels: docs

#2877 [ILM] Add ilm.setup.overwrite config option.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/7.5.asciidoc
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
Labels: [zube]: In Review, v7.5.0

#2882 [7.5] [ILM] Add ilm.setup.overwrite config option. (#2877)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/7.5.asciidoc
  idxmgmt/feature.go
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/manager.go
  idxmgmt/manager_test.go
Labels: backport
