Repository elastic/apm-server, pull requests merged in 2019-12, with the labels that each got.

#2991 [7.x] Adds support for API Keys in the Elasticsearch client. (#2989)
  beater/config/rum.go
  elasticsearch/client.go
  elasticsearch/config.go
  elasticsearch/estest/client.go
Labels: backport

#2993 [docs] Add bug fix to release notes
  changelogs/7.5.asciidoc
Labels: docs

#2995 [7.x] [docs] Add bug fix to release notes (#2993)
  changelogs/7.5.asciidoc
Labels: backport

#2996 [7.5] [docs] Add bug fix to release notes (#2993)
  changelogs/7.5.asciidoc
Labels: backport

#2998 ci(jenkins): support isGitRegionMatch
  Jenkinsfile
Labels: automation, bug, ci

#3005 [docs] Update releases.md
  RELEASES.md
Labels: docs

#2983 ci(jenkins): cancel previous running builds
  Jenkinsfile
Labels: automation, ci

#3015 [DOCS] Change Ruby APM `set_tags` link to `set_label`
  docs/guide/apm-data-model.asciidoc
Labels: docs

#3016 [DOCS] [7.5] Change Ruby APM `set_tags` link to `set_label`
  docs/guide/apm-data-model.asciidoc
Labels: docs

#3017 [DOCS] [7.4] Change Ruby APM `set_tags` link to `set_label`
  docs/guide/apm-data-model.asciidoc
Labels: docs

#3004 Add API Key support
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/config_agent_integration_test.go
  beater/api/intake/test_approved/integration/backend/TestIntakeBackendHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/intake/test_approved/integration/rum/TestRUMHandler_NoAuthorizationRequired.approved.json
  beater/api/intake_backend_integration_test.go
  beater/api/intake_rum_integration_test.go
  beater/api/mux.go
  beater/api/mux_test.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/api/root_integration_test.go
  beater/api/sourcemap_handler_integration_test.go
  beater/authorization/allow.go
  beater/authorization/allow_test.go
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  beater/authorization/bearer.go
  beater/authorization/bearer_test.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/authorization/deny.go
  beater/authorization/deny_test.go
  beater/authorization/privilege.go
  beater/authorization/privilege_test.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config.go
  beater/config/config_test.go
  beater/headers/keys.go
  beater/middleware/authorization_middleware.go
  beater/middleware/authorization_middleware_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/request/result.go
  beater/request/result_test.go
  changelogs/head.asciidoc
  elasticsearch/client.go
  elasticsearch/estest/client.go
  tests/system/test_integration_acm.py
Labels: [zube]: In Review

#3020 [DOCS] Added older release notice.
  docs/guide/page_header.html
  docs/page_header.html
Labels: docs

#3021 [DOCS] Add EOL notice.
  docs/page_header.html
Labels: [zube]: In Review, docs, v6.2

#3029 [DOCS] Add EOL notice to overview.
  docs/guide/page_header.html
Labels: docs, v6.2

#3032 feat: enable DIAGNOSTIC_INTERVAL env var
  Jenkinsfile
Labels: automation, ci

#3037 [7.x] Experimental self-profiling (#2839)
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/mux.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  beater/beater.go
  beater/config/config.go
  beater/config/instrumentation.go
  beater/integration_test.go
  beater/server_test.go
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  decoder/limited_reader.go
  decoder/limited_reader_test.go
  docs/fields.asciidoc
  idxmgmt/ilm/policy.go
  idxmgmt/indices.go
  idxmgmt/indices_test.go
  idxmgmt/manager_test.go
  include/fields.go
  model/profile/_meta/fields.yml
  model/profile/profile.go
  model/profile/profile_test.go
  testdata/profile/cpu.pprof
  testdata/profile/heap.pprof
  testdata/profile/metadata.json
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
  tests/system/test_setup_index_management.py
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/go.mod
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/google/pprof/LICENSE
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/filter.go
  vendor/github.com/google/pprof/profile/index.go
  vendor/github.com/google/pprof/profile/legacy_java_profile.go
  vendor/github.com/google/pprof/profile/legacy_profile.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/google/pprof/profile/proto.go
  vendor/github.com/google/pprof/profile/prune.go
Labels: backport

#3035 [7.x] Upgrade go version to 1.13.4 (#2985)
  .go-version
  Dockerfile
  README.md
  docs/version.asciidoc
  main_test.go
  tests/Dockerfile
Labels: backport

#3036 [7.x] Merge pull request #2999 from jmlrt/makefile-phony
  Makefile
Labels: backport

#3038 [7.x] speed up integration tests (#2565)
  script/jenkins/linux-test.sh
  script/jenkins/unit-test.sh
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/error.approved.json
  tests/system/test_integration.py
  tests/system/test_pipelines.py
  tests/system/test_requests.py
  tests/system/test_setup_index_management.py
  tests/system/transaction.approved.json
Labels: backport

#3041 [7.5] Retry connection when Kibana version is not compatible. (#3031)
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  changelogs/7.5.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  tests/kibana.go
Labels: backport

#3039 [7.x] Update system tests (#3014)
  docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/test_access.py
  tests/system/test_export.py
  tests/system/test_integration.py
  tests/system/test_integration_acm.py
  tests/system/test_integration_logging.py
  tests/system/test_pipelines.py
  tests/system/test_requests.py
  tests/system/test_setup_index_management.py
  tests/system/transaction.approved.json
Labels: backport

#3044 [7.x] Makefile: Drop -i flag in GOBUILD_FLAGS or go test (#2906)
  Makefile
  _beats/libbeat/scripts/Makefile
Labels: backport

#3046 [7.x] enable xpack security in system tests (#2799)
  Makefile
  TESTING.md
  _beats/libbeat/scripts/Makefile
  docker-compose.yml
  testing/docker/elasticsearch/roles.yml
  testing/docker/elasticsearch/users
  testing/docker/elasticsearch/users_roles
  tests/system/apmserver.py
Labels: backport

#3048 [7.x] capture es diagnostics per DIAGNOSTIC_INTERVAL (#3028)
  TESTING.md
  tests/system/apmserver.py
  tests/system/test_setup_index_management.py
Labels: backport

#3049 [7.x] Add mage packaging build and type filters (#3003)
  magefile.go
Labels: backport

#3050 tests: use approvals for system tests
  TESTING.md
  tests/approvals/approvals.go
  tests/system/apmserver.py
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/test_integration.py
  tests/system/transaction.approved.json
Labels: [zube]: In Review

#3052 [test] Isolate unit test from Kibana instance
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
Labels: [zube]: In Review

#3054 feat: allow to set different test environments
  Jenkinsfile
  Makefile
  docker-compose.yml
Labels: automation, enhancement

#3019 Add API Key Integration tests
  Makefile
  _beats/libbeat/scripts/Makefile
  beater/authorization/apikey.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/middleware/authorization_middleware.go
  docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_access.py
Labels: [zube]: In Review

#2644 ci(jenkins): update timeout and when regexp comparator
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#3055 [7.x] Add API Key support (#3004)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/config_agent_integration_test.go
  beater/api/intake/test_approved/integration/backend/TestIntakeBackendHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/intake/test_approved/integration/rum/TestRUMHandler_NoAuthorizationRequired.approved.json
  beater/api/intake_backend_integration_test.go
  beater/api/intake_rum_integration_test.go
  beater/api/mux.go
  beater/api/mux_test.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/api/root_integration_test.go
  beater/api/sourcemap_handler_integration_test.go
  beater/authorization/allow.go
  beater/authorization/allow_test.go
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  beater/authorization/bearer.go
  beater/authorization/bearer_test.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/authorization/deny.go
  beater/authorization/deny_test.go
  beater/authorization/privilege.go
  beater/authorization/privilege_test.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config.go
  beater/config/config_test.go
  beater/headers/keys.go
  beater/middleware/authorization_middleware.go
  beater/middleware/authorization_middleware_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/request/result.go
  beater/request/result_test.go
  elasticsearch/client.go
  elasticsearch/estest/client.go
  tests/system/test_integration_acm.py
Labels: backport

#3060 [7.x] tests: use approvals for system tests (#3050)
  TESTING.md
  tests/approvals/approvals.go
  tests/system/apmserver.py
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/test_integration.py
  tests/system/transaction.approved.json
Labels: backport

#3061 [7.x] [test] Isolate unit test from Kibana instance (#3052)
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
Labels: backport

#3064 Add 'overwrite' to destination.* fields
  _meta/fields.common.yml
  include/fields.go
Labels: [zube]: In Review

#3065 [7.5] Update beats framework to e1b49ce
  NOTICE.txt
  _beats/CHANGELOG.asciidoc
  _beats/CHANGELOG.next.asciidoc
  _beats/libbeat/docs/version.asciidoc
  _beats/script/build_docs.sh
  _beats/testing/environments/docker/kafka/run.sh
  _beats/vendor/vendor.json
  vendor/github.com/Shopify/sarama/broker.go
  vendor/github.com/Shopify/sarama/dev.yml
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/dev-tools/mage/config.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
  vendor/github.com/elastic/beats/libbeat/common/fmtstr/formattimestamp.go
  vendor/github.com/elastic/beats/libbeat/idxmgmt/ilm/ilm.go
  vendor/github.com/elastic/beats/libbeat/idxmgmt/std.go
  vendor/github.com/elastic/beats/libbeat/monitoring/monitoring.go
  vendor/github.com/elastic/beats/libbeat/monitoring/report/elasticsearch/client.go
  vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/bulkapi.go
  vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go
  vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/elasticsearch.go
  vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/json_read.go
  vendor/github.com/elastic/beats/libbeat/outputs/kafka/client.go
  vendor/github.com/elastic/beats/libbeat/outputs/kafka/kafka.go
  vendor/github.com/elastic/beats/libbeat/outputs/kafka/partition.go
  vendor/github.com/elastic/beats/libbeat/publisher/event.go
  vendor/vendor.json
Labels: [zube]: In Review

#3027 [docs] systemd and config ownership improvements
  docs/config-ownership.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/shared-systemd.asciidoc
  docs/getting-started-apm-server.asciidoc
Labels: docs

#3074 [docs] 6.8.6 release notes and doc version bump
  changelogs/6.8.asciidoc
  docs/version.asciidoc
Labels: docs

#3076 [7.x] ci(jenkins): cancel previous running builds (#2983)
  Jenkinsfile
Labels: backport

#3077 [7.x] feat: enable DIAGNOSTIC_INTERVAL env var (#3032)
  Jenkinsfile
Labels: backport

#3079 [7.x] ci(jenkins): when regexp comparator (#2644)
  Jenkinsfile
Labels: backport

#3078 [7.x] feat: allow to set different test environments (#3054)
  Jenkinsfile
  Makefile
  docker-compose.yml
Labels: backport

#3071 [7.5] [docs] systemd and config ownership improvements (#3027)
  docs/config-ownership.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/shared-systemd.asciidoc
  docs/getting-started-apm-server.asciidoc
Labels: backport

#3070 [7.x] [docs] systemd and config ownership improvements (#3027)
  docs/config-ownership.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/shared-systemd.asciidoc
  docs/getting-started-apm-server.asciidoc
Labels: backport

#3058 [7.x] Add API Key Integration tests (#3019)
  Makefile
  _beats/libbeat/scripts/Makefile
  beater/authorization/apikey.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/middleware/authorization_middleware.go
  docker-compose.yml
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_access.py
Labels: backport

#3082 [7.x] feat: grab docker container logs after run tests (#2948)
  .ci/scripts/docker-get-logs.sh
  Jenkinsfile
  script/jenkins/linux-test.sh
Labels: backport

#3066 [Jaeger] Add otel consumer converting batches to Elastic APM events
  beater/api/jaeger/grpc.go
  beater/api/jaeger/grpc_approval_test.go
  beater/api/jaeger/testdata/batch_1.approved.json
  beater/api/jaeger/testdata/batch_1.json
  beater/api/jaeger/testdata/batch_2.approved.json
  beater/api/jaeger/testdata/batch_2.json
  beater/http.go
  beater/jaeger/grpc.go
  beater/jaeger/grpc_test.go
  beater/server.go
  beater/server_test.go
  model/metadata/process.go
  model/span/event.go
  model/span/event_test.go
  model/transaction/event.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/consume_empty.approved.json
  processor/otel/test_approved/consume_emptytrace.approved.json
  processor/otel/test_approved/consume_span.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
Labels: [zube]: In Review, jaeger

#3084 [7.x] beater: disable auth for self-instrumentation (#3083)
  beater/beater.go
  beater/server.go
  beater/tracing.go
  beater/tracing_test.go
  tests/system/test_access.py
Labels: backport

#3073 [docs] Updates doc build script
  script/build_apm_docs.sh
Labels: docs

#3086 [7.x] docs: updates doc script (#3073)
  script/build_apm_docs.sh
Labels: backport

#3087 [7.5] docs: updates doc script (#3073)
  script/build_apm_docs.sh
Labels: backport
