Repository elastic/apm-server, pull requests merged in 2019-02, with the labels that each got.

#1863 Remove storing `context` in ES.
  model/error/event.go
  model/error/event_test.go
  model/span/event.go
  model/span/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions_spans.ndjson
Labels: [zube]: In Review

#1866 Fetch headers case insensitive
  model/context.go
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/transactions_spans.ndjson
Labels: [zube]: In Review

#1864 [docs] Update documentation from beats
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/template-config.asciidoc
Labels: docs

#1867 [docs] Update RUM links to 3.x
  docs/version.asciidoc
Labels: docs

#1650 Docs: add kubernetes metadata
  docs/metadata-api.asciidoc
Labels: docs

#1868 [6.x][docs] Backport documentation
  changelogs/head.asciidoc
  docs/events-api.asciidoc
  docs/exploring-es-data.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/overview.asciidoc
  docs/metadata-api.asciidoc
  docs/metricset-api.asciidoc
  docs/metricset-indices.asciidoc
  docs/version.asciidoc
Labels: docs

#1871 Index fields for `user_agent` pipeline when enabled.
  _meta/fields.common.yml
  changelogs/head.asciidoc
  docs/fields.asciidoc
  include/fields.go
  ingest/pipeline/definition.json
  processor/stream/package_tests/metadata_attrs_test.go
Labels: review

#1869 [6.6][docs] Backport documentation
  docs/events-api.asciidoc
  docs/exploring-es-data.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/overview.asciidoc
  docs/metadata-api.asciidoc
  docs/metricset-api.asciidoc
  docs/metricset-indices.asciidoc
  docs/version.asciidoc
Labels: docs

#1881 Update beats framework to 912ef57
  Makefile
  NOTICE.txt
  _beats/dev-tools/cmd/kibana_index_pattern/kibana_index_pattern.go
  _beats/dev-tools/ecs-migration.yml
  _beats/libbeat/_meta/fields.ecs.yml
  _beats/libbeat/scripts/Makefile
  _beats/libbeat/testing/mapvaltest/mapvaltest.go
  _beats/libbeat/testing/mapvaltest/mapvaltest_test.go
  _beats/testing/environments/docker/kafka/Dockerfile
  _beats/testing/environments/latest.yml
  _beats/testing/environments/snapshot.yml
  _beats/vendor/vendor.json
  docs/fields.asciidoc
  include/fields.go
  script/are_kibana_saved_objects_updated.py
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/dev-tools/mage/kibana.go
  vendor/github.com/elastic/beats/dev-tools/mage/settings.go
  vendor/github.com/elastic/beats/libbeat/cmd/export.go
  vendor/github.com/elastic/beats/libbeat/cmd/export/index_pattern.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
  vendor/github.com/elastic/beats/libbeat/common/field.go
  vendor/github.com/elastic/beats/libbeat/common/kafka/version.go
  vendor/github.com/elastic/beats/libbeat/dashboards/dashboards.go
  vendor/github.com/elastic/beats/libbeat/dashboards/importer.go
  vendor/github.com/elastic/beats/libbeat/dashboards/kibana_loader.go
  vendor/github.com/elastic/beats/libbeat/kibana/fields_transformer.go
  vendor/github.com/elastic/beats/libbeat/kibana/index_pattern_generator.go
  vendor/github.com/elastic/beats/libbeat/kibana/transformer.go
  vendor/github.com/elastic/beats/libbeat/template/load.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/api/auth_client.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/api/client.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/api/configuration.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/api/event_reporter.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/blacklist.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/cache.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/config.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/error.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/manager.go
  vendor/github.com/elastic/beats/x-pack/libbeat/management/state.go
  vendor/vendor.json
Labels: [zube]: In Review

#1875 Fix changelog for 6.6
  changelogs/6.6.asciidoc
Labels: [zube]: In Review, review

#1870 Align context handling with other fields.
  _meta/ecs-migration.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/spec/context.json
  docs/spec/request.json
  model/context.go
  model/context_test.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/test_approved_model/context_empty.approved.json
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_context.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/test_approved_model/context_user_id_integer.approved.json
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: [zube]: In Review, review

#1872 [docs] Grammar fixes
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/metadata-api.asciidoc
Labels: [zube]: In Review, docs

#1876 Create changelog for 6.7
  CHANGELOG.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  docs/release-notes.asciidoc
Labels: [zube]: In Review

#1877 Create changelog for 6.7, 7.0 and fix head
  CHANGELOG.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  changelogs/7.0.asciidoc
  changelogs/head.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/release-notes.asciidoc
Labels: [zube]: In Review

#1891 [7.0] clarify source of kubernetes metadata (#1889)
  _meta/fields.common.yml
  docs/fields.asciidoc
  include/fields.go
Labels: backport

#1890 [7.x] clarify source of kubernetes metadata (#1889)
  _meta/fields.common.yml
  docs/fields.asciidoc
  include/fields.go
Labels: backport

#1887 [docs] Add OpenTracing bridge
  docs/guide/index.asciidoc
  docs/guide/opentracing.asciidoc
Labels: docs

#1901 Allow overriding `service` information from `context`.
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/spec/context.json
  docs/spec/metadata.json
  docs/spec/service.json
  docs/spec/spans/span.json
  docs/spec/user.json
  model/context.go
  model/context_test.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/metadata/container.go
  model/metadata/generated/schema/metadata.go
  model/metadata/kubernetes.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/process.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/metadata/system.go
  model/metadata/user.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/test_approved_model/context_empty.approved.json
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_context.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/test_approved_model/context_user_id_integer.approved.json
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
Labels: review, v7.0

#1908 [7.0] Allow overriding `service` information from `context`. (#1901)
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/spec/context.json
  docs/spec/metadata.json
  docs/spec/service.json
  docs/spec/spans/span.json
  docs/spec/user.json
  model/context.go
  model/context_test.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/metadata/container.go
  model/metadata/generated/schema/metadata.go
  model/metadata/kubernetes.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/process.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/metadata/system.go
  model/metadata/user.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/test_approved_model/context_empty.approved.json
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_context.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/test_approved_model/context_user_id_integer.approved.json
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
Labels: backport

#1919 add empty dashboard list. Fixes #1905 (#1917)
  _beats/libbeat/scripts/unpack_dashboards.py
  _meta/kibana/7/dashboard/apm-dashboards.json
Labels: backport

#1918 [7.x] add empty dashboard list. Fixes #1905 (#1917)
  _beats/libbeat/scripts/unpack_dashboards.py
  _meta/kibana/7/dashboard/apm-dashboards.json
Labels: backport

#1920 index pattern sync check symmetry
  Makefile
  script/are_kibana_saved_objects_updated.py
Labels: [zube]: In Review, bug, test

#1907 [7.x] Allow overriding `service` information from `context`. (#1901)
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/spec/context.json
  docs/spec/metadata.json
  docs/spec/service.json
  docs/spec/spans/span.json
  docs/spec/user.json
  model/context.go
  model/context_test.go
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/metadata/container.go
  model/metadata/generated/schema/metadata.go
  model/metadata/kubernetes.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/process.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/metadata/system.go
  model/metadata/user.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/test_approved_model/context_empty.approved.json
  model/test_approved_model/context_full_event.approved.json
  model/test_approved_model/context_no_context.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/test_approved_model/context_user_id_integer.approved.json
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/errors_2.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
Labels: backport

#1929 Uncomment Beta1 changelog
  changelogs/7.0.asciidoc
Labels: docs

#1899 [APM-CI][WIP] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1898 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1897 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1896 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1895 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1894 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1893 [APM-CI] Enable store artifacts in GCS bucket
  Jenkinsfile
Labels: [zube]: In Progress, automation

#1926 [7.x] index pattern sync check symmetry (#1920)
  Makefile
  script/are_kibana_saved_objects_updated.py
Labels: backport

#1932 Update changelog and release state.
  changelogs/7.0.asciidoc
  changelogs/head.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/version.asciidoc
Labels: [zube]: In Progress

#1927 [7.0] index pattern sync check symmetry (#1920)
  Makefile
  script/are_kibana_saved_objects_updated.py
Labels: [zube]: In Review, backport

#1943 [docs] Add 6.6.1 release notes
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
Labels: [zube]: In Review, docs

#1944 [docs] Update stack-version to 6.6.1
  docs/version.asciidoc
Labels: docs

#1945 [docs] Add 6.6.1 release notes
  changelogs/6.6.asciidoc
Labels: docs

#1946 [docs] Add 6.6.1 release notes
  changelogs/6.6.asciidoc
Labels: docs

#1948 [docs] Add 6.6.1 release notes
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
Labels: docs

#1947 [docs] Add 6.6.1 release notes
  changelogs/6.6.asciidoc
Labels: docs

#1941 Specify minimal events on Intake API and ES level.
  beater/integration_test.go
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  docs/spec/metadata.json
  model/metadata/generated/schema/metadata.go
  testdata/intake-v2/minimal.ndjson
Labels: [zube]: In Review

#1952 [7.0] complete go update to 1.11.5 (#1950)
  .go-version
  changelogs/7.0.asciidoc
Labels: backport

#1951 [7.x] complete go update to 1.11.5 (#1950)
  .go-version
  changelogs/7.0.asciidoc
Labels: backport

#1940 [Docs] 7.0 Breaking changes, Release highlights, Migration assistant, ECS changes
  changelogs/7.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/context.asciidoc
  docs/field-name-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/index.asciidoc
  docs/release-notes.asciidoc
  docs/upgrading.asciidoc
  script/renamed_fields.py
Labels: docs

#1916 [docs] Add apm_user role
  docs/copied-from-beats/security/user-access.asciidoc
  docs/index.asciidoc
Labels: docs

#1956 generate apm-server.docker.yml
  Makefile
  apm-server.docker.yml
Labels: [zube]: In Review

#1958 [docs] make update-beats-docs
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/loggingconfig.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-logstash-config.asciidoc
Labels: docs

#1954 [Docs] Backport docs to 7.0
  changelogs/7.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/context.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/loggingconfig.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/user-access.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-logstash-config.asciidoc
  docs/field-name-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/index.asciidoc
  docs/guide/opentracing.asciidoc
  docs/index.asciidoc
  docs/release-notes.asciidoc
  docs/upgrading.asciidoc
  script/renamed_fields.py
Labels: backport, docs

#1955 [Docs] Backport docs to 7.x
  changelogs/7.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/context.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/loggingconfig.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/security/basic-auth.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/security/user-access.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-logstash-config.asciidoc
  docs/field-name-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/index.asciidoc
  docs/guide/opentracing.asciidoc
  docs/index.asciidoc
  docs/release-notes.asciidoc
  docs/upgrading.asciidoc
  script/renamed_fields.py
Labels: backport, docs

#1970 [7.0] Make Ingest pipeline path explicit (#1963)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config.go
Labels: backport
