Repository elastic/apm-server, pull requests merged in 2019-11, with the labels that each got.

#2890 [apm-ci] suppress the NativeCommandError in windows builds
  script/jenkins/windows-build.ps1
  script/jenkins/windows-test.ps1
Labels: automation, bug, ci

#2741 [docs] Use shared docs file
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/storage-management.asciidoc
  docs/version.asciidoc
Labels: docs

#2896 Add failure handling to ingest pipelines.
  ingest/pipeline/definition.json
Labels: [zube]: In Review, v7.5.0

#2900 [7.x] Add failure handling to ingest pipelines. (#2896)
  ingest/pipeline/definition.json
Labels: backport

#2901 [7.5] Add failure handling to ingest pipelines. (#2896)
  ingest/pipeline/definition.json
Labels: backport

#2894 [7.4][docs] Use shared docs file (#2741)
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/storage-management.asciidoc
  docs/version.asciidoc
Labels: docs

#2893 [7.5][docs] Use shared docs file (#2741)
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/storage-management.asciidoc
  docs/version.asciidoc
Labels: docs

#2892 [7.x][docs] Use shared docs file (#2741)
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/repositories.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/ilm-setup.asciidoc
  docs/index.asciidoc
  docs/storage-management.asciidoc
  docs/version.asciidoc
Labels: docs

#2876 [docs] ILM documentation updates
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/ilm-setup.asciidoc
  docs/ilm.asciidoc
Labels: docs

#2902 [7.x] [docs] ILM documentation updates (#2876)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/ilm-setup.asciidoc
  docs/ilm.asciidoc
Labels: backport

#2903 [7.5] [docs] ILM documentation updates (#2876)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/ilm-setup.asciidoc
  docs/ilm.asciidoc
Labels: backport

#2904 ci(jenkins): update argument
  Jenkinsfile
Labels: automation, ci

#2911 Fix RUM agent name to js-base.
  agentcfg/model.go
  tests/system/test_integration_acm.py
Labels: bug

#2914 [7.x] Fix RUM agent name to js-base. (#2911) (#2912)
  agentcfg/model.go
  tests/system/test_integration_acm.py
Labels: backport

#2891 [apm-ci] When asciidoc speedup skip some stages
  Jenkinsfile
Labels: automation, ci, docs, enhancement

#2920 [7.x] Add the `Access-Control-Expose-Headers` header to the agent config response. (#2918) (#2919)
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/headers/keys.go
  beater/middleware/cors_middleware.go
Labels: backport

#2924 [7.5] build with go 1.12.12 (#2922)
  .go-version
  Dockerfile
  README.md
  changelogs/7.5.asciidoc
  docs/version.asciidoc
Labels: backport

#2923 [7.x] build with go 1.12.12 (#2922)
  .go-version
  Dockerfile
  README.md
  changelogs/7.5.asciidoc
  docs/version.asciidoc
Labels: backport

#2925 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#2908 [7.5][docs] 7.5.0 release notes and breaking changes
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/breakdown-release-notes.png
  docs/guide/images/jvm-release-notes.png
  docs/guide/images/remote-config-release-notes.png
Labels: docs, v7.5.0

#2929 [7.5][docs] Fix documentation tag
  docs/guide/apm-breaking-changes.asciidoc
Labels: docs

#2928 [7.x][docs] 7.5.0 release notes and breaking changes (#2908)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/breakdown-release-notes.png
  docs/guide/images/jvm-release-notes.png
  docs/guide/images/remote-config-release-notes.png
Labels: docs

#2927 [docs] 7.5.0 release notes and breaking changes (#2908)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/breakdown-release-notes.png
  docs/guide/images/jvm-release-notes.png
  docs/guide/images/remote-config-release-notes.png
Labels: docs

#2926 Returns a sentinel value as Etag when there is no config in Kibana.
  agentcfg/cache_test.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: [zube]: In Review

#2932 [7.x] Returns a sentinel value as Etag when there is no config in Kibana. (#2926)
  agentcfg/cache_test.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: backport

#2933 [7.5] Returns a sentinel value as Etag when there is no config in Kibana. (#2926)
  agentcfg/cache_test.go
  agentcfg/fetch_test.go
  agentcfg/model.go
  agentcfg/model_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: backport

#2907 [6.8][docs] 6.8.5 release notes and version bump
  changelogs/6.8.asciidoc
  docs/version.asciidoc
Labels: docs

#2947 [7.0] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2946 [7.1] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2945 [7.2] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2944 [7.3] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2943 [7.4] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2942 [7.5] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2940 [7.x] Sync changelog. (#2939)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#2950 docs: fix changelog link
  changelogs/7.5.asciidoc
Labels: docs

#2952 [7.5] docs: fix changelog link (#2950)
  changelogs/7.5.asciidoc
Labels: backport

#2938 [7.x] Fix bug in testdata for error event (#2931)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  docs/data/intake-api/generated/events.ndjson
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  testdata/intake-v2/events.ndjson
Labels: backport

#2951 [7.x] docs: fix changelog link (#2950)
  changelogs/7.5.asciidoc
Labels: backport

#2959 Fix: respect setting for overwriting ILM setup
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/manager_test.go
Labels: bug

#2960 [7.x] Fix: respect setting for overwriting ILM setup (#2959)
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/manager_test.go
Labels: backport

#2961 [7.5] Fix: respect setting for overwriting ILM setup (#2959)
  idxmgmt/ilm/supporter_factory.go
  idxmgmt/manager_test.go
Labels: backport

#2956 [docs] Updates to the shared beats docs for 7.5
  docs/configuring.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/outputs/output-cloud.asciidoc
  docs/copied-from-beats/outputs/output-kafka.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/outputs/output-redis.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-securing-beat.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/template-config.asciidoc
Labels: docs

#2966 [DOCS] Fixes security links
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/security/beats-system.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
Labels: docs

#2964 [7.x] [docs] Updates to the shared beats docs for 7.5 (#2956)
  docs/configuring.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/outputs/output-cloud.asciidoc
  docs/copied-from-beats/outputs/output-kafka.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/outputs/output-redis.asciidoc
  docs/copied-from-beats/security/beats-system.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-securing-beat.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/template-config.asciidoc
Labels: backport

#2965 [7.5] [docs] Updates to the shared beats docs for 7.5 (#2956)
  docs/configuring.asciidoc
  docs/copied-from-beats/command-reference.asciidoc
  docs/copied-from-beats/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/outputconfig.asciidoc
  docs/copied-from-beats/outputs/output-cloud.asciidoc
  docs/copied-from-beats/outputs/output-kafka.asciidoc
  docs/copied-from-beats/outputs/output-logstash.asciidoc
  docs/copied-from-beats/outputs/output-redis.asciidoc
  docs/copied-from-beats/security/beats-system.asciidoc
  docs/copied-from-beats/security/securing-beats.asciidoc
  docs/copied-from-beats/shared-docker.asciidoc
  docs/copied-from-beats/shared-securing-beat.asciidoc
  docs/copied-from-beats/shared-ssl-config.asciidoc
  docs/copied-from-beats/shared-template-load.asciidoc
  docs/copied-from-beats/template-config.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/index.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/template-config.asciidoc
Labels: backport

#2970 ci(jenkins): change log rotation, use cached repo
  .ci/check-changelogs.groovy
  .ci/jobs/apm-server-check-changelogs-mbp.yml
  .ci/jobs/apm-server-mbp.yml
  .ci/jobs/defaults.yml
  Jenkinsfile
Labels: automation, ci

#2971 ci(jenkins): use git reference repo
  .ci/check-changelogs.groovy
  Jenkinsfile
Labels: automation, ci

#2948 feat: grab docker container logs after run tests
  .ci/scripts/docker-get-logs.sh
  Jenkinsfile
  script/jenkins/linux-test.sh
Labels: automation, ci, enhancement

#2839 Experimental self-profiling
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/mux.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  beater/beater.go
  beater/config/config.go
  beater/config/instrumentation.go
  beater/integration_test.go
  beater/server_test.go
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  changelogs/head.asciidoc
  decoder/limited_reader.go
  decoder/limited_reader_test.go
  docs/fields.asciidoc
  idxmgmt/ilm/policy.go
  idxmgmt/indices.go
  idxmgmt/indices_test.go
  idxmgmt/manager_test.go
  include/fields.go
  model/profile/_meta/fields.yml
  model/profile/profile.go
  model/profile/profile_test.go
  testdata/profile/cpu.pprof
  testdata/profile/heap.pprof
  testdata/profile/metadata.json
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
  tests/system/test_setup_index_management.py
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/go.mod
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/google/pprof/LICENSE
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/filter.go
  vendor/github.com/google/pprof/profile/index.go
  vendor/github.com/google/pprof/profile/legacy_java_profile.go
  vendor/github.com/google/pprof/profile/legacy_profile.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/google/pprof/profile/proto.go
  vendor/github.com/google/pprof/profile/prune.go
  vendor/vendor.json
Labels: [zube]: In Review
