Repository elastic/apm-server, pull requests merged in 2020-08, with the labels that each got.

#4047 [Docs]Replaces SIEM terminology
  docs/guide/apm-release-notes.asciidoc
Labels: v7.9.0

#4048 [7.x] [Docs]Replaces SIEM terminology (#4047)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#4049 [7.9] [Docs]Replaces SIEM terminology (#4047)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#4030 beater/middleware: log event.duration
  beater/middleware/log_middleware.go
  beater/middleware/log_middleware_test.go
  changelogs/head.asciidoc
Labels: enhancement

#3971 Flush aggregator on shutdown
  beater/beater.go
  changelogs/head.asciidoc
  publish/acker.go
  publish/pub.go
  publish/pub_test.go
  tests/system/test_aggregation.py
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
Labels: v7.10.0

#4042 docs: Add 7.9 release highlights
  changelogs/7.9.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: v7.9.0

#4053 [docs] Fix OpenTelemetry link in release highlights
  docs/guide/apm-release-notes.asciidoc
Labels: docs, v7.9.0

#4051 [7.x] [docs] Add 7.9 release highlights (#4042)
  changelogs/7.9.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: 7.10.0, backport

#4052 [7.9][docs] Add 7.9 release highlights (#4042)
  changelogs/7.9.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#4058 Remove ssl.certificate_authorities from apm-server.yml
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/ssl-input-settings.asciidoc
Labels: docs

#4072 Refactor decoder to take stuct as parameter instead of creating and returning map struct
  agentcfg/cache_test.go
  beater/authorization/privilege_test.go
  decoder/stream_decoder.go
  decoder/stream_decoder_test.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/processor.go
Labels: review

#4069 systemtest: add stack monitoring test
  systemtest/apmservertest/config.go
  systemtest/apmservertest/logs.go
  systemtest/apmservertest/server.go
  systemtest/elasticsearch.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/monitoring_test.go
  tests/system/test_monitoring.py
Labels: [zube]: In Review

#4078 Update beats framework to 744391a84931 + version bump
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  tests/system/es_helper.py
Labels: v7.9.0

#4080 docs: 6.8.12 release notes
  changelogs/6.8.asciidoc
Labels: docs

#4073 [DOCS] Fixes broken link in Release Notes
  docs/guide/apm-release-notes.asciidoc
Labels: docs, v7.10.0, v7.9.0, v8.0.0

#4082 [7.9] [DOCS] Fixes broken link in Release Notes (#4073)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#4081 [7.x] [DOCS] Fixes broken link in Release Notes (#4073)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#4091 [7.x] Flush aggregator on shutdown (#3971)
  beater/beater.go
  publish/acker.go
  publish/pub.go
  publish/pub_test.go
  tests/system/test_aggregation.py
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
Labels: backport

#4094 [7.x] Remove ssl.certificate_authorities from apm-server.yml (#4058)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/ssl-input-settings.asciidoc
Labels: backport

#4093 [7.x] Decouple event inputs from transformation (#4054)
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/handler_test.go
  beater/api/intake/handler_test.go
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/mux_test.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  beater/authorization/builder_test.go
  beater/beater.go
  beater/beater_test.go
  beater/config/aggregation_test.go
  beater/config/config.go
  beater/config/config_test.go
  beater/config/instrumentation_test.go
  beater/config/rum.go
  beater/config/rum_test.go
  beater/jaeger/server.go
  beater/jaeger/server_test.go
  beater/onboarding.go
  cmd/apikey.go
  go.sum
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/error.go
  model/modeldecoder/metricset.go
  model/modeldecoder/span.go
  model/modeldecoder/transaction.go
  model/profile.go
  model/profile_test.go
  model/sourcemap.go
  model/sourcemap_test.go
  model/span.go
  model/span_test.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  model/transaction.go
  model/transaction_test.go
  processor/asset/sourcemap/package_tests/processor_test.go
  processor/asset/sourcemap/package_tests/test_processor.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/stream/benchmark_test.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  publish/pub.go
  publish/pub_test.go
  transform/transform.go
Labels: backport

#4096 [7.x] elasticsearch: honour "headers" config (#4090)
  NOTICE.txt
  elasticsearch/client.go
  elasticsearch/client_test.go
  elasticsearch/config.go
  elasticsearch/config_test.go
  elasticsearch/estest/client.go
  go.mod
  go.sum
Labels: backport

#4095 [7.x] publish: fix shutdown timeout handling (#4075)
  publish/acker.go
  publish/pub_test.go
Labels: backport

#4099 [7.9] elasticsearch: honour "headers" config (#4090)
  NOTICE.txt
  elasticsearch/client.go
  elasticsearch/client_test.go
  elasticsearch/config.go
  elasticsearch/config_test.go
  elasticsearch/estest/client.go
  go.mod
  go.sum
Labels: backport

#4101 [7.x] Use peer.address for DestinationService.Resource when converting a Jaeger span (#3975)
  changelogs/7.9.asciidoc
  processor/otel/consumer.go
  processor/otel/test_approved/span_jaeger_http.approved.json
Labels: backport

#4100 [7.x] beater/middleware: log event.duration (#4030)
  beater/middleware/log_middleware.go
  beater/middleware/log_middleware_test.go
Labels: backport

#4098 [7.x] Add transaction.experience metrics (#4056)
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/fields.asciidoc
  docs/spec/rum_experience.json
  docs/spec/transactions/rum_v3_transaction.json
  docs/spec/transactions/transaction.json
  include/fields.go
  model/experience.go
  model/experience_test.go
  model/modeldecoder/experience.go
  model/modeldecoder/field/rum_v3_mapping.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction.go
  model/transaction/_meta/fields.yml
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v2/transactions_spans_rum.ndjson
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#4121 [7.x] Add telemetry for apm-server configuration (#4055)
  beater/beater.go
  beater/telemetry.go
  beater/telemetry_test.go
  idxmgmt/supporter_factory.go
Labels: backport

#4124 [7.x] Refactor transaction metrics aggregation, rename config (#4083)
  beater/config/aggregation.go
  beater/config/aggregation_test.go
  beater/config/config.go
  beater/config/config_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_sampling.py
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
Labels: backport
