Repository elastic/apm-server, pull requests merged in 2020-09, with the labels that each got.

#4116 processor/otel: set Span.RepresentativeCount
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
Labels: v7.10.0

#4129 [7.x] aggregation/txmetrics: include transaction outcome (#4110)
  model/metricset.go
  model/metricset_test.go
  tests/system/rum_transaction_histogram_metrics.approved.json
  tests/system/transaction_histogram_metrics.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport

#4131 aggregation/spanmetrics: add max_groups config
  beater/config/aggregation.go
  beater/config/config_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/main.go
Labels: v7.10.0

#4136 [CI][docker] prepare required context
  .ci/docker/Makefile
  .gitignore
Labels: automation, bug, ci

#4128 [7.x] Span metrics (#4077)
  beater/config/aggregation.go
  beater/config/config_test.go
  docs/fields.asciidoc
  docs/spec/spans/rum_v3_span.json
  docs/spec/spans/span.json
  docs/spec/transactions/rum_v3_transaction.json
  docs/spec/transactions/transaction.json
  log/selectors.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/field/rum_v3_mapping.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/span.go
  model/span/generated/schema/rum_v3_span.go
  model/span/generated/schema/span.go
  model/span_test.go
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
  x-pack/apm-server/main.go
Labels: backport

#4144 [7.9][docs] 7.9.1 release notes
  changelogs/7.9.asciidoc
Labels: docs, v7.9.1

#4145 [7.x] Cherry-pick 7.9.1 release notes
  changelogs/7.9.asciidoc
Labels: backport

#4140 [7.x] Change sourcemap logging (#4132)
  model/stacktrace.go
Labels: backport

#4151 [7.x] Introduce Go system tests (#3790)
  .gitignore
  script/jenkins/linux-test.sh
  systemtest/apikeycmd_test.go
  systemtest/apmservertest/command.go
  systemtest/apmservertest/config.go
  systemtest/apmservertest/expvar.go
  systemtest/apmservertest/logs.go
  systemtest/apmservertest/server.go
  systemtest/apmservertest/server_test.go
  systemtest/apmservertest/server_unix.go
  systemtest/apmservertest/server_windows.go
  systemtest/cmdflags_test.go
  systemtest/containers.go
  systemtest/elasticsearch.go
  systemtest/estest/client.go
  systemtest/estest/query.go
  systemtest/estest/request.go
  systemtest/estest/search.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/instrumentation_test.go
  systemtest/jaeger_test.go
  systemtest/main_test.go
  systemtest/onboarding_test.go
  tests/system/test_apikey_cmd.py
  tests/system/test_integration.py
  tests/system/test_integration_logging.py
  tests/system/test_jaeger.py
Labels: backport

#4155 [7.x] systemtest: fix API Key system test (#4063)
  systemtest/apikeycmd_test.go
Labels: backport

#4156 [7.x] systemtest: add stack monitoring test (#4069)
  systemtest/apmservertest/config.go
  systemtest/apmservertest/logs.go
  systemtest/apmservertest/server.go
  systemtest/elasticsearch.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/monitoring_test.go
  tests/system/test_monitoring.py
Labels: backport

#4152 [7.x] overwrite referrer (#3958)
  _meta/fields.common.yml
  include/fields.go
Labels: backport

#4160 [7.x] cmd/pprofessor: introduce pprof-based tool (#4017)
  NOTICE.txt
  beater/integration_test.go
  cmd/pprofessor/README.md
  cmd/pprofessor/fetcher.go
  cmd/pprofessor/flags.go
  cmd/pprofessor/pprof.go
  docs/fields.asciidoc
  go.mod
  go.sum
  include/fields.go
  model/profile.go
  model/profile/_meta/fields.yml
  model/profile_test.go
  tests/approvals/approvals.go
Labels: backport

#4161 [7.x] systemtest: migrate request logging tests to Go (#4074)
  systemtest/go.mod
  systemtest/logging_test.go
  tests/system/test_integration_logging.py
Labels: backport

#4157 [7.x] docs: fix errant "None" in APM Transaction fields (#4107)
  _meta/fields.common.yml
  docs/fields.asciidoc
  include/fields.go
  model/transaction/_meta/fields.yml
Labels: backport

#4158 [7.x] all: staticcheck cleanups (#4115)
  beater/beatertest/config.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  pipelistener/doc.go
  pipelistener/listener.go
  pipelistener/listener_test.go
  processor/stream/package_tests/intake_test_processor.go
  publish/pub.go
  utility/data_fetcher.go
  utility/map_str_enhancer.go
Labels: backport

#4166 [7.x] processor/otel: set Span.RepresentativeCount (#4116)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
Labels: backport

#4168 [7.x] aggregation/spanmetrics: add event.outcome (#4118)
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: backport

#4169 [7.x] processor/otel: set outcome from status code (#4127)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/consume_span.approved.json
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  testdata/jaeger/batch_0.approved.json
Labels: backport

#4170 [7.x] aggregation/spanmetrics: add max_groups config (#4131)
  beater/config/aggregation.go
  beater/config/config_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/main.go
Labels: backport

#4167 [7.x] sampling/eventstorage: introduce event storage (#4108)
  NOTICE.txt
  go.mod
  go.sum
  x-pack/apm-server/sampling/eventstorage/codec.go
  x-pack/apm-server/sampling/eventstorage/jsoncodec.go
  x-pack/apm-server/sampling/eventstorage/logger.go
  x-pack/apm-server/sampling/eventstorage/sharded.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
Labels: backport

#4171 [7.x] systemtest: add tests for aggregation and sampling (#4084)
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/apmservertest/filter.go
  systemtest/apmservertest/server.go
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/estest/query.go
  systemtest/logging_test.go
  systemtest/sampling_test.go
  tests/system/rum_transaction_histogram_metrics.approved.json
  tests/system/test_aggregation.py
  tests/system/transaction_histogram_metrics.approved.json
Labels: backport

#4172 [7.x] Fix indentation in instrumentation section of config (#4147)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: backport

#4173 [7.x] sampling/pubsub: new package for coordination (#4139)
  go.mod
  log/selectors.go
  x-pack/apm-server/sampling/pubsub/config.go
  x-pack/apm-server/sampling/pubsub/config_test.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
  x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
  x-pack/apm-server/sampling/pubsub/pubsub_test.go
Labels: backport

#4175 ci: only run Package on Beats update or comment
  Jenkinsfile
Labels: ci

#4130 docs: Add required privileges for using API Keys
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/feature-roles.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: docs, v7.9.0

#4126 docs: APM Server documentation updates
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/shared-configuring.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared/configuring-intro.asciidoc
  docs/copied-from-beats/docs/step-test-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/howto.asciidoc
  docs/ssl-input-settings.asciidoc
  docs/template-config.asciidoc
Labels: docs, v7.9.0

#4179 [7.9] docs: Add required privileges for using API Keys (#4130)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/feature-roles.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: backport

#4178 [7.x] docs: Add required privileges for using API Keys (#4130)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/feature-roles.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: backport

#4181 [7.9] docs: APM Server documentation updates (#4126)
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/shared-configuring.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared/configuring-intro.asciidoc
  docs/copied-from-beats/docs/step-test-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/howto.asciidoc
  docs/ssl-input-settings.asciidoc
  docs/template-config.asciidoc
Labels: backport

#4180 [7.x] docs: APM Server documentation updates (#4126)
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/howto/load-index-templates.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/shared-configuring.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared/configuring-intro.asciidoc
  docs/copied-from-beats/docs/step-test-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/howto.asciidoc
  docs/ssl-input-settings.asciidoc
  docs/template-config.asciidoc
Labels: backport

#4184 [7.x] Derive outcome from the HTTP status code when available (#4165)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
Labels: backport

#4187 [7.x] Makefile: fix golint target (#4183)
  Makefile
Labels: backport

#4189 [7.x] systemtest: retry deleting ILM policy (#4186)
  systemtest/elasticsearch.go
Labels: backport

#4193 [7.9] processor/otel: de-dot metadata labels (#4191)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/metadata_jaeger.approved.json
Labels: backport

#4194 [7.x] Fix metadata.service.* fields requirements in json schema (#4142)
  beater/api/profile/handler_test.go
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  docs/spec/cloud.json
  docs/spec/metadata.json
  docs/spec/rum_v3_metadata.json
  model/metadata/generated/schema/metadata.go
  model/metadata/generated/schema/rum_v3_metadata.go
  model/modeldecoder/metadata_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  testdata/profile/metadata.json
  tests/json_schema.go
Labels: backport

#4196 [7.x] ci: build apm-server before running systemtests (#4195)
  script/jenkins/linux-test.sh
Labels: backport

#4192 [7.x] processor/otel: de-dot metadata labels (#4191)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/metadata_jaeger.approved.json
Labels: backport

#4198 [7.x] Update index pattern path (#3822)
  script/are_kibana_saved_objects_updated.py
  script/update_kibana_objects.py
Labels: backport

#4199 aggregation/spanmetrics: rename metrics
  docs/fields.asciidoc
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/go.mod
  systemtest/go.sum
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
Labels: v7.10.0

#4200 [7.x] aggregation/spanmetrics: rename metrics (#4199)
  docs/fields.asciidoc
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/go.mod
  systemtest/go.sum
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
Labels: backport

#4209 [7.x] systemtest: add test for RUM & X-Forwarded-For (#4208)
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/estest/search.go
  systemtest/instrumentation_test.go
  systemtest/jaeger_test.go
  systemtest/monitoring_test.go
  systemtest/onboarding_test.go
  systemtest/rum_test.go
  systemtest/sampling_test.go
Labels: backport

#4211 [7.x] Add mapping for cgroup metrics. (#4176)
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/fields.asciidoc
  include/fields.go
  model/metricset/_meta/fields.yml
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultMetricsets.approved.json
  testdata/intake-v2/metricsets.ndjson
  tests/system/metricset.approved.json
  tests/system/test_integration.py
Labels: backport

#4214 [7.x] model/modeldecoder: parse transaction.sample_rate (#4212)
  model/modeldecoder/span.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/span.go
  model/transaction.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport, v7.10.0

#4213 [7.x] Remove unused inactive_file metric field (#4210)
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/fields.asciidoc
  include/fields.go
  model/metricset/_meta/fields.yml
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  testdata/intake-v2/metricsets.ndjson
  tests/system/metricset.approved.json
Labels: backport

#4216 [7.x] sampling: add trace group sampling reservoirs (#4182)
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/reservoir.go
  x-pack/apm-server/sampling/reservoir_test.go
Labels: backport

#4215 sampling: fix keep_unsampled processor
  changelogs/head.asciidoc
  sampling/sampling.go
  sampling/sampling_test.go
Labels: bug

#4217 [7.x] sampling: fix keep_unsampled processor (#4215)
  sampling/sampling.go
  sampling/sampling_test.go
Labels: backport, v7.10.0

#4219 docs: point to new CCS content
  docs/guide/cross-cluster-search.asciidoc
Labels: v7.9.0

#4220 [7.x] docs: point to new CCS content (#4219)
  docs/guide/cross-cluster-search.asciidoc
Labels: backport

#4221 [7.9] docs: point to new CCS content (#4219)
  docs/guide/cross-cluster-search.asciidoc
Labels: backport

#4224 [7.x] Remove/unexport/inline various utility functions (#4223)
  agentcfg/fetch.go
  agentcfg/model.go
  idxmgmt/manager.go
  model/modeldecoder/context_test.go
  model/modeldecoder/metricset.go
  utility/common.go
  utility/common_test.go
  utility/data_fetcher.go
  utility/data_fetcher_test.go
  utility/forwarded.go
  utility/forwarded_test.go
  utility/map_str_enhancer.go
  utility/remoteaddr.go
Labels: backport

#4205 Add new transaction decode handling
  model/modeldecoder/generator/cmd/main.go
  model/modeldecoder/generator/generator.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modeldecoder/modeldecodertest/strbuilder.go
  model/modeldecoder/modeldecodertest/testdata.go
  model/modeldecoder/nullable/nullable.go
  model/modeldecoder/nullable/nullable_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/decoder_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/decoder_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/transaction_test.go
Labels: 7.10.0, review

#4233 [7.x] metadata/modeldecoder: transaction decoding (#4205)
  model/modeldecoder/generator/cmd/main.go
  model/modeldecoder/generator/generator.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modeldecoder/modeldecodertest/strbuilder.go
  model/modeldecoder/modeldecodertest/testdata.go
  model/modeldecoder/nullable/nullable.go
  model/modeldecoder/nullable/nullable_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/decoder_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/decoder_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/transaction_test.go
Labels: backport

#4238 [7.x] Add transaction.experience.longtask metrics fields (#4230)
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/fields.asciidoc
  docs/spec/rum_experience.json
  docs/spec/transactions/rum_experience.json
  docs/spec/transactions/rum_v3_experience.json
  docs/spec/transactions/rum_v3_transaction.json
  docs/spec/transactions/transaction.json
  include/fields.go
  model/experience.go
  model/experience_test.go
  model/modeldecoder/experience.go
  model/modeldecoder/field/rum_v3_mapping.go
  model/modeldecoder/generator/generator.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/transaction_test.go
  model/transaction/_meta/fields.yml
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v2/transactions.ndjson
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#4239 7.9 version bump
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  testing/environments/latest.yml
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
  tests/system/es_helper.py
Labels: v7.9.3

#4227 docs: 7.9.2 release notes
  changelogs/7.9.asciidoc
Labels: v7.9.2

#4242 [7.x] script/generate_notice: add UBI to third-party CSV (#4237)
  script/generate_notice.py
Labels: backport

#4244 docs: sync changelogs with 7.9.2 release notes (#4227)
  changelogs/7.9.asciidoc
Labels: docs, v7.10.0

#4245 [7.x] docs: 7.9.2 release notes (#4227) (#4244)
  changelogs/7.9.asciidoc
Labels: backport

#4248 [7.x] Add update_kibana_objects options to reuse clone (#4243)
  script/update_kibana_objects.py
Labels: backport

#4222 docs: improve getting started experience
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/cross-cluster-search.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/features.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/obs-integrations.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/quick-start-overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/whats-new.asciidoc
  docs/tab-widgets/code.asciidoc
  docs/tab-widgets/configure-agent-widget.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/configure-server-widget.asciidoc
  docs/tab-widgets/configure-server.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/tab-widgets/open-kibana-widget.asciidoc
  docs/tab-widgets/open-kibana.asciidoc
  docs/tab-widgets/spin-up-stack-widget.asciidoc
  docs/tab-widgets/spin-up-stack.asciidoc
  docs/upgrading.asciidoc
Labels: docs, v7.9.0

#4252 [7.9] docs: improve getting started experience (#4222)
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/cross-cluster-search.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/features.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/obs-integrations.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/quick-start-overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/whats-new.asciidoc
  docs/tab-widgets/code.asciidoc
  docs/tab-widgets/configure-agent-widget.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/configure-server-widget.asciidoc
  docs/tab-widgets/configure-server.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/tab-widgets/open-kibana-widget.asciidoc
  docs/tab-widgets/open-kibana.asciidoc
  docs/tab-widgets/spin-up-stack-widget.asciidoc
  docs/tab-widgets/spin-up-stack.asciidoc
  docs/upgrading.asciidoc
Labels: backport, docs

#4251 [7.x] docs: improve getting started experience (#4222)
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/cross-cluster-search.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/features.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
  docs/guide/obs-integrations.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/quick-start-overview.asciidoc
  docs/guide/redirects.asciidoc
  docs/guide/rum.asciidoc
  docs/guide/whats-new.asciidoc
  docs/tab-widgets/code.asciidoc
  docs/tab-widgets/configure-agent-widget.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/configure-server-widget.asciidoc
  docs/tab-widgets/configure-server.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/tab-widgets/open-kibana-widget.asciidoc
  docs/tab-widgets/open-kibana.asciidoc
  docs/tab-widgets/spin-up-stack-widget.asciidoc
  docs/tab-widgets/spin-up-stack.asciidoc
  docs/upgrading.asciidoc
Labels: backport, docs

#4253 [7.x] docs: update release highlight include
  docs/guide/apm-release-notes.asciidoc
  docs/guide/index.asciidoc
  docs/guide/whats-new.asciidoc
Labels: backport, docs

#4254 [7.9] docs: update release highlight include
  docs/guide/apm-release-notes.asciidoc
  docs/guide/index.asciidoc
  docs/guide/whats-new.asciidoc
Labels: backport, docs
