Repository elastic/apm-server, pull requests merged in 2020-06, with the labels that each got.

#3832 Update beats framework to 6e91ce4988a7 fixes duplicate dynamic template names
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  processor/otel/consumer_test.go
  testing/environments/latest.yml
Labels: v7.9.0

#3834 [7.8] Update beats framework to 2c8f3147d1b7 and go version
  .ci/docker/golang-mage/Dockerfile
  .go-version
  Dockerfile
  NOTICE.txt
  README.md
  changelogs/7.8.asciidoc
  docs/version.asciidoc
  go.mod
  go.sum
  testing/environments/docker/elasticsearch_kerberos/Dockerfile
  testing/environments/latest.yml
  tests/Dockerfile
Labels: v7.8.0

#3839 docs: add 7.7.1 release notes
  changelogs/7.7.asciidoc
Labels: docs

#3838 docs: 6.8.10 release notes and version bump
  changelogs/6.8.asciidoc
  docs/version.asciidoc
Labels: docs

#3840 [7.x] Update go version to 1.13.10 (#3835)
  .ci/docker/golang-mage/Dockerfile
  .go-version
  Dockerfile
  README.md
  changelogs/7.8.asciidoc
  docs/version.asciidoc
  tests/Dockerfile
Labels: backport

#3842 [7.7] version bump through beats update
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  testing/environments/docker/kafka/Dockerfile
  testing/environments/latest.yml
  testing/environments/local.yml
  tests/system/es_helper.py
Labels: 7.7.2

#3843 [6.8] version bump through beats update
  NOTICE.txt
  _beats/libbeat/docs/version.asciidoc
  _beats/testing/environments/latest.yml
  _beats/testing/environments/snapshot-oss.yml
  _beats/testing/environments/snapshot.yml
  vendor/github.com/elastic/beats/libbeat/version/version.go
  vendor/vendor.json
Labels: v6.8

#3830 [7.x] docs: Update security documentation (#3799)
  docs/configure-kibana-endpoint.asciidoc
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/tls.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-logstash-config.asciidoc
  docs/feature-roles.asciidoc
  docs/index.asciidoc
Labels: backport

#3831 [7.8] docs: Update security documentation (#3799)
  docs/configure-kibana-endpoint.asciidoc
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/tls.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-logstash-config.asciidoc
  docs/feature-roles.asciidoc
  docs/index.asciidoc
Labels: backport

#3844 docs: Sync changelogs
  changelogs/6.8.asciidoc
  changelogs/7.7.asciidoc
  script/check_changelogs.py
Labels: docs, v7.8.0

#3853 model: make ID fields non-pointer string types
  model/error.go
  model/error_test.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  processor/otel/consumer.go
  utility/map_str_enhancer.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: v7.9.0

#3854 [7.x] aggregation/txmetrics: don't group on user-agent (#3848)
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport

#3856 [7.x] model: make ID fields non-pointer string types (#3853)
  model/error.go
  model/error_test.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  processor/otel/consumer.go
  utility/map_str_enhancer.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport

#3852 [7.7] docs: Sync changelogs (#3844)
  changelogs/6.8.asciidoc
Labels: backport

#3851 [7.8] docs: Sync changelogs (#3844)
  changelogs/6.8.asciidoc
  changelogs/7.7.asciidoc
Labels: backport

#3850 [7.x] docs: Sync changelogs (#3844)
  changelogs/6.8.asciidoc
  changelogs/7.7.asciidoc
Labels: backport

#3845 docs: OpenTelemetry Elastic exporter
  docs/guide/images/open-telemetry-elastic-arch.png
  docs/guide/index.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: docs

#3864 Update beats framework to a516c366f471
  NOTICE.txt
  go.mod
  go.sum
Labels: review, v7.8.0

#3857 Index page URL as ECS field
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  include/fields.go
  model/context.go
  model/error.go
  model/error_test.go
  model/modeldecoder/context.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/test_approved_model/context_client_ip_from_forwarded_header.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket_invalid_headers.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_header_case_insensitive.approved.json
  model/modeldecoder/test_approved_model/context_empty.approved.json
  model/modeldecoder/test_approved_model/context_experimental is not true.approved.json
  model/modeldecoder/test_approved_model/context_full_event with experimental=true.approved.json
  model/modeldecoder/test_approved_model/context_input_nil.approved.json
  model/modeldecoder/test_approved_model/context_no_url_protocol.approved.json
  model/modeldecoder/test_approved_model/context_request_body_string.approved.json
  model/modeldecoder/test_approved_model/context_url_port_string.approved.json
  model/modeldecoder/test_approved_model/context_user_id_integer.approved.json
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/consumer.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
Labels: [zube]: In Progress, v7.9.0

#3859 [7.x] docs: OpenTelemetry Elastic exporter (#3845)
  docs/guide/images/open-telemetry-elastic-arch.png
  docs/guide/index.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#3860 [7.8] docs: OpenTelemetry Elastic exporter (#3845)
  docs/guide/images/open-telemetry-elastic-arch.png
  docs/guide/index.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#3866 Include field name in decoding errors
  model/modeldecoder/context_test.go
  model/modeldecoder/metricset_test.go
  utility/data_fetcher.go
  utility/data_fetcher_test.go
Labels: [zube]: In Review

#3865 [7.x] Index page URL and Referer as ECS fields (#3857)
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  include/fields.go
  model/context.go
  model/error.go
  model/error_test.go
  model/modeldecoder/context.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/test_approved_model/context_client_ip_from_forwarded_header.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket_invalid_headers.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_header_case_insensitive.approved.json
  model/modeldecoder/test_approved_model/context_empty.approved.json
  model/modeldecoder/test_approved_model/context_experimental is not true.approved.json
  model/modeldecoder/test_approved_model/context_full_event with experimental=true.approved.json
  model/modeldecoder/test_approved_model/context_input_nil.approved.json
  model/modeldecoder/test_approved_model/context_no_url_protocol.approved.json
  model/modeldecoder/test_approved_model/context_request_body_string.approved.json
  model/modeldecoder/test_approved_model/context_url_port_string.approved.json
  model/modeldecoder/test_approved_model/context_user_id_integer.approved.json
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/consumer.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  tests/system/drop_unsampled_transactions.approved.json
  tests/system/error.approved.json
  tests/system/keep_unsampled_transactions.approved.json
  tests/system/transaction.approved.json
Labels: backport

#3872 [7.x] Include field name in decoding errors (#3866)
  model/modeldecoder/context_test.go
  model/modeldecoder/metricset_test.go
  utility/data_fetcher.go
  utility/data_fetcher_test.go
Labels: backport

#3869 docs: 7.8.0 release notes, breaking changes, highlights
  CHANGELOG.asciidoc
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.4.asciidoc
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
  changelogs/7.1.asciidoc
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  changelogs/7.4.asciidoc
  changelogs/7.5.asciidoc
  changelogs/7.6.asciidoc
  changelogs/7.7.asciidoc
  changelogs/7.8.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.8-service-map-anomaly.png
  docs/release-notes.asciidoc
Labels: docs

#3861 [7.7] docs: OpenTelemetry Elastic exporter (#3845)
  docs/guide/images/open-telemetry-elastic-arch.png
  docs/guide/index.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#3887 [7.x] docs: 7.8.0 release notes, breaking changes, highlights (#3869)
  CHANGELOG.asciidoc
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.4.asciidoc
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
  changelogs/7.1.asciidoc
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  changelogs/7.4.asciidoc
  changelogs/7.5.asciidoc
  changelogs/7.6.asciidoc
  changelogs/7.7.asciidoc
  changelogs/7.8.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.8-service-map-anomaly.png
  docs/release-notes.asciidoc
Labels: backport

#3888 [7.8] docs: 7.8.0 release notes, breaking changes, highlights (#3869)
  CHANGELOG.asciidoc
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.4.asciidoc
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
  changelogs/7.1.asciidoc
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  changelogs/7.4.asciidoc
  changelogs/7.5.asciidoc
  changelogs/7.6.asciidoc
  changelogs/7.7.asciidoc
  changelogs/7.8.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.8-service-map-anomaly.png
  docs/release-notes.asciidoc
Labels: backport

#3890 docs: update greater than equal to symbol
  docs/breaking-changes.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/upgrading-to-70.asciidoc
Labels: docs, v7.8.0

#3892 [7.8] docs: update greater than equal to symbol (#3890)
  docs/breaking-changes.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/upgrading-to-70.asciidoc
Labels: backport

#3891 [7.x] docs: update greater than equal to symbol (#3890)
  docs/breaking-changes.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/upgrading-to-70.asciidoc
Labels: backport

#3889 fix: check that docker is installed
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, bug, ci

#3893 [DOCS] Fixes license management link
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: 7.7.2, docs, v7.5.0, v7.6.1, v7.8.0, v7.9.0, v8.0.0

#3898 [7.x] [DOCS] Fixes license management link (#3893)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: backport

#3899 [7.8] [DOCS] Fixes license management link (#3893)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: backport

#3900 [7.7] [DOCS] Fixes license management link (#3893)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: backport

#3901 [7.6] [DOCS] Fixes license management link (#3893)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: backport

#3902 [7.5] [DOCS] Fixes license management link (#3893)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
Labels: backport

#3906 7.8 update version
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  tests/system/es_helper.py
Labels: review

#3907 [jjbb]: folder description is required
  .ci/jobs/apm-server.yml
Labels: automation, ci

#3905 ILM: restrict customization of alias to suffix.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/head.asciidoc
  docs/ilm-reference.asciidoc
  docs/ilm.asciidoc
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/supporter_factory.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_setup_index_management.py
Labels: review, test-plan, v7.9.0

#3911 [7.x] ILM: restrict customization of alias to suffix. (#3905)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/ilm-reference.asciidoc
  docs/ilm.asciidoc
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
  idxmgmt/ilm/supporter_factory.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_setup_index_management.py
Labels: backport

#3917 Only log error message instead of full document body when validation error occurs
  processor/stream/result.go
  processor/stream/result_test.go
Labels: review

#3921 [7.8] [logging] avoid logging processing error documents (#3917)
  processor/stream/result.go
  processor/stream/result_test.go
Labels: backport
