Repository elastic/apm-server, pull requests merged in 2020-01, with the labels that each got.

#3092 [docs] clarify apm-server.ssl.certificate example
  docs/secure-communication-agents.asciidoc
Labels: docs

#3088 [docs] Fix ILM copy pasta bug
  docs/ilm.asciidoc
Labels: docs

#3103 [7.5] Fixes incorrect name for output.elasticsearch.worker (#2887)
  docs/data-ingestion.asciidoc
Labels: backport

#3102 [7.x] Fixes incorrect name for output.elasticsearch.worker (#2887)
  docs/data-ingestion.asciidoc
Labels: backport

#3101 [7.5] docs: fix ilm copy pasta (#3088)
  docs/ilm.asciidoc
Labels: backport

#3100 [7.x] docs: fix ilm copy pasta (#3088)
  docs/ilm.asciidoc
Labels: backport

#3099 [7.5] docs: change client to apm-server (#3092)
  docs/secure-communication-agents.asciidoc
Labels: backport

#3098 [7.x] docs: change client to apm-server (#3092)
  docs/secure-communication-agents.asciidoc
Labels: backport

#3094 [docs] Match Beats directory structure for copied docs
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/debugging.asciidoc
  docs/copied-from-beats/docs/getting-help.asciidoc
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/keystore.asciidoc
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/docs/outputconfig.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/outputs/output-cloud.asciidoc
  docs/copied-from-beats/docs/repositories.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/beats-system.asciidoc
  docs/copied-from-beats/docs/security/linux-seccomp.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/tls.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/docs/shared-configuring.asciidoc
  docs/copied-from-beats/docs/shared-directory-layout.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
  docs/copied-from-beats/docs/shared-env-vars.asciidoc
  docs/copied-from-beats/docs/shared-path-config.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared-ssl-logstash-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/shared-template-load.asciidoc
  docs/copied-from-beats/docs/step-test-config.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/copied-from-beats/outputs/codec/docs/codec.asciidoc
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
  docs/copied-from-beats/shared-logstash-config.asciidoc
  docs/index.asciidoc
  docs/troubleshooting.asciidoc
  script/copy-docs.py
Labels: docs

#3110 [7.x] intake: Add classname as stacktrace frame attribute (#3096)
  NOTICE.txt
  beater/api/intake/test_approved/Success.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/intake-api/generated/events.ndjson
  docs/spec/stacktrace_frame.json
  model/error/event.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultErrors.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/spans.ndjson
  tests/common.go
Labels: backport

#3107 [7.x] intake: Add rows_affected to span db information (#3095)
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/spans.json
  docs/fields.asciidoc
  docs/spec/spans/span.json
  include/fields.go
  model/span/_meta/fields.yml
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport

#3115 [docs] remove docs/outputs folder
  docs/copied-from-beats/docs/output-cloud.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
Labels: docs

#3113 [7.x] Add message attributes to transactions and spans (#3104)
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/tracing_test.go
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  docs/spec/context.json
  docs/spec/message.json
  docs/spec/spans/span.json
  include/fields.go
  model/context.go
  model/context_test.go
  model/error/generated/schema/error.go
  model/message.go
  model/message_test.go
  model/span/_meta/fields.yml
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/span.go
  model/test_approved_model/context_client_ip_from_forwarded_header.approved.json
  model/test_approved_model/context_client_ip_from_socket.approved.json
  model/test_approved_model/context_client_ip_from_socket_invalid_headers.approved.json
  model/test_approved_model/context_client_ip_header_case_insensitive.approved.json
  model/test_approved_model/context_empty.approved.json
  model/test_approved_model/context_experimental is not true.approved.json
  model/test_approved_model/context_full_event with experimental=true.approved.json
  model/test_approved_model/context_no_context.approved.json
  model/test_approved_model/context_no_url_protocol.approved.json
  model/test_approved_model/context_request_body_string.approved.json
  model/test_approved_model/context_url_port_string.approved.json
  model/test_approved_model/context_user_id_integer.approved.json
  model/transaction/_meta/fields.yml
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/transaction.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultReadError.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultSpans.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultTransactions.approved.json
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  tests/common.go
  tests/system/test_access.py
  tests/system/test_pipelines.py
  utility/data_fetcher.go
  utility/map_str_enhancer.go
Labels: backport

#3119 [7.x] [intake] Fix reference to message json spec. (#3112)
  docs/spec/spans/span.json
Labels: backport

#3122 [7.x] elasticsearch: add libbeat compatibility test (#3120)
  elasticsearch/config_test.go
Labels: backport

#3121 Add experimental flag to Jaeger integration
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: [zube]: In Review

#3089 [docs] Adds APM app cross cluster search documentation
  docs/guide/cross-cluster-search.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: docs

#3093 [docs] Fix ambiguous *.output documentation
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: docs

#3117 [7.5] [docs] Directory structure for copied docs (#3094)(#3115)
  NOTICE.txt
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/debugging.asciidoc
  docs/copied-from-beats/docs/getting-help.asciidoc
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/keystore.asciidoc
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/docs/output-cloud.asciidoc
  docs/copied-from-beats/docs/outputconfig.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/repositories.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/beats-system.asciidoc
  docs/copied-from-beats/docs/security/linux-seccomp.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/tls.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/docs/shared-configuring.asciidoc
  docs/copied-from-beats/docs/shared-directory-layout.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
  docs/copied-from-beats/docs/shared-env-vars.asciidoc
  docs/copied-from-beats/docs/shared-path-config.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared-ssl-logstash-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/shared-template-load.asciidoc
  docs/copied-from-beats/docs/step-test-config.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/copied-from-beats/outputs/codec/docs/codec.asciidoc
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
  docs/copied-from-beats/shared-logstash-config.asciidoc
  docs/index.asciidoc
  docs/troubleshooting.asciidoc
  script/copy-docs.py
Labels: backport

#3118 Jaeger grpc system test
  beater/jaeger/server_test.go
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_0.json
  testdata/jaeger/batch_1.approved.json
  testdata/jaeger/batch_1.json
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/jaeger_batch_0.approved.json
  tests/system/jaegergrpc/main.go
  tests/system/test_integration.py
  tests/system/test_jaeger.py
Labels: [zube]: In Review

#3134 Add support for API Key auth to self-instrumentation
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config/instrumentation.go
  beater/tracing.go
  beater/tracing_test.go
  changelogs/head.asciidoc
  tests/system/config/apm-server.yml.j2
  tests/system/test_instrumentation.py
  tests/system/test_integration.py
  vendor/go.elastic.co/apm/CHANGELOG.asciidoc
  vendor/go.elastic.co/apm/CHANGELOG.md
  vendor/go.elastic.co/apm/Jenkinsfile
  vendor/go.elastic.co/apm/Makefile
  vendor/go.elastic.co/apm/go.mod
  vendor/go.elastic.co/apm/go.sum
  vendor/go.elastic.co/apm/internal/apmhttputil/remoteaddr.go
  vendor/go.elastic.co/apm/internal/apmhttputil/url.go
  vendor/go.elastic.co/apm/internal/apmschema/update.sh
  vendor/go.elastic.co/apm/internal/apmversion/version.go
  vendor/go.elastic.co/apm/model/marshal_fastjson.go
  vendor/go.elastic.co/apm/model/model.go
  vendor/go.elastic.co/apm/modelwriter.go
  vendor/go.elastic.co/apm/module/apmgrpc/client.go
  vendor/go.elastic.co/apm/module/apmgrpc/go.mod
  vendor/go.elastic.co/apm/module/apmgrpc/go.sum
  vendor/go.elastic.co/apm/module/apmgrpc/server.go
  vendor/go.elastic.co/apm/module/apmhttp/client.go
  vendor/go.elastic.co/apm/module/apmhttp/go.mod
  vendor/go.elastic.co/apm/module/apmhttp/go.sum
  vendor/go.elastic.co/apm/module/apmhttp/handler.go
  vendor/go.elastic.co/apm/module/apmhttp/traceheaders.go
  vendor/go.elastic.co/apm/spancontext.go
  vendor/go.elastic.co/apm/tracecontext.go
  vendor/go.elastic.co/apm/transaction.go
  vendor/go.elastic.co/apm/transport/http.go
  vendor/go.elastic.co/apm/version.go
  vendor/vendor.json
Labels: [zube]: In Review

#3135 [7.x] [test] Use apm_server_user for API Key tests. (#3124)
  Makefile
  testing/docker/elasticsearch/roles.yml
  testing/docker/elasticsearch/users
  testing/docker/elasticsearch/users_roles
  tests/system/test_access.py
Labels: backport

#3139 [7.x] Ignore "should have comment" golint errors (#3067)
  Makefile
Labels: backport

#3143 [7.x] beater/middleware: add trace/log correlation (#3136)
  NOTICE.txt
  beater/middleware/log_middleware.go
  beater/middleware/log_middleware_test.go
  tests/system/test_integration_logging.py
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/suite.go
  vendor/go.elastic.co/apm/apmtest/configwatcher.go
  vendor/go.elastic.co/apm/apmtest/discard.go
  vendor/go.elastic.co/apm/apmtest/httpsuite.go
  vendor/go.elastic.co/apm/apmtest/recorder.go
  vendor/go.elastic.co/apm/apmtest/recordlogger.go
  vendor/go.elastic.co/apm/apmtest/testlogger.go
  vendor/go.elastic.co/apm/apmtest/withtransaction.go
  vendor/go.elastic.co/apm/transport/transporttest/doc.go
  vendor/go.elastic.co/apm/transport/transporttest/err.go
  vendor/go.elastic.co/apm/transport/transporttest/recorder.go
  vendor/vendor.json
Labels: [zube]: In Progress, backport

#3144 beater/api/profile: fix pprof Content-Type
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
Labels: [zube]: In Review

#3147 [DOCS] Remove outdated CCR note
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: docs, v6.8, v7.5.0, v7.6.0, v8.0.0

#3125 [7.x] [docs] Adds APM app cross cluster search documentation (#3089)
  docs/guide/cross-cluster-search.asciidoc
  docs/guide/index.asciidoc
  docs/guide/install-and-run.asciidoc
Labels: backport

#3106 docs: Add quick start docker
  RELEASES.md
  docs/guide/docker-compose.yml
  docs/guide/install-and-run.asciidoc
Labels: docs

#3127 [7.x] [docs] Fix ambiguous *.output documentation (#3093)
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: backport

#3149 [7.5] [DOCS] Remove outdated CCR note (#3147)
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: backport

#3128 [7.5] [docs] Fix ambiguous *.output documentation (#3093)
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: backport

#3152 [7.5] docs: Add quick start docker (#3106)
  docs/guide/docker-compose.yml
  docs/guide/install-and-run.asciidoc
Labels: backport

#3148 [7.x] [DOCS] Remove outdated CCR note (#3147)
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: backport

#3151 [7.x] docs: Add quick start docker (#3106)
  docs/guide/docker-compose.yml
  docs/guide/install-and-run.asciidoc
Labels: backport

#3145 [7.x] beater/api/profile: fix pprof Content-Type (#3144)
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
Labels: backport

#3040 [7.x] Retry connection when Kibana version is not compatible. (#3031)
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  changelogs/7.5.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  tests/kibana.go
Labels: backport

#3169 [docs] Fix 7.5 merge conflict
  docs/guide/install-and-run.asciidoc
Labels: docs

#3167 Add changelog for 7.6
  changelogs/7.6.asciidoc
  changelogs/head.asciidoc
Labels: v7.6.0

#3172 [7.x] Add changelog for 7.6 (#3167)
  changelogs/7.6.asciidoc
Labels: backport

#3162 [7.x] Add apikey subcommand (#3157)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/mux.go
  beater/api/root/handler.go
  beater/authorization/allow.go
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  beater/authorization/bearer.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/authorization/deny.go
  beater/authorization/privilege.go
  beater/authorization/privilege_test.go
  beater/beater.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/middleware/authorization_middleware.go
  beater/middleware/authorization_middleware_test.go
  beater/middleware/log_middleware.go
  beater/middleware/log_middleware_test.go
  beater/server_test.go
  cmd/apikey.go
  cmd/root.go
  elasticsearch/client.go
  elasticsearch/config.go
  elasticsearch/security_api.go
  idxmgmt/manager_test.go
  sourcemap/es_store.go
  testing/docker/elasticsearch/roles.yml
  tests/system/test_apikey.py
Labels: backport

#3164 [7.x] Add description to Intake API for remote_address (#2809)
  docs/spec/request.json
  model/error/generated/schema/error.go
  model/transaction/generated/schema/transaction.go
Labels: backport

#3173 [7.x] Document api_key in apm-server.yml file (#3138)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  elasticsearch/client.go
Labels: backport

#3186 [7.x] [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3188 [7.6] [DOCS] Change Ruby APM `set_tags` link to `set_label` (#3015)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3190 [docs] add append_fields to docs
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: docs

#3194 [7.5] docs: add missing 6.8.6 release notes (#3191)
  changelogs/6.8.asciidoc
Labels: backport

#3193 [7.6] docs: add missing 6.8.6 release notes (#3191)
  changelogs/6.8.asciidoc
Labels: backport

#3192 [7.x] docs: add missing 6.8.6 release notes (#3191)
  changelogs/6.8.asciidoc
Labels: backport

#3206 [7.x] beater: rewrite flaky test (#3204)
  beater/beater.go
  beater/onboarding.go
  beater/onboarding_test.go
  beater/server.go
  beater/server_test.go
Labels: backport

#3205 [7.x] [test] Add tests for compressed requests (#3176)
  beater/api/intake/handler_test.go
  beater/api/intake/test_approved/CompressedBodyReaderDeflateInvalid.approved.json
  beater/api/intake/test_approved/CompressedBodyReaderDeflateValid.approved.json
  beater/api/intake/test_approved/CompressedBodyReaderGzipInvalid.approved.json
  beater/api/intake/test_approved/CompressedBodyReaderGzipValid.approved.json
Labels: backport

#3211 [7.6] beater: rewrite flaky test (#3204)
  beater/beater.go
  beater/onboarding.go
  beater/onboarding_test.go
  beater/server.go
  beater/server_test.go
Labels: backport

#3201 [7.5] docs: add append_fields to docs (#3190)
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: backport

#3199 [7.x] docs: add append_fields to docs (#3190)
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: backport

#3200 [7.6] docs: add append_fields to docs (#3190)
  docs/copied-from-beats/docs/template-config.asciidoc
Labels: backport

#3189 fix: trigger on _beats changes
  Jenkinsfile
Labels: automation, bug, ci

#3221 [7.6] Introduce elasticsearch.Error (#3218)
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  cmd/apikey.go
  elasticsearch/client.go
  elasticsearch/client_test.go
  elasticsearch/estest/client.go
  elasticsearch/security_api_test.go
  model/stacktrace_frame_test.go
  sourcemap/es_store_test.go
  sourcemap/test/es_client.go
Labels: backport

#3220 [7.x] Introduce elasticsearch.Error (#3218)
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  cmd/apikey.go
  elasticsearch/client.go
  elasticsearch/client_test.go
  elasticsearch/estest/client.go
  elasticsearch/security_api_test.go
  model/stacktrace_frame_test.go
  sourcemap/es_store_test.go
  sourcemap/test/es_client.go
Labels: backport

#3219 [docs][7.5] 7.5.2 release notes
  changelogs/7.5.asciidoc
Labels: docs

#3223 [docs][7.5] 7.5.2 release notes #3219
  changelogs/7.5.asciidoc
Labels: docs

#3225 [7.6] [docs][7.5] 7.5.2 release notes #3219 (#3223)
  changelogs/7.5.asciidoc
Labels: backport

#3224 [7.x] [docs][7.5] 7.5.2 release notes #3219 (#3223)
  changelogs/7.5.asciidoc
Labels: backport

#3210 [7.6] [test] Improve system tests related to API Keys (#3175)
  tests/system/apmserver.py
  tests/system/test_access.py
  tests/system/test_apikey.py
  tests/system/test_instrumentation.py
Labels: backport

#3208 [7.6] update beats script and beats
  NOTICE.txt
  _beats/CHANGELOG.next.asciidoc
  _beats/testing/environments/latest.yml
  _beats/vendor/vendor.json
  script/update_beats.sh
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/vendor.json
Labels: v7.6.0

#3207 [7.x] [test] Improve system tests related to API Keys (#3175)
  tests/system/apmserver.py
  tests/system/test_access.py
  tests/system/test_apikey.py
  tests/system/test_instrumentation.py
Labels: backport

#3228 chore: fetch all remotes before to checkout the branch
  script/update_beats.sh
Labels: automation, ci

#3232 [7.x] tests/system: attempt to speed up tests (#3202)
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_instrumentation.py
  tests/system/test_integration.py
Labels: backport

#3233 [7.6] tests/system: attempt to speed up tests (#3202)
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_export.py
  tests/system/test_instrumentation.py
  tests/system/test_integration.py
Labels: backport

#3229 [7.6] update go-elasticsearch client
  NOTICE.txt
  vendor/github.com/elastic/go-elasticsearch/v7/internal/version/version.go
  vendor/vendor.json
Labels: apm-test-plan-7.6.0, v7.6.0

#3235 [7.x] Improve system tests (#3217)
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/es_helper.py
  tests/system/helper.py
  tests/system/test_access.py
  tests/system/test_export.py
  tests/system/test_instrumentation.py
  tests/system/test_integration.py
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
  tests/system/test_monitoring.py
  tests/system/test_pipelines.py
  tests/system/test_requests.py
  tests/system/test_setup_index_management.py
Labels: backport

#3236 [7.6] Improve system tests (#3217)
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/es_helper.py
  tests/system/helper.py
  tests/system/test_access.py
  tests/system/test_export.py
  tests/system/test_instrumentation.py
  tests/system/test_integration.py
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
  tests/system/test_monitoring.py
  tests/system/test_pipelines.py
  tests/system/test_requests.py
  tests/system/test_setup_index_management.py
Labels: backport

#3238 decrease API Key cache time to one minute
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config_test.go
  tests/system/test_access.py
Labels: [zube]: In Review, v7.6.0

#3240 Add experimental flag to API Key feature
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: v7.6.0

#3242 [7.6] decrease API Key cache time to one minute (#3238)
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config_test.go
  tests/system/test_access.py
Labels: backport

#3245 [7.6] Add experimental flag to API Key feature (#3240)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: backport

#3247 Update Kibana index-pattern path
  script/are_kibana_saved_objects_updated.py
  script/update_kibana_objects.py
Labels: [zube]: In Review

#3243 [test] Fix flaky self instrumentation system test
  tests/system/test_access.py
  tests/system/test_instrumentation.py
Labels: test

#3248 [7.x] Update Kibana index-pattern path (#3247)
  script/are_kibana_saved_objects_updated.py
  script/update_kibana_objects.py
Labels: backport

#3250 [7.6] [test] Fix flaky self instrumentation system test (#3243)
  tests/system/test_access.py
  tests/system/test_instrumentation.py
Labels: backport

#3241 [7.x] decrease API Key cache time to one minute (#3238)
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config_test.go
  tests/system/test_access.py
Labels: backport

#3244 [7.x] Add experimental flag to API Key feature (#3240)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
Labels: backport

#3249 [7.x] [test] Fix flaky self instrumentation system test (#3243)
  tests/system/test_access.py
  tests/system/test_instrumentation.py
Labels: backport

#3252 [7.x] Remove creation of APM provileges. (#3251)
  cmd/apikey.go
  elasticsearch/security_api.go
  tests/system/test_access.py
  tests/system/test_apikey.py
Labels: backport

#3253 [7.6] Remove creation of APM provileges. (#3251)
  cmd/apikey.go
  elasticsearch/security_api.go
  tests/system/test_access.py
  tests/system/test_apikey.py
Labels: backport

#3212 [docs] Server/Agent API key documentation
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input-short.asciidoc
Labels: docs, v7.6.0

#3255 [7.x] [docs] Server/Agent API key documentation (#3212)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input-short.asciidoc
Labels: backport

#3256 [7.6] [docs] Server/Agent API key documentation (#3212)
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input-short.asciidoc
Labels: backport

#3257 [docs] Update apm-contrib link for dashboards
  docs/redirects.asciidoc
Labels: docs

#3259 [7.6] [docs] Update apm-contrib link for dashboardds (#3257)
  docs/redirects.asciidoc
Labels: backport

#3258 [7.x] [docs] Update apm-contrib link for dashboardds (#3257)
  docs/redirects.asciidoc
Labels: backport

#3260 [7.5] [docs] Update apm-contrib link for dashboardds (#3257)
  docs/redirects.asciidoc
Labels: backport

#3227 [docs] API key documentation from libbeat
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/beats-system.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: docs, v7.6.0

#3266 [7.6] Update beats framework to ee7cdc9
  NOTICE.txt
  _beats/.go-version
  _beats/CHANGELOG-developer.asciidoc
  _beats/CHANGELOG.asciidoc
  _beats/CHANGELOG.next.asciidoc
  _beats/libbeat/docs/version.asciidoc
  _beats/libbeat/scripts/Makefile
  vendor/github.com/cespare/xxhash/LICENSE.txt
  vendor/github.com/cespare/xxhash/README.md
  vendor/github.com/cespare/xxhash/go.mod
  vendor/github.com/cespare/xxhash/go.sum
  vendor/github.com/cespare/xxhash/xxhash.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/xxhash_other.go
  vendor/github.com/cespare/xxhash/xxhash_unsafe.go
  vendor/github.com/elastic/beats/libbeat/beat/event.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/beat.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/imports_common.go
  vendor/github.com/elastic/beats/libbeat/cmd/instance/settings.go
  vendor/github.com/elastic/beats/libbeat/common/config.go
  vendor/github.com/elastic/beats/libbeat/common/logging.go
  vendor/github.com/elastic/beats/libbeat/common/mapstr.go
  vendor/github.com/elastic/beats/libbeat/common/transport/tlscommon/tls_config.go
  vendor/github.com/elastic/beats/libbeat/kibana/client.go
  vendor/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go
  vendor/github.com/elastic/beats/libbeat/processors/actions/decode_json_fields.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/add_id.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/config.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/errors.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/generator/errors.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/generator/es_generator.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/generator/generator.go
  vendor/github.com/elastic/beats/libbeat/processors/add_id/generator/mac.go
  vendor/github.com/elastic/beats/libbeat/processors/fingerprint/config.go
  vendor/github.com/elastic/beats/libbeat/processors/fingerprint/encode.go
  vendor/github.com/elastic/beats/libbeat/processors/fingerprint/errors.go
  vendor/github.com/elastic/beats/libbeat/processors/fingerprint/fingerprint.go
  vendor/github.com/elastic/beats/libbeat/processors/fingerprint/hash.go
  vendor/github.com/elastic/beats/x-pack/libbeat/cmd/inject.go
  vendor/github.com/elastic/beats/x-pack/libbeat/licenser/es_callback.go
  vendor/vendor.json
Labels: v7.6.0

#3268 [7.6] update go to 1.13.7 (#3264)
  .go-version
  Dockerfile
  README.md
  changelogs/7.6.asciidoc
  docs/version.asciidoc
  tests/Dockerfile
Labels: backport

#3267 [7.x] update go to 1.13.7 (#3264)
  .go-version
  Dockerfile
  README.md
  changelogs/7.6.asciidoc
  docs/version.asciidoc
  tests/Dockerfile
Labels: backport
