Repository elastic/apm-server, pull requests merged in 2020-04, with the labels that each got.

#3597 Update go-elasticsearch dependency
  NOTICE.txt
  go.mod
  go.sum
Labels: v7.7.0

#3590 docs: Update agent links for API keys
  docs/secure-communication-agents.asciidoc
Labels: docs

#3589 [7.7] [docs] Reference structure and heading changes (#3492)
  docs/agent-configuration.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/outputconfig.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
  docs/copied-from-beats/docs/shared-path-config.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/data-ingestion.asciidoc
  docs/events-api.asciidoc
  docs/exploring-es-data.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/rum.asciidoc
  docs/howto.asciidoc
  docs/ilm-reference.asciidoc
  docs/ilm.asciidoc
  docs/index.asciidoc
  docs/jaeger-reference.asciidoc
  docs/jaeger-support.asciidoc
  docs/server-info.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
  docs/storage-management.asciidoc
  docs/troubleshooting.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3588 [7.x] [docs] Reference structure and heading changes (#3492)
  docs/agent-configuration.asciidoc
  docs/breaking-changes.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/outputconfig.asciidoc
  docs/copied-from-beats/docs/shared-docker.asciidoc
  docs/copied-from-beats/docs/shared-path-config.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/data-ingestion.asciidoc
  docs/events-api.asciidoc
  docs/exploring-es-data.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/rum.asciidoc
  docs/howto.asciidoc
  docs/ilm-reference.asciidoc
  docs/ilm.asciidoc
  docs/index.asciidoc
  docs/jaeger-reference.asciidoc
  docs/jaeger-support.asciidoc
  docs/server-info.asciidoc
  docs/setting-up-and-running.asciidoc
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
  docs/storage-management.asciidoc
  docs/troubleshooting.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3591 docs: Cloud first doc directory
  docs/guide/apm-doc-directory.asciidoc
Labels: docs

#3598 [7.x] docs: update agent links for API keys (#3590)
  docs/secure-communication-agents.asciidoc
Labels: backport

#3599 [7.7] docs: update agent links for API keys (#3590)
  docs/secure-communication-agents.asciidoc
Labels: backport

#3600 [7.6] docs: update agent links for API keys (#3590)
  docs/secure-communication-agents.asciidoc
Labels: backport

#3601 [7.x] docs: cloud first doc directory (#3591)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#3602 [7.7] docs: cloud first doc directory (#3591)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#3603 [7.6] docs: cloud first doc directory (#3591)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#3592 docs: Add RUM allow_headers configuration
  docs/configuration-rum.asciidoc
Labels: docs, v7.7.0

#3604 [7.x] docs: Add RUM allow_headers configuration (#3592)
  docs/configuration-rum.asciidoc
Labels: backport

#3605 [7.7] docs: Add RUM allow_headers configuration (#3592)
  docs/configuration-rum.asciidoc
Labels: backport

#3607 docs: fix typo in Jaeger docs
  docs/jaeger-support.asciidoc
Labels: v7.7.0

#3615 [7.x] Revert "Require a minimum version in the RUM V3 handler." (#3610)
  beater/api/mux.go
  beater/api/mux_intake_rum_test.go
Labels: backport

#3616 Add metricset spec and handling for RUM V3
  changelogs/head.asciidoc
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  docs/spec/metricsets/rum_v3_sample.json
  model/field/rum_v3_mapping.go
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/metricset.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
  script/inline_schemas/inline_schemas.go
  testdata/intake-v3/rum_events.ndjson
Labels: [zube]: In Review

#3612 [7.7] docs: fix typo in Jaeger docs (#3607)
  docs/jaeger-support.asciidoc
Labels: backport

#3611 [7.x] docs: fix typo in Jaeger docs (#3607)
  docs/jaeger-support.asciidoc
Labels: backport

#3593 docs: Update pipeline and processor docs for 7.7
  docs/configuration-process.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: docs, v7.7.0

#3620 packer: cache docker images
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, ci

#3622 [7.7] docs: update pipeline and processor docs (#3593)
  docs/configuration-process.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3621 [7.x] docs: update pipeline and processor docs (#3593)
  docs/configuration-process.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3608 [Doc] Improvements for APM fields
  docs/configuring-output-after.asciidoc
Labels: docs

#3625 [7.x] docs: improvements for APM fields (#3608)
  docs/configuring-output-after.asciidoc
Labels: backport

#3626 [7.7] docs: improvements for APM fields (#3608)
  docs/configuring-output-after.asciidoc
Labels: backport

#3627 [7.6] docs: improvements for APM fields (#3608)
  docs/configuring-output-after.asciidoc
Labels: backport

#3628 [7.x] Introduce model.Input for decoding (#3570)
  beater/api/asset/sourcemap/handler.go
  beater/api/profile/handler.go
  beater/onboarding.go
  model/config.go
  model/error/event.go
  model/error/event_test.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/profile/profile_test.go
  model/span/event.go
  model/span/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/otel/consumer.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/processor.go
  transform/transform.go
Labels: backport

#3629 [7.x] model/...: remove error parameter from decoders (#3571)
  model/error/event.go
  model/error/event_test.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/span/event.go
  model/span/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/stream/processor.go
Labels: backport

#3630 [7.x] all: add metadata directly to model types (#3573)
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/handler_test.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  model/error/event.go
  model/error/event_test.go
  model/input.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metadata/service.go
  model/metadata/service_test.go
  model/metricset/event.go
  model/metricset/event_test.go
  model/profile/profile.go
  model/profile/profile_test.go
  model/span/event.go
  model/span/event_test.go
  model/stacktrace.go
  model/stacktrace_test.go
  model/test_approved_model/context_full_event with experimental=true.approved.json
  model/transaction/event.go
  model/transaction/event_test.go
  processor/asset/processor.go
  processor/asset/sourcemap/package_tests/processor_test.go
  processor/asset/sourcemap/package_tests/test_processor.go
  processor/asset/sourcemap/sourcemap.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_custom_0.approved.json
  processor/otel/test_approved/span_jaeger_db_0.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_custom_0.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/processor.go
  transform/transform.go
Labels: backport

#3631 [7.x] model/...: encapsulate schema validation (#3594)
  beater/api/intake/test_approved/InvalidEvent.approved.json
  beater/api/intake/test_approved/InvalidMetadata.approved.json
  beater/api/profile/handler.go
  model/error/event.go
  model/error/event_test.go
  model/metadata/metadata.go
  model/metadata/metadata_test.go
  model/metricset/event.go
  model/span/event.go
  model/span/event_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/processor.go
  processor/stream/test_approved_stream_result/testIntegrationResultInvalidEvent.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultInvalidMetadata.approved.json
  tests/system/test_integration_logging.py
  tests/system/test_requests.py
  validation/validator.go
Labels: backport

#3632 [7.x] Report all libbeat/monitoring metrics in /debug/vars (#3550)
  beater/api/asset/sourcemap/handler.go
  beater/api/config/agent/handler.go
  beater/api/expvar.go
  beater/api/intake/handler.go
  beater/api/mux.go
  beater/api/profile/handler.go
  beater/api/root/handler.go
  beater/jaeger/grpc.go
  beater/jaeger/http.go
  beater/middleware/monitoring_middleware_test.go
  beater/request/result_test.go
  decoder/req_decoder.go
  model/error/event.go
  model/metricset/event.go
  model/sourcemap/payload.go
  model/span/event.go
  model/transaction/event.go
Labels: backport

#3634 [7.x] model/field: rewrite to avoid closure allocation (#3619)
  model/field/rum_v3_mapping.go
Labels: backport

#3636 [7.x] model: merge stream and per-event metadata (#3623)
  model/context.go
  model/error/event.go
  model/error/event_test.go
  model/modeldecoder/context.go
  model/modeldecoder/context_test.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/test_approved_model/context_client_ip_from_forwarded_header.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_from_socket_invalid_headers.approved.json
  model/modeldecoder/test_approved_model/context_client_ip_header_case_insensitive.approved.json
  model/modeldecoder/test_approved_model/context_empty.approved.json
  model/modeldecoder/test_approved_model/context_experimental is not true.approved.json
  model/modeldecoder/test_approved_model/context_full_event with experimental=true.approved.json
  model/modeldecoder/test_approved_model/context_input_nil.approved.json
  model/modeldecoder/test_approved_model/context_no_url_protocol.approved.json
  model/modeldecoder/test_approved_model/context_request_body_string.approved.json
  model/modeldecoder/test_approved_model/context_url_port_string.approved.json
  model/modeldecoder/test_approved_model/context_user_id_integer.approved.json
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction/event.go
  model/transaction/event_test.go
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_custom_0.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
Labels: backport

#3638 [7.x] Add metricset spec and handling for RUM V3 (#3616)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  docs/spec/metricsets/rum_v3_sample.json
  model/field/rum_v3_mapping.go
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/metricset.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
  script/inline_schemas/inline_schemas.go
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3643 docs: update links to APM app documentation
  docs/guide/apm-doc-directory.asciidoc
Labels: docs, v7.7.0

#3637 ci(jenkins): generate docker images for every commit
  Jenkinsfile
Labels: [zube]: In Review, automation, ci

#3645 [7.7] docs: update links to apm app reference (#3643)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#3644 [7.x] docs: update links to apm app reference (#3643)
  docs/guide/apm-doc-directory.asciidoc
Labels: backport

#3653 docs: 7.7.0 release highlights and breaking changes
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: docs

#3654 [7.x] docs: 7.7 release highlights and changes outline (#3653)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3655 [7.7] docs: 7.7 release highlights and changes outline (#3653)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3658 [7.x] [RUM V3] Embed spans inside transactions (#3648)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/spans/rum_v3_span.json
  docs/spec/transactions/rum_v3_transaction.json
  model/error/event.go
  model/error/event_test.go
  model/field/rum_v3_mapping.go
  model/modeldecoder/container_test.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/kubernetes_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/stacktrace_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/modeldecoder/user_test.go
  model/span/event.go
  model/span/event_test.go
  model/span/generated/schema/rum_v3_span.go
  model/transaction/event.go
  model/transaction/event_test.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/otel/consumer.go
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_custom_0.approved.json
  processor/otel/test_approved/span_jaeger_db_0.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_custom_0.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/processor.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3662 [7.x] RUM V3: Shorten ID fields in transaction and errors (#3659)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/errors/rum_v3_error.json
  docs/spec/transactions/rum_v3_transaction.json
  model/error/generated/schema/rum_v3_error.go
  model/field/rum_v3_mapping.go
  model/modeldecoder/error.go
  model/modeldecoder/transaction.go
  model/transaction/generated/schema/rum_v3_transaction.go
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3656 Enabled licensed fields/features
  .gitignore
  Makefile
  cmd/root.go
  docs/fields.asciidoc
  include/fields.go
  magefile.go
  main.go
  main_test.go
  tests/system/apmserver.py
  x-pack/apm-server/cmd/root.go
  x-pack/apm-server/cmd/root_test.go
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
  x-pack/apm-server/main.go
Labels: enhancement

#3666 [7.x] Enabled licensed fields/features (#3656)
  .gitignore
  Makefile
  cmd/root.go
  docs/fields.asciidoc
  include/fields.go
  magefile.go
  main.go
  main_test.go
  tests/system/apmserver.py
  x-pack/apm-server/cmd/root.go
  x-pack/apm-server/cmd/root_test.go
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
  x-pack/apm-server/main.go
Labels: backport

#3667 docs: 7.7 release docs
  CHANGELOG.asciidoc
  docs/common-problems.asciidoc
  docs/configuration-rum.asciidoc
  docs/events-api.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.7-apm-agent-configuration.png
  docs/guide/images/7.7-apm-alert.png
  docs/guide/images/7.7-service-maps-java.png
  docs/redirects.asciidoc
  docs/release-notes.asciidoc
  docs/sourcemap-api.asciidoc
  docs/upgrading-to-65.asciidoc
Labels: docs, v7.7.0

#3671 [7.x] docs: 7.7 release docs (#3667)
  CHANGELOG.asciidoc
  docs/common-problems.asciidoc
  docs/configuration-rum.asciidoc
  docs/events-api.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.7-apm-agent-configuration.png
  docs/guide/images/7.7-apm-alert.png
  docs/guide/images/7.7-service-maps-java.png
  docs/redirects.asciidoc
  docs/release-notes.asciidoc
  docs/sourcemap-api.asciidoc
  docs/upgrading-to-65.asciidoc
Labels: backport

#3672 [7.7] docs: 7.7 release docs (#3667)
  CHANGELOG.asciidoc
  docs/common-problems.asciidoc
  docs/configuration-rum.asciidoc
  docs/events-api.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/7.7-apm-agent-configuration.png
  docs/guide/images/7.7-apm-alert.png
  docs/guide/images/7.7-service-maps-java.png
  docs/redirects.asciidoc
  docs/release-notes.asciidoc
  docs/sourcemap-api.asciidoc
  docs/upgrading-to-65.asciidoc
Labels: backport

#3675 [7.x] model: fix span.transformations metric name (#3674)
  model/span.go
Labels: backport

#3676 [7.x] beater: introduce NewCreator and RunServer(Func) (#3668)
  beater/beater.go
  beater/beater_test.go
  beater/config/rum.go
  beater/http.go
  beater/integration_test.go
  beater/onboarding.go
  beater/onboarding_test.go
  beater/server.go
  beater/server_test.go
  beater/tracing.go
  beater/tracing_test.go
  main.go
  x-pack/apm-server/cmd/root.go
  x-pack/apm-server/cmd/root_test.go
  x-pack/apm-server/main.go
Labels: backport

#3684 [7.x] add span reparenting field child_ids (#3679)
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/data/elasticsearch/generated/spans.json
  docs/fields.asciidoc
  docs/spec/spans/span.json
  include/fields.go
  model/modeldecoder/container_test.go
  model/modeldecoder/kubernetes_test.go
  model/modeldecoder/metadata.go
  model/modeldecoder/metricset.go
  model/modeldecoder/process_test.go
  model/modeldecoder/service_test.go
  model/modeldecoder/span.go
  model/modeldecoder/user_test.go
  model/span.go
  model/span/_meta/fields.yml
  model/span/generated/schema/span.go
  processor/otel/test_approved/span_jaeger_custom_0.approved.json
  processor/otel/test_approved/span_jaeger_db_0.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/processor.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions_spans.ndjson
  tests/system/spans.approved.json
Labels: backport

#3683 [7.x] suggest make instead (#3680)
  magefile.go
Labels: backport

#3685 [7.x] sort system test approvals (#3682)
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  tests/approvals/approvals.go
  tests/system/apmserver.py
  tests/system/error.approved.json
  tests/system/jaeger_batch_0.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
  tests/system/metricset.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
Labels: backport

#3686 [7.x] Add appliedByAgent flag to agentcfg query. (#3677)
  agentcfg/model.go
  agentcfg/model_test.go
  beater/jaeger/grpc.go
  model/error_test.go
  model/span_test.go
Labels: backport

#3689 [7.x] Change name for mark_as_applied_by_agent config option (#3681)
  agentcfg/model.go
  agentcfg/model_test.go
  beater/jaeger/grpc.go
Labels: backport

#3699 [7.x] Introduce transaction metrics aggregation (#3651)
  Makefile
  NOTICE.txt
  beater/config/aggregation.go
  beater/config/aggregation_test.go
  beater/config/config.go
  beater/config/config_test.go
  docs/fields.asciidoc
  go.mod
  include/fields.go
  log/selectors.go
  model/metricset/_meta/fields.yml
  model/transaction.go
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_aggregation.py
  tests/system/transaction_histogram_metrics.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
Labels: backport

#3700 [7.x] tests/system: use Kibana REST API to cleanup ACM (#3690)
  tests/system/apmserver.py
  tests/system/es_helper.py
  tests/system/kibana.py
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
Labels: backport

#3701 [7.x] aggregation/txmetrics: optimise for concurrent writers (#3691)
  go.mod
  go.sum
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport

#3649 Correct apm-server.host in configuration process example
  docs/configuration-process.asciidoc
Labels: bug, docs

#3678 docs: How to apply source maps to error stack traces
  docs/images/source-map-after.png
  docs/images/source-map-before.png
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: docs

#3707 docs: correct apm-server.host in configuration process example (#3649)
  docs/configuration-process.asciidoc
Labels: docs

#3706 docs: correct apm-server.host in configuration process example (#3649)
  docs/configuration-process.asciidoc
Labels: docs

#3711 [7.6] docs: how to apply source maps to error stack traces (#3678)
  docs/images/source-map-after.png
  docs/images/source-map-before.png
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: backport

#3710 [7.7] docs: how to apply source maps to error stack traces (#3678)
  docs/images/source-map-after.png
  docs/images/source-map-before.png
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: backport

#3709 [7.x] docs: how to apply source maps to error stack traces (#3678)
  docs/images/source-map-after.png
  docs/images/source-map-before.png
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: backport

#3712 docs: fix 7.6 build error
  docs/rum.asciidoc
Labels: docs

#3714 [7.x] Fix typo in spec ids (#3713)
  docs/spec/context.json
  docs/spec/http_response.json
  docs/spec/message.json
  docs/spec/metadata.json
  docs/spec/process.json
  docs/spec/request.json
  docs/spec/rum_v3_context.json
  docs/spec/rum_v3_metadata.json
  docs/spec/rum_v3_service.json
  docs/spec/service.json
  docs/spec/system.json
  docs/spec/tags.json
  docs/spec/timestamp_epoch.json
  docs/spec/timestamp_rfc3339.json
  docs/spec/transactions/rum_v3_transaction.json
  model/error/generated/schema/error.go
  model/error/generated/schema/rum_v3_error.go
  model/metadata/generated/schema/metadata.go
  model/metadata/generated/schema/rum_v3_metadata.go
  model/metricset/generated/schema/metricset.go
  model/metricset/generated/schema/rum_v3_metricset.go
  model/span/generated/schema/rum_v3_span.go
  model/span/generated/schema/span.go
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
Labels: backport

#3708 docs: link to max spans config
  docs/guide/apm-data-model.asciidoc
Labels: docs

#3718 [7.6] docs: link to max spans config (#3708)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3717 [7.7] docs: link to max spans config (#3708)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3716 [7.x] docs: link to max spans config (#3708)
  docs/guide/apm-data-model.asciidoc
Labels: backport
