Repository elastic/apm-server, pull requests merged in 2020-05, with the labels that each got.

#3702 Configuration for dropping non-sampled transactions
  beater/beater.go
  beater/config/config.go
  beater/config/config_test.go
  beater/config/sampling.go
  beater/test_approved_es_documents/TestDropNonSampledTransactions.approved.json
  changelogs/head.asciidoc
  publish/pub.go
  sampling/sampling.go
  sampling/sampling_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/drop_unsampled_transactions.approved.json
  tests/system/keep_unsampled_transactions.approved.json
  tests/system/test_aggregation.py
  tests/system/test_sampling.py
Labels: enhancement

#3732 [7.x] Refactor: decode events into batches (#3724)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  model/batch.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/metricset.go
  model/modeldecoder/metricset_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction.go
  processor/otel/consumer.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/processor.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Events.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: backport

#3733 [RUMV3] allow metricsets inside transactions
  changelogs/head.asciidoc
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  docs/spec/transactions/rum_v3_transaction.json
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/transaction.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: [zube]: In Review

#3734 [7.x] [RUMV3] allow metricsets inside transactions (#3733)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  docs/spec/transactions/rum_v3_transaction.json
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/transaction.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3728 docs: fix bug in metadata docs
  docs/guide/apm-data-model.asciidoc
Labels: docs

#3729 Cloud metadata
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/cloud.json
  docs/spec/metadata.json
  include/fields.go
  model/cloud.go
  model/cloud_test.go
  model/metadata.go
  model/metadata/generated/schema/metadata.go
  model/modeldecoder/cloud.go
  model/modeldecoder/metadata.go
  model/modeldecoder/metadata_test.go
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_custom_0.approved.json
  processor/otel/test_approved/span_jaeger_db_0.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_custom_0.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultCloudMetadata.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/only-metadata.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: enhancement

#3741 [7.x] docs/spec: require duration >= 0 (#3721)
  NOTICE.txt
  docs/spec/spans/rum_v3_span.json
  docs/spec/spans/span.json
  docs/spec/transactions/rum_v3_transaction.json
  docs/spec/transactions/transaction.json
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction_test.go
  model/span/generated/schema/rum_v3_span.go
  model/span/generated/schema/span.go
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
Labels: backport

#3742 [7.x] Configuration for dropping non-sampled transactions (#3702)
  beater/beater.go
  beater/config/config.go
  beater/config/config_test.go
  beater/config/sampling.go
  beater/test_approved_es_documents/TestDropNonSampledTransactions.approved.json
  publish/pub.go
  sampling/sampling.go
  sampling/sampling_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/drop_unsampled_transactions.approved.json
  tests/system/keep_unsampled_transactions.approved.json
  tests/system/test_aggregation.py
  tests/system/test_sampling.py
Labels: backport

#3743 [7.x] Cloud metadata (#3729)
  _meta/fields.common.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/fields.asciidoc
  docs/spec/cloud.json
  docs/spec/metadata.json
  include/fields.go
  model/cloud.go
  model/cloud_test.go
  model/metadata.go
  model/metadata/generated/schema/metadata.go
  model/modeldecoder/cloud.go
  model/modeldecoder/metadata.go
  model/modeldecoder/metadata_test.go
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_custom_0.approved.json
  processor/otel/test_approved/span_jaeger_db_0.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_custom_0.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultCloudMetadata.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/only-metadata.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport

#3748 [7.x] fix typo in subtype (#3747)
  model/modeldecoder/field/rum_v3_mapping.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
Labels: backport

#3749 [7.x] Update beats framework to 553c92eeff2d
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  go.mod
  go.sum
  magefile.go
  testing/environments/docker/elasticsearch/kerberos/init.sh
  testing/environments/docker/elasticsearch/kerberos/installkdc.sh
  testing/environments/docker/elasticsearch_kerberos/Dockerfile
  testing/environments/docker/elasticsearch_kerberos/config/kdc.conf.template
  testing/environments/docker/elasticsearch_kerberos/config/krb5.conf
  testing/environments/docker/elasticsearch_kerberos/config/krb5.conf.template
  testing/environments/docker/elasticsearch_kerberos/healthcheck.sh
  testing/environments/docker/elasticsearch_kerberos/init.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/addprinc.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/addprincs.sh
  testing/environments/docker/elasticsearch_kerberos/scripts/installkdc.sh
  testing/environments/docker/elasticsearch_kerberos/start.sh
  testing/environments/docker/kafka/Dockerfile
  testing/environments/docker/kerberos_kdc/Dockerfile
  testing/environments/local.yml
Labels: [zube]: (7.8) Planned for release

#3756 [7.8] Update go-elasticsearch client dependency
  NOTICE.txt
  go.mod
  go.sum
Labels: v7.8.0

#3759 [7.8] Update beats framework to ~2c4c2432da71~ b1fdd94c7a16
  Makefile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: v7.8.0

#3760 [7.x] Fix performance degradation (#3755)
  model/batch.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/metricset.go
  model/modeldecoder/metricset_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  processor/otel/consumer.go
  processor/stream/processor.go
Labels: backport

#3761 [7.8] Fix performance degradation (#3755)
  model/batch.go
  model/modeldecoder/error.go
  model/modeldecoder/error_test.go
  model/modeldecoder/metricset.go
  model/modeldecoder/metricset_test.go
  model/modeldecoder/span.go
  model/modeldecoder/span_test.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  processor/otel/consumer.go
  processor/stream/processor.go
Labels: backport

#3753 Clarify error message when unauthorized Kibana connection
  agentcfg/fetch.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: [zube]: In Review

#3770 [7.x] update beats for bumping version to 7.9
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  tests/system/es_helper.py
Labels: enhancement, v7.9.0

#3767 docs: Remove outdated 7.0 update
  docs/data-ingestion.asciidoc
Labels: docs, v7.7.0

#3768 docs: Update Jaeger auth
  docs/jaeger-support.asciidoc
Labels: docs, v7.7.0

#3737 [7.x] docs: refresh metadata content (#3728)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3738 [7.7] docs: refresh metadata content (#3728)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3739 [7.6] docs: refresh metadata content (#3728)
  docs/guide/apm-data-model.asciidoc
Labels: backport

#3772 [7.x] docs: minor fix (#3767)
  docs/data-ingestion.asciidoc
Labels: backport

#3774 [7.7] docs: minor fix (#3767)
  docs/data-ingestion.asciidoc
Labels: backport

#3775 [7.6] docs: minor fix (#3767)
  docs/data-ingestion.asciidoc
Labels: backport

#3773 [7.8] docs: minor fix (#3767)
  docs/data-ingestion.asciidoc
Labels: backport

#3735 ci: aggregate downstream test results
  Jenkinsfile
Labels: automation, enhancement

#3778 [7.7] docs: jaeger auth (e7057e53)
  docs/jaeger-support.asciidoc
Labels: backport

#3777 [7.8] docs: jaeger auth (e7057e53)
  docs/jaeger-support.asciidoc
Labels: backport

#3776 [7.x] docs: jaeger auth (e7057e53)
  docs/jaeger-support.asciidoc
Labels: backport

#3764 [7.x] Clarify error message when unauthorized Kibana connection (#3753)
  agentcfg/fetch.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: backport, test-plan, v7.8.0

#3787 [7.x] Makefile: fix update-beats-module (#3785)
  Makefile
Labels: backport

#3788 [7.8] Makefile: fix update-beats-module (#3785)
  Makefile
Labels: backport

#3765 [7.8] Clarify error message when unauthorized Kibana connection (#3753)
  agentcfg/fetch.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
Labels: backport

#3780 [7.8] go es
  NOTICE.txt
  go.mod
  go.sum
Labels: v7.8.0

#3727 [6.8] docs: 6.8.9 docs version and add release notes
  changelogs/6.8.asciidoc
  docs/version.asciidoc
Labels: docs

#3791 [7.7] bump version through beats update
  NOTICE.txt
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  go.mod
  go.sum
  tests/system/es_helper.py
Labels: review

#3792 [6.8] Update version, update beats
  NOTICE.txt
  _beats/libbeat/docs/version.asciidoc
  _beats/libbeat/scripts/generate_fields_docs.py
  _beats/libbeat/tests/system/requirements.txt
  _beats/script/build_docs.sh
  _beats/testing/environments/latest.yml
  _beats/testing/environments/snapshot-oss.yml
  _beats/testing/environments/snapshot.yml
  vendor/github.com/elastic/beats/NOTICE.txt
  vendor/github.com/elastic/beats/libbeat/common/event.go
  vendor/github.com/elastic/beats/libbeat/common/mapstr.go
  vendor/github.com/elastic/beats/libbeat/processors/add_cloud_metadata/add_cloud_metadata.go
  vendor/github.com/elastic/beats/libbeat/publisher/pipeline/pipeline.go
  vendor/github.com/elastic/beats/libbeat/publisher/pipeline/processor.go
  vendor/github.com/elastic/beats/libbeat/version/version.go
  vendor/vendor.json
Labels: review

#3793 docs: Update documentation copied from Beats
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/shared-template-load.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: docs, v7.8.0

#3804 [7.x] elasticsearch: add known unhandled libbeat config (#3800)
  elasticsearch/config_test.go
Labels: backport

#3798 [7.8] docs: Update documentation copied from Beats (#3793)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/shared-template-load.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: backport

#3797 [7.x] docs: Update documentation copied from Beats (#3793)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  docs/copied-from-beats/docs/loggingconfig.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/shared-template-load.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/copied-from-beats/outputs/redis/docs/redis.asciidoc
Labels: backport

#3805 [7.x] beater: CreatorParams.RunServer -> WrapRunServer (#3803)
  beater/beater.go
  beater/beater_test.go
  beater/server.go
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/tracing_test.go
  main.go
  x-pack/apm-server/cmd/root_test.go
  x-pack/apm-server/main.go
Labels: backport

#3806 [7.8] beater: CreatorParams.RunServer -> WrapRunServer (#3803)
  beater/beater.go
  beater/beater_test.go
  beater/server.go
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/tracing_test.go
  main.go
  x-pack/apm-server/cmd/root_test.go
  x-pack/apm-server/main.go
Labels: backport

#3807 docs: update links to logstash getting started
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: docs, v7.8.0

#3809 [7.8] docs: update links to logstash getting started (#3807)
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: backport

#3808 [7.x] docs: update links to logstash getting started (#3807)
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: backport

#3810 docs: Update kerberos and upgrading docs
  docs/breaking-changes.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#3811 [7.x] docs: Update kerberos and upgrading docs (#3810)
  docs/breaking-changes.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3812 [7.8] docs: Update kerberos and upgrading docs (#3810)
  docs/breaking-changes.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3816 [RUM V3] Correctly process tags in RUMV3 metricsets.
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/metricset.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: bug, v7.8.0

#3815 Add `logging.ecs` parameter
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/7.8.asciidoc
Labels: enhancement

#3818 [7.8] Correctly process tags in RUMV3 metricsets. (#3816)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/metricset.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3817 [7.x] Correctly process tags in RUMV3 metricsets. (#3816)
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/metricsets/rum_v3_metricset.json
  model/metricset/generated/schema/rum_v3_metricset.go
  model/modeldecoder/metricset.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: backport

#3825 [7.x] Support custom response headers for RUM endpoints (#3820)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/mux.go
  beater/config/rum.go
  beater/middleware/response_headers_middleware.go
  beater/middleware/response_headers_middleware_test.go
Labels: backport

#3799 docs: Update security documentation
  docs/configure-kibana-endpoint.asciidoc
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/tls.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/copied-from-beats/docs/shared-ssl-logstash-config.asciidoc
  docs/feature-roles.asciidoc
  docs/index.asciidoc
Labels: docs, v7.8.0
