Repository elastic/apm-server, pull requests merged in 2020-07, with the labels that each got.

#3927 [7.x] Support for message_bus.destination in the Jaeger processor (#3884)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
Labels: backport

#3928 [7.x] Support for peer.service in the Jaeger processor (#3897)
  processor/otel/consumer.go
  processor/otel/test_approved/span_jaeger_http.approved.json
Labels: backport

#3929 [7.x] model: more depointering, decoder refactoring (#3894)
  model/context.go
  model/modeldecoder/transaction.go
  model/modeldecoder/transaction_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/consumer.go
  processor/otel/test_approved/consume_span.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json
  processor/otel/test_approved/metadata_jaeger_minimal.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport

#3923 [7.x] New tracer (#3836)
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/beater.go
  beater/server_test.go
  beater/tracing.go
  beater/tracing_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/testdata/conflict_instrumentation.yml
  cmd/testdata/legacy_instrumentation.yml
Labels: backport

#3930 [7.x] Use more inclusive language (#3903)
  agentcfg/fetch.go
  agentcfg/model.go
  docs/common-problems.asciidoc
  tests/fields.go
  tests/fields_test.go
Labels: backport

#3931 [7.x] aggregation/txmetrics: set timeseries.instance (#3904)
  model/metricset.go
  model/metricset_test.go
  tests/system/rum_transaction_histogram_metrics.approved.json
  tests/system/transaction_histogram_metrics.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport

#3925 [DOCS] Fixes Stack Overview links
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
Labels: 7.7.2, docs, v7.5.0, v7.6.1, v7.8.0, v7.9.0

#3935 [7.7] [DOCS] Fixes Stack Overview links (#3925)
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
Labels: backport

#3934 [7.8] [DOCS] Fixes Stack Overview links (#3925)
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
Labels: backport

#3936 [7.6] [DOCS] Fixes Stack Overview links (#3925)
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
Labels: backport

#3937 [7.5] [DOCS] Fixes Stack Overview links (#3925)
  docs/copied-from-beats/docs/https.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/security/basic-auth.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
Labels: backport

#3932 [7.x] Extrapolate Jaeger transaction count from reported sampling rate (#3722)
  docs/jaeger-reference.asciidoc
  docs/jaeger-support.asciidoc
  model/transaction.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/transaction_jaeger_sampling_rate.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport

#3943 Refactor metadata enrichment and fix bug in v3 Intake
  beater/api/intake/handler.go
  beater/api/profile/handler.go
  beater/middleware/request_metadata_middleware.go
  beater/middleware/request_metadata_middleware_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/metricsets.json
  model/modeldecoder/metadata.go
  model/modeldecoder/metadata_test.go
  model/modeldecoder/metricset.go
  model/modeldecoder/transaction_test.go
  processor/stream/benchmark_test.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  tests/system/metricset.approved.json
Labels: review

#3945 [7.x] Refactor metadata enrichment and fix bug in v3 Intake (#3943)
  beater/api/intake/handler.go
  beater/api/profile/handler.go
  beater/middleware/request_metadata_middleware.go
  beater/middleware/request_metadata_middleware_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  docs/data/elasticsearch/generated/metricsets.json
  model/modeldecoder/metadata.go
  model/modeldecoder/metadata_test.go
  model/modeldecoder/metricset.go
  model/modeldecoder/transaction_test.go
  processor/stream/benchmark_test.go
  processor/stream/package_tests/intake_test_processor.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  tests/system/metricset.approved.json
Labels: backport

#3939 Change links to refactored Beats getting started docs
  docs/guide/obs-integrations.asciidoc
Labels: docs, v7.9.0, v8.0.0

#3948 [7.x] Change links to refactored Beats getting started docs (#3939)
  docs/guide/obs-integrations.asciidoc
Labels: backport

#3952 [docs] 6.8.11 release notes
  changelogs/6.8.asciidoc
  script/check_changelogs.py
Labels: docs, v6.8, v7.8.0, v7.9.0

#3954 [7.x] [docs] 6.8.11 release notes (#3952)
  changelogs/6.8.asciidoc
Labels: backport

#3955 [7.8] [docs] 6.8.11 release notes (#3952)
  changelogs/6.8.asciidoc
Labels: backport

#3956 [6.8] [docs] 6.8.11 release notes (#3952)
  changelogs/6.8.asciidoc
Labels: backport

#3957 ci: remove cron trigger from the check changelog job
  .ci/check-changelogs.groovy
Labels: automation, bug, ci, team:automation

#3968 [7.x] beater/config: fix TLS config tests (#3962)
  beater/config/config_test.go
Labels: backport

#3967 [7.x] script: vendor gimme (#3965)
  NOTICE.txt
  cmd/root.go
  go.sum
  script/common.bash
  script/gimme/LICENSE
  script/gimme/gimme
Labels: backport

#3970 [7.x] Use peer.hostname for destination.address if peer.address is not given (#3969)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/span_jaeger_messaging.approved.json
Labels: backport

#3973 Update beats framework to 5c2863902fb
  NOTICE.txt
  go.mod
  go.sum
  magefile.go
  testing/environments/snapshot-oss.yml
  testing/environments/snapshot.yml
Labels: v7.9.0

#3980 docs: 7.8.1 release notes
  changelogs/7.8.asciidoc
Labels: v7.8.0

#3981 [7.x] docs: 7.8.1 release notes (#3980)
  changelogs/7.8.asciidoc
Labels: backport

#3982 [7.9] docs: 7.8.1 release notes (#3980)
  changelogs/7.8.asciidoc
Labels: backport

#3983 [7.8] docs: 7.8.1 release notes (#3980)
  changelogs/7.8.asciidoc
Labels: backport

#3975 Use peer.address for DestinationService.Resource when converting a Jaeger span
  changelogs/head.asciidoc
  processor/otel/consumer.go
  processor/otel/test_approved/span_jaeger_http.approved.json
Labels: v7.10.0

#3976 [DOCS] Update internal link to external
  docs/guide/install-and-run.asciidoc
Labels: backport, docs, v7.9.0

#3987 [7.9] [DOCS] Update internal link to external (#3976)
  docs/guide/install-and-run.asciidoc
Labels: backport

#3986 [7.x] [DOCS] Update internal link to external (#3976)
  docs/guide/install-and-run.asciidoc
Labels: backport

#3978 docs: add troubleshooting for resource exists but is not an alias
  docs/common-problems.asciidoc
Labels: docs, v7.8.0

#3979 docs: clean up upgrading content
  docs/breaking-changes.asciidoc
  docs/upgrading.asciidoc
Labels: docs, v7.8.0

#3977 docs: Update documentation from Beats for 7.9
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-instrumentation.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: docs, v7.9.0

#3990 [Docs]Fix broken links to the SIEM documentation
  docs/guide/apm-release-notes.asciidoc
Labels: docs, v7.10.0, v7.9.0, v8.0.0

#3997 [7.x] docs: Fix broken links to the SIEM documentation (#3990)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3998 [7.9] docs: Fix broken links to the SIEM documentation (#3990)
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3988 [7.x] docs: add troubleshooting (#3978)
  docs/common-problems.asciidoc
Labels: backport

#3992 [7.x] docs: clean up upgrading content (#3979)
  docs/breaking-changes.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3995 [7.x] docs: Update documentation from Beats for 7.9 (#3977)
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-instrumentation.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: backport

#3989 [7.9] docs: add troubleshooting (#3978)
  docs/common-problems.asciidoc
Labels: backport

#3993 [7.9] docs: clean up upgrading content (#3979)
  docs/breaking-changes.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#3996 [7.9] docs: Update documentation from Beats for 7.9 (#3977)
  docs/configuring.asciidoc
  docs/copied-from-beats/docs/command-reference.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-beats.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config-legacy.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/docs/shared-instrumentation.asciidoc
  docs/copied-from-beats/docs/shared-kerberos-config.asciidoc
  docs/copied-from-beats/docs/shared-systemd.asciidoc
  docs/copied-from-beats/docs/template-config.asciidoc
  docs/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
Labels: backport

#3991 [7.8] docs: add troubleshooting (#3978)
  docs/common-problems.asciidoc
Labels: backport

#3994 [7.8] docs: clean up upgrading content (#3979)
  docs/breaking-changes.asciidoc
  docs/upgrading.asciidoc
Labels: backport

#4000 Jenkins configuration for package testing
  .ci/check-packages.groovy
  .ci/jobs/apm-server-check-packages.yml
Labels: automation

#4003 docs: Updates to default index names
  docs/copied-from-beats/docs/output-cloud.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/error-indices.asciidoc
  docs/exploring-es-data.asciidoc
  docs/metricset-indices.asciidoc
  docs/sourcemap-indices.asciidoc
  docs/span-indices.asciidoc
  docs/transaction-indices.asciidoc
Labels: docs, v7.8.0

#4006 [DOCS] Add tagged regions for content reuse
  docs/guide/install-and-run.asciidoc
Labels: docs, v7.9.0

#4010 [7.9] [DOCS] Add tagged regions for content reuse (#4006)
  docs/guide/install-and-run.asciidoc
Labels: backport

#4009 [7.x] [DOCS] Add tagged regions for content reuse (#4006)
  docs/guide/install-and-run.asciidoc
Labels: backport

#4008 [7.9] docs: Updates to default index names (#4003)
  docs/copied-from-beats/docs/output-cloud.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/error-indices.asciidoc
  docs/exploring-es-data.asciidoc
  docs/metricset-indices.asciidoc
  docs/sourcemap-indices.asciidoc
  docs/span-indices.asciidoc
  docs/transaction-indices.asciidoc
Labels: backport

#4007 [7.x] docs: Updates to default index names (#4003)
  docs/copied-from-beats/docs/output-cloud.asciidoc
  docs/copied-from-beats/docs/outputs-list.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/error-indices.asciidoc
  docs/exploring-es-data.asciidoc
  docs/metricset-indices.asciidoc
  docs/sourcemap-indices.asciidoc
  docs/span-indices.asciidoc
  docs/transaction-indices.asciidoc
Labels: backport

#4012 Prep golang env for package build test
  .ci/check-packages.groovy
Labels: automation, ci

#4021 [7.x] tests/system: update user-agent pipline test (#4018)
  tests/system/test_pipelines.py
Labels: backport

#4022 [7.9] tests/system: update user-agent pipline test (#4018)
  tests/system/test_pipelines.py
Labels: backport

#3953 [docs] 6.8.11 version bump
  docs/version.asciidoc
Labels: docs, v6.8

#4024 docs: Add agent troubleshooting links
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: docs, v7.8.0

#4034 [7.x] docs: Add agent troubleshooting links (#4024)
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#4035 [7.9] docs: Add agent troubleshooting links (#4024)
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#4036 [7.8] docs: Add agent troubleshooting links (#4024)
  docs/guide/apm-data-model.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#4037 Use Darwin worker for packaging test job
  .ci/check-packages.groovy
Labels: automation, ci

#4038 [7.x] take ownership of version (#4028)
  cmd/root.go
  cmd/version.go
  go.sum
  magefile.go
  tests/system/es_helper.py
  tests/system/helper.py
Labels: backport

#4033 [docs] 7.9 release notes and breaking changes
  CHANGELOG.asciidoc
  changelogs/7.9.asciidoc
  changelogs/head.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/release-notes.asciidoc
Labels: docs, v7.9.0

#4040 [7.9] [docs] 7.9 release notes and breaking changes (#4033)
  CHANGELOG.asciidoc
  changelogs/7.9.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#4039 [7.x] [docs] 7.9 release notes and breaking changes (#4033)
  CHANGELOG.asciidoc
  changelogs/7.9.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/release-notes.asciidoc
Labels: backport
