Repository elastic/apm-server, pull requests merged in 2020-02, with the labels that each got.

#3270 remove enroll command
  changelogs/head.asciidoc
  x-pack/apm-server/cmd/root.go
  x-pack/apm-server/cmd/root_test.go
Labels: breaking change, bug, v7.7.0

#3274 [7.x] switch to xxhash to cespare (#3271)
  NOTICE.txt
  model/profile/profile.go
  vendor/github.com/OneOfOne/xxhash/LICENSE
  vendor/github.com/OneOfOne/xxhash/README.md
  vendor/github.com/OneOfOne/xxhash/go.mod
  vendor/github.com/OneOfOne/xxhash/xxhash.go
  vendor/github.com/OneOfOne/xxhash/xxhash_go17.go
  vendor/github.com/OneOfOne/xxhash/xxhash_safe.go
  vendor/github.com/OneOfOne/xxhash/xxhash_unsafe.go
  vendor/github.com/cespare/xxhash/LICENSE.txt
  vendor/github.com/cespare/xxhash/README.md
  vendor/github.com/cespare/xxhash/go.mod
  vendor/github.com/cespare/xxhash/go.sum
  vendor/github.com/cespare/xxhash/xxhash.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.go
  vendor/github.com/cespare/xxhash/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/xxhash_other.go
  vendor/github.com/cespare/xxhash/xxhash_unsafe.go
  vendor/vendor.json
Labels: backport

#3275 [7.x] remove enroll command (#3270)
  changelogs/7.7.asciidoc
  x-pack/apm-server/cmd/root.go
  x-pack/apm-server/cmd/root_test.go
Labels: backport

#3278 [7.6] backport update tls configuration
  elasticsearch/config.go
Labels: bug, v7.6.0

#3263 [7.6] [docs] API key documentation from libbeat (#3227)
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/beats-system.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport

#3262 [7.x] [docs] API key documentation from libbeat (#3227)
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection-legacy.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-internal-collection.asciidoc
  docs/copied-from-beats/docs/monitoring/monitoring-metricbeat.asciidoc
  docs/copied-from-beats/docs/monitoring/shared-monitor-config.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/security/beats-system.asciidoc
  docs/copied-from-beats/docs/security/securing-beats.asciidoc
  docs/copied-from-beats/docs/security/users.asciidoc
  docs/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport

#3269 [docs] Add Jaeger documentation
  docs/configuring.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/jaeger-support.asciidoc
Labels: docs, v7.6.0

#3284 [7.x] [docs] Add Jaeger documentation (#3269)
  docs/configuring.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/jaeger-support.asciidoc
Labels: backport

#3285 [7.6] [docs] Add Jaeger documentation (#3269)
  docs/configuring.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/jaeger-support.asciidoc
Labels: backport

#3283 [docs] Rename intake API
  docs/agent-configuration.asciidoc
  docs/events-api.asciidoc
  docs/intake-api.asciidoc
  docs/server-info.asciidoc
  docs/sourcemap-api.asciidoc
Labels: docs

#3294 [7.6] [docs] Rename intake API (#3283)
  docs/agent-configuration.asciidoc
  docs/events-api.asciidoc
  docs/intake-api.asciidoc
  docs/server-info.asciidoc
  docs/sourcemap-api.asciidoc
Labels: backport

#3293 [7.x] [docs] Rename intake API (#3283)
  docs/agent-configuration.asciidoc
  docs/events-api.asciidoc
  docs/intake-api.asciidoc
  docs/server-info.asciidoc
  docs/sourcemap-api.asciidoc
Labels: backport

#3295 [docs] Fix link to PR for breaking change
  changelogs/7.6.asciidoc
Labels: docs

#3286 chore: update PR template for contributions (#3214)
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: automation

#3307 [7.x] Make list of Access-Control-Allow-Headers configurable.
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/mux.go
  beater/config/config_test.go
  beater/config/rum.go
  beater/middleware/cors_middleware.go
  beater/middleware/cors_middleware_test.go
Labels: backport

#3282 [7.6][docs] 7.6.0 notes, highlights, and breaking changes
  CHANGELOG.asciidoc
  changelogs/7.6.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/apm-settings-kib.png
  docs/guide/images/apm-transactions-overview.png
  docs/guide/images/chained-exceptions.png
  docs/guide/images/java-kafka.png
  docs/guide/images/java-metadata.png
  docs/guide/images/siem-apm-integration.png
  docs/release-notes.asciidoc
Labels: docs, v7.6.0

#3301 [7.6] [docs] Remove 7.6 breaking change (#3295)
  changelogs/7.6.asciidoc
Labels: backport

#3300 [7.x] [docs] Remove 7.6 breaking change (#3295)
  changelogs/7.6.asciidoc
Labels: backport

#3309 [7.x] Separate event decoders. (#3297)
  beater/api/intake/handler_test.go
  beater/api/mux.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/package_tests/metricset_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/processor.go
  processor/stream/processor_test.go
Labels: backport

#3291 [7.x] strip trailing slashes from kibana host configuration (#3277)
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/config/config.go
  beater/config/config_test.go
  kibana/connecting_client.go
  kibana/connecting_client_test.go
Labels: backport

#3315 [7.x] 7.6.0 release notes, highlights, and breaking changes (#3282)
  CHANGELOG.asciidoc
  changelogs/7.6.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/apm-settings-kib.png
  docs/guide/images/apm-transactions-overview.png
  docs/guide/images/chained-exceptions.png
  docs/guide/images/java-kafka.png
  docs/guide/images/java-metadata.png
  docs/guide/images/siem-apm-integration.png
  docs/release-notes.asciidoc
Labels: docs

#3316 7.6.0 release notes, highlights, and breaking changes (#3282)
  CHANGELOG.asciidoc
  changelogs/7.6.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/guide/apm-release-notes.asciidoc
  docs/guide/images/apm-settings-kib.png
  docs/guide/images/apm-transactions-overview.png
  docs/guide/images/chained-exceptions.png
  docs/guide/images/java-kafka.png
  docs/guide/images/java-metadata.png
  docs/guide/images/siem-apm-integration.png
  docs/release-notes.asciidoc
Labels: docs

#3317 [7.x] adapt kibana host strip to new api (#3290)
  beater/config/config.go
Labels: backport

#3312 [7.x] beater/authorization: remove unnecessary code (#3306)
  beater/authorization/builder.go
Labels: backport

#3310 Refactor decoder.ReqDecoder bits
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/handler_test.go
  beater/api/config/agent/handler_test.go
  beater/api/intake/handler.go
  beater/api/intake/handler_test.go
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  beater/beatertest/context.go
  beater/jaeger/http_test.go
  beater/middleware/request_metadata_middleware.go
  beater/middleware/request_metadata_middleware_test.go
  beater/request/context.go
  beater/request/context_pool.go
  decoder/req_decoder.go
  decoder/req_decoder_test.go
Labels: [zube]: In Review

#3323 [7.6] Stop syncing _beats/libbeat/tests/system/beat/ in beat updates. (#3320)
  script/update_beats.sh
Labels: backport

#3322 [7.x] Stop syncing _beats/libbeat/tests/system/beat/ in beat updates. (#3320)
  script/update_beats.sh
Labels: backport

#3329 [docs] Add note about Jaeger availability on Cloud
  docs/jaeger-support.asciidoc
Labels: docs

#3330 [7.x] docs: add jaeger cloud note (#3329)
  docs/jaeger-support.asciidoc
Labels: backport

#3331 [7.6] docs: add jaeger cloud note (#3329)
  docs/jaeger-support.asciidoc
Labels: backport

#3332 [7.x] decoder: remove EventDecoder type (#3325)
  decoder/event_decoder.go
  processor/asset/sourcemap/sourcemap.go
Labels: backport

#3327 Add new http.response fields for transactions and spans
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/data/intake-api/generated/events.ndjson
  docs/spec/context.json
  docs/spec/http_response.json
  docs/spec/spans/span.json
  model/context.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/error/generated/schema/rum_v3_error.go
  model/span/event.go
  model/span/generated/schema/span.go
  model/test_approved_model/context_full_event with experimental=true.approved.json
  model/transaction/event_test.go
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
  processor/otel/consumer.go
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: enhancement

#3319 [7.x] Refactor decoder.ReqDecoder bits (#3310)
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/handler_test.go
  beater/api/config/agent/handler_test.go
  beater/api/intake/handler.go
  beater/api/intake/handler_test.go
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  beater/beatertest/context.go
  beater/jaeger/http_test.go
  beater/middleware/request_metadata_middleware.go
  beater/middleware/request_metadata_middleware_test.go
  beater/request/context.go
  beater/request/context_pool.go
  decoder/req_decoder.go
  decoder/req_decoder_test.go
Labels: backport

#3343 [7.x] Create specs, handler and processor for ingesting RUM V3 events. (#3328)
  Makefile
  beater/api/mux.go
  beater/config/config.go
  beater/middleware/request_metadata_middleware_test.go
  docs/data/elasticsearch/generated/rum_v3_spans.json
  docs/data/elasticsearch/generated/rum_v3_transactions.json
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/errors/rum_v3_error.json
  docs/spec/spans/rum_v3_span.json
  docs/spec/transactions/rum_v3_transaction.json
  model/error/event.go
  model/error/generated/schema/rum_v3_error.go
  model/span/event.go
  model/span/generated/schema/rum_v3_span.go
  model/transaction/event.go
  model/transaction/generated/schema/rum_v3_transaction.go
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Transactions.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Errors.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultRUMV3Transactions.approved.json
  script/inline_schemas/inline_schemas.go
  testdata/intake-v3/rum_errors.ndjson
  testdata/intake-v3/rum_events.ndjson
  testdata/intake-v3/rum_transactions_spans.ndjson
Labels: backport

#3344 [7.x] Add new http.response fields for transactions and spans (#3327)
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/data/intake-api/generated/events.ndjson
  docs/spec/context.json
  docs/spec/http_response.json
  docs/spec/spans/span.json
  model/context.go
  model/error/event_test.go
  model/error/generated/schema/error.go
  model/error/generated/schema/rum_v3_error.go
  model/span/event.go
  model/span/generated/schema/span.go
  model/test_approved_model/context_full_event with experimental=true.approved.json
  model/transaction/event_test.go
  model/transaction/generated/schema/rum_v3_transaction.go
  model/transaction/generated/schema/transaction.go
  processor/otel/consumer.go
  processor/otel/test_approved/span_error_jaeger_http_1.approved.json
  processor/otel/test_approved/span_error_jaeger_http_2.approved.json
  processor/otel/test_approved/span_error_jaeger_http_3.approved.json
  processor/otel/test_approved/span_error_jaeger_http_4.approved.json
  processor/otel/test_approved/span_error_jaeger_http_5.approved.json
  processor/otel/test_approved/span_error_jaeger_http_6.approved.json
  processor/otel/test_approved/span_jaeger_http_0.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code_0.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_1.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_2.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_3.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_4.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_5.approved.json
  processor/otel/test_approved/transaction_error_jaeger_full_6.approved.json
  processor/otel/test_approved/transaction_jaeger_full_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_0.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result_0.approved.json
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport

#3342 Merge default values with custom API Key Elasticsearch settings
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config_test.go
  changelogs/head.asciidoc
  elasticsearch/config.go
Labels: bug

#3352 [7.6] Remove extra closing brackets (format error) (#3346)
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport

#3351 [7.x] Remove extra closing brackets (format error) (#3346)
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport

#3363 ci(jenkins): retry build docker image up to 3 times with some sleep
  Jenkinsfile
Labels: automation, ci

#3354 [7.x] Merge default values with custom API Key Elasticsearch settings (#3342)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/config/api_key.go
  beater/config/api_key_test.go
  beater/config/config_test.go
  elasticsearch/config.go
Labels: backport

#3349 [test] custom elasticsearch config for sourcemaps
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
  tests/system/test_integration_sourcemap.py
Labels: test

#3365 [7.x] Merge ES default values to Sourcmeap configuration. (#3355)
  beater/config/config_test.go
  beater/config/rum.go
Labels: backport

#3366 [7.x] [test] custom elasticsearch config for sourcemaps (#3349)
  tests/system/apmserver.py
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration.py
  tests/system/test_integration_sourcemap.py
Labels: backport

#3377 [docs] Link to ES Geo IP processor
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: docs, v7.6.0

#3371 Simplify build scripts
  Jenkinsfile
  Makefile
  script/build_apm_docs.sh
  script/jenkins/ci.sh
  script/jenkins/unit-test.sh
  script/jenkins/update-beats.sh
Labels: enhancement

#3369 Add system test environment variable defaults to docker-compose.yml
  docker-compose.yml
  tests/system/apmserver.py
Labels: enhancement

#3381 [7.x] Simplify build scripts (#3371)
  Jenkinsfile
  Makefile
  script/build_apm_docs.sh
  script/jenkins/ci.sh
  script/jenkins/unit-test.sh
  script/jenkins/update-beats.sh
Labels: backport

#3382 [7.x] Add system test environment variable defaults to docker-compose.yml (#3369)
  docker-compose.yml
  tests/system/apmserver.py
Labels: backport

#3383 [7.x] magefile: use mage to build fields assets (#3372)
  Makefile
  magefile.go
  script/jenkins/windows-build.ps1
  script/jenkins/windows-test.ps1
Labels: backport

#3373 docker-compose: run system tests as non-root user
  .ci/scripts/docker-get-logs.sh
  .gitignore
  Makefile
  tests/Dockerfile
Labels: enhancement

#3359 Instrument kibana client with apm go agent
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  changelogs/head.asciidoc
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  tests/kibana.go
Labels: enhancement

#3376 [docs] Explain stack frames
  docs/guide/apm-data-model.asciidoc
  docs/storage-management.asciidoc
Labels: docs, v7.7.0

#3380 [7.5] docs: link to {ref} GeoIP processor (#3377)
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3378 [7.x] docs: link to {ref} GeoIP processor (#3377)
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3379 [7.6] docs: link to {ref} GeoIP processor (#3377)
  docs/configuration-rum.asciidoc
  docs/configuring-ingest.asciidoc
  docs/guide/apm-release-notes.asciidoc
Labels: backport

#3386 [7.x] Instrument kibana client with apm go agent (#3359)
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  elasticsearch/client.go
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  tests/kibana.go
Labels: backport

#3367 Attempt to fix flaky API Key test
  tests/system/test_apikey_cmd.py
  tests/system/test_auth.py
  tests/system/test_instrumentation.py
  tests/system/test_integration_sourcemap.py
  tests/system/test_tls.py
Labels: test

#3395 [7.x] Attempt to fix flaky API Key test (#3367)
  tests/system/test_apikey_cmd.py
  tests/system/test_auth.py
  tests/system/test_instrumentation.py
  tests/system/test_integration_sourcemap.py
  tests/system/test_tls.py
Labels: backport

#3397 Update changelog to 7.6.1 changes
  changelogs/7.6.asciidoc
  changelogs/head.asciidoc
Labels: v7.6.1

#3399 [7.6] Update changelog to 7.6.1 changes (#3397)
  changelogs/7.6.asciidoc
Labels: backport

#3398 [7.x] Update changelog to 7.6.1 changes (#3397)
  changelogs/7.6.asciidoc
Labels: backport

#3394 beater/jaeger: introduce "auth_tag" configuration
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/authorization/header.go
  beater/config/jaeger.go
  beater/jaeger/common.go
  beater/jaeger/grpc.go
  beater/jaeger/grpc_test.go
  beater/jaeger/server.go
  beater/jaeger/server_test.go
  beater/middleware/authorization_middleware.go
  changelogs/head.asciidoc
  docs/jaeger-support.asciidoc
  testdata/jaeger/batch_0_authorization.json
  tests/system/config/apm-server.yml.j2
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/test_jaeger.py
Labels: enhancement

#3402 [7.x] beater/jaeger: introduce "auth_tag" configuration (#3394)
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/authorization/header.go
  beater/config/jaeger.go
  beater/jaeger/common.go
  beater/jaeger/grpc.go
  beater/jaeger/grpc_test.go
  beater/jaeger/server.go
  beater/jaeger/server_test.go
  beater/middleware/authorization_middleware.go
  changelogs/7.7.asciidoc
  docs/jaeger-support.asciidoc
  testdata/jaeger/batch_0_authorization.json
  tests/system/config/apm-server.yml.j2
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/test_jaeger.py
Labels: backport

#3393 Makefile: rewrite all the things
  .gitignore
  Makefile
  TESTING.md
  docs/data/elasticsearch/generated/rum_v3_errors.json
  magefile.go
  script/jenkins/linux-test.sh
  script/jenkins/unit-test.sh
  tests/Dockerfile
Labels: enhancement

#3385 [7.x] docker-compose: run system tests as non-root user (#3373)
  .ci/scripts/docker-get-logs.sh
  .gitignore
  Makefile
  tests/Dockerfile
Labels: backport

#3406 ci(jenkins): apm-its-downstream params has changed
  Jenkinsfile
Labels: automation
