Repository elastic/apm-server, pull requests merged in 2021-04, with the labels that each got.

#4986 ingest: translate known OpenTelemetry JVM metrics
  apmpackage/apm/0.2.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_opentelemetry_metrics.json
  apmpackage/apm/0.2.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_opentelemetry_metrics.json
  apmpackage/apm/0.2.0/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_opentelemetry_metrics.json
  apmpackage/apm/0.2.0/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_opentelemetry_metrics.json
  apmpackage/apm/0.2.0/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/traces/elasticsearch/ingest_pipeline/apm_opentelemetry_metrics.json
  apmpackage/apm/0.2.0/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  changelogs/head.asciidoc
  docs/configuring-ingest.asciidoc
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
  systemtest/otlp_test.go
Labels: v7.13.0

#4997 [7.x] systemtest: fix Elastic Agent enrollment (#4883)
  systemtest/containers.go
Labels: backport

#5013 [7.x] systemtest: fix query for enrollment API Keys (#4942)
  systemtest/fleettest/client.go
Labels: backport

#5046 [7.12] docs: update agent/server compat for ruby (#5036)
  docs/guide/agent-server-compatibility.asciidoc
Labels: backport

#5045 [7.x] docs: update agent/server compat for ruby (#5036)
  docs/guide/agent-server-compatibility.asciidoc
Labels: backport

#5055 [mergify] run the check after the PR gets merged
  .mergify.yml
Labels: v7.13.0

#5053 docker-compose.yml: allow wildard deletes
  docker-compose.yml
  systemtest/elasticsearch.go
Labels: v7.13.0

#5048 ingest: make apm_ingest_timestamp first pipeline
  apmpackage/apm/0.2.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.2.0/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  changelogs/head.asciidoc
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
Labels: v7.13.0

#5052 processor/stream: fix panic in benchmarks
  processor/stream/benchmark_test.go
Labels: v7.13.0

#5065 Do not copy the template file for the Readme
  script/copy_package.py
Labels: v7.13.0

#5056 Introduce session.{id,sequence} for transactions
  apmpackage/apm/0.2.0/data_stream/traces/fields/fields.yml
  apmpackage/apm/0.2.0/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/rumv3/transaction.json
  docs/spec/v2/transaction.json
  include/fields.go
  model/modeldecoder/generator/nint.go
  model/modeldecoder/generator/nstring.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/model_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/model_test.go
  model/modeldecoder/v2/transaction_test.go
  model/transaction.go
  model/transaction/_meta/fields.yml
  model/transaction_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_stream_result/testIntegrationResultReadError.approved.json
  testdata/intake-v2/transactions.ndjson
Labels: v7.13.0

#5054 Add a reason to some auth failures
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/intake/test_approved/integration/backend/TestIntakeBackendHandler_AuthorizationMiddleware/Unauthorized.approved.json
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/authorization/allow.go
  beater/authorization/allow_test.go
  beater/authorization/apikey.go
  beater/authorization/apikey_test.go
  beater/authorization/bearer.go
  beater/authorization/bearer_test.go
  beater/authorization/builder.go
  beater/authorization/builder_test.go
  beater/authorization/deny.go
  beater/authorization/deny_test.go
  beater/grpcauth.go
  beater/jaeger/common.go
  beater/middleware/authorization_middleware.go
  beater/middleware/authorization_middleware_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/request/result.go
  changelogs/head.asciidoc
  cmd/apikey.go
  tests/system/test_auth.py
Labels: enhancement, v7.13.0

#5067 Support for ingesting user.domain
  apmpackage/apm/0.2.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.2.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.2.0/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/rumv3/error.json
  docs/spec/rumv3/metadata.json
  docs/spec/rumv3/transaction.json
  docs/spec/v2/error.json
  docs/spec/v2/metadata.json
  docs/spec/v2/transaction.json
  include/fields.go
  model/error/_meta/fields.yml
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  model/user.go
  model/user_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/metadata.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: v7.13.0

#5078 docs: Link to .NET `ServerCert` docs
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
Labels: docs, v7.12.0

#5080 [7.12] docs: Link to .NET ServerCert docs (#5078)
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
Labels: backport

#5079 [7.x] docs: Link to .NET ServerCert docs (#5078)
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
Labels: backport

#5090 Add metadata to API Keys created by server
  changelogs/head.asciidoc
  cmd/apikey.go
  elasticsearch/security_api.go
  systemtest/apikeycmd_test.go
Labels: v7.13.0

#5097 [ilm] Apply lowercasing after resolving variables
  idxmgmt/ilm/config.go
  idxmgmt/ilm/config_test.go
Labels: v7.13.0

#5100 [7.12] Update to elastic/beats@060ae4340959 and go version update
  .go-version
  NOTICE.txt
  go.mod
  go.sum
Labels: v7.12.0

#5091 docs: remove experimental label from API Key auth
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/head.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: v7.13.0

#5103 mergify: prefix PR title with target branch
  .mergify.yml
Labels: v7.12.0

#5106 mergify: hardcode target branch name
  .mergify.yml
Labels: v7.12.0

#5085 systemtest: use Fleet Server
  systemtest/apmservertest/config.go
  systemtest/containers.go
  systemtest/fleet_test.go
  systemtest/fleettest/client.go
Labels: v7.13.0

#5068 docs: data security, filtering, and obfuscation
  docs/configuring-ingest.asciidoc
  docs/guide/data-security.asciidoc
  docs/guide/features.asciidoc
Labels: docs, v7.12.0

#5111 [7.12] docs: data security, filtering, and obfuscation (#5068)
  docs/configuring-ingest.asciidoc
  docs/guide/data-security.asciidoc
  docs/guide/features.asciidoc
Labels: backport

#5109 [7.x] docs: data security, filtering, and obfuscation (#5068)
  docs/configuring-ingest.asciidoc
  docs/guide/data-security.asciidoc
  docs/guide/features.asciidoc
Labels: backport

#5115 docker-compose: fix kibana config
  docker-compose.yml
Labels: v7.13.0

#5074 processor/otel: add support for rpc conventions
  apmpackage/apm/0.2.0/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/0.2.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.2.0/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/0.2.0/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/0.2.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.2.0/docs/README.md
  changelogs/head.asciidoc
  docs/fields.asciidoc
  include/fields.go
  model/client.go
  model/client_test.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/metadata_test.go
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/stream/package_tests/error_attrs_test.go
  processor/stream/package_tests/metadata_attrs_test.go
  processor/stream/package_tests/span_attrs_test.go
  processor/stream/package_tests/transaction_attrs_test.go
Labels: v7.13.0

#5118 Fix approvals for system tests
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  systemtest/approvals/TestRUMErrorSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: v7.13.0

#5121 systemtest: enable TLS for fleet-server
  systemtest/containers.go
Labels: v7.13.0

#5083 systemtest: update go.opentelemetry.io/otel
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/go.mod
  systemtest/go.sum
  systemtest/logging_test.go
  systemtest/otlp_test.go
Labels: v7.13.0

#5124 docs: add 7.12.1 release notes
  changelogs/7.12.asciidoc
Labels: docs, v7.12.0, v7.13.0

#5132 systemtest: fix exposed port mapping
  systemtest/containers.go
  systemtest/fleet_test.go
  systemtest/go.mod
Labels: v7.13.0

#5129 [7.12] docs: add 7.12.1 release notes (#5124)
  changelogs/7.12.asciidoc
Labels: backport

#5128 [7.x] docs: add 7.12.1 release notes (#5124)
  changelogs/7.12.asciidoc
Labels: backport

#5138 systemtest: add fleet-server to docker-compose.yml
  docker-compose.yml
  systemtest/containers.go
  systemtest/fleet_test.go
Labels: v7.13.0, v7.14.0

#5137 [7.13] create 7.13 changelog (3ec1c48b)
  CHANGELOG.asciidoc
  changelogs/7.13.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#5136 [7.x] create 7.13 changelog (3ec1c48b)
  CHANGELOG.asciidoc
  changelogs/7.13.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#5127 Bump elastic stack version automation
  .ci/bump-stack-version.sh
  .gitignore
  .mergify.yml
  script/check_docker_compose.sh
Labels: v7.12.0, v7.13.0, v7.14.0

#5171 automation: use the right variable name
  .ci/bump-stack-version.sh
Labels: v7.12.0, v7.13.0, v7.14.0

#5172 docs: remove apm_user limitation
  docs/apm-package/apm-integration.asciidoc
Labels: Team:Docs, v7.13.0

#5183 [7.x] docs: remove apm_user limitation (#5172)
  docs/apm-package/apm-integration.asciidoc
Labels: backport

#5184 [7.13] docs: remove apm_user limitation (#5172)
  docs/apm-package/apm-integration.asciidoc
Labels: backport

#5186 [automation] update elastic stack version for testing 8.0.0-4fa04b7f
  docker-compose.yml
Labels: automation, dependency

#5181 [mergify] use variable for the target branch
  .mergify.yml
Labels: Team:Automation

#5189 [automation] update elastic stack version for testing 8.0.0-dec8157c
  docker-compose.yml
Labels: automation, dependency

#5191 [7.x] feat: add support for auto-backports (#4990)
  .mergify.yml
Labels: backport

#5192 [7.13] feat: add support for auto-backports (#4990)
  .mergify.yml
Labels: backport

#5194 [7.13] [mergify] run the check after the PR gets merged (#5055)
  .mergify.yml
Labels: backport

#5193 [7.x] [mergify] run the check after the PR gets merged (#5055)
  .mergify.yml
Labels: backport

#5196 [7.13] [mergify] assign the original author (#5069)
  .mergify.yml
Labels: backport

#5195 [7.x] [mergify] assign the original author (#5069)
  .mergify.yml
Labels: backport

#5197 [7.x] mergify: prefix PR title with target branch (#5103)
  .mergify.yml
Labels: backport

#5198 [7.13] mergify: prefix PR title with target branch (#5103)
  .mergify.yml
Labels: backport

#5199 [7.x] mergify: hardcode target branch name (#5106)
  .mergify.yml
Labels: backport

#5200 [7.13] mergify: hardcode target branch name (#5106)
  .mergify.yml
Labels: backport

#5202 [7.13] [7.x] mergify: add backports for 7.13/7.14 (#5201)
  .mergify.yml
Labels: backport
