Repository elastic/apm-server, pull requests merged in 2021-08, with the labels that each got.

#5835 update-beats: git add fields updates
  .ci/scripts/update-beats.sh
Labels: backport-7.x

#5842 sourcemap: fix data race in test
  sourcemap/fleet_store_test.go
Labels: backport-7.x

#5840 Move labels and timestamp to model.APMEvent
  agentcfg/reporter.go
  agentcfg/reporter_test.go
  beater/api/profile/convert.go
  beater/beater_test.go
  model/apmevent.go
  model/apmevent_test.go
  model/error.go
  model/error_test.go
  model/labels.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/input.go
  model/modeldecoder/modeldecoderutil/labels.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/rumv3/metricset_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/exceptions.go
  processor/otel/exceptions_test.go
  processor/otel/metadata.go
  processor/otel/metadata_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/processor.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-7.x, v7.15.0

#5845 [automation] update elastic stack version for testing 7.14.0-8d3ee29d
  docker-compose.yml
Labels: automation, dependency

#5854 Remove sourcemap/test and elasticsearch/estest
  beater/beater_test.go
  elasticsearch/estest/client.go
  sourcemap/es_store_test.go
  sourcemap/mapper_test.go
  sourcemap/processor_test.go
  sourcemap/store_test.go
  sourcemap/test/es_client.go
Labels: backport-7.x

#5861 docs: add 6.8.18 release notes
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: Team:Docs, v6.8, v7.14.0, v7.15.0

#5863 [7.14] docs: add 6.8.18 release notes (#5861)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#5855 [7.x] sourcemap: fix data race in test (#5842)
  sourcemap/fleet_store_test.go
Labels: backport

#5862 [7.x] docs: add 6.8.18 release notes (#5861)
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
Labels: backport

#5780 Added AWS Lambda Node.js instructions
  docs/guide/opentelemetry-elastic.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0, v8.0.0

#5867 [master] Added AWS Lambda Node.js instructions (#5780)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5866 [7.14] Added AWS Lambda Node.js instructions (#5780)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5865 [7.x] Added AWS Lambda Node.js instructions (#5780)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5860 docs: add 7.14 release notes
  CHANGELOG.asciidoc
  changelogs/7.13.asciidoc
  changelogs/7.14.asciidoc
  changelogs/8.0.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#5864 [6.8] docs: add 6.8.18 release notes (#5861)
  changelogs/6.8.asciidoc
Labels: backport

#5869 [automation] update elastic stack version for testing 7.14.0-28f3035b
  docker-compose.yml
Labels: automation, dependency

#5870 [7.14] docs: add 7.14 release notes (#5860)
  CHANGELOG.asciidoc
  changelogs/7.13.asciidoc
  changelogs/7.14.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#5871 [7.x] docs: add 7.14 release notes (#5860)
  CHANGELOG.asciidoc
  changelogs/7.13.asciidoc
  changelogs/7.14.asciidoc
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#5868 [automation] update elastic stack version for testing 8.0.0-93ecf1d0
  docker-compose.yml
Labels: automation, dependency

#5859 docs: update data streams naming
  docs/apm-package/data-streams.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#5877 [7.x] docs: update data streams naming (#5859)
  docs/apm-package/data-streams.asciidoc
Labels: backport

#5878 [7.14] docs: update data streams naming (#5859)
  docs/apm-package/data-streams.asciidoc
Labels: backport

#5880 [7.14] docs: add iOS agent links (#5634)
  docs/common-problems.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: backport

#5875 docs: update transaction metrics
  docs/transaction-metrics.asciidoc
Labels: backport-7.13, backport-7.14, backport-7.x

#5876 ingest/pipeline: fix compat with old Elasticsearch
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_error_grouping_name.json
  changelogs/head.asciidoc
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
Labels: backport-7.14, backport-7.x, v7.15.0

#5886 [automation] update elastic stack version for testing 7.14.0-1738ccc6
  docker-compose.yml
Labels: automation, dependency

#5884 beater: implement reload.ReloadableList directly
  beater/beater.go
  beater/server_test.go
Labels: backport-7.x, v7.15.0

#5885 [automation] update elastic stack version for testing 8.0.0-0c340354
  docker-compose.yml
Labels: automation, dependency

#5671 Update network connection fields
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  apmpackage/cmd/gen-package/genfields.go
  changelogs/head.asciidoc
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/fields.asciidoc
  docs/spec/rumv3/metadata.json
  docs/spec/v2/metadata.json
  include/fields.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/network.go
  model/network_test.go
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v2/transactions_spans_rum.ndjson
  testdata/intake-v3/rum_events.ndjson
Labels: OpenTelemetry, backport-7.x, v7.15.0

#5892 Conditionally restart apm-server
  beater/beater.go
  beater/beater_test.go
Labels: backport-7.x, v7.15.0

#5895 [automation] update elastic stack version for testing 8.0.0-4c35f443
  docker-compose.yml
Labels: automation, dependency

#5900 [automation] update elastic stack version for testing 8.0.0-e8455215
  docker-compose.yml
Labels: dependency, automation

#5901 [automation] update elastic stack version for testing 7.14.1-22366df8
  docker-compose.yml
Labels: dependency, automation

#5890 Update go-elasticsearch/v7
  beater/auth/authenticator_test.go
  go.mod
  go.sum
  sourcemap/processor_test.go
Labels: v7.15.0

#5896 aggregation/spanmetrics: handle composite spans
  changelogs/head.asciidoc
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: v7.15.0, backport-7.x

#5902 [automation] update libbeat and beats packaging
  NOTICE.txt
  beater/config/config_test.go
  docs/fields.asciidoc
  elasticsearch/config_test.go
  go.mod
  go.sum
  include/fields.go
  x-pack/apm-server/include/fields.go
Labels: automation

#5879 [7.x] docs: add iOS agent links (#5634)
  docs/common-problems.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: backport

#5905 systemtest: test agent config
  systemtest/agentconfig.go
  systemtest/agentconfig_test.go
  systemtest/apmservertest/config.go
  tests/system/test_integration_acm.py
Labels: v7.15.0, backport-7.x

#5908 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#5907 [automation] update elastic stack version for testing 7.14.1-8dd23e93
  docker-compose.yml
Labels: dependency, automation

#5911 Reuse port
  NOTICE.txt
  beater/beater.go
  beater/beater_test.go
  beater/http.go
  beater/jaeger/server.go
  changelogs/head.asciidoc
  go.mod
  go.sum
Labels: backport-7.x

#5916 [automation] update elastic stack version for testing 7.14.1-899a999b
  docker-compose.yml
Labels: dependency, automation

#5915 sampling/pubsub: fix flaky test
  x-pack/apm-server/sampling/pubsub/pubsub_test.go
Labels: backport-7.14, backport-7.x

#5917 beater/api/mux: fix Fleet agent config enablement
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_test.go
  beater/http.go
  beater/server.go
  beater/tracing.go
  changelogs/head.asciidoc
  systemtest/agentconfig_test.go
Labels: v7.15.0, backport-7.x

#5903 Move setting destination.ip back into apm-server
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  apmpackage/cmd/gen-package/genfields.go
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
  model/apmevent.go
  model/apmevent_test.go
  model/destination.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/span.go
  model/span_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  systemtest/ingest_test.go
Labels: v7.15.0, backport-7.x

#5927 [automation] update elastic stack version for testing 7.14.1-a5e22cba
  docker-compose.yml
Labels: dependency, automation

#5926 [automation] update elastic stack version for testing 7.15.0-83f2fe8a
  docker-compose.yml
Labels: dependency, automation

#5933 [automation] update elastic stack version for testing 7.14.1-5a4d121c
  docker-compose.yml
Labels: dependency, automation

#5934 Wait for integration using Elasticsearch queries
  beater/beater.go
  beater/config/data_streams.go
  beater/server_test.go
  beater/waitintegration.go
  docs/configuration-process.asciidoc
Labels: v7.15.0, backport-7.x

#5939 [automation] update elastic stack version for testing 7.14.1-3af02427
  docker-compose.yml
Labels: dependency, automation

#5938 [automation] update elastic stack version for testing 7.15.0-ba42231a
  docker-compose.yml
Labels: dependency, automation

#5940 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#5930 docs: Anonymous authentication
  docs/apm-package/apm-input-settings.asciidoc
  docs/apm-package/input-apm.asciidoc
  docs/configuration-anonymous.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring.asciidoc
  docs/data-ingestion.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: v7.15.0, Team:Docs

#5935 docs: add source map upload notes
  docs/apm-package/apm-integration.asciidoc
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: v7.14.0, v7.15.0, Team:Docs

#5943 [7.14] docs: add sourcemap upload notes (#5935)
  docs/apm-package/apm-integration.asciidoc
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: backport

#5941 [7.x] docs: Anonymous authentication (#5930)
  docs/apm-package/apm-input-settings.asciidoc
  docs/apm-package/input-apm.asciidoc
  docs/configuration-anonymous.asciidoc
  docs/configuration-rum.asciidoc
  docs/configuring.asciidoc
  docs/data-ingestion.asciidoc
  docs/secure-communication-agents.asciidoc
Labels: backport

#5942 [7.x] docs: add sourcemap upload notes (#5935)
  docs/apm-package/apm-integration.asciidoc
  docs/sourcemap-api.asciidoc
  docs/sourcemaps.asciidoc
Labels: backport

#5945 [automation] update elastic stack version for testing 7.14.1-c6219279
  docker-compose.yml
Labels: dependency, automation

#5944 [automation] update elastic stack version for testing 8.0.0-2e89a578
  docker-compose.yml
Labels: dependency, automation

#5946 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#5947 apmpackage: copy full field hierarchy
  apmpackage/apm/data_stream/app_metrics/fields/base-fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  apmpackage/apm/data_stream/error_logs/fields/base-fields.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/fields/base-fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/data_stream/profile_metrics/fields/base-fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/manifest.yml
  apmpackage/apm/data_stream/sampled_traces/fields/base-fields.yml
  apmpackage/apm/data_stream/sampled_traces/manifest.yml
  apmpackage/apm/data_stream/traces/fields/base-fields.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/data_stream/traces/manifest.yml
  apmpackage/apm/docs/README.md
  apmpackage/cmd/gen-package/field.go
  apmpackage/cmd/gen-package/gendocs.go
  apmpackage/cmd/gen-package/genfields.go
  changelogs/head.asciidoc
Labels: v7.15.0, backport-7.x

#5957 [automation] update elastic stack version for testing 7.14.1-904a8260
  docker-compose.yml
Labels: dependency, automation

#5956 [automation] update elastic stack version for testing 7.15.0-4b8a78a4
  docker-compose.yml
Labels: dependency, automation

#5955 [automation] update elastic stack version for testing 8.0.0-7e122dd9
  docker-compose.yml
Labels: dependency, automation

#5958 model: add APMEvent.{Observer,ECSVersion}
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  beater/beater.go
  beater/processors.go
  beater/server_test.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/fields.asciidoc
  include/fields.go
  model/apmevent.go
  model/apmevent_test.go
  model/batch.go
  model/error/_meta/fields.yml
  model/host_test.go
  model/metricset/_meta/fields.yml
  model/metricset_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/metadata_test.go
  model/observer.go
  model/observer_test.go
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/span_test.go
  model/transaction/_meta/fields.yml
  model/transaction_test.go
  publish/pub.go
Labels: v7.15.0, backport-7.x

#5952 Update tail sampling to require data streams
  apmpackage/apm/data_stream/sampled_traces/manifest.yml
  beater/config/config.go
  beater/config/config_test.go
  beater/config/sampling.go
  beater/config/sampling_test.go
  beater/waitintegration.go
  changelogs/head.asciidoc
  systemtest/apmservertest/config.go
  systemtest/fleettest/client.go
  systemtest/sampling_test.go
  testing/docker/elasticsearch/roles.yml
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
  x-pack/apm-server/sampling/pubsub/datastream.go
Labels: v7.15.0, backport-7.x

#5965 [7.15] Update to elastic/beats@21bbe7ffc579
  Makefile
  NOTICE.txt
  apmpackage/apm/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/metricsets.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/fields.asciidoc
  go.mod
  go.sum
  include/fields.go
  tests/system/error.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
  tests/system/metricset.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
Labels: v7.15.0

#5968 [automation] update elastic stack version for testing 7.14.1-a6cb01c7
  docker-compose.yml
Labels: dependency, automation

#5969 [automation] update elastic stack version for testing 8.0.0-fa246295
  docker-compose.yml
Labels: dependency, automation

#5972 Update mergify to 7.15
  .mergify.yml
Labels: backport-7.x

#5974 Copy `error.log.message` or `error.exception.message` to `message`
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/docs/README.md
  beater/beater.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/fields.asciidoc
  include/fields.go
  model/apmevent.go
  model/apmevent_test.go
  model/error/_meta/fields.yml
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modelprocessor/errormessage.go
  model/modelprocessor/errormessage_test.go
  systemtest/approvals/TestRUMErrorSourcemapping.approved.json
  tests/system/error.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
Labels: v7.16.0, backport-7.x

#5978 [automation] update elastic stack version for testing 8.0.0-8ac8c039
  docker-compose.yml
Labels: dependency, automation

#5980 [automation] update elastic stack version for testing 7.16.0-ab6de48d
  docker-compose.yml
Labels: dependency, automation

#5979 [automation] update elastic stack version for testing 7.15.0-e06b4078
  docker-compose.yml
Labels: dependency, automation

#6004 [automation] update elastic stack version for testing 7.16.0-2d73c7e8
  docker-compose.yml
Labels: dependency, automation

#6005 [automation] update elastic stack version for testing 7.15.0-a7c04a10
  docker-compose.yml
Labels: dependency, automation

#6006 [automation] update elastic stack version for testing 8.0.0-56a61c29
  docker-compose.yml
Labels: dependency, automation

#5982 [apmpackage] Remove duplicate input variable attributes
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/manifest.yml
Labels: [zube]: In Review, v7.15.0, backport-7.x

#6012 [CI]: use setEnvVar instead of global env variable
  .ci/check-packages.groovy
Labels: automation, Team:Automation, backport-7.x

#5976 docs: link to APM Server central config privileges
  docs/configure-kibana-endpoint.asciidoc
Labels: [zube]: In Review, v7.14.0, v7.15.0, Team:Docs

#6015 [7.14] docs: link to req’d privs (#5976)
  docs/configure-kibana-endpoint.asciidoc
Labels: backport

#6014 [7.x] docs: link to req’d privs (#5976)
  docs/configure-kibana-endpoint.asciidoc
Labels: backport

#5954 docs: add rum response_headers
  docs/configuration-rum.asciidoc
Labels: [zube]: In Review, v7.14.0, Team:Docs

#6017 [7.x] docs: add rum response_headers (#5954)
  docs/configuration-rum.asciidoc
Labels: backport

#6018 [7.14] docs: add rum response_headers (#5954)
  docs/configuration-rum.asciidoc
Labels: backport

#5953 docs: Change API key docs to Kibana UI
  docs/api-keys.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/images/api-key-copy.png
  docs/images/api-key-create.png
  docs/images/server-api-key-create.png
  docs/secure-communication-agents.asciidoc
Labels: [zube]: In Review, v7.14.0, Team:Docs

#6019 [7.15] docs: add rum response_headers (#5954)
  docs/configuration-rum.asciidoc
Labels: backport

#6021 [7.14] docs: Change API key docs to Kibana UI (#5953)
  docs/api-keys.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/images/api-key-copy.png
  docs/images/api-key-create.png
  docs/images/server-api-key-create.png
  docs/secure-communication-agents.asciidoc
Labels: backport

#6022 [7.15] docs: Change API key docs to Kibana UI (#5953)
  docs/api-keys.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/images/api-key-copy.png
  docs/images/api-key-create.png
  docs/images/server-api-key-create.png
  docs/secure-communication-agents.asciidoc
Labels: backport

#6020 [7.x] docs: Change API key docs to Kibana UI (#5953)
  docs/api-keys.asciidoc
  docs/copied-from-beats/docs/security/api-keys.asciidoc
  docs/copied-from-beats/docs/shared-securing-beat.asciidoc
  docs/images/api-key-copy.png
  docs/images/api-key-create.png
  docs/images/server-api-key-create.png
  docs/secure-communication-agents.asciidoc
Labels: backport

#5983 Introduce model.Trace
  model/apmevent.go
  model/apmevent_test.go
  model/error.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/span.go
  model/span_test.go
  model/trace.go
  model/transaction.go
  processor/otel/exceptions_test.go
  processor/otel/metadata_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_bench_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: [zube]: In Review, v7.16.0, backport-7.x

#6024 systemtest: fix approval due to geoIP change
  systemtest/approvals/TestRUMXForwardedFor.approved.json
Labels: backport-7.x

#5984 Introduce model.Processor
  beater/api/profile/convert.go
  beater/beater.go
  changelogs/head.asciidoc
  model/apmevent.go
  model/apmevent_test.go
  model/error.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  model/modelprocessor/eventcounter.go
  model/modelprocessor/eventcounter_test.go
  model/processor.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/exceptions_test.go
  processor/otel/metadata_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  processor/otel/traces.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: [zube]: In Review, v7.16.0, backport-7.x

#6031 [automation] update elastic stack version for testing 7.16.0-c3b80e7b
  docker-compose.yml
Labels: dependency, automation

#6033 [7.x] Introduce model.Processor (#5984)
  beater/api/profile/convert.go
  beater/beater.go
  model/apmevent.go
  model/apmevent_test.go
  model/error.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  model/modelprocessor/eventcounter.go
  model/modelprocessor/eventcounter_test.go
  model/processor.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/exceptions_test.go
  processor/otel/metadata_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  processor/otel/traces.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#6011 fail open if snapshot not available
  script/check_docker_compose.sh
  script/latest_snapshot_version.py
Labels: backport-7.x

#6041 [automation] update elastic stack version for testing 7.16.0-13c65289
  docker-compose.yml
Labels: dependency, automation

#6070 [automation] update elastic stack version for testing 7.15.0-0211404a
  docker-compose.yml
Labels: dependency, automation

#6071 [automation] update elastic stack version for testing 8.0.0-1efff7fc
  docker-compose.yml
Labels: dependency, automation

#6069 [automation] update elastic stack version for testing 7.16.0-d17acf1e
  docker-compose.yml
Labels: dependency, automation

#6065 modeldecoder/rumv3: drop standalone metricsets
  changelogs/head.asciidoc
  docs/data/intake-api/generated/rum_v3_events.ndjson
  docs/spec/rumv3/metricset.json
  docs/spec/rumv3/transaction.json
  model/modeldecoder/generator/cmd/main.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metricset_test.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/model_test.go
  processor/stream/processor.go
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  testdata/intake-v3/rum_events.ndjson
Labels: v7.16.0, backport-7.x

#6072 Migrate/remove some more Python system tests
  systemtest/apikeycmd_test.go
  tests/system/drop_unsampled_transactions.approved.json
  tests/system/jaeger_batch_0.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
  tests/system/jaegergrpc/main.go
  tests/system/keep_unsampled_transactions.approved.json
  tests/system/test_apikey_cmd.py
  tests/system/test_auth.py
  tests/system/test_jaeger.py
Labels: backport-7.x

#6067 Move duration to model.Event.Duration
  model/apmevent.go
  model/apmevent_test.go
  model/event.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  utility/map_str_enhancer.go
  utility/map_str_enhancer_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: v7.16.0, backport-7.x

#6079 Update go-elasticsearch client
  NOTICE.txt
  go.mod
  go.sum
Labels: v7.15.0

#6058 Stop updating/checking Kibana index pattern
  .ci/scripts/sync.sh
  Jenkinsfile
  Makefile
  RELEASES.md
  script/are_kibana_saved_objects_updated.py
  script/update_kibana_objects.py
Labels: backport-7.x, backport-7.15

#6076 [DOCS] Fix invalid code snippet
  docs/storage-management.asciidoc
Labels: backport-7.13, backport-7.14, backport-7.x, backport-7.15

#6091 [automation] update elastic stack version for testing 8.0.0-78724554
  docker-compose.yml
Labels: dependency, automation

#6092 [automation] update elastic stack version for testing 7.16.0-978c8c33
  docker-compose.yml
Labels: dependency, automation

#6093 [automation] update elastic stack version for testing 7.15.0-1649f9c1
  docker-compose.yml
Labels: dependency, automation

#6086 Remove `apm-server.mode` and experimental fields
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  beater/config/config.go
  beater/config/mode.go
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  include/fields.go
  model/error.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/modeldecoder/input.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  model/profile/_meta/fields.yml
  model/span.go
  model/span/_meta/fields.yml
  model/transaction.go
  model/transaction/_meta/fields.yml
  processor/stream/processor.go
  testdata/intake-v2/experimental.ndjson
  tests/system/test_integration.py
Labels: v7.16.0, backport-7.x

#6083 docs: add 7.14.1 release notes
  changelogs/7.14.asciidoc
Labels: v7.15.0, Team:Docs, 7.14.0

#6097 [7.15] docs: add 7.14.1 release notes (#6083)
  changelogs/7.14.asciidoc
Labels: backport

#6096 [7.x] docs: add 7.14.1 release notes (#6083)
  changelogs/7.14.asciidoc
Labels: backport
