Repository elastic/apm-server, pull requests merged in 2021-01, with the labels that each got.

#4596 docs: add 7.10.2 release notes
  changelogs/7.10.asciidoc
  changelogs/7.11.asciidoc
Labels: docs, v7.10.0

#4598 [7.11] docs: add 7.10.2 release notes (#4596)
  changelogs/7.10.asciidoc
Labels: backport

#4597 [7.x] docs: add 7.10.2 release notes (#4596)
  changelogs/7.10.asciidoc
Labels: backport

#4599 [7.10] docs: add 7.10.2 release notes (#4596)
  changelogs/7.10.asciidoc
Labels: backport

#4585 processor/otel: update tests to use Jaeger model
  processor/otel/consumer_test.go
  processor/otel/test_approved/consume_empty.approved.json
  processor/otel/test_approved/consume_emptytrace.approved.json
  processor/otel/test_approved/consume_span.approved.json
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
Labels: v7.12.0

#4593 Update go-elasticsearch client to 7.11 branch
  NOTICE.txt
  go.mod
  go.sum
Labels: test-plan-skip, v7.11.0

#4590 Switch to JSON logging by default
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/7.11.asciidoc
  cmd/root.go
  systemtest/export_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
Labels: v7.11.0

#4605 [7.11] Switch to JSON logging by default (#4590)
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  cmd/root.go
  systemtest/export_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
Labels: backport

#4604 [7.x] Switch to JSON logging by default (#4590)
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  changelogs/7.11.asciidoc
  cmd/root.go
  systemtest/export_test.go
  tests/system/config/apm-server.yml.j2
  tests/system/test_integration_acm.py
  tests/system/test_jaeger.py
Labels: backport

#4600 docs: 7.11 breaking changes
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
Labels: v7.11.0

#4607 [7.11] docs: 7.11 breaking changes (#4600)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
Labels: backport

#4606 [7.x] docs: 7.11 breaking changes (#4600)
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
Labels: backport

#4608 docs: link to other troubleshooting guides
  docs/guide/troubleshooting.asciidoc
  docs/troubleshooting.asciidoc
Labels: docs, v7.10.0

#4611 Add missing fields properties
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/cmd/gen-package/field.go
Labels: bug

#4615 [7.10] docs: link to other troubleshooting guides (#4608)
  docs/guide/troubleshooting.asciidoc
  docs/troubleshooting.asciidoc
Labels: backport

#4614 [7.11] docs: link to other troubleshooting guides (#4608)
  docs/guide/troubleshooting.asciidoc
  docs/troubleshooting.asciidoc
Labels: backport

#4613 [7.x] docs: link to other troubleshooting guides (#4608)
  docs/guide/troubleshooting.asciidoc
  docs/troubleshooting.asciidoc
Labels: backport

#4624 [7.x] fix: avoid panic when sourcemap doc does not contain hit (#4619)
  sourcemap/es_store.go
  sourcemap/es_store_test.go
  sourcemap/test/es_client.go
Labels: backport

#4634 [7.10] go.mod: use upstream badger (#4631)
  NOTICE.txt
  go.mod
  go.sum
Labels: backport

#4632 [7.x] go.mod: use upstream badger (#4631)
  NOTICE.txt
  go.mod
  go.sum
Labels: backport

#4633 [7.11] go.mod: use upstream badger (#4631)
  NOTICE.txt
  go.mod
  go.sum
Labels: backport

#4638 [7.11] script: simplify generate_notice.py by using go-licence-detector. (#4635)
  Makefile
  NOTICE.txt
  go.sum
  script/generate_notice.py
Labels: backport

#4637 [7.x] script: simplify generate_notice.py by using go-licence-detector. (#4635)
  Makefile
  NOTICE.txt
  go.sum
  script/generate_notice.py
Labels: backport

#4646 [7.11] script: simplify generate_notice.py (#4644)
  Makefile
  NOTICE.txt
  go.sum
  script/generate_notice.py
Labels: backport

#4645 [7.x] script: simplify generate_notice.py (#4644)
  Makefile
  NOTICE.txt
  go.sum
  script/generate_notice.py
Labels: backport

#4639 [7.11] Update to elastic/beats@b1e32c1925af
  .go-version
  Makefile
  NOTICE.txt
  go.mod
  go.sum
  testing/environments/latest.yml
Labels: v7.11.0

#4626 intake: add cloud.service.name to metadata
  CONTRIBUTING.md
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/apm/0.1.0/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/v2/metadata.json
  include/fields.go
  model/cloud.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/metadata.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  x-pack/apm-server/sampling/processor_test.go
Labels: v7.12.0

#4657 7.11 wildcard keywords
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.1.0/docs/README.md
  changelogs/7.11.asciidoc
  docs/fields.asciidoc
  include/fields.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
Labels: v7.11.0
