Repository elastic/apm-server, pull requests merged in 2021-12, with the labels that each got.

#6756 apmpackage: Fix rum traces ILM name
  apmpackage/apm/data_stream/rum_traces/manifest.yml
Labels: bug, v8.0.0, backport-8.0

#6763 [automation] update elastic stack version for testing 7.16.0-046aeba5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6766 [automation] update elastic stack version for testing 8.0.0-df873dde
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6765 [automation] update elastic stack version for testing 8.1.0-274c36a2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6743 changed .mergify.yml to use queue instead of merge actions
  .mergify.yml
Labels: automation, backport-skip

#6749 docs: add temp AWS lambda docs
  docs/aws-lambda-extension.asciidoc
  docs/features.asciidoc
  docs/images/assets.png
  docs/images/config-layer.png
  docs/images/data-flow.png
  docs/images/layers.png
Labels: backport-7.16, backport-8.0

#6771 [automation] update elastic stack version for testing 8.0.0-aab6301c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6769 [automation] update elastic stack version for testing 7.16.0-80ab1dd0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6770 [automation] update elastic stack version for testing 8.1.0-376424f6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6777 Java attacher update integration
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
Labels: backport-skip

#6779 systemtest: Remove setup and output config
  systemtest/apmservertest/config.go
  systemtest/estest/search.go
Labels: test, v8.0.0, backport-8.0

#6781 [automation] update elastic stack version for testing 7.16.0-f17274e7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6782 [automation] update elastic stack version for testing 7.15.3-2191b0f7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6783 [automation] update elastic stack version for testing 8.0.0-eda77a0f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6780 [automation] update elastic stack version for testing 8.1.0-58719e16
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6776 [java attacher] set each space-separated arg individually in cmd
  beater/java_attacher/java_attacher.go
  beater/java_attacher/java_attacher_test.go
Labels: backport-8.0

#6793 [automation] update elastic stack version for testing 7.16.0-ef210289
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6792 [automation] update elastic stack version for testing 8.1.0-30a394f1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6795 [automation] update elastic stack version for testing 7.15.3-70c2e21f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6767 datastream: Use internal metrics on empty service.name
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/docs/README.md
  changelogs/head.asciidoc
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
Labels: bug, backport-7.16, backport-8.0

#6800 systemtest: Update metricsets.ndjson timestamps
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  testdata/intake-v2/metricsets.ndjson
Labels: flaky test, backport-7.16, backport-8.0

#6802 Reintroduce integration package generator
  Makefile
  apmpackage/README.md
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/error_logs/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/rum_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/rum_traces/fields/base-fields.yml
  apmpackage/apm/data_stream/rum_traces/fields/ecs.yml
  apmpackage/apm/data_stream/rum_traces/fields/fields.yml
  apmpackage/apm/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/sampled_traces/manifest.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/docs/README.md
  apmpackage/apm/manifest.yml
  apmpackage/cmd/genpackage/main.go
  apmpackage/cmd/genpackage/pipelines.go
  apmpackage/cmd/genpackage/transform.go
  go.mod
Labels: v8.0.0, backport-8.0

#6794 [automation] update elastic stack version for testing 8.0.0-1e314182
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6796 waitready: Add remediation to error message
  beater/checkintegration.go
  beater/errors.go
  beater/server_test.go
  beater/waitready.go
  changelogs/head.asciidoc
Labels: bug, v8.0.0, backport-7.16, backport-8.0

#6809 [8.0][docs] Update RUM source map absolute path logic (#6786) (forward-port)
  docs/legacy/sourcemap-api.asciidoc
Labels: backport-skip

#6808 [7.16][docs] Update RUM source map absolute path logic (#6786) (forward-port)
  docs/legacy/sourcemap-api.asciidoc
Labels: backport-skip

#6805 Java attacher fix allowlist
  beater/config/config.go
  beater/config/java_attacher.go
  beater/config/java_attacher_test.go
Labels: backport-8.0

#6791 Check APM Server version in ingest pipeline
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/app_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_logs/fields/base-fields.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_logs/manifest.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/rum_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/cmd/genpackage/main.go
  apmpackage/cmd/genpackage/pipelines.go
  beater/processors.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  model/observer.go
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/elasticsearch.go
  systemtest/ingest_test.go
  systemtest/main_test.go
Labels: v8.0.0, backport-8.0

#6709 docs: Add upgrading documentation
  docs/agent-server-compatibility.asciidoc
  docs/apm-breaking.asciidoc
  docs/images/agent-settings-migration.png
  docs/images/scale-apm.png
  docs/images/schema-agent.png
  docs/integrations-index.asciidoc
  docs/legacy/guide/index.asciidoc
  docs/legacy/index.asciidoc
  docs/legacy/upgrading.asciidoc
  docs/notices.asciidoc
  docs/upgrade.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading-to-datastreams.asciidoc
  docs/upgrading-to-integration.asciidoc
  docs/upgrading-to-legacy.asciidoc
  docs/upgrading.asciidoc
Labels: backport-7.16, backport-8.0

#6818 docs: add 7.16 release notes
  CHANGELOG.asciidoc
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
  changelogs/head.asciidoc
  docs/apm-breaking.asciidoc
  docs/release-notes.asciidoc
Labels: docs, v7.16.0, backport-7.16, backport-8.0

#6824 systemtest: fix flaky instrumentation test
  systemtest/instrumentation_test.go
Labels: backport-7.16, backport-8.0

#6768 otlp: Add beta support to receive logs
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  beater/otlp/grpc.go
  beater/otlp/grpc_test.go
  changelogs/head.asciidoc
  docs/open-telemetry.asciidoc
  model/apmevent.go
  model/error.go
  model/error_test.go
  model/event.go
  model/log.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modelprocessor/culprit_test.go
  model/modelprocessor/errormessage_test.go
  model/modelprocessor/excludefromgrouping_test.go
  model/modelprocessor/groupingkey_test.go
  model/modelprocessor/libraryframe_test.go
  processor/otel/logs.go
  processor/otel/logs_test.go
  processor/otel/traces.go
  sourcemap/processor_test.go
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/go.mod
  systemtest/go.sum
  systemtest/otlp_test.go
Labels: enhancement, v8.0.0, backport-8.0

#6830 [automation] update elastic stack version for testing 7.15.3-9e171938
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6831 [automation] update elastic stack version for testing 8.1.0-52507339
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6826 Increase system tests timeout
  .ci/scripts/linux-test.sh
  Makefile
Labels: backport-8.0

#6825 docs: fix release notes for 7.16.0
  changelogs/7.16.asciidoc
  changelogs/head.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0

#6834 Update default span/transaction type for OTel
  changelogs/head.asciidoc
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/traces.go
  processor/otel/traces_test.go
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: v8.0.0, backport-8.0

#6842 systemtest: fix TestOTLPRateLimit
  systemtest/otlp_test.go
Labels: backport-7.16, backport-8.0

#6810 [docs] Update RUM source map absolute path logic (#6786) (forward-port)
  docs/legacy/sourcemap-api.asciidoc
Labels: backport-skip

#6833 [7.15] Add page header to legacy docs
  docs/guide/page_header.html
  docs/page_header.html
Labels: v7.15.0

#6829 [automation] update elastic stack version for testing 7.16.0-f2941f42
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6850 beater: improve tests
  beater/beater_test.go
  beater/integration_test.go
Labels: backport-7.16, backport-8.0

#6854 [automation] update elastic stack version for testing 7.16.0-eaf40d57
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6853 [automation] update elastic stack version for testing 8.0.0-4535d287
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6851 [automation] update elastic stack version for testing 7.15.3-984b6e42
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6857 Fix various lint warnings
  beater/api/config/agent/handler.go
  beater/api/firehose/handler.go
  beater/beater.go
  beater/beatertest/encode.go
  beater/config/helper.go
  beater/config/helper_test.go
  beater/request/context.go
  beater/server.go
  decoder/stream_decoder.go
  model/modeldecoder/generator/cmd/main.go
  model/modeldecoder/generator/jsonschema_test.go
  model/modeldecoder/generator/nint.go
  model/modeldecoder/generator/ninterface.go
  model/modeldecoder/generator/nstring.go
  model/modeldecoder/generator/slice.go
  model/modeldecoder/generator/struct.go
  model/modeldecoder/generator/testdata/model.go
  model/modeldecoder/generator/validation.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modelindexer/bulk_indexer.go
  processor/otel/traces.go
  sourcemap/processor.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
Labels: backport-skip

#6864 [automation] update elastic stack version for testing 7.16.1-53c0de77
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6866 [automation] update elastic stack version for testing 7.16.1-1d21f78b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6865 [automation] update elastic stack version for testing 8.1.0-3cacb07d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6867 [automation] update elastic stack version for testing 8.0.0-a8855495
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6869 [automation] update elastic stack version for testing 8.0.0-3c6e08ba
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6870 [automation] update elastic stack version for testing 7.16.1-2ceb4af4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6868 [automation] update elastic stack version for testing 8.1.0-b6e7e1f3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6871 Bump version to 7.16.2
  cmd/version.go
Labels: backport-skip

#6859 [java-attacher] convert -vmarg to -vmargs
  beater/config/java_attacher.go
  beater/config/java_attacher_test.go
  beater/java_attacher/java_attacher.go
  beater/java_attacher/java_attacher_test.go
Labels: backport-8.0

#6874 docs: add 7.16.1 release notes
  changelogs/7.16.asciidoc
Labels: Team:Docs

#6876 docs: 7.16.1 and 6.8.21 release notes
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0

#6880 [automation] update elastic stack version for testing 7.16.2-926bc45c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6883 [automation] update elastic stack version for testing 8.1.0-f02e597e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6882 [automation] update elastic stack version for testing 8.0.0-6b5f794c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6884 [automation] update elastic stack version for testing 7.16.2-e7a873d4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6885 [automation] update elastic stack version for testing 8.0.0-9fb1bbae
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6900 [automation] update elastic stack version for testing 8.1.0-befff95a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6899 [automation] update elastic stack version for testing 8.0.0-002bf944
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6891 [automation] update elastic stack version for testing 7.16.2-682993ae
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6797 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#6896 Update ITs main
  Jenkinsfile
Labels: backport-7.16, backport-7.x, backport-8.0

#6903 [7.17] fix linter deprecations
  beater/config/aggregation_test.go
  beater/config/helper.go
  beater/jaeger/server_test.go
  beater/otlp/grpc_test.go
  beater/server_test.go
  systemtest/jaeger_test.go
  systemtest/logging_test.go
Labels: backport-7.16

#6897 Cherry pick release notes
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0, backport-7.17

#6914 [automation] update elastic stack version for testing 8.0.0-7b79b556
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6908 Update to main branch when using beats-tester
  .ci/check-packages.groovy
Labels: backport-7.16, backport-8.0, backport-7.17

#6915 apm agent: Update to `v1.15.0`
  NOTICE.txt
  go.mod
  go.sum
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestFleetIntegration.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/go.mod
  systemtest/go.sum
Labels: v8.0.0, backport-8.0

#6919 [faas] add `id` field
  apmpackage/apm/data_stream/traces/fields/fields.yml
  docs/spec/v2/transaction.json
  model/apmevent_test.go
  model/faas.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/transaction_test.go
Labels: v8.0.0, test-plan, backport-8.0

#6911 [7.17] Cherry pick release notes (#6897)
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
Labels: backport

#6924 [7.17] Fix CI build
  Makefile
  docker-compose.yml
Labels: ci

#6912 Add `transaction.name` mapping to `logs-apm.error`
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
  systemtest/errors_test.go
  testdata/intake-v2/errors.ndjson
Labels: bug, v8.0.0, backport-v8.0

#6930 [automation] update elastic stack version for testing 7.17.0-e76712ab
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6931 [automation] update elastic stack version for testing 8.1.0-76902d39
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6929 [automation] update elastic stack version for testing 8.0.0-52f8db06
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6935 [automation] update elastic stack version for testing 8.1.0-dbc834fd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6942 [automation] update elastic stack version for testing 7.17.0-09b71949
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6944 ci: Run `go mod download` before systemtest
  .ci/scripts/linux-test.sh
Labels: ci, backport-7.16, backport-8.0, backport-7.17

#6952 [automation] update elastic stack version for testing 7.17.0-c02e8773
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6948 Java attacher remove vmarg conversion
  Makefile
  beater/java_attacher/java_attacher.go
  beater/java_attacher/java_attacher_test.go
Labels: v8.1.0, backport-v8.1

#6926 docs: Add deprecation notice to source map upload docs
  docs/legacy/sourcemaps.asciidoc
  docs/source-map-how-to.asciidoc
Labels: Team:Docs, backport-7.16, backport-7.17

#6927 docs: update source map docs for 8.0
  docs/legacy/sourcemaps.asciidoc
  docs/legacy/tab-widgets/kibana-endpoint-widget.asciidoc
  docs/legacy/tab-widgets/kibana-endpoint.asciidoc
  docs/source-map-how-to.asciidoc
Labels: backport-8.0, backport-8.1

#6957 [7.17] docs: Add deprecation notice to source map upload docs (backport #6926)
  docs/legacy/sourcemaps.asciidoc
  docs/source-map-how-to.asciidoc
Labels: backport

#6960 [automation] update elastic stack version for testing 7.17.0-a34e30fc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6933 Fix dependencies
  NOTICE.txt
  go.mod
  go.sum
  systemtest/go.mod
  systemtest/go.sum
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#6955 Fix packaging for .deb and .rpm
  packaging/files/linux/deb-post-install.sh.tmpl
Labels: v8.1.0, backport-8.0

#6967 [automation] update elastic stack version for testing 7.17.0-53d9a9d2
  docker-compose.yml
Labels: dependency, automation, backport-skip
