Repository elastic/apm-server, pull requests merged in 2021-09, with the labels that each got.

#6102 [automation] update elastic stack version for testing 7.16.0-8a18fe34
  docker-compose.yml
Labels: dependency, automation

#6103 [automation] update elastic stack version for testing 7.15.0-caca3588
  docker-compose.yml
Labels: dependency, automation

#6101 Remove package tests
  .ci/scripts/test-install-packages.sh
  Jenkinsfile
  magefile.go
  tests/packaging/Dockerfile.aarch64.rpm.install
  tests/packaging/Dockerfile.amd64.deb.install
  tests/packaging/Dockerfile.arm64.deb.install
  tests/packaging/Dockerfile.i386.deb.install
  tests/packaging/Dockerfile.i686.rpm.install
  tests/packaging/Dockerfile.x86_64.rpm.install
  tests/packaging/package_test.go
  tests/packaging/test.sh
Labels: backport-7.x

#6066 model: allow mixing Span/Transaction/Error/Metricset in APMEvent
  agentcfg/reporter.go
  beater/beater_test.go
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/transactions.json
  model/apmevent.go
  model/apmevent_test.go
  model/child.go
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/transaction_test.go
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  model/modelprocessor/metricsetname.go
  model/modelprocessor/metricsetname_test.go
  model/parent.go
  model/profile.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/exceptions_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  processor/otel/traces.go
  sampling/sampling.go
  sampling/sampling_test.go
  tests/system/transaction.approved.json
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_bench_test.go
Labels: v7.16.0, backport-7.x

#6098 [7.14] docs: add 7.14.1 release notes (#6083)
  changelogs/7.14.asciidoc
Labels: backport

#6109 magefile: fix Package target
  magefile.go
Labels: backport-7.x

#6111 Introduce dedicated fields for internal metrics
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/metricsets.json
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modeldecoder/modeldecoderutil/metrics.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  model/modelprocessor/metricsetname.go
  model/modelprocessor/metricsetname_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  testdata/intake-v2/metricsets.ndjson
  tests/system/metricset.approved.json
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: v7.16.0, backport-7.x

#6116 apmpackage: sort internal metrics data stream
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/manifest.yml
  changelogs/head.asciidoc
Labels: v7.16.0, backport-7.x

#6043 Add dynamic_templates to app_metrics data stream
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/docs/README.md
  apmpackage/cmd/gen-package/field.go
  apmpackage/cmd/gen-package/genfields.go
  changelogs/head.asciidoc
  systemtest/approvals/TestApprovedMetrics/data_streams_disabled.approved.json
  systemtest/approvals/TestApprovedMetrics/data_streams_enabled.approved.json
  systemtest/estest/search.go
  systemtest/helpers_test.go
  systemtest/metrics_test.go
Labels: v7.16.0, backport-7.x

#6122 processor/otel: index span events as logs
  beater/beater.go
  changelogs/head.asciidoc
  docs/guide/opentelemetry-elastic.asciidoc
  docs/jaeger-reference.asciidoc
  model/log.go
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  processor/otel/exceptions_test.go
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/traces.go
  processor/otel/traces_test.go
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_disabled.approved.json
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_enabled.approved.json
  systemtest/otlp_test.go
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: v7.16.0, backport-7.x

#6125 Remove package "convert"
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  convert/convert.go
  kibana/connecting_client_test.go
  kibana/kibanatest/kibana.go
Labels: v7.16.0, backport-7.x

#6134 [automation] update elastic stack version for testing 7.15.0-b8b8307a
  docker-compose.yml
Labels: dependency, automation

#6133 [automation] update elastic stack version for testing 7.16.0-a96d8aa5
  docker-compose.yml
Labels: dependency, automation

#6131 processor/otel: deprecate `service.version` span tag
  changelogs/head.asciidoc
  processor/otel/traces.go
Labels: v7.16.0, backport-7.x

#6136 apmpackage: mark package as GA
  apmpackage/apm/manifest.yml
Labels: v7.16.0, backport-7.x

#6143 [automation] update elastic stack version for testing 7.15.0-f15c4154
  docker-compose.yml
Labels: dependency, automation

#6144 [automation] update elastic stack version for testing 7.16.0-468522bc
  docker-compose.yml
Labels: dependency, automation

#6141 systemtest: migrate TLS cert tests to Go
  beater/http.go
  changelogs/head.asciidoc
  systemtest/apmservertest/client_cert.pem
  systemtest/apmservertest/client_key.pem
  systemtest/apmservertest/config.go
  systemtest/apmservertest/server.go
  systemtest/jaeger_test.go
  systemtest/tls_test.go
  tests/system/test_tls.py
Labels: v7.16.0, backport-7.x

#6149 [automation] update elastic stack version for testing 7.15.0-4efca5cc
  docker-compose.yml
Labels: dependency, automation

#6150 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#6145 Add deprecation warnings about ES setup
  beater/beater.go
  changelogs/head.asciidoc
  cmd/root.go
  docs/configuration-process.asciidoc
  docs/configuring-ingest.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/ilm-reference.asciidoc
  docs/ilm.asciidoc
  idxmgmt/manager.go
  idxmgmt/manager_test.go
  idxmgmt/supporter_factory.go
  idxmgmt/supporter_factory_test.go
Labels: v7.16.0, backport-7.x

#6142 [automation] update elastic stack version for testing 8.0.0-c0c740b6
  docker-compose.yml
Labels: dependency, automation

#6154 [automation] update elastic stack version for testing 8.0.0-6b488890
  docker-compose.yml
Labels: dependency, automation

#6155 [automation] update elastic stack version for testing 7.16.0-fbd5fab2
  docker-compose.yml
Labels: dependency, automation

#6156 [automation] update elastic stack version for testing 7.15.0-a59055d8
  docker-compose.yml
Labels: dependency, automation

#6157 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#6158 docs: promote jaeger & transaction metrics to GA
  docs/jaeger-reference.asciidoc
  docs/jaeger-support.asciidoc
  docs/transaction-metrics.asciidoc
Labels: v7.16.0, backport-7.x

#6147 model: move HTTP to APMEvent, unify fields
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  changelogs/head.asciidoc
  model/apmevent.go
  model/apmevent_test.go
  model/error.go
  model/http.go
  model/modeldecoder/modeldecodertest/populator.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
Labels: v7.16.0, backport-7.x

#6152 Remove `http.request.socket` fields
  beater/api/mux.go
  beater/interceptors/logging.go
  beater/interceptors/logging_test.go
  beater/interceptors/metadata.go
  beater/interceptors/metadata_test.go
  beater/interceptors/ratelimit.go
  beater/interceptors/ratelimit_test.go
  beater/middleware/rate_limit_middleware.go
  beater/middleware/rate_limit_middleware_test.go
  beater/otlp/clientmetadata.go
  beater/otlp/clientmetadata_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/spec/v2/error.json
  docs/spec/v2/transaction.json
  model/apmevent.go
  model/apmevent_test.go
  model/http.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/source.go
  model/transaction_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/rum_test.go
  systemtest/sourcemap_test.go
  tests/system/error.approved.json
  tests/system/transaction.approved.json
  utility/ip.go
  utility/ip_test.go
Labels: v7.16.0, backport-7.x

#6165 [automation] update elastic stack version for testing 8.0.0-64718381
  docker-compose.yml
Labels: dependency, automation

#6166 [automation] update elastic stack version for testing 7.15.0-d48cd6f3
  docker-compose.yml
Labels: dependency, automation

#6167 [automation] update elastic stack version for testing 7.16.0-f4fa0a64
  docker-compose.yml
Labels: dependency, automation

#6164 model: remove Exception.Parent
  model/error.go
  model/error_test.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/v2/error_test.go
Labels: v7.16.0, backport-7.x

#6174 [automation] update elastic stack version for testing 7.16.0-b40a7e80
  docker-compose.yml
Labels: dependency, automation

#6175 [automation] update elastic stack version for testing 7.15.0-4d52e36a
  docker-compose.yml
Labels: dependency, automation

#6173 docs: document internal metrics
  Makefile
  apmpackage/apm/docs/README.md
  apmpackage/cmd/gen-package/gendocs.go
  docs/data/elasticsearch/generated/metricsets.json
  docs/data/elasticsearch/metricset.json
  docs/metricset-indices.asciidoc
  tests/system/metricset.approved.json
  tests/system/test_integration.py
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: v7.16.0, backport-7.x

#6171 docs: update OTel limitations
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport-7.14

#6183 [automation] update elastic stack version for testing 8.0.0-da75ec54
  docker-compose.yml
Labels: dependency, automation

#6181 [automation] update elastic stack version for testing 7.16.0-63cdb007
  docker-compose.yml
Labels: dependency, automation

#6180 Drop transaction.duration.{count,sum.us}
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/rumv3/transaction.json
  include/fields.go
  model/metricset/_meta/fields.yml
  model/metricset_test.go
  model/modeldecoder/modeldecoderutil/metrics.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/rumv3/model_generated.go
  model/modeldecoder/rumv3/model_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/metricset_test.go
  model/transaction.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestApprovedMetrics/data_streams_disabled.approved.json
  systemtest/approvals/TestApprovedMetrics/data_streams_enabled.approved.json
Labels: v7.16.0, backport-7.x

#6182 [automation] update elastic stack version for testing 7.15.0-1bab4292
  docker-compose.yml
Labels: dependency, automation

#6188 [automation] update elastic stack version for testing 7.15.0-353cd7d4
  docker-compose.yml
Labels: dependency, automation

#6189 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#6190 [automation] update elastic stack version for testing 7.15.0-bc82566e
  docker-compose.yml
Labels: dependency, automation

#6192 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation

#6196 [automation] update elastic stack version for testing 8.0.0-c8bb0791
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6197 [automation] update elastic stack version for testing 7.16.0-3f2f8446
  docker-compose.yml
Labels: dependency, automation

#6198 [automation] update elastic stack version for testing 7.15.0-5ab1fe99
  docker-compose.yml
Labels: dependency, automation

#6124 systemtest: update opentelemetry-go
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_disabled.approved.json
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_enabled.approved.json
  systemtest/benchtest/clients.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/logging_test.go
  systemtest/otlp_test.go
Labels: v7.16.0, backport-7.x

#6177 intake: Add `context.message.routing_key` to API
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  include/fields.go
  model/message.go
  model/message_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: enhancement, v7.16.0, backport-7.x

#6207 [7.x] docs: 7.14.2 release notes (#6195)
  changelogs/7.14.asciidoc
Labels: backport

#6209 [7.15] docs: 6.8.19 release notes (#6194)
  changelogs/6.8.asciidoc
Labels: backport

#6208 [7.15] docs: 7.14.2 release notes (#6195)
  changelogs/7.14.asciidoc
Labels: backport

#6211 [master] docs: 6.8.19 release notes (#6194) (#6209)
  changelogs/6.8.asciidoc
Labels: backport

#6210 [7.x] docs: 6.8.19 release notes (#6194) (#6209)
  changelogs/6.8.asciidoc
Labels: backport

#6213 [7.15] docs: prepare 7.15 release notes (#6178)
  CHANGELOG.asciidoc
  changelogs/7.14.asciidoc
  changelogs/7.15.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#6212 [7.x] docs: prepare 7.15 release notes (#6178)
  CHANGELOG.asciidoc
  changelogs/7.14.asciidoc
  changelogs/7.15.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#6214 docs: update APM Overview breaking changes
  docs/guide/apm-breaking-changes.asciidoc
Labels: v7.15.0, Team:Docs, v7.16.0, backport-7.x, backport-7.15

#6215 [automation] update elastic stack version for testing 7.15.0-28b0107a
  docker-compose.yml
Labels: dependency, automation

#6220 docs: fix 7.15 breaking changes
  docs/breaking-changes.asciidoc
  docs/guide/apm-breaking-changes.asciidoc
Labels: Team:Docs, backport-7.x, backport-7.15

#6206 [CI] use obltGitHubComments
  Jenkinsfile
Labels: automation, Team:Automation, backport-7.14, backport-7.15

#6231 [automation] update elastic stack version for testing 8.0.0-aa012679
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6230 [automation] update elastic stack version for testing 7.16.0-51a7a70c
  docker-compose.yml
Labels: dependency, automation

#6232 [automation] update elastic stack version for testing 7.15.1-f9f656c4
  docker-compose.yml
Labels: dependency, automation

#6229 apmpackage: remove warm phase from ILM policies
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/traces/elasticsearch/ilm/default_policy.json
Labels: v7.16.0, backport-7.x

#6224 messaging.routing_key: Remove from tx,span mapping
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  docs/fields.asciidoc
  include/fields.go
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
Labels: v7.16.0, backport-7.x

#6200 intake: Handle `transaction.dropped_spans_stats`
  beater/integration_test.go
  beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  changelogs/head.asciidoc
  docs/spec/v2/transaction.json
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/model_test.go
  model/modeldecoder/v2/transaction_test.go
  model/transaction.go
  model/transaction_test.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
  systemtest/approvals.go
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  systemtest/huge_traces_test.go
  systemtest/main_test.go
  testdata/intake-v2/transactions-huge_traces.ndjson
  tests/system/test_pipelines.py
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: feature, [zube]: In Review, v7.16.0, backport-7.x

#6239 [automation] update elastic stack version for testing 8.0.0-61c5a306
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6240 [automation] update elastic stack version for testing 7.16.0-70330f11
  docker-compose.yml
Labels: dependency, automation

#6241 [automation] update elastic stack version for testing 7.15.1-de1fe33e
  docker-compose.yml
Labels: dependency, automation

#6245 [automation] update elastic stack version for testing 7.15.1-5f9d0364
  docker-compose.yml
Labels: dependency, automation

#6244 [automation] update elastic stack version for testing 7.16.0-4cbd636a
  docker-compose.yml
Labels: dependency, automation

#6247 [bump][automation] skip backports for the automation
  .ci/update-beats.groovy
Labels: backport-7.x

#6251 [automation] update elastic stack version for testing 8.0.0-9d408327
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6253 [automation] update elastic stack version for testing 7.15.1-34ec300e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6258 [automation] update elastic stack version for testing 7.15.1-56129787
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6257 [automation] update elastic stack version for testing 8.0.0-aef26e82
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6262 [automation] update elastic stack version for testing 7.15.1-f3d0455b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6261 [automation] update elastic stack version for testing 7.16.0-f67263fd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6256 fix: Dedot http.request.body.original
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  changelogs/7.15.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  model/apmevent_test.go
  model/http.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  tests/system/error.approved.json
  tests/system/transaction.approved.json
Labels: [zube]: In Review, backport-7.15

#6246 [automation] update libbeat and beats packaging
  NOTICE.txt
  docs/fields.asciidoc
  go.mod
  go.sum
  include/fields.go
Labels: automation, backport-skip
