Repository elastic/apm-server, pull requests merged in 2021-07, with the labels that each got.

#5591 [automation] update elastic stack version for testing 7.13.3-dbdefa2a
  docker-compose.yml
Labels: automation, dependency

#5592 [automation] update elastic stack version for testing 8.0.0-abbf7c2f
  docker-compose.yml
Labels: automation, dependency

#5605 [automation] update elastic stack version for testing 7.14.0-e1afed34
  docker-compose.yml
Labels: automation, dependency

#5604 [automation] update elastic stack version for testing 8.0.0-08d745df
  docker-compose.yml
Labels: automation, dependency

#5600 docs: fix typo
  docs/secure-communication-agents.asciidoc
Labels: v7.13.0, v7.14.0, v7.15.0

#5615 Add missing RUM vars to apmpackage manifest
  apmpackage/apm/manifest.yml
Labels: bug, fleet, v7.14.0, v7.15.0

#5596 docs: add 7.13.3 release notes
  changelogs/7.13.asciidoc
Labels: Team:Docs, v7.13.0, v7.14.0

#5597 docs: add 6.8.17 release notes
  changelogs/6.8.asciidoc
Labels: Team:Docs, v6.8, v7.13.0, v7.14.0

#5629 [6.8] docs: add 6.8.17 release notes
  changelogs/6.8.asciidoc
Labels: backport

#5632 bump version to 6.8.18
  vendor/github.com/elastic/beats/libbeat/version/version.go
Labels: v6.8

#5637 Stop running python system tests on Windows
  .ci/scripts/windows-test.ps1
Labels: v7.15.0

#5638 tests/system: remove test_requests.py
  beater/api/mux_expvar_test.go
  systemtest/apmservertest/config.go
  systemtest/rum_test.go
  tests/system/test_requests.py
Labels: v7.15.0

#5636 systemtest: use new auth config
  systemtest/agentconfig.go
  systemtest/apmservertest/config.go
  systemtest/apmservertest/server.go
  systemtest/auth_test.go
  systemtest/instrumentation_test.go
  systemtest/jaeger_test.go
  systemtest/otlp_test.go
  systemtest/rum_test.go
Labels: v7.15.0

#5635 Fleet decode sourcemap response
  beater/beater_test.go
  sourcemap/fleet_store.go
  sourcemap/fleet_store_test.go
  sourcemap/store_test.go
Labels: v7.14.0

#5670 Don't panic re-registering monitoring functions
  changelogs/head.asciidoc
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
Labels: v7.14.0, v7.15.0

#5631 Move source mapping to model processing
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/handler_test.go
  beater/api/mux.go
  beater/api/mux_test.go
  beater/beater.go
  beater/beater_test.go
  beater/config/config_test.go
  beater/config/rum.go
  beater/http.go
  beater/server.go
  beater/tracing.go
  changelogs/head.asciidoc
  model/error.go
  model/error_test.go
  model/sourcemap.go
  model/sourcemap_test.go
  model/span.go
  model/span_test.go
  model/stacktrace.go
  model/stacktrace_frame.go
  model/stacktrace_frame_test.go
  model/stacktrace_test.go
  sourcemap/processor.go
  sourcemap/processor_test.go
  sourcemap/store.go
  sourcemap/store_test.go
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/sourcemap_test.go
  transform/transform.go
Labels: v7.15.0

#5656 Fix rum rate limit default value
  kibana/send_config.go
  kibana/send_config_test.go
Labels: backport-7.14, bug, test-plan, v7.14.0

#5641 docs: free and open terminology
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: Team:Docs, v7.13.0, v7.14.0, v7.15.0

#5684 [7.x] docs: free and open terminology (#5641)
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#5685 [7.13] docs: free and open terminology (#5641)
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#5686 [7.14] docs: free and open terminology (#5641)
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/overview.asciidoc
  docs/guide/troubleshooting.asciidoc
Labels: backport

#5690 [JJBB] for the update-beats
  .ci/jobs/apm-server-check-changelogs-mbp.yml
  .ci/jobs/apm-server-check-packages-mbp.yml
  .ci/jobs/defaults.yml
  .ci/jobs/update-beats-mbp.yml
Labels: Team:Automation, automation

#5691 Bump integration to 0.4.0, use apm-server.auth config
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/manifest.yml
  systemtest/fleet_test.go
  systemtest/fleettest/types.go
  systemtest/kibana.go
  systemtest/main_test.go
Labels: backport-7.x, v7.15.0

#5696 [automation] update elastic stack version for testing 8.0.0-2f008f4a
  docker-compose.yml
Labels: automation, dependency

#5697 [automation] update elastic stack version for testing 7.14.0-c78a4632
  docker-compose.yml
Labels: automation, dependency

#5623 Introduce `apm-server.auth.anonymous` config
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_AuthorizationMiddleware/Forbidden.approved.json
  beater/api/config/agent/handler.go
  beater/api/mux.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/auth/anonymous.go
  beater/auth/anonymous_test.go
  beater/auth/authenticator.go
  beater/auth/authenticator_test.go
  beater/config/auth.go
  beater/config/auth_test.go
  beater/config/config.go
  beater/config/config_test.go
  beater/config/ratelimit.go
  beater/config/rum.go
  beater/interceptors/auth_test.go
  beater/jaeger/grpc.go
  beater/jaeger/grpc_test.go
  beater/middleware/auth_middleware.go
  beater/middleware/auth_middleware_test.go
  beater/middleware/rate_limit_middleware.go
  beater/server.go
  changelogs/head.asciidoc
  systemtest/apmservertest/config.go
  systemtest/auth_test.go
  systemtest/fleet_test.go
  systemtest/otlp_test.go
  systemtest/rum_test.go
Labels: backport-7.x, v7.15.0

#5695 Move setting of destination.ip to ingest pipeline
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_convert_destination_address.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
  model/span.go
  model/span_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  systemtest/ingest_test.go
Labels: backport-7.x, v7.15.0

#5692 [CI] automate update-beats
  .ci/scripts/update-beats.sh
  .ci/update-beats.groovy
  .mergify.yml
Labels: automation

#5699 Fix: remove unsupported rum rate limit key
  kibana/send_config.go
  kibana/send_config_test.go
Labels: backport-7.14, backport-7.x

#5624 chore: use withMageEnv step
  Jenkinsfile
  script/common.bash
Labels: Team:Automation, automation, v7.15.0

#5674 Document AWS Lambda OpenTelemetry support
  docs/guide/opentelemetry-elastic.asciidoc
Labels: OpenTelemetry, Team:Docs, v7.14.0, v7.15.0, v8.0.0

#5709 [master] Document AWS Lambda OpenTelemetry support (#5674)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5710 [7.x] Document AWS Lambda OpenTelemetry support (#5674)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5711 [7.14] Document AWS Lambda OpenTelemetry support (#5674)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5700 model: make APMEvents 1:1 with beat.Events
  beater/api/profile/convert.go
  beater/api/profile/handler.go
  beater/api/profile/handler_test.go
  model/apmevent.go
  model/batch.go
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/modelprocessor/environment_test.go
  model/modelprocessor/metadata.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
Labels: backport-7.x, v7.15.0

#5704 processor/otel: record array resource attributes
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/metadata.go
  processor/otel/metadata_test.go
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: backport-7.14, backport-7.x, test-plan, v7.14.0, v7.15.0

#5687 Move more code from model to model processors
  beater/api/mux.go
  beater/beater.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  docs/data/elasticsearch/generated/errors.json
  model/error.go
  model/error_test.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/span_test.go
  model/modelprocessor/culprit.go
  model/modelprocessor/culprit_test.go
  model/modelprocessor/excludefromgrouping.go
  model/modelprocessor/excludefromgrouping_test.go
  model/modelprocessor/libraryframe.go
  model/modelprocessor/libraryframe_test.go
  model/span.go
  model/stacktrace.go
  model/stacktrace_test.go
  processor/stream/processor.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  sourcemap/processor.go
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  tests/system/error.approved.json
  tests/system/test_integration.py
  transform/transform.go
Labels: backport-7.x, v7.15.0

#5718 beater/request: clear multpart.Form on reset
  beater/request/context.go
  beater/request/context_pool.go
  beater/request/context_test.go
  changelogs/head.asciidoc
Labels: backport-7.14, backport-7.x, v7.14.0, v7.15.0

#5723 [automation] update elastic stack version for testing 7.14.0-11e92b49
  docker-compose.yml
Labels: automation, dependency

#5721 [automation] update elastic stack version for testing 8.0.0-52a5431f
  docker-compose.yml
Labels: automation, dependency

#5720 Move Sourcemap from model to sourcemap handler
  beater/api/asset/sourcemap/handler.go
  beater/api/asset/sourcemap/sourcemap.go
  beater/api/asset/sourcemap/sourcemap_test.go
Labels: backport-7.x, v7.15.0

#5719 processor/otel: handle net.host.* as span attributes
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/metadata.go
  processor/otel/metadata_test.go
Labels: backport-7.14, backport-7.x, test-plan, v7.14.0

#5722 [automation] update elastic stack version for testing 7.15.0-588e7872
  docker-compose.yml
Labels: automation, dependency

#5733 [7.14] chore: use withMageEnv step (backport #5624)
  Jenkinsfile
  script/common.bash
Labels: Team:Automation

#5729 Remove package transform
  beater/api/asset/sourcemap/handler_test.go
  beater/api/asset/sourcemap/sourcemap.go
  beater/api/asset/sourcemap/sourcemap_test.go
  beater/beater.go
  beater/jaeger/server_test.go
  beater/onboarding.go
  model/apmevent.go
  model/batch.go
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/consumer_test.go
  processor/stream/processor_test.go
  publish/pub.go
  publish/pub_test.go
  transform/transform.go
Labels: backport-7.x, v7.15.0

#5739 Restructure model.Metricset
  agentcfg/reporter.go
  apmpackage/apm/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  docs/data/elasticsearch/generated/metricsets.json
  model/metricset.go
  model/metricset_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metricset_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metricset_test.go
  model/modelprocessor/metricsetname.go
  model/modelprocessor/metricsetname_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/metrics_test.go
  tests/system/metricset.approved.json
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-7.x, v7.15.0

#5741 Move grouping key calculation to model processor
  beater/beater.go
  model/error.go
  model/error_test.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/v2/error_test.go
  model/modelprocessor/groupingkey.go
  model/modelprocessor/groupingkey_test.go
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: backport-7.x, v7.15.0

#5748 Improve OpenTelemetry docs, fix #5688
  docs/guide/images/open-telemetry-protocol-arch.png
  docs/guide/opentelemetry-elastic.asciidoc
Labels: OpenTelemetry

#5756 docs: add 7.13.4 release notes
  changelogs/7.13.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#5762 [7.13] docs: add 7.13.4 cl (#5756)
  changelogs/7.13.asciidoc
Labels: backport

#5761 [7.14] docs: add 7.13.4 cl (#5756)
  changelogs/7.13.asciidoc
Labels: backport

#5760 [7.x] docs: add 7.13.4 cl (#5756)
  changelogs/7.13.asciidoc
Labels: backport

#5757 [7.x] Improve OpenTelemetry docs, fix #5688 (#5748)
  docs/guide/images/open-telemetry-protocol-arch.png
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5758 [7.14] Improve OpenTelemetry docs, fix #5688 (#5748)
  docs/guide/images/open-telemetry-protocol-arch.png
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5759 [master] Improve OpenTelemetry docs, fix #5688 (#5748)
  docs/guide/images/open-telemetry-protocol-arch.png
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#5634 docs: add iOS agent links
  docs/common-problems.asciidoc
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/tab-widgets/configure-agent.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: docs, v7.14.0, v7.15.0

#5746 model: de-pointer Transaction.Sampled
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/v2/decoder.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/consumer.go
  processor/otel/exceptions_test.go
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  sampling/sampling.go
  sampling/sampling_test.go
  testdata/jaeger/batch_0.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-7.x, v7.15.0

#5768 ingest: introduce apm_data_stream_migration
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.json
  changelogs/head.asciidoc
  ingest/pipeline/definition.json
  ingest/pipeline/definition.yml
  systemtest/elasticsearch.go
  systemtest/ingest_test.go
Labels: backport-7.x, v7.15.0

#5773 [automation] update elastic stack version for testing 8.0.0-1e9bea0f
  docker-compose.yml
Labels: automation, dependency

#5764 Consolidate model.HTTP and model.Http
  apmpackage/apm/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  model/context.go
  model/error.go
  model/error_test.go
  model/http.go
  model/modeldecoder/modeldecoderutil/http.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  model/url.go
  processor/otel/builder.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  tests/system/error.approved.json
  tests/system/spans.approved.json
  tests/system/transaction.approved.json
Labels: backport-7.x, v7.15.0

#5775 [automation] update elastic stack version for testing 7.15.0-c23a5439
  docker-compose.yml
Labels: automation, dependency

#5774 [automation] update elastic stack version for testing 7.14.0-cff72e71
  docker-compose.yml
Labels: automation, dependency

#5661 Add support for Composite spans in the intake API
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  changelogs/head.asciidoc
  docs/fields.asciidoc
  docs/spec/v2/span.json
  include/fields.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/model_test.go
  model/span.go
  model/span/_meta/fields.yml
  model/span_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport-7.x, v7.15.0

#5781 [automation] update elastic stack version for testing 8.0.0-a6334483
  docker-compose.yml
Labels: automation, dependency

#5783 [automation] update elastic stack version for testing 7.14.0-803ff817
  docker-compose.yml
Labels: automation, dependency

#5782 [automation] update elastic stack version for testing 7.15.0-192e1003
  docker-compose.yml
Labels: automation, dependency

#5778 chore: update-beats goal to bump the go version
  .ci/scripts/update-beats.sh
  .gitignore
  Makefile
  README.md
Labels: Team:Automation

#5771 Document data streams migration limitations
  docs/apm-package/apm-integration.asciidoc
  docs/apm-package/configure.asciidoc
  docs/apm-package/data-streams.asciidoc
  docs/apm-package/input-apm.asciidoc
Labels: Team:Docs, v7.14.0, v7.15.0

#5788 [7.x] Document data streams migration limitations (#5771)
  docs/apm-package/apm-integration.asciidoc
  docs/apm-package/configure.asciidoc
  docs/apm-package/data-streams.asciidoc
  docs/apm-package/input-apm.asciidoc
Labels: backport

#5789 [7.14] Document data streams migration limitations (#5771)
  docs/apm-package/apm-integration.asciidoc
  docs/apm-package/configure.asciidoc
  docs/apm-package/data-streams.asciidoc
  docs/apm-package/input-apm.asciidoc
Labels: backport

#5785 Tidy up model to resembles ECS more closely
  beater/api/mux.go
  beater/beater.go
  beater/otlp/clientmetadata.go
  beater/otlp/clientmetadata_test.go
  beater/processors.go
  model/agent.go
  model/agent_test.go
  model/error_test.go
  model/host.go
  model/host_test.go
  model/metadata.go
  model/metadata_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modelprocessor/hostname.go
  model/modelprocessor/hostname_test.go
  model/modelprocessor/nodename.go
  model/modelprocessor/nodename_test.go
  model/os.go
  model/service.go
  model/service_test.go
  model/system.go
  model/system_test.go
  model/test_approved/host/full.approved.json
  model/test_approved/host/full_hostname_info.approved.json
  model/test_approved/host/hostname.approved.json
  model/test_approved/host/ignored_hostname.approved.json
  model/test_approved/system/network.approved.json
  model/transaction_test.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/exceptions_test.go
  processor/otel/metadata.go
  processor/otel/metadata_test.go
  processor/otel/metrics_test.go
  processor/stream/processor_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-7.x, v7.15.0

#5794 [automation] update elastic stack version for testing 8.0.0-1aed0c4f
  docker-compose.yml
Labels: automation, dependency

#5793 [automation] update elastic stack version for testing 7.15.0-5e783247
  docker-compose.yml
Labels: automation, dependency

#5797 [automation] update elastic stack version for testing 8.0.0-cdc598b1
  docker-compose.yml
Labels: automation, dependency

#5798 [automation] update elastic stack version for testing 7.15.0-514bcfaf
  docker-compose.yml
Labels: automation, dependency

#5799 [automation] update elastic stack version for testing 7.14.0-0ce5c542
  docker-compose.yml
Labels: automation, dependency

#5805 [automation] update elastic stack version for testing 7.15.0-6e66e5d1
  docker-compose.yml
Labels: automation, dependency

#5806 [automation] update elastic stack version for testing 7.14.0-de25a427
  docker-compose.yml
Labels: automation, dependency

#5802 docs: draft 8.0.0-alpha1 release notes
  CHANGELOG.asciidoc
  changelogs/8.0.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: v8.0.0

#5803 correctly set etag when not defined
  beater/config/config.go
  beater/config/config_test.go
Labels: v7.15.0

#5809 Create our own glog replacement
  .gitignore
  NOTICE.txt
  go.mod
  go.sum
  internal/glog/glog.go
  internal/glog/go.mod
  internal/glog/go.sum
  script/generate_notice.py
  tests/Dockerfile
Labels: backport-7.x

#5815 [automation] update elastic stack version for testing 8.0.0-571dad33
  docker-compose.yml
Labels: automation, dependency

#5816 [automation] update elastic stack version for testing 7.15.0-bd471fd6
  docker-compose.yml
Labels: automation, dependency

#5814 sammpling: refactor to read/write model.APMEvents
  x-pack/apm-server/sampling/eventstorage/codec.go
  x-pack/apm-server/sampling/eventstorage/jsoncodec.go
  x-pack/apm-server/sampling/eventstorage/sharded.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-7.x, v7.15.0

#5818 model/modeldecoder: decode events into model.Batch
  beater/api/intake/handler.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/rumv3/metricset_test.go
  model/modeldecoder/rumv3/transaction_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/error_test.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  processor/stream/benchmark_test.go
  processor/stream/processor.go
  processor/stream/processor_test.go
Labels: backport-7.x, v7.15.0

#5817 [automation] update elastic stack version for testing 7.14.0-cd696777
  docker-compose.yml
Labels: automation, dependency

#5824 [automation] update elastic stack version for testing 8.0.0-ae1e1c3b
  docker-compose.yml
Labels: automation, dependency

#5825 [automation] update elastic stack version for testing 7.15.0-2cefb6a4
  docker-compose.yml
Labels: automation, dependency

#5826 [automation] update elastic stack version for testing 7.14.0-9fdd79d4
  docker-compose.yml
Labels: automation, dependency

#5820 processor/otel: prepare for APMEventgeddon
  processor/otel/builder.go
  processor/otel/exceptions_test.go
  processor/otel/traces.go
  processor/otel/traces_test.go
Labels: backport-7.x, v7.15.0

#5819 beater/api/profile: always record request metadata
  beater/api/profile/handler.go
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
Labels: backport-7.x, v7.15.0

#5831 [automation] update elastic stack version for testing 8.0.0-cf3e6139
  docker-compose.yml
Labels: automation, dependency

#5832 [automation] update elastic stack version for testing 7.14.0-56a8365b
  docker-compose.yml
Labels: automation, dependency

#5827 Move "tool" module dependencies to tools/go.mod
  .ci/scripts/unit-test.sh
  Makefile
  NOTICE.txt
  elasticsearch/backoff_test.go
  elasticsearch/estest/client.go
  go.mod
  go.sum
  script/generate_notice.py
  tools/go.mod
  tools/go.sum
  tools/tools.go
  x-pack/apm-server/sampling/pubsub/pubsubtest/client.go
Labels: backport-7.x
