Repository elastic/apm-server, pull requests merged in 2021-02, with the labels that each got.

#4668 [7.x] 7.11 wildcard keywords (#4657) (#4666)
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.1.0/docs/README.md
  changelogs/7.11.asciidoc
  docs/fields.asciidoc
  include/fields.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
Labels: backport

#4679 [7.x] Add note about tags vs labels to json schemas (#4675)
  docs/spec/v2/error.json
  docs/spec/v2/metricset.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  model/modeldecoder/v2/model.go
Labels: backport

#4672 ci: fix benchmark stage
  Jenkinsfile
Labels: [zube]: In Review, automation, bug, ci, team:automation

#4682 [7.11] docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#4681 [7.x] docs: bump Otel ex to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#4680 docs: bump Otel to otel-java-agent 0.15.0 and otel-collector-contrib 0.19.0 (#4676)
  docs/guide/opentelemetry-elastic.asciidoc
Labels: backport

#4688 [7.x] ci: fix benchmark stage (#4672)
  Jenkinsfile
Labels: automation, backport, bug, ci, team:automation

#4686 [7.10] ci: fix benchmark stage (#4672)
  Jenkinsfile
Labels: automation, backport, bug, ci, team:automation

#4687 [7.11] ci: fix benchmark stage (#4672)
  Jenkinsfile
Labels: automation, backport, bug, ci, team:automation

#4691 docs: Add 7.9 cloud metadata known issue
  changelogs/7.9.asciidoc
  docs/release-notes.asciidoc
Labels: docs

#4698 [DOCS] Make tagged sections for breaking changes unique
  docs/guide/apm-breaking-changes.asciidoc
Labels: docs, v7.11.0

#4699 [7.x] docs: Add 7.9 cloud metadata known issue (#4691)
  changelogs/7.9.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#4700 [7.11] docs: Add 7.9 cloud metadata known issue (#4691)
  changelogs/7.9.asciidoc
  docs/release-notes.asciidoc
Labels: backport

#4701 [7.10] docs: Add 7.9 cloud metadata known issue (#4691)
  changelogs/7.9.asciidoc
Labels: backport

#4702 [7.9] docs: Add 7.9 cloud metadata known issue (#4691)
  changelogs/7.9.asciidoc
Labels: backport

#4697 docs: add release notes for 6.8.14
  changelogs/6.8.asciidoc
Labels: docs, v6.8

#4703 [7.x] docs: add release notes for 6.8.14 (#4697)
  changelogs/6.8.asciidoc
Labels: backport

#4704 [7.11] docs: add release notes for 6.8.14 (#4697)
  changelogs/6.8.asciidoc
Labels: backport

#4705 [7.10] docs: add release notes for 6.8.14 (#4697)
  changelogs/6.8.asciidoc
Labels: backport

#4706 [6.8] docs: add release notes for 6.8.14 (#4697)
  changelogs/6.8.asciidoc
Labels: backport

#4690 [apmpackage] Add config options supported in ESS
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/agent/input/template.yml.hbs
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/apm/0.1.0/manifest.yml
  changelogs/head.asciidoc
Labels: v7.12.0

#4732 [7.x] [apmpackage] Add config options supported in ESS (#4690)
  apmpackage/apm/0.1.0/agent/input/template.yml.hbs
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/apm/0.1.0/manifest.yml
  apmpackage/docs/README.template.md
Labels: backport

#4722 Add support for consuming OTLP/gRPC metrics
  beater/otlp/grpc.go
  beater/otlp/grpc_test.go
  changelogs/head.asciidoc
  processor/otel/consumer.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: test-plan, v7.12.0

#4739 [7.11] docs: add 7.11.1 release notes (#4727)
  changelogs/7.11.asciidoc
Labels: backport

#4741 [7.x] processor/otel: update tests to use Jaeger model (#4585)
  processor/otel/consumer_test.go
  processor/otel/test_approved/consume_empty.approved.json
  processor/otel/test_approved/consume_emptytrace.approved.json
  processor/otel/test_approved/consume_span.approved.json
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/metadata_jaeger_full-traceid.approved.json
  processor/otel/test_approved/metadata_minimal.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
Labels: backport

#4696 ci: set proper parameters for the tar step
  .ci/scripts/docker-get-logs.sh
  Jenkinsfile
Labels: automation, bug, ci, team:automation

#4742 [7.x] beater: separate recording static/dynamic config (#4609)
  beater/beater.go
  beater/telemetry.go
  beater/telemetry_test.go
Labels: backport

#4747 [7.x] beater: move event ACKer from publisher to beater (#4617)
  beater/acker.go
  beater/beater.go
  publish/pub.go
Labels: backport

#4746 [DOCS] Fixes URLs on Secure communication with APM Agents page
  docs/secure-communication-agents.asciidoc
Labels: docs, v7.1.0, v7.10.1, v7.11.0, v7.2.0, v7.3.0, v7.5.0, v7.6.1, v7.7.0, v7.8.0, v7.9.3, v8.0.0

#4752 [7.9] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4754 [7.8] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4749 [7.x] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.12.0

#4750 [7.11] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.11.0

#4751 [7.10] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.10.0

#4755 [7.7] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.7.0

#4756 [7.6] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.6.0

#4758 [7.4] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs

#4759 [7.3] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.3.0

#4760 [7.2] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.2.0

#4757 [7.5] [DOCS] Fixes URLs on Secure communication with APM Agents page (#4746)
  docs/secure-communication-agents.asciidoc
Labels: backport, docs, v7.5.0

#4761 [7.x] beater: stop relying on onboarding in tests (#4622)
  beater/beater.go
  beater/beater_test.go
Labels: backport

#4753 [7.x] processor/otel: update to go.opentelemetry.io (#4602)
  NOTICE.txt
  beater/jaeger/common.go
  beater/jaeger/grpc.go
  beater/jaeger/grpc_test.go
  beater/jaeger/http.go
  beater/jaeger/http_test.go
  go.mod
  go.sum
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/metadata.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/stream/processor_test.go
  testdata/jaeger/batch_1.approved.json
Labels: backport

#4764 docs: readds .NET link
  docs/secure-communication-agents.asciidoc
Labels: docs

#4765 [7.x] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4766 [7.11] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4767 [7.10] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4768 [7.9] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4769 [7.8] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4770 [7.7] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4771 [7.6] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4772 [7.5] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4773 [7.4] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4774 [7.3] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4775 [7.2] docs: readds .NET link (#4764)
  docs/secure-communication-agents.asciidoc
Labels: backport

#4779 [7.x] update elasticsearch client versions (#4293)
  NOTICE.txt
  go.mod
  go.sum
Labels: backport

#4782 [7.x] sampling: fix TestStorageGC (#4656)
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#4778 [7.x] beater: refactor tracerServer (#4628)
  beater/beater.go
  beater/tracing.go
Labels: backport

#4781 [7.x] Add a _doc_count field for single-histogram metricsets (#4647)
  model/metricset.go
  model/metricset_test.go
  systemtest/aggregation_test.go
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/estest/search.go
Labels: backport

#4780 [7.x] Makefile: add check-fmt target (#4654)
  Makefile
  beater/config/config_test.go
  publish/pub_test.go
  script/autopep8_all.sh
  script/check_goimports.sh
  script/generate_notice.py
  script/goimports.sh
  systemtest/apikeycmd_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport

#4785 [7.x] Delete unused package "validation" (#4643)
  go.mod
  validation/validator.go
  validation/validator_test.go
Labels: backport

#4784 [7.x] beater: run gmuxed gRPC server by default (#4618)
  NOTICE.txt
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  beater/http.go
  beater/jaeger/server.go
  beater/server.go
  beater/server_test.go
  go.mod
  go.sum
  systemtest/apmservertest/cert.pem
  systemtest/apmservertest/command.go
  systemtest/apmservertest/key.pem
  systemtest/apmservertest/server.go
  systemtest/apmservertest/server_test.go
  systemtest/jaeger_test.go
Labels: backport

#4787 [7.x] beater: add support for config reloading (#4623)
  beater/acker.go
  beater/beater.go
  beater/beater_test.go
  beater/server_test.go
  systemtest/approvals/TestDataStreamsEnabled/true.approved.json
  systemtest/elasticsearch.go
Labels: backport

#4792 [7.x] beater: ensure Fleet config contains 'apm-server' (#4684)
  beater/beater.go
  beater/config/integration.go
  beater/config/integration_test.go
  beater/server_test.go
Labels: backport

#4793 [7.x] Add support for receiving traces over OTLP/gRPC (#4677)
  NOTICE.txt
  beater/grpcauth.go
  beater/otlp/grpc.go
  beater/otlp/grpc_test.go
  beater/server.go
  beater/server_test.go
  go.mod
  go.sum
  systemtest/approvals/TestOTLPGRPC.approved.json
  systemtest/go.mod
  systemtest/go.sum
  systemtest/otlp_test.go
Labels: backport

#4794 [7.x] Version template for package docs (#4568)
  apmpackage/README.md
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/cmd/gen-package/gendocs.go
  apmpackage/cmd/gen-package/paths.go
Labels: backport

#4797 [7.x] add ilm policiy to apm data streams (#4620)
  apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/traces/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
Labels: backport

#4796 [7.x] Add missing fields properties (#4611)
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/cmd/gen-package/field.go
Labels: backport

#4798 [7.x] intake: add cloud.service.name to metadata (#4626)
  CONTRIBUTING.md
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/apm/0.1.0/docs/README.md
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  docs/fields.asciidoc
  docs/spec/v2/metadata.json
  include/fields.go
  model/cloud.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/profile/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  testdata/intake-v2/errors.ndjson
  testdata/intake-v2/metadata.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#4799 [7.x] Script to automatically copy and bump package version in the storage … (#4595)
  apmpackage/README.md
  script/copy_package.py
Labels: backport

#4800 [7.x] fix make fmt (#4659)
  script/autopep8_all.sh
Labels: backport

#4802 [7.x] sampling: match policies in the given order (#4685)
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#4803 [7.x] Makefile: always use .go_version (#4710)
  Makefile
Labels: backport

#4795 [7.12] Add package settings and icon (#4542)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/apm/0.1.0/img/logo_apm.svg
  apmpackage/apm/0.1.0/manifest.yml
Labels: backport

#4801 [7.12] Do not strip leading 0s from traceIds and spanIds if the span source is jaeger (#4671)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
  tests/system/jaeger_batch_0.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
Labels: backport

#4744 [7.11] ci: set proper parameters for the tar step (#4696)
  .ci/scripts/docker-get-logs.sh
  Jenkinsfile
Labels: automation, backport, bug, ci, team:automation

#4745 [7.10] ci: set proper parameters for the tar step (#4696)
  .ci/scripts/docker-get-logs.sh
  Jenkinsfile
Labels: automation, backport, bug, ci, team:automation

#4811 [7.x] Do not strip leading 0s from traceIds and spanIds if the span source is jaeger (#4671)
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
  tests/system/jaeger_batch_0.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
Labels: backport

#4812 [7.x] Add package settings and icon (#4542)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/apm/0.1.0/img/logo_apm.svg
  apmpackage/apm/0.1.0/manifest.yml
Labels: backport

#4814 [7.12] Clean up field definitions (#4689)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/cmd/gen-package/gendocs.go
  docs/fields.asciidoc
  include/fields.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
Labels: backport

#4819 [7.x] sampling: use a data stream for sampled trace docs (#4707)
  apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/base-fields.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/manifest.yml
  apmpackage/cmd/gen-package/genfields.go
  apmpackage/cmd/gen-package/main.go
  beater/beater.go
  beater/server.go
  systemtest/elasticsearch.go
  systemtest/estest/search.go
  systemtest/monitoring_test.go
  systemtest/sampling_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
  x-pack/apm-server/sampling/pubsub/config.go
  x-pack/apm-server/sampling/pubsub/config_test.go
  x-pack/apm-server/sampling/pubsub/datastream.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
  x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
  x-pack/apm-server/sampling/pubsub/pubsub_test.go
Labels: backport

#4818 [7.12] processor/otel: extend support for OpenTelemetry semantic conventions (#4711)
  model/context.go
  model/error_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/v2/decoder.go
  model/transaction_test.go
  processor/otel/builder.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/metadata.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  systemtest/approvals/TestOTLPGRPC.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
Labels: backport

#4813 [7.x] Clean up field definitions (#4689)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/traces/fields/fields.yml
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/cmd/gen-package/gendocs.go
  docs/fields.asciidoc
  include/fields.go
  model/error/_meta/fields.yml
  model/metricset/_meta/fields.yml
  model/span/_meta/fields.yml
  model/transaction/_meta/fields.yml
  x-pack/apm-server/fields/_meta/fields.yml
  x-pack/apm-server/include/fields.go
Labels: backport

#4821 [7.x] Use the apm-server version everywhere* (#4725)
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/mux_test.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/beater_test.go
  beater/beatertest/monitoring.go
  beater/http.go
  beater/middleware/monitoring_middleware_test.go
  beater/server.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/tracing.go
  publish/pub.go
Labels: backport

#4822 [7.12] Use the apm-server version everywhere* (#4725)
  beater/api/mux.go
  beater/api/mux_config_agent_test.go
  beater/api/mux_intake_backend_test.go
  beater/api/mux_intake_rum_test.go
  beater/api/mux_root_test.go
  beater/api/mux_sourcemap_handler_test.go
  beater/api/mux_test.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  beater/beater_test.go
  beater/beatertest/monitoring.go
  beater/http.go
  beater/middleware/monitoring_middleware_test.go
  beater/server.go
  beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  beater/tracing.go
  publish/pub.go
Labels: backport

#4820 [7.12] sampling: use a data stream for sampled trace docs (#4707)
  apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ilm/default_policy.json
  apmpackage/apm/0.1.0/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/base-fields.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/ecs.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/fields/fields.yml
  apmpackage/apm/0.1.0/data_stream/sampled_traces/manifest.yml
  apmpackage/cmd/gen-package/genfields.go
  apmpackage/cmd/gen-package/main.go
  beater/beater.go
  beater/server.go
  systemtest/elasticsearch.go
  systemtest/estest/search.go
  systemtest/monitoring_test.go
  systemtest/sampling_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
  x-pack/apm-server/sampling/pubsub/config.go
  x-pack/apm-server/sampling/pubsub/config_test.go
  x-pack/apm-server/sampling/pubsub/datastream.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
  x-pack/apm-server/sampling/pubsub/pubsub_integration_test.go
  x-pack/apm-server/sampling/pubsub/pubsub_test.go
Labels: backport

#4817 [7.x] processor/otel: extend support for OpenTelemetry semantic conventions (#4711)
  model/context.go
  model/error_test.go
  model/modeldecoder/rumv3/decoder.go
  model/modeldecoder/v2/decoder.go
  model/transaction_test.go
  processor/otel/builder.go
  processor/otel/consumer.go
  processor/otel/consumer_test.go
  processor/otel/metadata.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  systemtest/approvals/TestOTLPGRPC.approved.json
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
  tests/system/jaeger_batch_0_auth_tag_removed.approved.json
  tests/system/jaeger_batch_0_authorization.approved.json
  tests/system/jaeger_span.approved.json
Labels: backport

#4826 [7.12] Add support for consuming OTLP/gRPC metrics (#4722)
  beater/otlp/grpc.go
  beater/otlp/grpc_test.go
  processor/otel/consumer.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: backport

#4827 [7.x] sampling: require a default policy (#4729)
  beater/beater.go
  beater/config/config_test.go
  beater/config/sampling.go
  beater/config/sampling_test.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#4825 [7.x] Add support for consuming OTLP/gRPC metrics (#4722)
  beater/otlp/grpc.go
  beater/otlp/grpc_test.go
  processor/otel/consumer.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: backport

#4828 [7.12] sampling: require a default policy (#4729)
  beater/beater.go
  beater/config/config_test.go
  beater/config/sampling.go
  beater/config/sampling_test.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport

#4835 [7.x] Add dataset_is_prefix field to manifest files (#4653)
  apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
Labels: backport

#4833 [7.x] processor/otel: add unit test for span status (#4734)
  processor/otel/consumer_test.go
Labels: backport

#4838 [7.12] Rename dataset to avoid ambiguous index pattern generation (#4669)
  apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
  model/metricset.go
  model/metricset_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
Labels: backport

#4840 [7.12] Wire kibana config from fleet (#4670)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/docs/README.md
  beater/api/config/agent/handler_test.go
  beater/api/mux.go
  beater/beater.go
  beater/config/config.go
  beater/config/integration.go
  beater/config/rum.go
  beater/config/rum_test.go
  beater/jaeger/server.go
  beater/server.go
  cmd/apikey.go
  go.sum
  kibana/connecting_client.go
  kibana/connecting_client_test.go
Labels: backport

#4839 [7.x] Wire kibana config from fleet (#4670)
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/docs/README.md
  beater/api/config/agent/handler_test.go
  beater/api/mux.go
  beater/beater.go
  beater/config/config.go
  beater/config/integration.go
  beater/config/rum.go
  beater/config/rum_test.go
  beater/jaeger/server.go
  beater/server.go
  cmd/apikey.go
  go.sum
  kibana/connecting_client.go
  kibana/connecting_client_test.go
Labels: backport

#4832 [7.12] systemtest: test apm-server in Fleet mode (#4650) | systemtest: fix missing error check (#4683) | systemtest: compensate for Fleet API bug (#4693)
  docker-compose.yml
  go.sum
  systemtest/apmservertest/command.go
  systemtest/apmservertest/config.go
  systemtest/containers.go
  systemtest/datastreams_test.go
  systemtest/elasticsearch.go
  systemtest/fleet_test.go
  systemtest/fleettest/client.go
  systemtest/fleettest/error.go
  systemtest/fleettest/types.go
  systemtest/kibana.go
  testing/docker/package-registry/config.yml
Labels: backport

#4837 [7.x] Rename dataset to avoid ambiguous index pattern generation (#4669)
  apmpackage/apm/0.1.0/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.json
  apmpackage/apm/0.1.0/data_stream/app_metrics/manifest.yml
  model/metricset.go
  model/metricset_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
Labels: backport

#4836 [7.12] Add dataset_is_prefix field to manifest files (#4653)
  apmpackage/apm/0.1.0/data_stream/error_logs/manifest.yml
  apmpackage/apm/0.1.0/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/profile_metrics/manifest.yml
  apmpackage/apm/0.1.0/data_stream/traces/manifest.yml
Labels: backport

#4740 docs: Add PHP agent information to shared docs
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/trace-sampling.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: docs, v7.12.0

#4844 [7.x] docs: Add PHP agent information to shared docs (#4740)
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/trace-sampling.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: backport

#4845 [7.12] docs: Add PHP agent information to shared docs (#4740)
  docs/getting-started-apm-server.asciidoc
  docs/guide/agent-server-compatibility.asciidoc
  docs/guide/apm-data-model.asciidoc
  docs/guide/apm-doc-directory.asciidoc
  docs/guide/distributed-tracing.asciidoc
  docs/guide/opentracing.asciidoc
  docs/guide/trace-sampling.asciidoc
  docs/guide/troubleshooting.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/ssl-input.asciidoc
  docs/tab-widgets/distributed-trace-receive-widget.asciidoc
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send-widget.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/tab-widgets/install-agents.asciidoc
  docs/troubleshooting.asciidoc
  docs/version.asciidoc
Labels: backport

#4834 [7.12] processor/otel: add unit test for span status (#4734)
  processor/otel/consumer_test.go
Labels: backport

#4831 [7.x] systemtest: test apm-server in Fleet mode (#4650) | systemtest: fix missing error check (#4683) | systemtest: compensate for Fleet API bug (#4693)
  docker-compose.yml
  go.sum
  systemtest/apmservertest/command.go
  systemtest/apmservertest/config.go
  systemtest/containers.go
  systemtest/datastreams_test.go
  systemtest/elasticsearch.go
  systemtest/fleet_test.go
  systemtest/fleettest/client.go
  systemtest/fleettest/error.go
  systemtest/fleettest/types.go
  systemtest/kibana.go
  testing/docker/package-registry/config.yml
Labels: backport

#4850 [7.x] Support for Node.js profiles (#4728)
  apmpackage/apm/0.1.0/data_stream/profile_metrics/fields/fields.yml
  cmd/pprofessor/fetcher.go
  docs/fields.asciidoc
  include/fields.go
  model/profile.go
  model/profile/_meta/fields.yml
  model/profile_test.go
Labels: backport

#4849 [7.12] Disable sourcemap upload endpoint when data streams enabled (#4735)
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/DataStreams.approved.json
  beater/api/mux.go
  beater/api/mux_sourcemap_handler_test.go
Labels: backport

#4848 [7.x] Disable sourcemap upload endpoint when data streams enabled (#4735)
  beater/api/asset/sourcemap/test_approved/integration/TestSourcemapHandler_KillSwitchMiddleware/DataStreams.approved.json
  beater/api/mux.go
  beater/api/mux_sourcemap_handler_test.go
Labels: backport

#4846 [7.x] Add service name to dataset field (#4674)
  datastreams/servicename.go
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestDataStreamsEnabled/true.approved.json
Labels: backport

#4852 [7.12] apmpackage: disallow multiple "apm" integrations (#4694)
  apmpackage/apm/0.1.0/manifest.yml
  systemtest/fleet_test.go
  systemtest/fleettest/client.go
  systemtest/fleettest/helpers.go
  systemtest/fleettest/types.go
Labels: backport

#4851 [7.x] apmpackage: disallow multiple "apm" integrations (#4694)
  apmpackage/apm/0.1.0/manifest.yml
  systemtest/fleet_test.go
  systemtest/fleettest/client.go
  systemtest/fleettest/helpers.go
  systemtest/fleettest/types.go
Labels: backport

#4847 [7.12] Add service name to dataset field (#4674)
  datastreams/servicename.go
  model/error.go
  model/error_test.go
  model/metricset.go
  model/metricset_test.go
  model/profile.go
  model/profile_test.go
  model/span.go
  model/span_test.go
  model/transaction.go
  model/transaction_test.go
  processor/otel/test_approved/jaeger_sampling_rate.approved.json
  processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  processor/otel/test_approved/metadata_jaeger-version.approved.json
  processor/otel/test_approved/metadata_jaeger.approved.json
  processor/otel/test_approved/span_jaeger_custom.approved.json
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  processor/otel/test_approved/transaction_jaeger_custom.approved.json
  processor/otel/test_approved/transaction_jaeger_full.approved.json
  processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationInvalidJSONEvent.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetadataNullValues.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMinimalService.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumErrors.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Errors.approved.json
  processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestDataStreamsEnabled/true.approved.json
Labels: backport

#4860 [JJBB] Centralize approach used by agents to fetch json schema files from the apm server repo
  .ci/jobs/defaults.yml
  .ci/jobs/update-json-schema.yml
Labels: automation, ci

#4862 Update PHP agent section of Manual distributed tracing docs
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
Labels: docs, v7.12.0

#4871 [7.3] Update documentation links to .NET agent
  docs/guide/apm-release-notes.asciidoc
  docs/secure-communication-agents.asciidoc
  docs/version.asciidoc
Labels: docs

#4872 [7.2] Update documentation links to .NET agent #4871
  docs/secure-communication-agents.asciidoc
  docs/version.asciidoc
Labels: docs

#4873 [7.1] Update documentation links to .NET agent #4871
  docs/version.asciidoc
Labels: docs

#4874 [7.0] Update documentation links to .NET agent #4871
  docs/version.asciidoc
Labels: docs

#4863 [7.x] docs: Update PHP agent manual distributed tracing docs (#4862)
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
Labels: backport

#4864 [7.12] docs: Update PHP agent manual distributed tracing docs (#4862)
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
Labels: backport

#4856 [7.x] processor/otel: test service.version handling (#4853)
  processor/otel/consumer_test.go
Labels: backport

#4859 [CI] Centralize approach used by agents to fetch json schema files from the apm server repo
  .ci/.jenkins-schema.yml
  .ci/jobs/update-json-schema.yml
  .ci/scripts/prepare-spec-changes.sh
  .ci/update-json-schema.groovy
Labels: automation

#4870 [CI][arm] build and unit tests
  Jenkinsfile
Labels: automation, ci, team:automation

#4861 Introduce a configurable default service environment
  _meta/beat.yml
  apm-server.docker.yml
  apm-server.yml
  apmpackage/apm/0.1.0/_dev/docs/README.template.md
  apmpackage/apm/0.1.0/agent/input/template.yml.hbs
  apmpackage/apm/0.1.0/docs/README.md
  apmpackage/apm/0.1.0/manifest.yml
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/api/mux.go
  beater/beater.go
  beater/config/config.go
  beater/config/config_test.go
  changelogs/head.asciidoc
  docs/configuration-process.asciidoc
  model/modelprocessor/environment.go
  model/modelprocessor/environment_test.go
  systemtest/apmservertest/config.go
  systemtest/environment_test.go
  transform/transform.go
  x-pack/apm-server/main.go
Labels: test-plan, v7.13.0
