Repository elastic/apm-server, pull requests merged in 2022-07, with the labels that each got.

#8519 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8518 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8520 [automation] update elastic stack version for testing 8.4.0-3d206b5d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8521 [8.3] Bump version to 8.3.2
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  cmd/version.go
Labels: backport-skip

#8522 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8523 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8526 [automation] update elastic stack version for testing 8.4.0-3ad82aa8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8525 [automation] update elastic stack version for testing 7.17.6-63d4a205
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8512 [automation] update elastic stack version for testing 8.2.4-e7c42e26
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8477 smoketest: Add APM Managed tests
  Makefile
  testing/smoke/basic_upgrade/basic-upgrade.sh
  testing/smoke/basic_upgrade/legacy-managed.sh
  testing/smoke/basic_upgrade/main.tf
  testing/smoke/basic_upgrade/standalone-major-managed.sh
  testing/smoke/lib.sh
Labels: enhancement, backport-skip, v8.4.0

#8524 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8529 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8530 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8513 [automation] update elastic stack version for testing 8.3.1-b95de5e6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8531 [automation] update elastic stack version for testing 8.3.2-d34285fd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8532 [automation] update elastic stack version for testing 8.4.0-03bd6f3f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8528 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8527 Chore: retry benchmarks once when failed
  .ci/benchmarks.groovy
Labels: backport-skip

#8533 ci: use baremetal for the microbenchmarking
  Jenkinsfile
Labels: automation, Team:Automation, backport-8.3, backport-7.17

#8540 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8539 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8541 [automation] update libbeat and beats packaging
  go.mod
Labels: automation, backport-skip

#8542 [automation] update elastic stack version for testing 8.4.0-533f1e30
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8544 [automation] update elastic stack version for testing 8.3.2-56253b46
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8543 [automation] update elastic stack version for testing 7.17.6-1e4f9cbf
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8471 ci: enable report benchmark diff on a PR basis
  Jenkinsfile
Labels: ci, backport-8.3, backport-7.17

#8546 docs: add 8.3.2 release notes
  changelogs/8.3.asciidoc
  changelogs/head.asciidoc
Labels: docs, backport-8.3

#8538 docs: clarify secret token create/update
  docs/input-apm.asciidoc
  docs/secure-agent-communication.asciidoc
Labels: Team:Docs, backport-8.3, backport-7.17

#8553 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8554 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8555 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8558 [automation] update elastic stack version for testing 8.3.2-97fdd78b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8557 [automation] update elastic stack version for testing 8.4.0-d0a4da44
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8556 [automation] update elastic stack version for testing 7.17.6-94c92680
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8560 bump version to 8.3.3
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  cmd/version.go
Labels: backport-skip

#8561 ci: use the microbenchmarks-pool
  Jenkinsfile
Labels: backport-8.3, backport-7.17

#8564 Revert "ci: use the microbenchmarks-pool"
  Jenkinsfile
Labels: backport-skip

#8566 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8567 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8565 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8568 Revert "Revert "ci: use the microbenchmarks-pool""
  Jenkinsfile
Labels: backport-skip

#8571 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8570 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8572 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8574 [automation] update elastic stack version for testing 8.3.3-385d4fdb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8573 [automation] update elastic stack version for testing 8.4.0-dd98ded4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8575 [automation] update elastic stack version for testing 7.17.6-38278486
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8584 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8586 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8589 [automation] update elastic stack version for testing 8.4.0-164d9a10
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8587 [automation] update elastic stack version for testing 8.3.3-46b07667
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8588 [automation] update elastic stack version for testing 7.17.6-cff0caa9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8547 Add terraform module to create soaktest workers on GCP
  TESTING.md
  systemtest/cmd/apmsoak/.gitignore
  testing/apmsoak/Makefile
  testing/apmsoak/README.md
  testing/apmsoak/main.tf
  testing/apmsoak/terraform.tfvars.example
  testing/apmsoak/variables.tf
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/header.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/provider.tf
  testing/infra/terraform/modules/soaktest_workers/systemd.tpl
  testing/infra/terraform/modules/soaktest_workers/variables.tf
Labels: backport-skip

#8585 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8545 dev-docs: Add smoke tests docs to `TESTING.md`
  TESTING.md
Labels: docs, backport-skip, v8.4.0

#8594 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8595 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8598 [automation] update elastic stack version for testing 8.4.0-00048b66
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8597 [automation] update elastic stack version for testing 8.3.3-0264aa15
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8599 [automation] update elastic stack version for testing 7.17.6-5c77e057
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8577 package: correct default TLS protocols (add 1.3, remove 1.0)
  apmpackage/apm/manifest.yml
  systemtest/tls_test.go
Labels: bug, backport-7.16, backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-7.17

#8600 smoketest: Add APM Integration assertions
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/smoke/basic_upgrade/basic-upgrade.sh
  testing/smoke/basic_upgrade/legacy-managed.sh
  testing/smoke/basic_upgrade/main.tf
  testing/smoke/basic_upgrade/standalone-major-managed.sh
  testing/smoke/lib.sh
Labels: enhancement, backport-skip, v8.4.0

#8612 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8610 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8609 apmbench: Fix broken `-benchtime`
  systemtest/benchtest/main.go
Labels: backport-skip, v8.4.0

#8613 [automation] update elastic stack version for testing 8.3.3-fba30f71
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8611 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8615 ci: Introduce schedule-everyday job for benchmarks
  .ci/jobs/apm-server-schedule-everyday.yml
  .ci/schedule-daily.groovy
  .ci/schedule-everyday.groovy
Labels: ci, backport-skip

#8616 benchmark: Add `BENCHMARK_MAX_RATE` tune warmup
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  testing/benchmark/Makefile
Labels: enhancement, backport-skip, v8.4.0

#8626 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8625 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8627 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8629 [automation] update elastic stack version for testing 8.4.0-3cd57abb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8628 [automation] update elastic stack version for testing 8.3.3-f93ba5f4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8630 [automation] update elastic stack version for testing 7.17.6-75df96d4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8631 smoketest: Add apm-ci link in docs
  README.md
  TESTING.md
Labels: backport-skip

#8633 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8632 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8634 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8635 [automation] update elastic stack version for testing 8.4.0-a324b98b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8636 [automation] update elastic stack version for testing 8.3.3-99553f72
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8637 [automation] update elastic stack version for testing 7.17.6-0aa797e4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8639 Update dependencies
  NOTICE.txt
  go.mod
  go.sum
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#8608 Add “Team:Docs” issues to obs-docs project
  .github/workflows/add-to-docs-project.yml
Labels: automation, backport-skip

#8239 test: replace env workaround with native T.SetEnv
  beater/java_attacher/java_attacher_test.go
  beater/tracing_test.go
  systemtest/environment_test.go
Labels: backport-skip

#8643 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8641 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8646 [automation] update elastic stack version for testing 8.3.3-302be7c1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8645 [automation] update elastic stack version for testing 8.4.0-31315ca3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8642 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8592 apmpackage: update APM integration description
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  changelogs/8.3.asciidoc
Labels: backport-8.3

#8654 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8653 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8655 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8658 [automation] update elastic stack version for testing 8.3.3-e5bc7e69
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8657 [automation] update elastic stack version for testing 8.4.0-31269fd2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8537 automate the ironbank generation
  Makefile
  magefile.go
  packaging/ironbank/Dockerfile.tmpl
  packaging/ironbank/LICENSE
  packaging/ironbank/README.md.tmpl
  packaging/ironbank/hardening_manifest.yaml.tmpl
Labels: automation, backport-8.3, backport-7.17

#8667 docs: add 8.3.3 jump link
  changelogs/8.3.asciidoc
Labels: Team:Docs, backport-8.3

#8669 Update integration screenshots
  apmpackage/apm/changelog.yml
  apmpackage/apm/img/apm-01-service-inventory.png
  apmpackage/apm/img/apm-02-service-overview.png
  apmpackage/apm/img/apm-03-trace.png
  apmpackage/apm/img/apm-04-service-map.png
Labels: Team:Docs, backport-8.3

#8678 Remove unused cruft from the repo
  .backportrc.json
  .dockerignore
  .editorconfig
  Dockerfile
Labels: backport-skip

#8674 Update golang.org/x/tools
  go.mod
  go.sum
Labels: backport-skip

#8679 Move Jenkinsfile under .ci
  .ci/Jenkinsfile
  .ci/jobs/apm-server-mbp.yml
Labels: backport-8.3, backport-7.17

#8663 Correct smoketests running in the CI
  .ci/smoke-tests.groovy
  Makefile
Labels: backport-skip

#8688 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8687 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8690 [automation] update elastic stack version for testing 7.17.6-9675035b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8685 ci: enable github actions for macos
  .ci/Jenkinsfile
  .github/workflows/macos.yml
Labels: backport-8.3, backport-7.17

#8682 Add failure report for smoketests
  .ci/smoke-tests.groovy
Labels: backport-skip

#8695 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8694 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8591 systemtest: close response body after refreshing indices
  systemtest/estest/search.go
Labels: backport-skip

#8698 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8699 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8680 Remove golint, just use staticcheck
  Makefile
  go.mk
  internal/agentcfg/fetch.go
  internal/beater/server_test.go
  internal/processor/otel/traces.go
  reviewdog.yml
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: backport-skip

#8638 smoketest: Improve output, parallelize by test
  .gitignore
  Makefile
  testing/smoke/basic-upgrade/cleanup.sh
  testing/smoke/basic-upgrade/test.sh
  testing/smoke/basic_upgrade/test.sh
  testing/smoke/legacy-managed/cleanup.sh
  testing/smoke/legacy-managed/test.sh
  testing/smoke/legacy-standalone-major-managed/cleanup.sh
  testing/smoke/legacy-standalone-major-managed/test.sh
  testing/smoke/lib.sh
  testing/smoke/main.tf
Labels: enhancement, backport-skip

#8590 Implementing JVM discovery for Java Agent attacher integration
  Makefile
  internal/beater/config/java_attacher.go
  internal/beater/java_attacher/discovery_rules.go
  internal/beater/java_attacher/java_attacher.go
  internal/beater/java_attacher/java_attacher_test.go
  internal/beater/java_attacher/main.go
  internal/beater/java_attacher/set_run_as_user.go
  internal/beater/java_attacher/set_run_as_user_windows.go
  magefile.go
Labels: backport-skip, ci:windows

#8703 [automation] update elastic stack version for testing 7.17.6-964edfea
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8704 Fix Windows build
  go.mk
  magefile.go
Labels: backport-skip

#8702 [automation] update elastic stack version for testing 8.3.3-5fe7d8b1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8701 [automation] update elastic stack version for testing 8.4.0-d058e92f
  docker-compose.yml
  systemtest/fleet_test.go
Labels: dependency, automation, backport-skip

#8649 chore: benchmarks: fix retry count
  .ci/benchmarks.groovy
Labels: backport-skip

#8689 Simplify CI
  .ci/Jenkinsfile
  .ci/packaging.groovy
  .ci/scripts/build.sh
  .ci/scripts/linux-test.sh
  .ci/scripts/package-docker.sh
  .ci/scripts/unit-test.sh
  .ci/scripts/windows-build.ps1
  .ci/scripts/windows-test.ps1
  Makefile
  go.mod
  magefile.go
  tools.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: backport-skip, ci:windows

#8681 Reduce magefile
  .ci/Jenkinsfile
  Makefile
  _meta/beat.yml
  apm-server.docker.yml
  magefile.go
  script/check_git_clean.sh
  script/run_agent.sh
Labels: backport-skip

#8714 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8713 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8715 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8716 [automation] update elastic stack version for testing 8.3.3-d520d440
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8712 Update to elastic-package 0.58.1
  .ci/scripts/Makefile
  Makefile
  apmpackage/apm/changelog.yml
  docker-compose.yml
  systemtest/kibana.go
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#8720 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8721 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8722 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8723 [automation] update elastic stack version for testing 7.17.6-3f4b9bc6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8719 .ci: remove beats-tester pipeline
  .ci/Jenkinsfile
  .ci/check-packages.groovy
  .ci/jobs/apm-server-check-packages-mbp.yml
Labels: backport-7.17

#8648 changelog: add missing TLS changelog entry to main branch
  apmpackage/apm/changelog.yml
Labels: backport-skip

#8726 bump version to 8.5
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip

#8727 fix: minor fix in make clean command
  Makefile
Labels: backport-8.4

#8735 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8739 [automation] update elastic stack version for testing 8.4.0-60171339
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8738 [automation] update elastic stack version for testing 8.3.3-8631d33c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8740 Add 8.4.0 changelog
  CHANGELOG.asciidoc
  changelogs/8.4.asciidoc
  changelogs/head.asciidoc
Labels: backport-8.4

#8737 .ci: don't notify of packaging failure on PRs
  .ci/packaging.groovy
Labels: backport-skip

#8744 Handle ctx canceled as non fatal in apmsoak
  systemtest/cmd/apmsoak/main.go
Labels: backport-skip

#8743 Update go-elasticsearch version to 8.3
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.4

#8736 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8746 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8747 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8751 [automation] update elastic stack version for testing 8.4.0-fb724a71
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8749 [automation] update elastic stack version for testing 8.3.3-326db639
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8753 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
