Repository elastic/apm-server, pull requests merged in 2022-01, with the labels that each got.

#6939 docs: Remove OSS
  docs/legacy/copied-from-beats/docs/repositories.asciidoc
  docs/legacy/copied-from-beats/docs/shared-docker.asciidoc
  docs/legacy/getting-started-apm-server.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1

#6975 notice: Update notice to 2022
  NOTICE.txt
Labels: ci, backport-7.16, backport-8.0, backport-7.17

#6923 modelindexer: Fix TooManyRequests stat reporting
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer.go
  model/modelindexer/indexer_test.go
Labels: bug, v8.0.0, test-plan, backport-8.0

#6976 mergify: Add `backport-7.17` config
  .mergify.yml
Labels: ci, backport-skip

#6983 Update beats 20220104124402
  .go-version
  Dockerfile
  NOTICE.txt
  beater/jaeger/grpc_test.go
  beater/otlp/grpc_test.go
  beater/server_test.go
  docs/version.asciidoc
  go.mod
  go.sum
Labels: backport-skip

#6973 [automation] update elastic stack version for testing 7.17.0-343e3146
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6988 [automation] update elastic stack version for testing 7.17.0-b402b9a8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6985 docs: update span compression links
  docs/span-compression.asciidoc
Labels: Team:Docs, backport-7.16, backport-v8.0, backport-7.17

#6997 [automation] update elastic stack version for testing 7.17.0-32e424af
  docker-compose.yml
Labels: dependency, automation, backport-skip

#6991 [java-attacher] invalid config fails open
  beater/config/config.go
  beater/config/config_test.go
Labels: v8.1.0, backport-8.1

#6984 docs: Source AWS Lambda extension docs from repo
  docs/aws-lambda-extension.asciidoc
  docs/integrations-index.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0, backport-7.17

#7008 [automation] update elastic stack version for testing 7.17.0-fe65ce80
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7011 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7015 systemtest: Skip `TestTailSampling` for now
  systemtest/sampling_test.go
Labels: test, v8.0.0, backport-8.0

#7003 jjbb: enable 7.17 branch
  .ci/jobs/apm-server-check-changelogs-mbp.yml
  .ci/jobs/apm-server-check-packages-mbp.yml
  .ci/jobs/apm-server-mbp.yml
Labels: automation, backport-skip

#7004 [apmpackage] fix booleans for package upgrade
  apmpackage/apm/agent/input/template.yml.hbs
Labels: v8.0.0, v8.1.0, backport-v8.1, backport-v8.0, v7.17.0, backport-7.17

#7014 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7030 [automation] update elastic stack version for testing 7.17.0-9b8314f9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7034 compose: Wait until `fleet-server` is healthy
  docker-compose.yml
Labels: test, backport-7.16, backport-8.0, backport-7.17

#7043 [7.16] Update stack to `7.16.3-980486b6-SNAPSHOT`
  docker-compose.yml
Labels: backport-skip

#7042 apmpackage: update instruction in README
  apmpackage/README.md
Labels: backport-8.0

#7041 docs: add release notes
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
  changelogs/8.0.asciidoc
  changelogs/head.asciidoc
Labels: Team:Docs, backport-skip

#7052 [6.8] docs: add release notes (#7041)
  changelogs/6.8.asciidoc
Labels: backport

#7050 [7.17] docs: add release notes (#7041)
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
Labels: backport

#7051 [7.16] docs: add release notes (#7041)
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
Labels: backport

#7049 [8.0] docs: add release notes (#7041)
  changelogs/6.8.asciidoc
  changelogs/7.16.asciidoc
  changelogs/8.0.asciidoc
Labels: backport

#7037 [java-attacher] update to v1.28.4
  Makefile
Labels: v8.0.0, backport-8.0, backport-8.1

#7055 docs: fix distributed tracing images
  docs/legacy/guide/distributed-tracing.asciidoc
Labels: backport-7.16, backport-8.0, backport-7.17

#7059 apmpackage: fix Kibana URL in README
  apmpackage/README.md
Labels: backport-8.0

#7062 [automation] update elastic stack version for testing 7.17.0-049bcf23
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7002 docs: update OTel messaging spans limitation
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: backport-7.16, backport-8.0, backport-7.17

#7066 docker-compose: use KIBANA_FLEET_* env vars
  docker-compose.yml
Labels: backport-8.0

#7033 aggregation: Add dimensions to transaction metrics
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  changelogs/head.asciidoc
  docs/legacy/metricset-indices.asciidoc
  systemtest/aggregation_test.go
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/intake.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: enhancement, v8.1.0, backport-8.1

#7075 [automation] update elastic stack version for testing 7.17.0-560490e9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7078 integration: Update README
  apmpackage/apm/_dev/build/docs/README.md
Labels: backport-7.16, backport-8.0, v7.17.0, backport-7.17

#7085 [automation] update elastic stack version for testing 7.17.0-079761a0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7086 [automation] update libbeat and beats packaging
  NOTICE.txt
  elasticsearch/config_test.go
  go.mod
  go.sum
Labels: automation, backport-skip

#7079 Add app_logs to apmpackage.
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/app_logs/fields/base-fields.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_logs/manifest.yml
  apmpackage/apm/manifest.yml
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_enabled.approved.json
Labels: v7.16.3

#6940 docs: Update index-related config for 8.0
  changelogs/head.asciidoc
  docs/apm-breaking.asciidoc
  docs/cross-cluster-search.asciidoc
  docs/custom-index-template.asciidoc
  docs/how-to.asciidoc
  docs/ilm-how-to.asciidoc
  docs/ingest-pipelines.asciidoc
  docs/input-apm.asciidoc
  docs/legacy/breaking-changes.asciidoc
  docs/legacy/common-problems.asciidoc
  docs/legacy/configuration-process.asciidoc
  docs/legacy/configuration-rum.asciidoc
  docs/legacy/configuring-ingest.asciidoc
  docs/legacy/configuring.asciidoc
  docs/legacy/copied-from-beats/docs/command-reference.asciidoc
  docs/legacy/copied-from-beats/docs/howto/load-index-templates.asciidoc
  docs/legacy/copied-from-beats/docs/https.asciidoc
  docs/legacy/copied-from-beats/docs/template-config.asciidoc
  docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/legacy/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/legacy/data-ingestion.asciidoc
  docs/legacy/feature-roles.asciidoc
  docs/legacy/getting-started-apm-server.asciidoc
  docs/legacy/guide/apm-breaking-changes.asciidoc
  docs/legacy/guide/cross-cluster-search.asciidoc
  docs/legacy/ilm-reference.asciidoc
  docs/legacy/ilm.asciidoc
  docs/legacy/index.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading-to-datastreams.asciidoc
  docs/upgrading-to-integration.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1

#7106 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7107 docs: Add placeholder 7.17 upgrading content
  CHANGELOG.asciidoc
  changelogs/7.17.asciidoc
  docs/apm-breaking.asciidoc
  docs/release-notes.asciidoc
  docs/upgrading-to-717.asciidoc
  docs/upgrading-to-legacy.asciidoc
  docs/upgrading.asciidoc
Labels: Team:Docs, backport-skip

#7112 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7111 [automation] update elastic stack version for testing 8.0.0-6ce456eb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7121 [automation] update elastic stack version for testing 7.16.4-206b88b5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7123 Map `error.id` in error_logs data stream
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
Labels: backport-7.16, backport-8.0, backport-7.17

#7103 docs: Upgrade to 8.0
  CHANGELOG.asciidoc
  docs/apm-breaking.asciidoc
  docs/legacy/breaking-changes.asciidoc
  docs/legacy/getting-started-apm-server.asciidoc
  docs/legacy/guide/apm-breaking-changes.asciidoc
  docs/release-notes.asciidoc
  docs/upgrading-to-65.asciidoc
  docs/upgrading-to-70.asciidoc
  docs/upgrading-to-77.asciidoc
  docs/upgrading-to-8.x.asciidoc
  docs/upgrading-to-datastreams.asciidoc
  docs/upgrading-to-integration.asciidoc
  docs/upgrading-to-legacy.asciidoc
  docs/upgrading.asciidoc
Labels: Team:Docs, backport-8.0

#7117 docs: add 8.0.0rc2 release notes
  changelogs/8.0.asciidoc
Labels: Team:Docs, backport-8.0

#7119 docs: fix info API response
  docs/api-info.asciidoc
  docs/legacy/server-info.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0, backport-7.17

#7118 docs: add 7.17 upgrading instructions
  docs/upgrading-to-717.asciidoc
Labels: Team:Docs

#7100 chore: update branch filter
  .ci/jobs/update-beats-mbp.yml
Labels: ci, Team:Automation, backport-skip

#7099 [apmpackage] Add TBS enabled config option
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  systemtest/sampling_test.go
Labels: backport-skip

#7140 [automation] update elastic stack version for testing 7.16.4-1b320a84
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7142 [automation] update elastic stack version for testing 8.0.0-e2e78bad
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7143 Fix libbeat metrics replacement
  beater/beater.go
  beater/server_test.go
  systemtest/fleet_test.go
Labels: v8.0.0, v8.1.0, backport-8.0

#7145 [automation] update elastic stack version for testing 7.16.4-42a1f428
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7146 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#7148 [automation] update elastic stack version for testing 7.16.4-047be5da
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7149 [automation] update elastic stack version for testing 8.0.0-f8220c88
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7150 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
