Repository elastic/apm-server, pull requests merged in 2022-05, with the labels that each got.

#8012 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8014 [automation] update elastic stack version for testing 8.1.4-76569f3d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8016 [automation] update elastic stack version for testing 8.2.0-e7ad9ef0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8013 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8017 [automation] update elastic stack version for testing 7.17.4-ed667030
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7901 [docs] New APM troubleshooting / Update legacy version
  docs/api-events.asciidoc
  docs/common-problems.asciidoc
  docs/legacy/common-problems.asciidoc
  docs/legacy/events-api.asciidoc
  docs/legacy/getting-started-apm-server.asciidoc
  docs/legacy/high-availability.asciidoc
  docs/legacy/troubleshooting.asciidoc
  docs/troubleshoot-apm.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1, backport-8.2

#8022 docs: fix attributes
  docs/common-problems.asciidoc
  docs/legacy/common-problems.asciidoc
  docs/troubleshoot-apm.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1, backport-8.2

#8023 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8024 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8029 [automation] update elastic stack version for testing 8.1.4-1cdc80b6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8030 [automation] update elastic stack version for testing 8.2.0-56396fd0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8031 [automation] update elastic stack version for testing 7.17.4-9ca33e9a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8035 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8036 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8028 [automation] update elastic stack version for testing 8.3.0-0b6ea9f2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8011 benchmark: Add `index-benchmark-results` target
  Makefile
  go.make
  testing/benchmark/Makefile
  testing/benchmark/README.md
  tools/go.mod
  tools/go.sum
Labels: benchmarking, backport-skip, v8.3.0

#8037 [automation] update elastic stack version for testing 8.1.4-86899ed7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8039 [automation] update elastic stack version for testing 8.3.0-7f585873
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7998 ci: run the packaging only once
  .ci/packaging.groovy
  .ci/scripts/package-docker.sh
  .ci/scripts/package.sh
  .ci/scripts/push-docker.sh
  Jenkinsfile
Labels: Team:Automation, backport-8.3, backport-8.2, backport-7.17

#8044 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8046 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8047 [automation] update elastic stack version for testing 8.1.4-37d447ec
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7882 Send system and runtime metrics to the internal metrics data stream
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/dotnet_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/go_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/jvm_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/nodejs_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ruby_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/system_metrics.yml
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  changelogs/head.asciidoc
  main.go
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  model/modelprocessor/generate_internal_metrics.go
  model/modelprocessor/internal_metrics.go
  systemtest/approvals/TestApprovedMetrics.approved.json
Labels: backport-skip, v8.3.0

#8051 packaging: exclude the pipeline
  .ci/packaging.groovy
  .ci/scripts/Makefile
Labels: automation, backport-8.3, backport-8.2

#8058 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8060 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8059 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8062 [automation] update elastic stack version for testing 8.1.4-6c818705
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8061 [automation] update elastic stack version for testing 8.3.0-6ba9f710
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8063 [automation] update elastic stack version for testing 7.17.4-2fe5353f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8055 support `output.elasticsearch.max_requests`
  beater/beater.go
  changelogs/head.asciidoc
Labels: v8.3.0, backport-8.3

#8065 mount static geoip db into es container
  docker-compose.yml
  systemtest/containers.go
  testing/docker/elasticsearch/ingest-geoip/GeoLite2-ASN.mmdb
  testing/docker/elasticsearch/ingest-geoip/GeoLite2-City.mmdb
  testing/docker/elasticsearch/ingest-geoip/GeoLite2-Country.mmdb
Labels: backport-skip

#8005 Update to remove a workaround recommendation
  docs/open-telemetry.asciidoc
Labels: backport-skip

#8056 docs: add links to span type resources
  docs/data-model.asciidoc
Labels: Team:Docs, backport-8.2

#8069 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8070 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8071 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8072 [automation] update elastic stack version for testing 8.3.0-5c1ff35f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8073 [automation] update elastic stack version for testing 7.17.4-1ffd290e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8053 testing: Introduce `buildapm` command
  TESTING.md
  systemtest/apmservertest/command.go
  systemtest/cmd/buildapm/main.go
  systemtest/cmd/runapm/main.go
  systemtest/containers.go
Labels: benchmarking, backport-skip, v8.3.0

#8066 cancel server process context after timeout
  systemtest/apikeycmd_test.go
  systemtest/apmservertest/command.go
  systemtest/apmservertest/server.go
  systemtest/export_test.go
Labels: v8.3.0, backport-8.3

#8075 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8077 [automation] update elastic stack version for testing 8.3.0-d380914f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8078 [automation] update elastic stack version for testing 8.2.1-d6d75d75
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8079 [automation] update elastic stack version for testing 7.17.4-37e626ca
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7987 apmbench: Warm-up with specified agent number
  systemtest/benchtest/clients.go
  systemtest/benchtest/eventhandler/handler.go
  systemtest/benchtest/eventhandler/handler_test.go
  systemtest/benchtest/expvar.go
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  systemtest/go.mod
  testing/benchmark/Makefile
  testing/benchmark/terraform.tfvars.example
  testing/infra/terraform/modules/benchmark_executor/apmbench.tf
Labels: benchmarking, backport-skip, v8.3.0

#8080 mergify: Attempt auto-merge fix for beats-update
  .mergify.yml
Labels: backport-skip

#8076 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8083 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8082 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8085 [automation] update elastic stack version for testing 8.2.1-2eb01953
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8084 [automation] update elastic stack version for testing 8.3.0-53513548
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8081 processor: Avoid leaking labels between batches
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  changelogs/head.asciidoc
  processor/stream/processor.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
Labels: bug, v8.3.0, backport-8.2

#8089 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#8093 [automation] update elastic stack version for testing 8.2.1-91d7a53f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8092 [automation] update elastic stack version for testing 8.3.0-8ee1196f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8094 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8097 [automation] update elastic stack version for testing 8.3.0-b85385ff
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8096 [automation] update elastic stack version for testing 8.2.1-05a5ca87
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8098 [automation] update elastic stack version for testing 7.17.4-153c53bf
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8095 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8103 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8108 [automation] update elastic stack version for testing 8.2.1-3d12787c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8106 [automation] update elastic stack version for testing 8.3.0-19aba912
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8107 [automation] update elastic stack version for testing 7.17.4-191b5600
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8110 update failing regexp for 1.18
  beater/server_test.go
Labels: v8.3.0, backport-8.3

#8112 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8113 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8115 [automation] update elastic stack version for testing 8.2.1-736d131e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8116 [automation] update elastic stack version for testing 7.17.4-16fc7c23
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8117 [automation] update elastic stack version for testing 8.3.0-4149272f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8109 remove firehose endpoint
  beater/api/firehose/handler.go
  beater/api/firehose/handler_test.go
  beater/api/mux.go
  changelogs/head.asciidoc
Labels: v8.3.0, backport-8.3

#8122 make: Rename `go.make` to `go.mk`
  Makefile
  go.mk
  testing/benchmark/Makefile
Labels: backport-skip

#8125 systemtest: build apm-server with cgo disabled
  systemtest/apmservertest/command.go
Labels: backport-8.2, backport-7.17

#8130 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8131 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8133 [automation] update elastic stack version for testing 8.3.0-e4aa1f83
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8134 [automation] update elastic stack version for testing 7.17.4-3585da41
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8135 [automation] update elastic stack version for testing 8.2.1-8d9ffca9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8124 add timeout to http client
  systemtest/agentconfig_test.go
Labels: v8.3.0, backport-8.3, backport-8.2, backport-7.17

#7925 Backward compatibility with svc target and dest resource
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  changelogs/head.asciidoc
  docs/spec/rumv3/span.json
  docs/spec/rumv3/transaction.json
  docs/spec/v2/span.json
  model/modeldecoder/rumv3/model.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/span_test.go
  model/span.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  systemtest/approvals/TestCompressedSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport-skip

#8111 docs: add APM app API key instructions
  docs/images/apm-ui-api-key.png
  docs/legacy/sourcemap-api.asciidoc
  docs/secure-agent-communication.asciidoc
Labels: Team:Docs, backport-8.2

#8146 buildapm: Add `-cloud` bool flag
  TESTING.md
  systemtest/cmd/buildapm/main.go
  systemtest/containers.go
Labels: benchmarking, backport-skip, v8.3.0

#8148 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8120 apmbench: Remove `b.Error()` from BenchmarkAgent
  systemtest/cmd/apmbench/main.go
Labels: benchmarking, backport-skip, v8.3.0

#8150 [automation] update elastic stack version for testing 8.2.1-93582d09
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8151 [automation] update elastic stack version for testing 7.17.4-16f62393
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8138 apmbench: Adjust warmup timeout to account agents
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
Labels: benchmarking, backport-skip

#8149 [automation] update elastic stack version for testing 8.3.0-a55286cc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7924 Add support for target service in metric aggregation
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  changelogs/head.asciidoc
  docs/spec/v2/transaction.json
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/transaction.go
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: backport-skip

#8152 Prevent index failed precondition
  beater/beater.go
  beater/server_test.go
  beater/waitready.go
  elasticsearch/client.go
Labels: v8.3.0, backport-8.3, backport-8.2, backport-7.17

#8144 docs: Update delete and update by query examples
  docs/legacy/storage-management.asciidoc
  docs/manage-storage.asciidoc
Labels: Team:Docs, backport-8.2

#8143 docs: add and link to java agent cert docs
  docs/legacy/ssl-input-settings.asciidoc
Labels: Team:Docs, backport-8.2, backport-7.17

#7957 docs: 7.17.4 release notes
  changelogs/7.17.asciidoc
Labels: Team:Docs

#8121 mod: Update github.com/containerd/imgcrypt@v1.1.4
  go.mod
  go.sum
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#8127 release: Add release notes for 8.2.1
  changelogs/8.2.asciidoc
  changelogs/head.asciidoc
Labels: docs, backport-8.2

#8165 buildapm: Use correct vcsref, pull missing image
  systemtest/cmd/buildapm/main.go
  systemtest/containers.go
Labels: benchmarking, backport-skip, v8.3.0

#8132 Use modelindexer instead of libbeat ES output in tests
  beater/api/profile/convert.go
  beater/beater_test.go
  beater/beatertest/encode.go
  beater/integration_test.go
  beater/jaeger/grpc_test.go
  beater/server_test.go
  beater/tracing_test.go
  model/modelindexer/indexer_test.go
  model/modelindexer/modelindexertest/modelindexertest.go
  processor/otel/traces_test.go
  processor/stream/processor_test.go
Labels: backport-skip

#8168 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#8167 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8171 [automation] update elastic stack version for testing 8.3.0-d754f94f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8170 [automation] update elastic stack version for testing 8.2.1-54274789
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8169 [automation] update elastic stack version for testing 7.17.4-60cd01b1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8172 Update to elastic/beats@f30375cea889
  .go-version
  Dockerfile
  NOTICE.txt
  beater/config/config.go
  beater/config/config_test.go
  beater/http.go
  docs/version.asciidoc
  elasticsearch/config.go
  go.mod
  go.sum
  magefile.go
Labels: backport-skip

#8157 chore: added a preliminary benchmarks job definition
  .ci/jobs/apm-server-benckmarks-mbp.yml
Labels: automation, backport-skip

#8164 [docs] Lint all non-legacy docs for spelling, attributes
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.6.asciidoc
  changelogs/7.0.asciidoc
  changelogs/7.10.asciidoc
  changelogs/7.12.asciidoc
  changelogs/7.13.asciidoc
  changelogs/7.14.asciidoc
  changelogs/7.15.asciidoc
  changelogs/7.16.asciidoc
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  changelogs/7.5.asciidoc
  changelogs/7.6.asciidoc
  changelogs/7.7.asciidoc
  changelogs/7.9.asciidoc
  changelogs/8.0.asciidoc
  changelogs/8.1.asciidoc
  changelogs/8.2.asciidoc
  docs/agent-server-compatibility.asciidoc
  docs/api-config.asciidoc
  docs/api-metadata.asciidoc
  docs/api-metricset.asciidoc
  docs/apm-breaking.asciidoc
  docs/apm-components.asciidoc
  docs/apm-data-security.asciidoc
  docs/apm-distributed-tracing.asciidoc
  docs/apm-input-settings.asciidoc
  docs/apm-overview.asciidoc
  docs/apm-rum.asciidoc
  docs/apm-tune-elasticsearch.asciidoc
  docs/common-problems.asciidoc
  docs/cross-cluster-search.asciidoc
  docs/custom-index-template.asciidoc
  docs/data-model.asciidoc
  docs/data-streams.asciidoc
  docs/ilm-how-to.asciidoc
  docs/ingest-pipelines.asciidoc
  docs/input-apm.asciidoc
  docs/jaeger-integration.asciidoc
  docs/log-correlation.asciidoc
  docs/manage-storage.asciidoc
  docs/monitor.asciidoc
  docs/open-telemetry.asciidoc
  docs/overview.asciidoc
  docs/processing-performance.asciidoc
  docs/sampling.asciidoc
  docs/secure-agent-communication.asciidoc
  docs/shared/distributed-trace-receive/distributed-trace-receive.asciidoc
  docs/shared/distributed-trace-send/distributed-trace-send.asciidoc
  docs/shared/jaeger/jaeger.asciidoc
  docs/source-map-how-to.asciidoc
  docs/span-compression.asciidoc
  docs/tab-widgets/configure-agent-widget.asciidoc
  docs/tab-widgets/configure-server-widget.asciidoc
  docs/tab-widgets/install-agents-widget.asciidoc
  docs/troubleshoot-apm.asciidoc
  docs/upgrading-to-8.x.asciidoc
  docs/upgrading-to-integration.asciidoc
Labels: Team:Docs, backport-8.2

#8184 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8185 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8155 Allow indexing of empty service.{target, name}
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/service.go
  model/service_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
Labels: backport-skip

#8187 Update to elastic/beats@d38dadbcc2b3
  NOTICE.txt
  agentcfg/fetch.go
  agentcfg/fetch_test.go
  apmpackage/cmd/genpackage/main.go
  apmpackage/cmd/genpackage/pipelines.go
  apmpackage/cmd/genpackage/transform.go
  beater/api/config/agent/handler_test.go
  beater/config/config_test.go
  beater/config/kibana.go
  beater/jaeger/grpc_test.go
  go.mod
  go.sum
  kibana/connecting_client.go
  kibana/connecting_client_test.go
  kibana/kibanatest/kibana.go
  sourcemap/kibana_test.go
Labels: backport-skip

#8189 [automation] update elastic stack version for testing 8.2.1-539cf6f5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8190 [automation] update elastic stack version for testing 7.17.4-1170b674
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8188 [automation] update elastic stack version for testing 8.3.0-3a5a0cd2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8186 sampling: speed up TestStorageGC
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.2, backport-7.17

#8198 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8197 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8199 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8202 [automation] update elastic stack version for testing 8.3.0-bf0ad929
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8200 [automation] update elastic stack version for testing 7.17.4-1572020b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8201 [automation] update elastic stack version for testing 8.2.1-e97da867
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8142 ci: use orka
  .ci/scripts/build-darwin.sh
  .ci/scripts/test-darwin.sh
  Jenkinsfile
Labels: backport-8.3, backport-8.2, backport-7.17

#8175 all: Use `gomaxprocs` library to set GOMAXPROCS
  NOTICE.txt
  beater/beater.go
  go.mod
  go.sum
Labels: enhancement, backport-skip

#8206 [7.17] release: Bump version to `7.17.5`
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  cmd/version.go
Labels: backport-skip

#8211 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8210 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8209 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8214 [automation] update elastic stack version for testing 8.3.0-a2430aec
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8212 [automation] update elastic stack version for testing 8.2.1-f86dca4c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8213 [automation] update elastic stack version for testing 7.17.4-d3844d00
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8208 Collect apm-server memstats correctly from expvar
  systemtest/benchtest/main.go
Labels: bug, backport-skip

#8119 apmbench: Support multiple apm servers in cloud
  systemtest/benchtest/expvar.go
Labels: benchmarking, backport-skip, v8.3.0

#8207 docs: add 8.2.2 release notes
  changelogs/8.2.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.2

#8226 Enable backports to 8.3 via label
  .mergify.yml
Labels: backport-skip

#8230 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8231 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8232 cmd: don't override compression_level
  cmd/root.go
  cmd/root_test.go
Labels: v8.3.0, backport-8.3

#8233 sampling: allow 100% tail-based sampling
  changelogs/head.asciidoc
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/processor.go
Labels: v8.3.0, backport-8.3

#8237 dev_docs: add application metrics
  dev_docs/app_metrics.md
Labels: backport-skip

#8236 dev_docs: add trace metrics aggregation
  dev_docs/trace_metrics.md
Labels: backport-skip
