Repository elastic/apm-server, pull requests merged in 2022-10, with the labels that each got.

#9238 smoke: Use cURL `--fail-with-body` option
  testing/infra/terraform/modules/ec_deployment/scripts/index_shards.tftpl
  testing/smoke/lib.sh
Labels: enhancement, test, backport-skip

#9246 docs: remove included extension content
  docs/apm-mutating-webhook.asciidoc
  docs/aws-lambda-extension.asciidoc
  docs/integrations-index.asciidoc
Labels: Team:Docs, v8.5.0, backport-8.4, backport-8.5

#9253 docs: remove aws includes
  docs/aws-lambda-extension.asciidoc
  docs/integrations-index.asciidoc
Labels: Team:Docs, backport-7.16, backport-8.0, backport-8.1, backport-8.2, backport-7.17

#9257 [7.17] docs: remove aws includes (#9253)
  docs/aws-lambda-extension.asciidoc
  docs/features.asciidoc
  docs/integrations-index.asciidoc
Labels: backport

#9260 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9262 Revert "smoke: Use cURL `--fail-with-body` option"
  testing/infra/terraform/modules/ec_deployment/scripts/index_shards.tftpl
  testing/smoke/lib.sh
Labels: backport-skip

#9261 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9264 [automation] update elastic stack version for testing 8.4.3-5e0dd488
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9263 [automation] update elastic stack version for testing 8.5.0-49b2dce3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9267 test: improve Profiling, wait for gRPC server to be up
  systemtest/profiling_test.go
Labels: backport-8.5

#9259 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9272 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9273 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9277 [automation] update elastic stack version for testing 8.4.3-ff95b7c5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9276 [automation] update elastic stack version for testing 7.17.7-70d4ef7d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9274 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9254 [8.2] docs: remove aws includes (#9253)
  docs/aws-lambda-extension.asciidoc
  docs/integrations-index.asciidoc
Labels: backport

#9256 [8.0] docs: remove aws includes (#9253)
  docs/aws-lambda-extension.asciidoc
  docs/features.asciidoc
  docs/integrations-index.asciidoc
Labels: backport

#9255 [8.1] docs: remove aws includes (#9253)
  docs/aws-lambda-extension.asciidoc
  docs/integrations-index.asciidoc
Labels: backport

#9245 docs: remove otel logs beta label
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: Team:Docs, backport-8.4, backport-8.5

#9258 [7.16] docs: remove aws includes (#9253)
  docs/aws-lambda-extension.asciidoc
  docs/features.asciidoc
  docs/integrations-index.asciidoc
Labels: backport

#9252 docs: link to APM Attacher docs
  docs/apm-mutating-webhook.asciidoc
  docs/legacy/redirects.asciidoc
Labels: Team:Docs, backport-8.4, backport-8.5

#9293 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9292 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9298 [automation] update elastic stack version for testing 8.4.3-83e508e5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9291 Fix rally cluster setup
  .gitignore
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/rally_workers/README.md
  testing/infra/terraform/modules/rally_workers/main.tf
  testing/infra/terraform/modules/rally_workers/outputs.tf
  testing/infra/terraform/modules/rally_workers/variables.tf
Labels: backport-skip

#9294 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9302 ironbank: fix docker builder name
  packaging/ironbank/Dockerfile
Labels: bug, backport-7.17, backport-8.4, backport-8.5

#9309 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9311 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9315 [automation] update elastic stack version for testing 8.4.4-ac374c4b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9312 [automation] update elastic stack version for testing 7.17.7-f9849b81
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9320 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9319 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9321 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9325 [automation] update elastic stack version for testing 8.4.4-17ce02d0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9324 [automation] update elastic stack version for testing 8.6.0-7c9f25a9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9323 [automation] update elastic stack version for testing 7.17.7-3947c049
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9268 test: fix TestIntakeAsync/semaphore_size_default flaky test
  systemtest/intake_async_test.go
Labels: backport-8.5

#9270 apmbench: disable OTLP benchmarks
  systemtest/cmd/apmbench/main.go
Labels: backport-skip

#9248 feat: add global labels to service metrics
  changelogs/head.asciidoc
  systemtest/aggregation_test.go
  x-pack/apm-server/aggregation/labels/labels.go
  x-pack/apm-server/aggregation/labels/labels_test.go
  x-pack/apm-server/aggregation/servicemetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-skip, v8.6.0

#9327 fix: set error.id for OpenTelemetry exception span events
  changelogs/head.asciidoc
  internal/processor/otel/exceptions.go
  internal/processor/otel/exceptions_test.go
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: backport-8.5

#9330 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9329 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9331 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9290 docs: update span compression links
  docs/span-compression.asciidoc
Labels: Team:Docs, backport-8.4, backport-8.5

#9337 [automation] update elastic stack version for testing 8.4.4-221d2ff4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9336 [automation] update elastic stack version for testing 8.6.0-c49fac70
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9338 [automation] update elastic stack version for testing 7.17.7-32fc38cc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9332 ec_deployment: Add `drop_pipeline` variable
  testing/benchmark/main.tf
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/ec_deployment/.gitignore
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/scripts/drop_pipeline.tftpl
  testing/infra/terraform/modules/ec_deployment/variables.tf
  testing/infra/terraform/modules/rally_workers/README.md
Labels: enhancement, backport-skip

#9318 modelindexer: Run active in dedicated goroutine
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/server_test.go
  internal/model/modelindexer/indexer.go
  internal/model/modelindexer/indexer_test.go
  systemtest/fleet_test.go
Labels: enhancement, backport-skip, v8.6.0

#9343 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9342 [automation] update libbeat and beats packaging
  .go-version
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#9344 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9347 [automation] update elastic stack version for testing 8.4.4-5fbb5bd0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9345 [automation] update elastic stack version for testing 8.6.0-5a8d757d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9348 [automation] update elastic stack version for testing 8.5.0-09886b6e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9346 [automation] update elastic stack version for testing 7.17.7-8081bbcb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9247 Relocate libbeat output & instrumentation
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
  internal/beatcmd/locker_test.go
  internal/beatcmd/maxprocs.go
  internal/beatcmd/maxprocs_test.go
  internal/beatcmd/testcmd.go
  internal/beater/beater.go
  internal/beater/beater_test.go
  internal/beater/integration_test.go
  internal/beater/server_test.go
  internal/beater/tracing.go
  internal/beater/tracing_test.go
  internal/idxmgmt/supporter_factory.go
  internal/idxmgmt/supporter_factory_test.go
Labels: backport-skip

#9317 docs: update transaction metrics limit reached log message
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-skip

#9351 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9352 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9353 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9355 [automation] update elastic stack version for testing 8.6.0-40086bc7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9356 [automation] update elastic stack version for testing 8.4.4-1129f33b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9354 [automation] update elastic stack version for testing 8.5.0-fe2e6147
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9357 [automation] update elastic stack version for testing 7.17.7-a44998d0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9360 docs: add 8.5 release notes link and include statement
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
Labels: backport-8.5

#9365 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9364 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9368 [automation] update elastic stack version for testing 8.4.4-fdf1902b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9370 [automation] update elastic stack version for testing 7.17.7-40d7eba9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9362 docs: add 7.17.7 breaking change
  changelogs/7.17.asciidoc
Labels: docs

#9363 apmbench: Increase `waitInactiveTimeout` to `60s`
  systemtest/benchtest/main.go
Labels: enhancement, backport-skip, v8.6.0

#9371 Move config reloading to beatcmd
  cmd/apm-server/main.go
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
  internal/beatcmd/locker_test.go
  internal/beatcmd/reloader.go
  internal/beatcmd/reloader_test.go
  internal/beater/beater.go
  internal/beater/beater_test.go
  internal/beater/beatertest/output.go
  internal/beater/beatertest/server.go
  internal/beater/integration_test.go
  internal/beater/server.go
  internal/beater/server_test.go
  internal/beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationErrorsTxID.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationUnknownSpanType.approved.json
  internal/beater/tracing_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/root.go
  x-pack/apm-server/root_test.go
Labels: backport-skip, v8.6.0

#9374 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9375 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9378 [automation] update elastic stack version for testing 8.5.0-f8c98e5d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9379 [automation] update elastic stack version for testing 8.4.4-2db0c963
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9380 [automation] update elastic stack version for testing 7.17.7-e7a47621
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9381 beatcmd: make GOMAXPROCS test more robust
  internal/beatcmd/beat.go
  internal/beatcmd/maxprocs.go
  internal/beatcmd/maxprocs_test.go
Labels: backport-skip

#9376 Support string format for timestamp
  changelogs/head.asciidoc
  internal/model/modeldecoder/nullable/nullable.go
  internal/model/modeldecoder/nullable/nullable_test.go
Labels: backport-skip

#9349 Add ECS log files to the intake log endpoint
  changelogs/head.asciidoc
  docs/spec/v2/log.json
  internal/model/error.go
  internal/model/error_test.go
  internal/model/event.go
  internal/model/event_test.go
  internal/model/log.go
  internal/model/log_test.go
  internal/model/modeldecoder/generator/cmd/main.go
  internal/model/modeldecoder/generator/code.go
  internal/model/modeldecoder/generator/preprocessor.go
  internal/model/modeldecoder/rumv3/error_test.go
  internal/model/modeldecoder/rumv3/model_generated.go
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/error_test.go
  internal/model/modeldecoder/v2/log_test.go
  internal/model/modeldecoder/v2/metadata_test.go
  internal/model/modeldecoder/v2/model.go
  internal/model/modeldecoder/v2/model_generated.go
  internal/model/process.go
  internal/model/process_test.go
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationLogs.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/intake_log_test.go
  testdata/intake-v2/logs.ndjson
Labels: backport-skip

#9308 fix: recognize OpenTelemetry grpc spans generated by the Javascript SDK
  changelogs/head.asciidoc
  internal/processor/otel/traces.go
  internal/processor/otel/traces_test.go
Labels: backport-8.5

#9386 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9387 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9382 modelindexer: don't allow Close to be blocked
  internal/model/modelindexer/indexer.go
  internal/model/modelindexer/indexer_test.go
Labels: backport-skip

#9391 [automation] update elastic stack version for testing 8.4.4-93b2bfdf
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9390 [automation] update elastic stack version for testing 8.5.0-7c74e950
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9389 [automation] update elastic stack version for testing 7.17.7-f82fb944
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9397 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9396 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9395 Simplify Kibana client
  internal/agentcfg/fetch.go
  internal/agentcfg/fetch_test.go
  internal/beatcmd/beat.go
  internal/beatcmd/version.go
  internal/beater/api/config/agent/handler.go
  internal/beater/api/config/agent/handler_test.go
  internal/beater/api/mux.go
  internal/beater/beater.go
  internal/beater/checkintegration.go
  internal/beater/jaeger/grpc.go
  internal/beater/jaeger/grpc_test.go
  internal/beater/server.go
  internal/kibana/client.go
  internal/kibana/client_test.go
  internal/kibana/connecting_client.go
  internal/kibana/connecting_client_test.go
  internal/kibana/kibanatest/kibana.go
  internal/kibana/send_config.go
  internal/sourcemap/kibana.go
  internal/sourcemap/kibana_test.go
  internal/version/settings.go
Labels: backport-skip, v8.6.0

#9398 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9401 [automation] update elastic stack version for testing 8.4.4-e97ba82f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9403 [automation] update elastic stack version for testing 8.5.0-792499b4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9404 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9406 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9408 [automation] update elastic stack version for testing 7.17.7-55166c00
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9410 [automation] update elastic stack version for testing 8.6.0-055acc83
  docker-compose.yml
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
Labels: dependency, automation, backport-skip

#9415 [automation] update libbeat and beats packaging
  go.mod
  go.sum
Labels: automation, backport-skip

#9416 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9418 [automation] update elastic stack version for testing 8.6.0-baf193e8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9420 [automation] update elastic stack version for testing 8.4.4-4edb5c6b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9419 [automation] update elastic stack version for testing 8.5.0-754ef325
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9417 [automation] update elastic stack version for testing 7.17.7-60386d02
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9423 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9422 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9424 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9427 [automation] update elastic stack version for testing 8.4.4-9b801d60
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9425 [automation] update elastic stack version for testing 8.6.0-22d60ec9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9428 [automation] update elastic stack version for testing 7.17.7-e6ce36d2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9430 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9434 [automation] update elastic stack version for testing 8.4.4-46f2f222
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9433 [automation] update elastic stack version for testing 8.6.0-b8b35931
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9435 [automation] update elastic stack version for testing 7.17.7-0a02d958
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9429 Map RUM PerformanceResourceTiming fields
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  changelogs/head.asciidoc
  docs/spec/rumv3/error.json
  docs/spec/rumv3/span.json
  docs/spec/rumv3/transaction.json
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  internal/model/http.go
  internal/model/mapstr.go
  internal/model/modeldecoder/rumv3/model.go
  internal/model/modeldecoder/v2/model.go
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions-huge_traces.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport-skip, v8.6.0

#9437 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9421 Introduce Kustomize and Tilt
  .ci/bump-stack-version.sh
  Tiltfile
  dev_docs/TESTING.md
  testing/infra/k8s/base/kustomization.yaml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/base/stack/secret-basic-auth.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
  testing/infra/k8s/overlays/local/trial-license.yaml
Labels: backport-skip

#9443 [automation] update elastic stack version for testing 8.4.4-1ee39d03
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9442 [automation] update elastic stack version for testing 8.5.0-bdb74671
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9411 Fix time parsing format for timezone
  internal/model/modeldecoder/nullable/nullable.go
  internal/model/modeldecoder/nullable/nullable_test.go
Labels: backport-skip

#9439 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9438 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9393 modelindexer: Scale active indexers based on load
  changelogs/head.asciidoc
  dev_docs/ARCHITECTURE.md
  internal/beater/beater.go
  internal/beater/server_test.go
  internal/model/modelindexer/indexer.go
  internal/model/modelindexer/indexer_test.go
  systemtest/fleet_test.go
Labels: enhancement, backport-skip, v8.6.0

#9450 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9449 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9452 [automation] update elastic stack version for testing 8.6.0-a892f234
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9454 .ci: commit k8s changes in bump-stack-version
  .ci/bump-stack-version.sh
Labels: backport-skip

#9447 Unit tail-based sampling license check
  internal/beater/server_test.go
  systemtest/containers.go
  systemtest/sampling_test.go
Labels: backport-skip

#9455 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9456 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9460 [automation] update elastic stack version for testing 8.6.0-89d224d2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9459 [automation] update elastic stack version for testing 8.5.0-4028b295
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9461 [automation] update elastic stack version for testing 8.4.4-6eb63640
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9462 [automation] update elastic stack version for testing 7.17.8-d89bf16d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9446 Deprecate `apm-server apikey`
  changelogs/head.asciidoc
  docs/legacy/copied-from-beats/docs/command-reference.asciidoc
  docs/legacy/secure-communication-agents.asciidoc
  internal/beatcmd/apikey.go
  systemtest/apikeycmd_test.go
Labels: backport-skip

#9445 docs: fix environment variable name typo
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-7.17, backport-8.4, backport-8.5

#9471 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9473 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9474 [automation] update elastic stack version for testing 8.6.0-949a38d2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9476 [automation] update elastic stack version for testing 8.4.4-f3b8851a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9475 [automation] update elastic stack version for testing 8.5.0-f48cdca0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9359 Fix wrong punctuation for arguments in curl commands
  docs/source-map-how-to.asciidoc
Labels: backport-skip

#9472 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
