Repository elastic/apm-server, pull requests merged in 2022-11, with the labels that each got.

#9481 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9480 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9484 [automation] update elastic stack version for testing 8.6.0-26dc1164
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9483 [automation] update elastic stack version for testing 8.4.4-55734bd7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9316 poc: enable doc-value-only mappings for APM data streams
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/dotnet_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/go_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/jvm_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/nodejs_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ruby_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/system_metrics.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
Labels: backport-skip

#9478 packaging: fix /licenses in Docker images
  packaging/docker/Dockerfile
Labels: backport-8.5

#9491 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9492 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9493 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9494 [automation] update elastic stack version for testing 8.6.0-4765d2b0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9463 modelindexer: disable scale up when 429 > 1%
  changelogs/head.asciidoc
  internal/model/modelindexer/indexer.go
  internal/model/modelindexer/indexer_test.go
Labels: enhancement, backport-skip, v8.6.0

#9490 docs: add known issue for 8.5.0
  changelogs/8.5.asciidoc
Labels: Team:Docs, backport-8.5

#9496 Dockerfile: define the apm-server user
  changelogs/head.asciidoc
  packaging/docker/Dockerfile
Labels: backport-8.5

#9500 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9499 [automation] update libbeat and beats packaging
  .go-version
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#9501 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9503 [automation] update elastic stack version for testing 8.4.4-dcd4a95f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9502 [automation] update elastic stack version for testing 8.6.0-8a615646
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9506 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9458 Add {span,transaction}.representative_count fields
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  changelogs/head.asciidoc
  internal/beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationMinimalEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationUnknownSpanType.approved.json
  internal/model/span.go
  internal/model/span_test.go
  internal/model/transaction.go
  internal/model/transaction_test.go
  internal/processor/otel/test_approved/jaeger_sampling_rate.approved.json
  internal/processor/otel/test_approved/metadata_jaeger-no-language.approved.json
  internal/processor/otel/test_approved/metadata_jaeger-version.approved.json
  internal/processor/otel/test_approved/metadata_jaeger.approved.json
  internal/processor/otel/test_approved/span_jaeger_custom.approved.json
  internal/processor/otel/test_approved/span_jaeger_db.approved.json
  internal/processor/otel/test_approved/span_jaeger_http.approved.json
  internal/processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  internal/processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  internal/processor/otel/test_approved/span_jaeger_messaging.approved.json
  internal/processor/otel/test_approved/span_jaeger_subtype_component.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_custom.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_full.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_no_attrs.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_type_component.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_type_messaging.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_type_request.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_type_request_result.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationRumTransactions.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationSpanLinks.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeRUMV3Events.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestFleetIntegration.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: backport-skip, v8.6.0

#9508 [automation] update elastic stack version for testing 8.5.1-7fd6ffae
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9509 [automation] update elastic stack version for testing 7.17.8-1d146f89
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9507 [automation] update elastic stack version for testing 8.6.0-3f5f98b7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9358 beater: Set semaphore, modelindexer chan from mem
  changelogs/head.asciidoc
  internal/beater/api/intake/handler_test.go
  internal/beater/api/mux_intake_rum_test.go
  internal/beater/beater.go
  internal/beater/config/config.go
  internal/beater/config/config_test.go
  internal/beater/memlimit_cgroup.go
  internal/beater/memlimit_system.go
  internal/beater/server_test.go
  internal/beater/tracing.go
  internal/model/modelindexer/indexer.go
  internal/model/modelindexer/indexer_test.go
  systemtest/fleet_test.go
  systemtest/intake_async_test.go
Labels: enhancement, backport-skip, v8.6.0

#9514 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9515 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9518 [automation] update elastic stack version for testing 8.6.0-f20b7179
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9516 [automation] update elastic stack version for testing 8.5.1-2ceb7fad
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9517 [automation] update elastic stack version for testing 7.17.8-a281a566
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9512 Benchmark reporting: fixed Kibana request timezone and stack version
  .ci/scripts/download-png-from-kibana.sh
Labels: backport-skip

#9520 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9522 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9504 feat: mark custom metrics as doc-value-only
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  systemtest/metrics_test.go
Labels: backport-skip

#9525 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9526 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9527 [automation] update elastic stack version for testing 8.6.0-da453972
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9528 [automation] update elastic stack version for testing 8.5.1-2041424b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9519 [docs] Update link to agent monitoring docs
  docs/common-problems.asciidoc
Labels: docs, backport-8.5

#9532 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9533 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9535 [automation] update elastic stack version for testing 8.6.0-c9d1a5e9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9536 [automation] update elastic stack version for testing 8.5.1-6bdef2c7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9534 [automation] update elastic stack version for testing 7.17.8-e6d29314
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9537 populate date label/tag in terraform
  .ci/benchmarks.groovy
Labels: backport-skip

#9539 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9540 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9542 [automation] update elastic stack version for testing 8.5.1-1f91140d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9548 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9549 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9550 [automation] update elastic stack version for testing 8.5.1-d7343c55
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9551 [automation] update elastic stack version for testing 7.17.8-8be7042c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9546 beater/config: treat null agent config as empty
  changelogs/head.asciidoc
  internal/beater/config/agentconfig.go
  internal/beater/config/agentconfig_test.go
  internal/beater/config/config.go
  internal/beater/config/config_test.go
Labels: v8.6.0, backport-8.5, v8.5.2

#9553 ci: Populate `USER` variable with build id
  .ci/benchmarks.groovy
Labels: backport-skip

#9555 github: Add test plan template issue
  .github/ISSUE_TEMPLATE/test-plan.md
  dev_docs/RELEASES.md
Labels: backport-skip

#9552 .ci: only publish package to storage v2
  .ci/packaging.groovy
  .ci/scripts/Makefile
Labels: backport-skip

#9560 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9564 [automation] update elastic stack version for testing 8.5.1-49e04c16
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9562 [automation] update elastic stack version for testing 7.17.8-581ea684
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9561 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9558 Universal Profiling: implement custom ILM strategy for K/V data
  internal/beater/config/config_test.go
  internal/beater/config/profiling.go
  testing/docker/kibana/kibana.yml
  x-pack/apm-server/main.go
  x-pack/apm-server/profiling/collection_agent.pb.go
  x-pack/apm-server/profiling/collection_agent_grpc.pb.go
  x-pack/apm-server/profiling/collector.go
  x-pack/apm-server/profiling/constants.go
  x-pack/apm-server/profiling/ilm.go
  x-pack/apm-server/profiling/ilm_test.go
  x-pack/apm-server/profiling/libpf.go
Labels: backport-skip

#9569 bench: tear down the environment within the post-cleanup stage
  .ci/benchmarks.groovy
Labels: backport-skip

#9571 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9572 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9574 [automation] update elastic stack version for testing 7.17.8-e4279e1a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9575 ci: Disable failing benchmark report
  .ci/benchmarks.groovy
Labels: backport-skip

#9576 backport: Add 8.6 branch
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: Team:Automation, impact:critical, backport-skip, release

#9577 Benchmark CI: Returned version parameter to PNG POST URL
  .ci/benchmarks.groovy
  .ci/scripts/download-png-from-kibana.sh
Labels: backport-skip

#9582 systemtest: Fix `TestTransactionAggregation` test
  systemtest/approvals.go
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
Labels: flaky test, backport-8.6

#9578 Universal Profiling: Fix error logging
  x-pack/apm-server/profiling/collector.go
Labels: backport-8.6

#9589 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9590 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9583 sampling: Discard writes on full badger storage
  x-pack/apm-server/sampling/eventstorage/badger.go
  x-pack/apm-server/sampling/eventstorage/sharded.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
Labels: bug, v8.6.0, backport-8.5, v8.5.2, backport-8.6

#9580 testing/k8s: Set memory limit, deployment strategy
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: enhancement, backport-8.6

#9592 fix: replace _realpath_ with _readlink -f_
  Makefile
  testing/docker/elastic-agent/build.sh
Labels: backport-skip

#9600 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9603 [automation] update elastic stack version for testing 8.5.2-733d317b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9602 [automation] update elastic stack version for testing 7.17.8-ca244ec8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9607 systemtest: fix flaky TestProfiling test
  systemtest/profiling_test.go
Labels: backport-8.6

#9544 Adapt to Elastic Agent v2 protocol changes
  .go-version
  NOTICE.txt
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  changelogs/head.asciidoc
  docker-compose.yml
  docs/version.asciidoc
  go.mod
  go.sum
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
  internal/beatcmd/config.go
  internal/beatcmd/reloader.go
  internal/beatcmd/reloader_test.go
  internal/beater/config/fleet.go
  internal/beater/config/integration.go
  packaging/docker/Dockerfile
  systemtest/approvals/TestAgentConfig.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestServiceMetricsAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  systemtest/containers.go
  systemtest/fleet_test.go
  systemtest/metrics_test.go
  testing/docker/elastic-agent/Dockerfile
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
  x-pack/apm-server/main.go
Labels: backport-skip, v8.6.0

#9604 docker: fix file access for apm-server user
  changelogs/head.asciidoc
  packaging/docker/Dockerfile
Labels: v8.6.0, backport-8.5, backport-8.6, v8.5.3

#9605 infra/k8s: Add credentials as Kibana banner
  testing/infra/k8s/base/stack/kibana.yaml
Labels: enhancement, backport-skip

#9615 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9440 feat: set up automated smoke tests for supported Operating Systems
  .gitignore
  testing/smoke/lib.sh
  testing/smoke/supported-os/latest_apm_server.sh
  testing/smoke/supported-os/main.tf
  testing/smoke/supported-os/test.sh
Labels: backport-skip

#9616 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9614 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9621 [automation] update elastic stack version for testing 8.7.0-84b6e00d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9618 [automation] update elastic stack version for testing 8.6.0-afa9010f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9619 [automation] update elastic stack version for testing 8.5.2-13a22054
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9620 [automation] update elastic stack version for testing 7.17.8-c416a4cb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9617 Remove datastreams package
  internal/datastreams/constants.go
  internal/datastreams/servicename.go
  internal/datastreams/servicename_test.go
  internal/idxmgmt/supporter_factory.go
  internal/idxmgmt/supporter_factory_test.go
  internal/model/datastream.go
  internal/model/error.go
  internal/model/log.go
  internal/model/metricset.go
  internal/model/modelprocessor/datastream.go
  internal/model/modelprocessor/datastream_test.go
  internal/model/transaction.go
  internal/processor/otel/test_approved/span_jaeger_http.approved.json
  internal/processor/otel/test_approved/transaction_jaeger_full.approved.json
  internal/processor/otel/traces.go
  testdata/jaeger/batch_0.approved.json
  testdata/jaeger/batch_1.approved.json
Labels: backport-skip, v8.7.0

#9623 jjbb: smoke-tests on ESS and for supported OS
  .ci/jobs/apm-server-smoketests-ess-mbp.yml
  .ci/jobs/apm-server-smoketests-os-mbp.yml
  .ci/schedule-daily.groovy
  .ci/smoke-tests-ess.groovy
  README.md
Labels: backport-skip

#9625 compliance: Tag CSP resources according to policy
  testing/benchmark/main.tf
  testing/infra/terraform/modules/rally_workers/README.md
  testing/infra/terraform/modules/rally_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/tags/README.md
  testing/infra/terraform/modules/tags/header.md
  testing/infra/terraform/modules/tags/output.tf
  testing/infra/terraform/modules/tags/vars.tf
Labels: backport-skip

#9388 testing: use "self" for observability by default
  testing/benchmark/main.tf
  testing/cloud/main.tf
  testing/cloud/variables.tf
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/terraform.tf
  testing/infra/terraform/modules/ec_deployment/variables.tf
  testing/rally-cloud/main.tf
  testing/smoke/main.tf
Labels: backport-skip

#9626 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9627 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9629 benchmark: Fix merge tags source
  testing/benchmark/main.tf
Labels: backport-skip

#9630 [automation] update elastic stack version for testing 8.6.0-e72cd235
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9632 [automation] update elastic stack version for testing 8.5.2-c2e5a3f4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9646 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9647 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9652 [automation] update elastic stack version for testing 8.6.0-3747fc18
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9650 [automation] update elastic stack version for testing 8.7.0-c5c709bf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9651 [automation] update elastic stack version for testing 8.5.2-98bdbc90
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9639 8.5.2 release notes
  changelogs/8.5.asciidoc
  changelogs/head.asciidoc
Labels: Team:Docs, backport-8.6

#9661 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9664 [automation] update elastic stack version for testing 8.7.0-11ac5926
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9665 [automation] update elastic stack version for testing 8.6.0-742fd135
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9663 [automation] update elastic stack version for testing 8.5.3-760caed9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#9668 go.mod: exclude elastic-agent
  go.mod
  go.sum
Labels: backport-8.6

#9667 Logs intake fixes
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/log_test.go
  internal/model/modeldecoder/v2/model.go
  internal/model/modeldecoder/v2/model_generated.go
  internal/model/modelprocessor/groupingkey.go
  internal/model/modelprocessor/groupingkey_test.go
  testdata/intake-v2/logs.ndjson
Labels: test-plan, v8.6.0, backport-8.6

#9673 Add `request.id` to `span.context.http` intake
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  changelogs/head.asciidoc
  docs/spec/v2/span.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  internal/model/http.go
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/model.go
  internal/model/modeldecoder/v2/model_generated.go
  internal/model/modeldecoder/v2/span_test.go
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport-skip

#9674 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9675 [automation] update elastic stack version for testing 8.6.0-94ebec53
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9677 [automation] update elastic stack version for testing 8.7.0-d050210c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9678 [automation] update elastic stack version for testing 8.6.0-3e06249e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9681 Fixes for Elastic Agent v2 changes
  internal/beatcmd/reloader.go
  internal/beater/beater.go
Labels: test-plan, v8.6.0, backport-8.6

#9670 .ci: add SKIP_COMMIT option to bump-stack-version
  .ci/bump-stack-version.sh
Labels: backport-8.6

#9686 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9687 [automation] update elastic stack version for testing 8.6.0-c163a6d5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9680 apmbench: makefile with shellflags
  testing/benchmark/Makefile
Labels: backport-8.5, backport-8.6

#9691 Updated elastic-agent-client to v7.0.2-0.20221129150247-15881a8e64ef
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-8.6

#9695 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#9696 [automation] update elastic stack version for testing 8.6.0-ecfefdaf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#9698 actions: use go-version-file: .go-version
  .github/workflows/macos.yml
Labels: automation, Team:Automation, backport-7.17, backport-8.5, backport-8.6

#9693 docs: update “Reduce storage”
  docs/manage-storage.asciidoc
Labels: Team:Docs, backport-8.5, backport-8.6
