Repository elastic/apm-server, pull requests merged in 2022-06, with the labels that each got.

#8259 [automation] update elastic stack version for testing 7.17.5-366dc66d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8174 Collect aggregates from expvar metrices
  systemtest/benchtest/expvar/expvar.go
  systemtest/benchtest/expvar/metrics.go
  systemtest/benchtest/expvar/metrics_test.go
  systemtest/benchtest/flags.go
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#8266 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8267 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8272 [automation] update elastic stack version for testing 8.2.3-e78add13
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8271 [automation] update elastic stack version for testing 7.17.5-7c990f83
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8264 Fix agent metrics
  apmpackage/apm/data_stream/internal_metrics/fields/jvm_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/nodejs_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/system_metrics.yml
  model/modelprocessor/datastream.go
  model/modelprocessor/datastream_test.go
  model/modelprocessor/internal_metrics.go
Labels: v8.3.0, backport-8.3

#8275 apmbench: Add `BenchmarkAgentAll` benchmark
  systemtest/cmd/apmbench/main.go
Labels: benchmarking, backport-skip

#8281 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8280 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8284 [automation] update elastic stack version for testing 8.2.3-656a5d89
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8283 [automation] update elastic stack version for testing 8.4.0-df27a645
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8285 [automation] update elastic stack version for testing 7.17.5-a303ce60
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8221 modelindexer: Fix compressed `BytesTotal` metric
  beater/server_test.go
  changelogs/head.asciidoc
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer.go
  model/modelindexer/indexer_test.go
  systemtest/fleet_test.go
Labels: bug, backport-8.3

#8043 docs: Update data security
  docs/apm-data-security.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.2

#8292 Add tags field to internal_metrics data stream
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
Labels: v8.3.0, backport-8.3, backport-8.2

#8294 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8295 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8299 [automation] update elastic stack version for testing 8.2.3-f986a1ff
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8300 [automation] update elastic stack version for testing 8.3.0-378ebcca
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8301 [automation] update elastic stack version for testing 8.4.0-3525aaf7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8298 [automation] update elastic stack version for testing 7.17.5-f01fee6a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8145 [7.17] docs: how to delete other APM data
  docs/legacy/storage-management.asciidoc
Labels: Team:Docs, backport-skip

#8307 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8305 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8306 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8308 [automation] update elastic stack version for testing 8.3.0-9596ee28
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8310 [automation] update elastic stack version for testing 7.17.5-572a2baf
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8309 [automation] update elastic stack version for testing 8.4.0-42ce0eef
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8311 [automation] update elastic stack version for testing 8.2.3-def79f93
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7772 Add support for summary metrics
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  beater/otlp/grpc_test.go
  beater/otlp/http_test.go
  changelogs/head.asciidoc
  model/metricset.go
  model/metricset_test.go
  processor/otel/metrics.go
  processor/otel/metrics_test.go
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/otlp_test.go
Labels: backport-skip

#8317 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8316 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8287 Fix flaking test for TestAggregate
  systemtest/benchtest/expvar/metrics_test.go
Labels: backport-skip

#8320 [automation] update elastic stack version for testing 8.4.0-b8fce3f8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8318 [automation] update elastic stack version for testing 8.3.0-f530a93f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8319 [automation] update elastic stack version for testing 7.17.5-1c762894
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8312 docs: it’s a switch, not an upgrade
  docs/upgrading-to-integration.asciidoc
Labels: backport-7.16, backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-7.17

#8323 systemtest/cmd/sendotlp: add http/protobuf support
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/cmd/sendotlp/main.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/otlp_test.go
Labels: backport-skip

#8278 gomaxprocs: Use a ticker (30s) to set gomaxprocs
  beater/beater.go
  beater/beater_test.go
  beater/server_test.go
  changelogs/8.3.asciidoc
Labels: enhancement, test-plan, v8.3.0, backport-8.3

#8342 Don't vendor opentelemetry-collector docs
  internal/otel_collector/docs/design.md
  internal/otel_collector/docs/ga-roadmap.md
  internal/otel_collector/docs/images/design-collector-agent.png
  internal/otel_collector/docs/images/design-collector-service.png
  internal/otel_collector/docs/images/design-exporters.png
  internal/otel_collector/docs/images/design-pipelines.png
  internal/otel_collector/docs/images/design-processors.png
  internal/otel_collector/docs/images/design-receivers.png
  internal/otel_collector/docs/images/design-service-lifecycle.png
  internal/otel_collector/docs/images/opentelemetry-service-deployment-models.png
  internal/otel_collector/docs/images/zpages-example.png
  internal/otel_collector/docs/monitoring.md
  internal/otel_collector/docs/observability.md
  internal/otel_collector/docs/performance.md
  internal/otel_collector/docs/processing.md
  internal/otel_collector/docs/release.md
  internal/otel_collector/docs/roadmap.md
  internal/otel_collector/docs/security.md
  internal/otel_collector/docs/service-extensions.md
  internal/otel_collector/docs/troubleshooting.md
  internal/otel_collector/docs/vision.md
  script/vendor_otel.sh
Labels: backport-skip

#8344 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8345 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8346 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8347 [automation] update elastic stack version for testing 8.2.3-a46e98e9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8348 [automation] update elastic stack version for testing 8.4.0-3a09e26c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8349 [automation] update elastic stack version for testing 8.3.0-3c22a7f7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8350 [automation] update elastic stack version for testing 7.17.5-dae6f87e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8341 benchmark: Update `GOBENCH_DEFAULT_TAGS`, default cfg
  testing/benchmark/Makefile
  testing/benchmark/README.md
  testing/benchmark/outputs.tf
Labels: benchmarking, backport-skip

#8352 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8353 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8354 [automation] update elastic stack version for testing 8.3.0-158b3cba
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8355 [automation] update elastic stack version for testing 8.4.0-a27cbcfa
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8356 [automation] update elastic stack version for testing 8.2.3-303333da
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8357 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8358 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8359 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8360 [automation] update elastic stack version for testing 8.3.0-db012561
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8362 [automation] update elastic stack version for testing 8.2.3-4b95b897
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8361 [automation] update elastic stack version for testing 8.4.0-3bedeef4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8313 docs: add 8.2.3 release notes
  changelogs/8.2.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.2

#8366 docs: Remove extra space in link
  changelogs/8.2.asciidoc
Labels: docs, Team:Docs, backport-skip

#8363 Fix race condition while reading attributes in translate span
  changelogs/head.asciidoc
  processor/otel/traces.go
  processor/otel/traces_test.go
Labels: backport-skip

#8369 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8368 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8371 [automation] update elastic stack version for testing 8.4.0-7e67f5d9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8372 [automation] update elastic stack version for testing 8.3.0-e4e76686
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8180 WIP: chore: Benchmarks 2.0 Jenkins job
  .ci/benchmarks.groovy
  testing/benchmark/Makefile
  testing/benchmark/main.tf
  testing/benchmark/outputs.tf
  testing/benchmark/system-profiles/16GBx2zone.tfvars
  testing/benchmark/system-profiles/1GBx1zone.tfvars
  testing/benchmark/system-profiles/2GBx1zone.tfvars
  testing/benchmark/system-profiles/4GBx1zone.tfvars
  testing/benchmark/system-profiles/8GBx1zone.tfvars
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/variables.tf
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#8380 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8381 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8382 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8385 [automation] update elastic stack version for testing 8.4.0-40cff009
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8384 [automation] update elastic stack version for testing 8.3.0-460dc667
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8374 Upgrading Java agent attacher CLI to 1.32.0
  Makefile
  changelogs/head.asciidoc
Labels: backport-skip

#8387 CI: remove codecov references
  Jenkinsfile
  README.md
  codecov.yml
Labels: backport-skip

#8392 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8396 [automation] update elastic stack version for testing 8.3.0-fe62331f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8395 [automation] update elastic stack version for testing 8.2.4-d8d37990
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8397 [automation] update elastic stack version for testing 8.4.0-5e6770b1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8398 [automation] update elastic stack version for testing 8.2.4-4cc4fbfd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8393 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8394 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8373 Decode Faas fields from metricset model
  docs/spec/v2/metricset.json
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metricset_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
Labels: backport-skip, v8.4.0

#8391 spanmetrics: aggregate on span.name
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  changelogs/head.asciidoc
  docs/data-model.asciidoc
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: backport-skip, v8.4.0

#8402 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8403 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8401 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8405 [automation] update elastic stack version for testing 8.2.4-01ccaf06
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8404 [automation] update elastic stack version for testing 8.4.0-da5a1c6d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8334 Support service.target.{type, name} for OTLP events
  changelogs/head.asciidoc
  model/modeldecoder/v2/span_test.go
  processor/otel/test_approved/span_jaeger_db.approved.json
  processor/otel/test_approved/span_jaeger_http.approved.json
  processor/otel/test_approved/span_jaeger_http_status_code.approved.json
  processor/otel/test_approved/span_jaeger_https_default_port.approved.json
  processor/otel/test_approved/span_jaeger_messaging.approved.json
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
Labels: backport-skip

#8408 chore: Nightly schedule for benchmarks
  .ci/benchmarks.groovy
  .ci/schedule-daily.groovy
Labels: backport-skip

#8390 docs: describe resource attributes
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: Team:Docs, backport-8.3, backport-8.2, backport-7.17

#8412 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8414 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8417 [automation] update elastic stack version for testing 8.4.0-b13123ee
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8416 [automation] update elastic stack version for testing 8.2.4-698e06ec
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8400 Create lambda_metrics.yml
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/fields/faas_metrics.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  beater/test_approved_es_documents/TestPublishIntegrationMetricsets.approved.json
  model/modelprocessor/internal_metrics.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationMetricsets.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  testdata/intake-v2/metricsets.ndjson
Labels: backport-skip, v8.4.0

#8388 [TBS] Wait for ProcessBatch before stopping sampler
  x-pack/apm-server/main.go
Labels: backport-skip, v8.4.0

#8415 [automation] update elastic stack version for testing 8.3.0-75d7500e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8413 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8421 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8420 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8419 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8422 [automation] update elastic stack version for testing 8.3.0-6d4bb852
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8423 [automation] update elastic stack version for testing 8.2.4-b657c8f5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8427 [automation] update elastic stack version for testing 8.3.0-e0057e17
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8428 [automation] update elastic stack version for testing 8.2.4-589bdf37
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8432 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8436 [automation] update elastic stack version for testing 8.2.4-a34570b4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8435 [automation] update elastic stack version for testing 8.4.0-4fe26f2a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8376 terraform: Allow `integrations_server` resource
  testing/infra/terraform/modules/benchmark_executor/README.md
  testing/infra/terraform/modules/ec_deployment/.gitignore
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/infra/terraform/modules/ec_deployment/scripts/enable_expvar.tftpl
  testing/infra/terraform/modules/ec_deployment/scripts/secret_token.tftpl
  testing/infra/terraform/modules/ec_deployment/variables.tf
Labels: backport-skip, v8.4.0

#8434 Build apm-server binary for darwin/arm64
  Makefile
Labels: backport-skip

#8430 docs: Fix "upgrade" bug
  docs/upgrading-to-8.x.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.3, backport-8.1, backport-8.2

#8447 [7.16] docs: upgrade —> switch (#8431)
  changelogs/7.16.asciidoc
  docs/upgrading-to-integration.asciidoc
Labels: backport

#8450 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8451 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8456 [automation] update elastic stack version for testing 8.3.0-47d97929
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8457 testing/infra: fix expvar/pprof script
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/scripts/enable_expvar.tftpl
  testing/infra/terraform/modules/ec_deployment/variables.tf
Labels: backport-skip

#8454 [automation] update elastic stack version for testing 8.2.4-b5aa40e4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8429 Document APM Server support for OTLP/HTTP
  docs/images/ingest-flow.png
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: Team:Docs, backport-8.3

#8465 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8464 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8463 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8468 [automation] update elastic stack version for testing 8.3.0-3b390c7b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8469 [automation] update elastic stack version for testing 8.4.0-722a7d79
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8467 [automation] update elastic stack version for testing 7.17.5-781a81f2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8458 testing/smoke: Add initial smoke tests
  .gitignore
  Makefile
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/smoke/basic_upgrade/main.tf
  testing/smoke/basic_upgrade/test.sh
  testing/smoke/lib.sh
Labels: enhancement, backport-skip, v8.4.0

#8470 ci: archive bench output from the base_dir folder
  Jenkinsfile
Labels: backport-8.3, backport-7.17

#8472 make: Add BENCH_BENCHTIME and BENCH_COUNT to bench
  Makefile
Labels: backport-skip

#8460 [DOC] Removed references to the stack GS
  docs/legacy/getting-started-apm-server.asciidoc
  docs/legacy/tab-widgets/spin-up-stack.asciidoc
Labels: docs, backport-8.3, v8.4.0, v8.3.1

#8478 magefile: build x-pack/apm-server
  magefile.go
  systemtest/apmservertest/command.go
Labels: backport-skip, v8.4.0

#8459 [7.17] docs: add 7.17.5 release notes
  changelogs/7.17.asciidoc
Labels: Team:Docs

#8480 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8481 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8482 [automation] update elastic stack version for testing 8.4.0-210dd487
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8485 [automation] update elastic stack version for testing 8.3.0-fdf97a2e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8484 [automation] update elastic stack version for testing 8.2.4-b7bb3a0c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8483 [automation] update elastic stack version for testing 7.17.5-3896ff07
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8476 ci: honour BENCH_COUNT with 5 for the benchmark
  .ci/scripts/bench.sh
Labels: backport-8.3, backport-7.17

#8488 testing/ec_deployment: Fix apm_secret_token
  testing/benchmark/main.tf
  testing/infra/terraform/modules/ec_deployment/.gitignore
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/infra/terraform/modules/ec_deployment/scripts/secret_token.tftpl
  testing/infra/terraform/modules/ec_deployment/terraform.tf
Labels: backport-skip

#8492 Add initial support of smoketests in CI
  .ci/jobs/apm-server-smoketests-mbp.yml
  .ci/smoke-tests.groovy
Labels: backport-skip

#8502 [DOCS] Update xref to ES & Kibana docker install
  docs/legacy/guide/quick-start-overview.asciidoc
Labels: docs, Team:Docs, v8.3.1

#8515 docs: add 8.3.1 release notes
  changelogs/8.3.asciidoc
Labels: Team:Docs, backport-8.3
