Repository elastic/apm-server, pull requests merged in 2022-04, with the labels that each got.

#7765 [automation] update elastic stack version for testing 8.3.0-1ecd9720
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7764 [automation] update elastic stack version for testing 8.2.0-5d1042d1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7766 [automation] update elastic stack version for testing 8.1.2-ed029c28
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7763 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7762 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7761 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7767 [automation] update elastic stack version for testing 7.17.3-22be2d34
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7736 Add available bulk indexers metric
  beater/beater.go
  beater/server_test.go
  model/modelindexer/indexer.go
  model/modelindexer/indexer_test.go
  systemtest/fleet_test.go
Labels: v8.3.0, backport-8.3

#7453 testing: Enable stack monitoring local testing
  .gitignore
  TESTING.md
  docker-compose.yml
  script/common.bash
  script/requirements.txt
  systemtest/cmd/runapm/main.go
  systemtest/containers.go
  systemtest/fleet_test.go
  testing/docker/apm-server/agent-monitoring.sh
  testing/docker/metricbeat/apm-server.yml.tpl
  testing/docker/metricbeat/elasticsearch-xpack.yml
  testing/stack-monitoring.sh
Labels: test, backport-skip

#7769 docs: Update anchor link to new AWS Lambda docs
  docs/features.asciidoc
  docs/legacy/guide/opentracing.asciidoc
Labels: backport-8.1, backport-8.2

#7774 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7776 [automation] update elastic stack version for testing 8.2.0-f531236e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7778 [automation] update elastic stack version for testing 8.3.0-4cd86339
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7777 [automation] update elastic stack version for testing 7.17.3-42e5086c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7775 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7773 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#7780 dra: prepare staging
  .ci/packaging.groovy
Labels: automation, backport-8.3, backport-8.1, backport-8.2, backport-7.17

#7790 [automation] update elastic stack version for testing 8.1.3-4eb9bf7f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7791 [automation] update elastic stack version for testing 8.3.0-657f2d50
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7788 [automation] update elastic stack version for testing 7.17.3-206df1ed
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7793 packer_cache: restore permissions and ownership
  .ci/packer_cache.sh
Labels: automation, backport-skip

#7800 [automation] update elastic stack version for testing 8.1.3-c3f4b7e6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7799 [automation] update elastic stack version for testing 8.2.0-fdfc79e3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7802 [automation] update elastic stack version for testing 7.17.3-60b577ee
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7797 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#7798 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7796 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7801 [automation] update elastic stack version for testing 8.3.0-00f4f855
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7804 beater: fix pprof endpoints
  beater/api/mux.go
  beater/server_test.go
Labels: test-plan, v8.2.0, backport-8.2

#7544 docs: clarify API key user privileges
  docs/images/api-key-create.png
  docs/legacy/feature-roles.asciidoc
  docs/legacy/secure-communication-agents.asciidoc
  docs/secure-agent-communication.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.2, backport-7.17

#7811 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7812 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7814 [automation] update elastic stack version for testing 8.1.3-6f211282
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7815 [automation] update elastic stack version for testing 8.3.0-5bb6f468
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7816 [automation] update elastic stack version for testing 8.2.0-c56d8262
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7813 [automation] update elastic stack version for testing 7.17.3-0bbada2a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7809 stream/processor: Limit concurrent decoders to 200
  beater/api/intake/handler_test.go
  beater/api/mux.go
  beater/config/config.go
  beater/config/config_test.go
  changelogs/head.asciidoc
  processor/stream/benchmark_test.go
  processor/stream/processor.go
  processor/stream/processor_test.go
Labels: backport-8.0, v8.2.0, backport-8.1, backport-8.2, v8.1.2

#7737 mod: Update go.elastic.co/apm & modules to v2.0.0
  Makefile
  NOTICE.txt
  beater/api/config/agent/handler.go
  beater/api/config/agent/handler_test.go
  beater/auth/authenticator_test.go
  beater/beater.go
  beater/middleware/log_middleware.go
  beater/middleware/log_middleware_test.go
  beater/server.go
  beater/waitready.go
  elasticsearch/client.go
  go.mod
  go.sum
  kibana/connecting_client.go
  model/modelindexer/indexer.go
  model/modelindexer/indexer_test.go
  processor/stream/processor.go
  publish/pub.go
  publish/pub_test.go
  systemtest/aggregation_test.go
  systemtest/apmservertest/filter.go
  systemtest/apmservertest/server.go
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/benchtest/clients.go
  systemtest/benchtest/main.go
  systemtest/errorgrouping_test.go
  systemtest/fleet_test.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/huge_traces_test.go
  systemtest/intake.go
  systemtest/logging_test.go
  systemtest/metrics_test.go
  systemtest/sampling_test.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
  x-pack/apm-server/main_test.go
Labels: enhancement, dependency, backport-skip, v8.3.0

#7829 [automation] update elastic stack version for testing 8.2.0-4df380a5
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7828 [automation] update elastic stack version for testing 8.1.3-25093d2a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7827 [automation] update elastic stack version for testing 8.3.0-76e0128f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7830 [automation] update elastic stack version for testing 7.17.3-2d046908
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7825 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7824 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7826 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7834 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7833 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7835 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7848 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7849 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7850 [automation] update elastic stack version for testing 8.1.3-9689383f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7851 [automation] update elastic stack version for testing 8.3.0-2c8f9574
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7852 [automation] update elastic stack version for testing 7.17.3-860249fc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7836 [automation] update elastic stack version for testing 8.2.0-bcbc1a13
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7857 [8.1] Add `8.1.3` release notes
  changelogs/8.1.asciidoc
Labels: backport-skip

#7859 [main] [8.1] Add `8.1.3` release notes (#7857)
  changelogs/8.1.asciidoc
Labels: backport, backport-8.2

#7691 dev_docs: add rally doc
  dev_docs/rally.md
Labels: backport-skip

#7706 Record plaintext stack traces as error.stack_trace
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  changelogs/head.asciidoc
  model/error.go
  model/error_test.go
  model/modeldecoder/rumv3/error_test.go
  model/modeldecoder/v2/error_test.go
  processor/otel/exceptions.go
  processor/otel/exceptions_test.go
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/otlp_test.go
Labels: backport-skip, v8.3.0

#7867 [automation] update elastic stack version for testing 8.2.0-a99722cc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7866 [automation] update elastic stack version for testing 8.1.3-f8a17b61
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7865 [automation] update elastic stack version for testing 7.17.3-b688e1c0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7862 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7863 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7864 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7877 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7876 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7880 [automation] update elastic stack version for testing 8.2.0-39d3fe7f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7878 [automation] update elastic stack version for testing 8.1.3-bb164e02
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7881 [automation] update elastic stack version for testing 8.3.0-4be61f32
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7879 [automation] update elastic stack version for testing 7.17.3-d599ee07
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7874 dev_docs: add tail-based sampling doc
  dev_docs/tbs.md
Labels: backport-skip

#7891 [automation] update elastic stack version for testing 8.2.0-edf55ea1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7889 [automation] update elastic stack version for testing 8.3.0-55ba6f37
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7890 [automation] update elastic stack version for testing 8.1.3-5c80e943
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7892 [automation] update elastic stack version for testing 7.17.3-a0d290fb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7898 [automation] update elastic stack version for testing 8.2.0-c65cb8e3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7896 [automation] update elastic stack version for testing 8.1.3-28740185
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7899 [automation] update elastic stack version for testing 8.3.0-c655cda8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7895 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7894 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7885 Updated link to the new tag with the update
  docs/open-telemetry.asciidoc
Labels: backport-skip

#7897 [automation] update elastic stack version for testing 7.17.3-feda78d8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7904 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7903 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7906 [automation] update elastic stack version for testing 8.2.0-3a7e2f99
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7905 [automation] update elastic stack version for testing 8.1.3-2a8b1f31
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7870 Extend ingest API to accept info about target service
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  changelogs/head.asciidoc
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/transaction_test.go
  model/service.go
  model/service_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  testdata/intake-v2/spans.ndjson
Labels: backport-skip

#7794 Fix typo in {span,transaction}.service.origin.id
  docs/spec/v2/error.json
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  model/modeldecoder/v2/model.go
Labels: backport-8.2

#7873 model: remove context from APMEvent.BeatEvent()
  model/apmevent.go
  model/apmevent_test.go
  model/batch.go
  model/error_test.go
  model/host_test.go
  model/metricset_test.go
  model/modelindexer/indexer.go
  model/span_test.go
  model/transaction_test.go
Labels: backport-skip

#7917 [automation] update elastic stack version for testing 8.1.3-0c4e7b42
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7915 [automation] update elastic stack version for testing 8.2.0-a7e9513d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7918 [automation] update elastic stack version for testing 7.17.3-b148b9ca
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7914 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7912 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7929 [automation] update elastic stack version for testing 8.2.0-000e1c18
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7930 [automation] update elastic stack version for testing 7.17.3-e9aee937
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7911 docs: Update `logging.files.permissions` to consider umask
  docs/legacy/copied-from-beats/docs/loggingconfig.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.2, backport-7.17

#7927 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7909 docs: Add sample APM documents
  docs/data-model.asciidoc
  docs/data-streams.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.2

#7944 [automation] update elastic stack version for testing 8.2.0-c47183cf
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7945 [automation] update elastic stack version for testing 8.1.4-4911e5d4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7943 [automation] update elastic stack version for testing 7.17.4-51efa5cc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7946 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7947 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7952 [automation] update elastic stack version for testing 8.2.0-14a8abdc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7950 [automation] update elastic stack version for testing 8.1.4-bc369beb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7923 ci: split dra meta-stage in two stages
  .ci/packaging.groovy
Labels: backport-8.3, backport-8.1, backport-8.2, backport-7.17

#7961 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7959 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7963 [automation] update elastic stack version for testing 8.1.4-96de35ab
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7964 [automation] update elastic stack version for testing 7.17.4-073e030e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7962 [automation] update elastic stack version for testing 8.2.0-63f66f47
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7900 Automate apmpackage publishing to package-storage (snapshot)
  .ci/packaging.groovy
  .ci/scripts/Makefile
Labels: backport-8.3, backport-8.2

#7926 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
  publish/pub_test.go
Labels: automation, backport-skip

#7966 benchmark: Adds TF modules, benchmark workspace
  .gitignore
  Makefile
  testing/benchmark/Makefile
  testing/benchmark/README.md
  testing/benchmark/main.tf
  testing/benchmark/outputs.tf
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/benchmark_executor/README.md
  testing/infra/terraform/modules/benchmark_executor/apmbench.tf
  testing/infra/terraform/modules/benchmark_executor/header.md
  testing/infra/terraform/modules/benchmark_executor/instance.tf
  testing/infra/terraform/modules/benchmark_executor/outputs.tf
  testing/infra/terraform/modules/benchmark_executor/variables.tf
  testing/infra/terraform/modules/ec_deployment/.gitignore
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/header.md
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/infra/terraform/modules/ec_deployment/scripts/enable_expvar.tftpl
  testing/infra/terraform/modules/ec_deployment/terraform.tf
  testing/infra/terraform/modules/ec_deployment/variables.tf
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: enhancement, benchmarking, backport-skip, v8.3.0

#7919 docs: Add initial benchmarking 2.0 docs
  TESTING.md
Labels: docs, backport-skip, v8.3.0

#7977 [automation] update elastic stack version for testing 8.1.4-483e60fd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7978 [automation] update elastic stack version for testing 8.2.0-bdd1c93d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7973 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7972 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7971 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#7979 [automation] update elastic stack version for testing 7.17.4-a30db1f9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7975 Various improvements to sendotlp
  systemtest/cmd/sendotlp/main.go
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#7956 docs: 8.2.0 release notes
  CHANGELOG.asciidoc
  changelogs/8.2.asciidoc
  changelogs/head.asciidoc
  docs/apm-breaking.asciidoc
Labels: backport-8.2

#7869 Document exporting Otel Metrics and Logs
  docs/open-telemetry.asciidoc
Labels: docs, backport, backport-8.1, backport-8.2

#7990 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7989 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7991 [automation] update elastic stack version for testing 8.2.0-8b4cfac3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7974 Allow benchmarks to specify max rate limit for events
  TESTING.md
  systemtest/benchtest/clients.go
  systemtest/benchtest/eventhandler/handler.go
  systemtest/benchtest/eventhandler/handler_test.go
  systemtest/benchtest/flags.go
  systemtest/benchtest/main.go
  systemtest/cmd/apmbench/main.go
  systemtest/go.mod
Labels: backport-skip

#7982 ci: use downstream pattern
  .ci/packaging.groovy
  Jenkinsfile
Labels: backport-8.3, backport-8.1, backport-8.2, backport-7.17

#7997 ci: use changeset
  .ci/packaging.groovy
Labels: backport-8.1, backport-8.2, backport-7.17

#7988 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8003 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8004 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8002 Add pprof_enabled config option
  apmpackage/apm/agent/input/template.yml.hbs
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
Labels: backport-skip

#8008 [automation] update elastic stack version for testing 8.2.0-2c25c9de
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8006 [automation] update elastic stack version for testing 8.1.4-7b3e4fd0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8009 [automation] update elastic stack version for testing 7.17.4-40d3b33d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8010 benchmark tf: Allow setting individual image tags
  testing/benchmark/Makefile
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/variables.tf
Labels: benchmarking, backport-skip, v8.3.0
