Repository elastic/apm-server, pull requests merged in 2022-03, with the labels that each got.

#7420 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7422 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7424 [automation] update elastic stack version for testing 8.2.0-bdf2ad74
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7425 [automation] update elastic stack version for testing 7.17.1-bf42f386
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7421 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7423 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7391 docs: Remove coming tag for 8.0.1
  changelogs/8.0.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1

#7434 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7435 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7437 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7439 [automation] update elastic stack version for testing 8.2.0-43df679f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7436 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7445 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7448 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7447 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7452 [automation] update elastic stack version for testing 7.17.2-e8098595
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7460 [automation] update elastic stack version for testing 8.0.2-ae36dda7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7454 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7455 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7457 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7428 modelindexer: Report all Stack Monitoring metrics
  beater/beater.go
  beater/server_test.go
  changelogs/head.asciidoc
  model/modelindexer/indexer.go
  model/modelindexer/indexer_test.go
  systemtest/containers.go
  systemtest/fleet_test.go
Labels: bug, backport-7.x, backport-8.0, v8.2.0, backport-8.1

#7442 Add X-Elastic-Product-Origin header to es requests
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer_test.go
Labels: v8.2.0, backport-8.2

#7458 [automation] update elastic stack version for testing 8.2.0-190af159
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7472 [automation] update elastic stack version for testing 8.2.0-a12f7069
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7468 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7471 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7474 [automation] update elastic stack version for testing 8.0.2-901e2b50
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7470 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7473 [automation] update elastic stack version for testing 8.1.0-52a8d1d4
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7467 Clean up apmpackage changelog.yml
  apmpackage/apm/changelog.yml
Labels: backport-skip

#7299 docs: Add APM-defined metrics to data model guide
  docs/data-model.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1

#7479 [docs] Fix images and link to input settings
  docs/apm-components.asciidoc
  docs/input-apm.asciidoc
  docs/legacy/guide/apm-doc-directory.asciidoc
  docs/legacy/guide/distributed-tracing.asciidoc
  docs/legacy/guide/trace-sampling.asciidoc
  docs/secure-agent-communication.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1

#7486 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7485 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7484 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7483 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7478 [8.1] 8.1.0 release notes
  CHANGELOG.asciidoc
  changelogs/8.0.asciidoc
  changelogs/8.1.asciidoc
  changelogs/head.asciidoc
  docs/apm-breaking.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, backport-8.2

#7480 docs: document central config troubleshooting
  docs/legacy/common-problems.asciidoc
Labels: Team:Docs, backport-8.0, backport-8.1, backport-7.17

#7317 docs: Tail-based sampling
  docs/apm-input-settings.asciidoc
  docs/images/dt-sampling-example-1.png
  docs/images/dt-sampling-example-2.png
  docs/images/dt-sampling-example-3.png
  docs/images/dt-sampling-example.png
  docs/input-apm.asciidoc
  docs/legacy/guide/trace-sampling.asciidoc
  docs/sampling.asciidoc
Labels: Team:Docs, backport-8.1, backport-8.2

#7493 docs: Cherry pick 8.1 release notes to main
  CHANGELOG.asciidoc
  changelogs/8.0.asciidoc
  changelogs/8.1.asciidoc
  changelogs/head.asciidoc
  docs/apm-breaking.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, backport-skip

#7492 Better documentation of OpenTelemetry logs support
  docs/legacy/guide/opentelemetry-elastic.asciidoc
  docs/open-telemetry.asciidoc
Labels: backport-8.0, backport-8.1

#7501 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7499 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7498 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7416 benchmark: Introduce new binary `intake-receiver`
  .gitignore
  Makefile
  cmd/intake-receiver/README.md
  cmd/intake-receiver/go.mod
  cmd/intake-receiver/go.sum
  cmd/intake-receiver/main.go
  cmd/intake-receiver/main_test.go
  cmd/intake-receiver/version.go
  script/intake-receiver-version.sh
Labels: benchmarking, backport-skip

#7500 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7375 ci: add windows-2022 stage, support nightlies for all the windows and label/command on a PR basis
  .ci/schedule-daily.groovy
  Jenkinsfile
Labels: Team:Automation, backport-8.0, backport-8.1, ci:windows

#7510 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7512 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7509 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7511 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7518 [automation] update elastic stack version for testing 8.1.1-b9a6c108
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7522 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7521 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7519 [automation] update elastic stack version for testing 8.2.0-63265ec9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7524 [automation] update elastic stack version for testing 8.1.1-da392dcd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7525 [automation] update elastic stack version for testing 7.17.2-c18736fc
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7523 [automation] update elastic stack version for testing 8.2.0-d02c907a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7526 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7505 [Docs - OpenTelemetry] Document limitation on OTLP/HTTP not being supported
  docs/open-telemetry.asciidoc
Labels: backport-7.x, backport-8.0, backport-8.1

#7399 Removed `observer.version_major`
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/cmd/genpackage/pipelines.go
  changelogs/head.asciidoc
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/spans.json
  docs/data/elasticsearch/generated/transactions.json
  docs/data/elasticsearch/metricset.json
  docs/legacy/fields.asciidoc
  systemtest/approvals.go
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestApprovedMetrics/data_streams_disabled.approved.json
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
  systemtest/approvals/TestFleetIntegration.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/approvals/TestOTLPGRPCTraces/data_streams_disabled.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestRUMXForwardedFor/data_streams_disabled.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestSourcemapUploadInvalidElasticsearchConfig.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
Labels: backport-skip

#7535 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7538 [automation] update elastic stack version for testing 8.1.1-2d188131
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7537 [automation] update elastic stack version for testing 8.2.0-fee3b8d2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7539 [automation] update elastic stack version for testing 7.17.2-8be09371
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7533 Fix modelindexer benchmarks
  go.mod
  model/modelindexer/indexer_test.go
Labels: backport-8.1

#7534 [automation] update libbeat and beats packaging
  NOTICE.txt
  beater/beater.go
  beater/server_test.go
  go.mod
  go.sum
Labels: automation, backport-skip

#7545 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7546 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7547 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7550 [automation] update elastic stack version for testing 7.17.2-2208f979
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7548 [automation] update elastic stack version for testing 8.1.1-31faf00b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7549 [automation] update elastic stack version for testing 8.2.0-9bac538c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7552 Update module deps
  go.mod
  go.sum
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-8.1

#7551 systemtest: set min TLS version to 1.2
  systemtest/apmservertest/server.go
Labels: backport-8.0, backport-8.1, backport-7.17

#7562 [automation] update elastic stack version for testing 8.1.1-9bb65a23
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7563 [automation] update elastic stack version for testing 7.17.2-8f7db3a8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7560 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7558 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7561 [automation] update elastic stack version for testing 8.2.0-ff67d7b8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7531 jjbb: Daily Releasable Artifacts pipeline
  .ci/jobs/apm-server-package-mbp.yml
Labels: backport-skip

#7553 Add span links to intake v2
  changelogs/head.asciidoc
  docs/spec/v2/span.json
  docs/spec/v2/transaction.json
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/model.go
  model/modeldecoder/v2/model_generated.go
  model/modeldecoder/v2/model_test.go
  model/modeldecoder/v2/span_test.go
  model/modeldecoder/v2/transaction_test.go
  processor/stream/processor_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationSpanLinks.approved.json
  testdata/intake-v2/span-links.ndjson
Labels: backport-skip, v8.2.0

#7559 [automation] update libbeat and beats packaging
  NOTICE.txt
  beater/beater.go
  beater/server_test.go
  go.mod
  go.sum
Labels: automation, backport-skip

#7570 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7571 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7573 [automation] update elastic stack version for testing 8.1.1-da22c151
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7572 [automation] update elastic stack version for testing 8.2.0-82b803a1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7569 ci: remove APM Integration Tests stage
  Jenkinsfile
Labels: ci, backport-8.0, backport-8.1, backport-7.17

#7574 [automation] update elastic stack version for testing 7.17.2-15b5bc7a
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7530 ci: Daily Releasable Artifacts pipeline
  .ci/packaging.groovy
  .ci/packer_cache.sh
  .ci/scripts/release-manager.sh
Labels: backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7444 Add `source.nat.ip`
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  beater/api/mux.go
  beater/interceptors/metadata.go
  beater/interceptors/metadata_test.go
  beater/otlp/clientmetadata.go
  beater/otlp/clientmetadata_test.go
  beater/request/context.go
  beater/request/context_test.go
  beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  changelogs/head.asciidoc
  model/apmevent_test.go
  model/modeldecoder/rumv3/metadata_test.go
  model/modeldecoder/v2/decoder.go
  model/modeldecoder/v2/metadata_test.go
  model/modeldecoder/v2/transaction_test.go
  model/source.go
  processor/otel/traces.go
  processor/otel/traces_test.go
  processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
Labels: v8.2.0, backport-8.2

#7585 ci: -SNAPSHOT suffix is required
  .ci/scripts/release-manager.sh
Labels: automation, Team:Automation, backport-skip

#7565 Create developer docs
  dev_docs/otel.md
  systemtest/approvals/TestOTLPGRPCMetrics.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/cmd/sendotlp/README.md
  systemtest/cmd/sendotlp/main.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/otlp_test.go
Labels: backport-skip

#7576 magefile: fix and clean up packaging
  changelogs/head.asciidoc
  docs/legacy/copied-from-beats/docs/repositories.asciidoc
  magefile.go
Labels: backport-skip, v8.2.0

#7592 [automation] update elastic stack version for testing 7.17.2-3b3b663d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7587 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7588 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7589 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7590 [automation] update elastic stack version for testing 8.2.0-5cc993c1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7591 [automation] update elastic stack version for testing 8.1.1-0d572bb7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7586 dra: retry docker pull
  .ci/scripts/release-manager.sh
Labels: backport-8.0, backport-8.1, backport-7.17

#7567 Always set timestamp on APMEvents for incoming http requests
  beater/api/mux.go
  beater/api/mux_test.go
  changelogs/8.1.asciidoc
  changelogs/head.asciidoc
Labels: backport-8.1

#7601 docs: add 8.1.1 release notes
  changelogs/8.1.asciidoc
Labels: Team:Docs, backport-8.1

#7608 [automation] update elastic stack version for testing 7.17.2-81597e21
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7603 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7596 ci: packaging pipeline should not notify build status in github comments
  .ci/packaging.groovy
Labels: backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7618 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#7617 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7609 Fix asciidoc hyperlink syntax
  docs/open-telemetry.asciidoc
Labels: backport-8.0, backport-8.1, backport-7.17

#7607 [automation] update elastic stack version for testing 8.1.1-c72e1d1e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7602 [automation] update libbeat and beats packaging
  NOTICE.txt
  beater/beater.go
  beater/server_test.go
  go.mod
  go.sum
Labels: automation, backport-skip

#7620 [automation] update elastic stack version for testing 8.2.0-4509f321
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7624 model/modelindexer: close gzip writer
  changelogs/head.asciidoc
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer_test.go
Labels: bug, v8.1.0, v8.2.0, backport-8.1

#7627 [8.1] Add X-Elastic-Product-Origin header to es requests (#7442)
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer_test.go
Labels: backport

#7629 [8.1] model/modelindexer: close gzip writer (#7624)
  changelogs/head.asciidoc
  model/modelindexer/bulk_indexer.go
  model/modelindexer/indexer_test.go
Labels: backport

#6731 Introduce new Rally track and tooling
  Makefile
  magefile.go
  rally/.gitignore
  rally/README.md
  rally/_tools/fetch_data.py
  rally/_tools/prepare.py
  rally/_tools/requirements.txt
  rally/challenges/default.json
  rally/gencorpora/api.go
  rally/gencorpora/go.mod
  rally/gencorpora/go.sum
  rally/gencorpora/main.go
  rally/index.json
  rally/operations/default.json
  rally/track.json
  script/cat_bulk.py
  script/requirements.txt
Labels: v8.0.0, backport-8.0

#7638 Update go.mod
  NOTICE.txt
  go.mod
  go.sum
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#7640 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7641 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7644 [automation] update elastic stack version for testing 8.1.2-2393b0c1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7643 Update magefile for universal Darwin binaries
  magefile.go
Labels: backport-skip

#7642 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7645 [automation] update elastic stack version for testing 7.17.2-1941719d
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7636 dra: enforce version
  .ci/scripts/release-manager.sh
Labels: backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7650 make: fix get-version with space
  Makefile
Labels: backport-skip

#7598 [apmpackage] add quotes around {{this}}
  apmpackage/apm/agent/input/template.yml.hbs
Labels: v8.2.0, backport-8.1, backport-7.17

#7631 dra: run release-manager if branch is available
  .ci/packaging.groovy
Labels: backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7649 modelindexer: Reduce locking on flushActive
  changelogs/head.asciidoc
  model/modelindexer/indexer.go
Labels: bug, backport-8.0, v8.2.0, backport-8.1, backport-8.2, backport-7.17

#7664 docs: update aws-lambda-extension.asciidoc
  docs/aws-lambda-extension.asciidoc
Labels: Team:Docs, backport-8.1

#7669 [automation] update elastic stack version for testing 8.1.2-5d446358
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7670 [automation] update elastic stack version for testing 8.2.0-dcff22d7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7668 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7667 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7639 Update backporting docs
  CONTRIBUTING.md
Labels: backport-skip

#7672 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7673 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7674 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7676 [automation] update elastic stack version for testing 8.1.2-d0bc828f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7675 [automation] update elastic stack version for testing 7.17.2-cf7cf1eb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7687 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7685 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7684 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7689 [automation] update elastic stack version for testing 8.1.2-e94d7716
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7690 [automation] update elastic stack version for testing 7.17.2-99f889e2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#7679 Use gorilla/mux
  NOTICE.txt
  beater/api/mux.go
  beater/api/root/handler.go
  beater/api/root/handler_test.go
  beater/server.go
  beater/tracing_test.go
  changelogs/head.asciidoc
  go.mod
  go.sum
Labels: backport-skip, v8.2.0

#7584 ci: support staging for all branches but main
  .ci/packaging.groovy
  .ci/scripts/release-manager.sh
Labels: automation, backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7681 dra: notify package and dra failures with the digested build summary
  .ci/packaging.groovy
Labels: automation, Team:Automation, backport-8.0, backport-8.1, backport-8.2, backport-7.17

#7698 apmpackage: add `url.original` field back in
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
Labels: v8.2.0, backport-8.1, backport-7.17

#7711 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#7709 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
