Repository elastic/apm-server, pull requests merged in 2022-08, with the labels that each got.

#8758 feat: set a default User-Agent field value when making HTTP requests
  changelogs/head.asciidoc
  internal/beater/server_test.go
  internal/elasticsearch/client.go
  internal/elasticsearch/client_test.go
Labels: backport-skip

#8759 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8760 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8761 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8762 [automation] update elastic stack version for testing 8.4.0-d88c8a44
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8763 [automation] update elastic stack version for testing 7.17.6-74b6df3e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8732 Move building of binaries, Docker images, and packages to Makefile
  .ci/Jenkinsfile
  .ci/packaging.groovy
  .ci/packer_cache.sh
  .ci/scripts/prepare-release-manager.sh
  .ci/scripts/push-docker.sh
  .dockerignore
  .gitignore
  Makefile
  go.mk
  magefile.go
  packaging.mk
  packaging/docker/Dockerfile
  packaging/docker/README.md
  packaging/docker/docker-entrypoint
  packaging/docker/tini-amd64.tar.xz
  packaging/docker/tini-arm64.tar.xz
  packaging/files/linux/apm-server.sh
  packaging/files/linux/deb-post-install.sh.tmpl
  packaging/files/linux/postinstall.sh
  packaging/files/linux/pre-install.sh.tmpl
  packaging/files/linux/preinstall.sh
  packaging/files/linux/systemd.unit
  packaging/files/windows/install-service.ps1
  packaging/files/windows/uninstall-service.ps1
  packaging/ironbank/Dockerfile
  packaging/ironbank/README.md
  packaging/ironbank/hardening_manifest.yaml
  packaging/nfpm.yml
  packaging/versioninfo.json
  script/goimports.sh
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: backport-skip, ci:windows, v8.5.0

#8767 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8769 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8771 [automation] update elastic stack version for testing 8.5.0-c54c3404
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8773 [automation] update elastic stack version for testing 8.4.0-5954f776
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8772 [automation] update elastic stack version for testing 8.3.4-9c50d4cb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8776 [automation] update elastic stack version for testing 8.5.0-7dbc10f8
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8770 .ci: cache Go modules
  .ci/packer_cache.sh
  script/common.bash
Labels: backport-skip

#8779 Actually running attacher as another user
  internal/beater/java_attacher/java_attacher.go
Labels: bug, backport-8.4

#8786 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8787 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8785 .ci: fix apmpackage trigger condition
  .ci/packaging.groovy
Labels: backport-8.4

#8788 [automation] update elastic stack version for testing 8.3.4-a15c6beb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8789 [automation] update elastic stack version for testing 7.17.6-02b91d00
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8717 CI: Publish apm package to Package Storage v2
  .ci/packaging.groovy
  Makefile
  apmpackage/apm/changelog.yml
  apmpackage/cmd/genpackage/transform.go
Labels: backport-skip

#8791 Fix broken link to Docker getting started
  docs/legacy/guide/quick-start-overview.asciidoc
Labels: Team:Docs, backport-8.4

#8796 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8795 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8794 Fix link to Docker getting started
  docs/legacy/guide/quick-start-overview.asciidoc
Labels: Team:Docs, backport-8.4

#8798 [automation] update elastic stack version for testing 7.17.6-308858b9
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8728 feat: add BEATS_VERSION check make task
  .ci/scripts/check-beats-version.sh
  .ci/update-beats.groovy
Labels: backport-skip

#8800 [automation] update elastic stack version for testing 8.4.0-b5074ef3
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8804 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8805 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8807 [automation] update elastic stack version for testing 8.4.0-43c061d1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8806 [automation] update elastic stack version for testing 8.3.4-73c9af3c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8808 [automation] update elastic stack version for testing 7.17.6-39f8da8e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8783 feat: rename process.ppid to process.parent.pid
  apmpackage/apm/data_stream/app_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  apmpackage/cmd/genpackage/pipelines.go
  docs/data/elasticsearch/generated/errors.json
  docs/data/elasticsearch/generated/transactions.json
  docs/data/elasticsearch/metricset.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationErrors.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationEvents.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationSpans.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactions.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationTransactionsHugeTraces.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationUnknownSpanType.approved.json
  internal/model/process.go
  internal/model/process_test.go
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationErrors.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationEvents.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationOpenTelemetryBridge.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationOptionalTimestamps.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationSpans.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactions.approved.json
  internal/processor/stream/test_approved_es_documents/testIntakeIntegrationTransactionsHugeTraces.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
Labels: backport-skip

#8810 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8802 Fix usage of date cmd for unix systems in packaging
  packaging.mk
Labels: backport-skip

#8812 [automation] update elastic stack version for testing 8.4.0-4b3e8f6e
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8813 [automation] update elastic stack version for testing 8.3.4-9c6c318b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8814 [automation] update elastic stack version for testing 7.17.6-49d2f2df
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8815 .ci: fix check-beats-version
  .ci/scripts/check-beats-version.sh
Labels: backport-skip

#8816 Handle wrapped ctx canceled errors for apmsoak
  systemtest/cmd/apmsoak/main.go
Labels: backport-skip

#8817 Makefile: use -compat=1.17 in go mod tidy
  Makefile
  internal/glog/go.mod
Labels: backport-8.4

#8811 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8819 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8784 feat: map additional fields from mobile agents
  changelogs/head.asciidoc
  internal/model/host_test.go
  internal/model/modeldecoder/v2/metadata_test.go
  internal/model/os.go
  internal/model/test_approved/host/full.approved.json
  internal/processor/otel/metadata.go
  internal/processor/otel/metadata_test.go
  internal/processor/otel/metrics_test.go
  internal/processor/otel/traces.go
  internal/processor/otel/traces_test.go
Labels: backport-skip

#8820 decoder: Always map transaction.id
  changelogs/8.4.asciidoc
  internal/beater/integration_test.go
  internal/beater/test_approved_es_documents/TestPublishIntegrationErrorsTxID.approved.json
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/error_test.go
  testdata/intake-v2/errors_transaction_id.ndjson
Labels: bug, backport-7.17, v8.5.0, backport-8.4

#8824 packaging: actually gzip docker tarballs
  packaging.mk
Labels: backport-skip

#8825 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8826 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8827 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8828 [automation] update elastic stack version for testing 8.4.0-96568c7b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8830 [automation] update elastic stack version for testing 8.3.4-fd43be48
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8829 [automation] update elastic stack version for testing 7.17.6-a65acb36
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8833 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8832 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8834 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8837 [automation] update elastic stack version for testing 8.4.0-9adc8090
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8835 [automation] update elastic stack version for testing 8.5.0-41aadc32
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8836 [automation] update elastic stack version for testing 8.3.4-b4aa6143
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8838 [automation] update elastic stack version for testing 7.17.6-e11a9305
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8843 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8844 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8845 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8848 [automation] update elastic stack version for testing 8.5.0-60a4c029
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8847 [automation] update elastic stack version for testing 8.4.0-c17572db
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8846 [automation] update elastic stack version for testing 8.3.4-a5e24e15
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8849 [automation] update elastic stack version for testing 7.17.6-9b06d311
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8123 Update dev notes related to release guidelines and contribution
  CONTRIBUTING.md
  RELEASES.md
Labels: backport-skip

#8777 feat: add support for Otel semantic conventions for JVM metrics
  internal/processor/otel/metrics.go
  internal/processor/otel/metrics_test.go
Labels: backport-skip

#8840 Tidy up building and installing integration package
  .ci/packaging.groovy
  Makefile
  docker-compose.yml
  go.mk
  systemtest/cmd/runapm/main.go
  systemtest/fleettest/client.go
  systemtest/kibana.go
  testing/docker/package-registry/config.yml
Labels: backport-skip

#8851 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8852 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8854 [automation] update elastic stack version for testing 8.3.4-adc3e57f
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8853 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8778 Introduce systemtest/cmd/fleetctl
  systemtest/cmd/fleetctl/README.md
  systemtest/cmd/fleetctl/main.go
  systemtest/fleettest/client.go
  systemtest/fleettest/types.go
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#8858 .ci: remove check-changelogs job & scripts
  .ci/check-changelogs.groovy
  .ci/jobs/apm-server-check-changelogs-mbp.yml
  .ci/scripts/check-changelogs.sh
  Makefile
  RELEASES.md
  script/check_changelogs.py
Labels: backport-skip

#8859 Remove all uses of Python apart from Rally
  .ci/scripts/linux-test.sh
  Makefile
  apmpackage/README.md
  packaging.mk
  script/check_docker_compose.sh
  script/copy-docs.py
  script/copy_package.py
  script/generate_notice.py
  script/latest_snapshot_version.py
  script/latest_snapshot_version.sh
  script/requirements.txt
  tools/notice/NOTICE.txt.tmpl
  tools/notice/dependencies.csv.tmpl
  tools/notice/overrides.json
  tools/notice/rules.json
Labels: backport-skip

#8856 Introduce more support for cloud-first testing
  TESTING.md
  systemtest/cmd/buildapm/main.go
  systemtest/containers.go
  testing/benchmark/Makefile
  testing/cloud/.gitignore
  testing/cloud/Makefile
  testing/cloud/README.md
  testing/cloud/main.tf
  testing/cloud/outputs.tf
  testing/cloud/variables.tf
  testing/docker/elastic-agent/Dockerfile
  testing/docker/elastic-agent/build.sh
  testing/docker/kibana/Dockerfile-apmpackage
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-skip

#8861 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8860 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8863 [automation] update elastic stack version for testing 8.4.0-fea9abbe
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8862 [automation] update elastic stack version for testing 8.3.4-6d6eaf28
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8864 [automation] update elastic stack version for testing 7.17.6-efe703c7
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8855 apmbench: Replace -warmup-events for -warmup-time
  TESTING.md
  systemtest/benchtest/config.go
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  testing/benchmark/Makefile
  testing/benchmark/README.md
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
Labels: enhancement, backport-skip, v8.5.0

#8865 Defer beats directory evaluation
  Makefile
Labels: backport-skip

#8809 Fix event loss during reload of TBS processor
  changelogs/head.asciidoc
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/eventstorage/sharded.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_bench_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-skip

#8871 [automation] update libbeat and beats packaging
  .go-version
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
Labels: automation, backport-skip

#8872 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8873 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8870 build: update Go to 1.18
  Makefile
  cmd/intake-receiver/go.mod
  go.mod
  internal/approvaltest/go.mod
  internal/glog/go.mod
  packaging/docker/Dockerfile
  rally/gencorpora/go.mod
  systemtest/go.mod
  tools/go.mod
Labels: backport-skip

#8876 [automation] update elastic stack version for testing 8.4.0-9bd354a1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8874 [automation] update elastic stack version for testing 8.3.4-58ddca7b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8875 [automation] update elastic stack version for testing 7.17.6-03b746cb
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8867 testing/benchmark: Allow setting apm index shards
  testing/benchmark/README.md
  testing/benchmark/main.tf
  testing/benchmark/system-profiles/8GBx1zone.tfvars
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
Labels: enhancement, backport-skip, v8.5.0

#8839 txmetrics: Add global labels to metric sets
  changelogs/head.asciidoc
  docs/data-model.asciidoc
  internal/model/apmevent.go
  internal/model/labels.go
  internal/model/modeldecoder/modeldecoderutil/labels.go
  internal/model/modeldecoder/rumv3/decoder.go
  internal/model/modeldecoder/rumv3/error_test.go
  internal/model/modeldecoder/rumv3/metadata_test.go
  internal/model/modeldecoder/rumv3/transaction_test.go
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/error_test.go
  internal/model/modeldecoder/v2/metadata_test.go
  internal/model/modeldecoder/v2/transaction_test.go
  internal/processor/otel/logs_test.go
  internal/processor/otel/metadata.go
  internal/processor/otel/metadata_test.go
  internal/processor/stream/processor_test.go
  systemtest/aggregation_test.go
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/go.mod
  systemtest/go.sum
  systemtest/huge_traces_test.go
  systemtest/metrics_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_label_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: enhancement, backport-skip, v8.5.0

#8882 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8883 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8881 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8885 [automation] update elastic stack version for testing 8.4.0-aff0df12
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8884 [automation] update elastic stack version for testing 7.17.6-202119fd
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8880 feat: migrate to the new net/netip package
  internal/beater/api/mux.go
  internal/beater/api/mux_test.go
  internal/beater/interceptors/metadata.go
  internal/beater/interceptors/metadata_test.go
  internal/beater/interceptors/ratelimit_test.go
  internal/beater/middleware/log_middleware.go
  internal/beater/otlp/clientmetadata.go
  internal/beater/otlp/clientmetadata_test.go
  internal/beater/ratelimit/store.go
  internal/beater/ratelimit/store_test.go
  internal/beater/request/context.go
  internal/beater/request/context_test.go
  internal/model/apmevent_test.go
  internal/model/client.go
  internal/model/client_test.go
  internal/model/host.go
  internal/model/host_test.go
  internal/model/modeldecoder/modeldecodertest/populator.go
  internal/model/modeldecoder/rumv3/metadata_test.go
  internal/model/modeldecoder/rumv3/transaction_test.go
  internal/model/modeldecoder/v2/decoder.go
  internal/model/modeldecoder/v2/error_test.go
  internal/model/modeldecoder/v2/metadata_test.go
  internal/model/modeldecoder/v2/transaction_test.go
  internal/model/source.go
  internal/netutil/netutil.go
  internal/netutil/netutil_test.go
  internal/processor/otel/metadata.go
  internal/processor/otel/traces.go
  internal/processor/otel/traces_test.go
  internal/processor/stream/processor_test.go
Labels: backport-skip

#8891 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8892 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8893 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8895 [automation] update elastic stack version for testing 8.5.0-6b9f92c0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8896 [automation] update elastic stack version for testing 8.4.0-b95305c2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8897 [automation] update elastic stack version for testing 8.3.4-e23a59c6
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8894 [automation] update elastic stack version for testing 7.17.6-091e6fb1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8878 Add gencorpora cmd to generate ES corpora for rally
  systemtest/apmservertest/command.go
  systemtest/apmservertest/server.go
  systemtest/benchtest/clients.go
  systemtest/benchtest/main.go
  systemtest/benchtest/profiles.go
  systemtest/cmd/gencorpora/main.go
  systemtest/gencorpora/apmserver.go
  systemtest/gencorpora/catbulk.go
  systemtest/gencorpora/config.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/loadgen/config/config.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#8889 docs: add tech preview mutating webhook docs
  docs/apm-mutating-webhook.asciidoc
  docs/features.asciidoc
  docs/integrations-index.asciidoc
Labels: Team:Docs, backport-8.4

#8890 docs: update 8.4 release notes
  changelogs/8.4.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, backport-8.4

#8904 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8906 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8905 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8900 Fix race condition in custom libbeat instrumentation
  changelogs/head.asciidoc
  internal/beater/beater.go
Labels: backport-8.4

#8914 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8910 Refactor beatertest
  internal/beater/api/mux_test.go
  internal/beater/api/root/handler_test.go
  internal/beater/beatertest/context.go
  internal/beater/beatertest/handler.go
  internal/beater/beatertest/result.go
  internal/beater/interceptors/metrics_test.go
  internal/beater/middleware/auth_middleware_test.go
  internal/beater/middleware/cors_middleware_test.go
  internal/beater/middleware/kill_switch_middleware_test.go
  internal/beater/middleware/log_middleware_test.go
  internal/beater/middleware/middleware_test.go
  internal/beater/middleware/monitoring_middleware_test.go
  internal/beater/middleware/recover_panic_middleware_test.go
  internal/beater/middleware/response_headers_middleware_test.go
  internal/beater/monitoringtest/monitoring.go
Labels: backport-skip

#8915 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8913 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8912 Terminate beat.Info
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_PanicMiddleware.approved.json
  internal/beater/api/intake/test_approved/integration/backend/TestIntakeBackendHandler_PanicMiddleware.approved.json
  internal/beater/api/intake/test_approved/integration/rum/TestIntakeRUMHandler_PanicMiddleware.approved.json
  internal/beater/api/mux.go
  internal/beater/api/mux_config_agent_test.go
  internal/beater/api/mux_intake_backend_test.go
  internal/beater/api/mux_intake_rum_test.go
  internal/beater/api/mux_root_test.go
  internal/beater/api/mux_test.go
  internal/beater/api/root/test_approved/integration/TestRootHandler_AuthorizationMiddleware/Authorized.approved.json
  internal/beater/api/root/test_approved/integration/TestRootHandler_PanicMiddleware.approved.json
  internal/beater/beater.go
  internal/beater/http.go
  internal/beater/otlp/http_test.go
  internal/beater/server.go
  internal/beater/tracing.go
  x-pack/apm-server/main.go
Labels: backport-skip

#8923 [automation] update elastic stack version for testing 8.4.0-910fe5e1
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8921 [automation] update elastic stack version for testing 8.3.4-70c0b53c
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8924 [automation] update elastic stack version for testing 7.17.6-b8ca5a33
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8922 [automation] update elastic stack version for testing 8.5.0-0616acda
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8898 systemtest/apmservertest: make use of testing.TB optional
  systemtest/agentconfig_test.go
  systemtest/aggregation_test.go
  systemtest/apmservertest/server.go
  systemtest/apmservertest/server_test.go
  systemtest/auth_test.go
  systemtest/cmd/gencorpora/main.go
  systemtest/cmdflags_test.go
  systemtest/environment_test.go
  systemtest/errorgrouping_test.go
  systemtest/errors_test.go
  systemtest/gencorpora/apmserver.go
  systemtest/gencorpora/config.go
  systemtest/headers_test.go
  systemtest/huge_traces_test.go
  systemtest/ingest_test.go
  systemtest/instrumentation_test.go
  systemtest/jaeger_test.go
  systemtest/logging_test.go
  systemtest/metrics_test.go
  systemtest/monitoring_test.go
  systemtest/otlp_test.go
  systemtest/rum_test.go
  systemtest/sampling_test.go
  systemtest/sourcemap_test.go
  systemtest/tls_test.go
Labels: backport-skip

#8919 tf/ec_deployment: Add autoscaling control variable
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/variables.tf
Labels: backport-skip, v8.5.0

#8920 testing/benchmark: Add make cleanup-elasticsearch
  testing/benchmark/Makefile
  testing/benchmark/README.md
  testing/benchmark/outputs.tf
Labels: backport-skip, v8.5.0

#8918 tf/ec_deployment: Use script for shard settings
  testing/benchmark/main.tf
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/ec_deployment/.gitignore
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/scripts/index_shards.tftpl
  testing/infra/terraform/modules/ec_deployment/variables.tf
Labels: backport-skip, v8.5.0

#8926 systemtest: Fix apm-server log getter from test container
  systemtest/containers.go
Labels: backport-skip

#8911 Remove experimental profiling support
  NOTICE.txt
  apm-server.docker.yml
  apm-server.yml
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/profile_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/profile_metrics/fields/base-fields.yml
  apmpackage/apm/data_stream/profile_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/profile_metrics/fields/fields.yml
  apmpackage/apm/data_stream/profile_metrics/manifest.yml
  changelogs/head.asciidoc
  cmd/pprofessor/README.md
  cmd/pprofessor/fetcher.go
  cmd/pprofessor/flags.go
  cmd/pprofessor/pprof.go
  docs/data-streams.asciidoc
  docs/ilm-how-to.asciidoc
  go.mod
  internal/beater/api/mux.go
  internal/beater/api/profile/convert.go
  internal/beater/api/profile/handler.go
  internal/beater/api/profile/handler_test.go
  internal/beater/integration_test.go
  internal/beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfile.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationProfileCPUProfileMetadata.approved.json
  internal/beater/test_approved_es_documents/TestPublishIntegrationProfileHeapProfile.approved.json
  internal/model/apmevent.go
  internal/model/modeldecoder/rumv3/metadata_test.go
  internal/model/modeldecoder/v2/metadata_test.go
  internal/model/modelprocessor/datastream.go
  internal/model/modelprocessor/datastream_test.go
  internal/model/profile.go
  internal/model/profile_test.go
  systemtest/apmservertest/config.go
  systemtest/instrumentation_test.go
Labels: backport-skip, v8.5.0

#8930 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8931 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8899 Stop using legacy syntax for parameters on triggerRemoteJob
  .ci/packaging.groovy
Labels: backport-skip

#8932 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8935 [automation] update elastic stack version for testing 8.5.0-dd6f2bb0
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8936 [automation] update elastic stack version for testing 8.4.0-7f4eb04b
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8934 [automation] update elastic stack version for testing 7.17.6-a9c53531
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8933 [automation] update elastic stack version for testing 8.3.4-45336fec
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8929 Remove dependencies from non-beater code on beater/config
  internal/agentcfg/fetch.go
  internal/agentcfg/fetch_test.go
  internal/beater/api/config/agent/handler_test.go
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_AuthorizationMiddleware/Authorized.approved.json
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_AuthorizationMiddleware/Unauthorized.approved.json
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_DirectConfiguration.approved.json
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/Off.approved.json
  internal/beater/api/config/agent/test_approved/integration/TestConfigAgentHandler_KillSwitchMiddleware/On.approved.json
  internal/beater/api/intake/handler_test.go
  internal/beater/api/mux.go
  internal/beater/api/mux_config_agent_test.go
  internal/beater/api/mux_test.go
  internal/beater/beater.go
  internal/beater/config/kibana.go
  internal/beater/otlp/http_test.go
  internal/beater/server.go
  internal/beater/tracing.go
  internal/kibana/connecting_client.go
  internal/kibana/connecting_client_test.go
  internal/processor/stream/benchmark_test.go
  internal/processor/stream/processor.go
  internal/processor/stream/processor_test.go
  internal/sourcemap/caching_test.go
  internal/sourcemap/fleet.go
  internal/sourcemap/fleet_test.go
  internal/sourcemap/kibana_test.go
Labels: backport-skip

#8793 docs: add APM AWS Lambda release notes
  changelogs/8.4.asciidoc
  docs/agent-server-compatibility.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Docs, backport-8.4

#8908 docs: custom ingest pipelines
  docs/apm-data-security.asciidoc
  docs/ingest-pipelines.asciidoc
Labels: Team:Docs, backport-8.4

#8937 systemtest/gencorpora: generate corpus metadata
  systemtest/gencorpora/apmserver.go
  systemtest/gencorpora/catbulk.go
  systemtest/gencorpora/config.go
Labels: backport-skip

#8942 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8943 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8944 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#8917 apmbench: Rewrite handler to be concurrently safe
  systemtest/benchtest/clients.go
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  systemtest/cmd/apmbench/main.go
  systemtest/loadgen/eventhandler/handler.go
Labels: backport-skip, v8.5.0

#8945 [automation] update elastic stack version for testing 8.5.0-feb644de
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8948 [automation] update elastic stack version for testing 8.4.0-fa661330
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8946 [automation] update elastic stack version for testing 7.17.6-4816e9ef
  docker-compose.yml
Labels: dependency, automation, backport-skip

#8941 Update rally cmd to use corpora generated by agent data
  Makefile
  rally/gencorpora/api.go
  rally/gencorpora/go.mod
  rally/gencorpora/go.sum
  rally/gencorpora/main.go
  rally/track.json
  script/cat_bulk.py
Labels: backport-skip
