Repository elastic/apm-server, pull requests merged in 2023-09, with the labels that each got.

#11543 Upgrade opentelemetry in systemtest
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/cmd/sendotlp/main.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/jaeger_test.go
  systemtest/otlp_test.go
Labels: backport-skip

#11539 apmpackage: define DLM retention periods in apm package
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/lifecycle.yml
  apmpackage/apm/data_stream/app_metrics/lifecycle.yml
  apmpackage/apm/data_stream/error_logs/lifecycle.yml
  apmpackage/apm/data_stream/internal_metrics/lifecycle.yml
  apmpackage/apm/data_stream/rum_traces/lifecycle.yml
  apmpackage/apm/data_stream/sampled_traces/lifecycle.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/lifecycle.10m.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/lifecycle.1m.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/lifecycle.60m.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/lifecycle.10m.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/lifecycle.1m.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/lifecycle.60m.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/lifecycle.10m.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/lifecycle.1m.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/lifecycle.60m.yml
  apmpackage/apm/data_stream/traces/lifecycle.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/lifecycle.10m.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/lifecycle.1m.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/lifecycle.60m.yml
  apmpackage/apm/manifest.yml
  apmpackage/cmd/genpackage/main.go
  changelogs/head.asciidoc
  systemtest/go.mod
  systemtest/go.sum
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#11565 buildkite: docker login
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
Labels: backport-7.17, backport-8.10

#11570 [updatecli] Bump elastic stack version to 8.11.0-8369a13a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11571 [updatecli] Update to elastic/beats@c23978a8de52
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11572 [updatecli] Update to elastic/beats@a6bae85b20b8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11569 [updatecli] Bump elastic stack version to 8.10.0-fc582a97
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11578 [updatecli] Update to elastic/beats@b017e506dc26
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11577 [updatecli] Update to elastic/beats@ab2f67d7ee4e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11575 [updatecli] Bump elastic stack version to 8.10.0-e4344f1d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11576 [updatecli] Bump elastic stack version to 8.11.0-e6822a57
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11564 Expose HTTP/gRPC metrics to OpenTelemetry as well
  internal/beater/api/mux.go
  internal/beater/beater.go
  internal/beater/interceptors/metrics.go
  internal/beater/interceptors/metrics_test.go
  internal/beater/middleware/monitoring_middleware.go
  internal/beater/middleware/monitoring_middleware_test.go
  internal/beater/monitoringtest/opentelemetry.go
  internal/beater/otlp/grpc_test.go
Labels: backport-skip

#11545 Allow setting the metric batch exporter early
  internal/beater/beater.go
  internal/telemetry/metric_exporter.go
  internal/telemetry/metric_exporter_config.go
  internal/telemetry/metric_exporter_test.go
Labels: backport-skip

#11586 [updatecli] Update to elastic/beats@62873ab51c9c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11585 [updatecli] Update to elastic/beats@3b02b8a82a5a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11588 [updatecli] Update to elastic/beats@ae06ed7e6c73
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11584 [updatecli] Bump elastic stack version to 8.11.0-32daf5de
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11583 [updatecli] Bump elastic stack version to 8.10.0-befeb0ae
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11595 [updatecli] Update to elastic/beats@c723290c2d3a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11582 Expose local metrics to the batch processor
  changelogs/head.asciidoc
  docs/monitoring/monitoring-beats.asciidoc
  docs/monitoring/monitoring-local-collection.asciidoc
  internal/beater/beater.go
Labels: backport-skip

#11599 CHANGELOG: add bug fix entry for dropped_spans_stats.duration
  changelogs/8.10.asciidoc
Labels: backport-8.10

#11587 [updatecli] Update to elastic/beats@0df87840b218
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11592 Document all the APIs
  docs/api-config.asciidoc
  docs/api-events.asciidoc
  docs/api-info.asciidoc
  docs/api-jaeger.asciidoc
  docs/api-otlp.asciidoc
  docs/api.asciidoc
Labels: docs, backport-8.9, backport-8.10

#11604 [updatecli] Bump elastic stack version to 8.10.0-fa76ee05
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11609 Remove empty deprecations and add breaking changes [8.10]
  changelogs/8.10.asciidoc
  docs/apm-breaking.asciidoc
Labels: backport-8.10

#11606 [updatecli] Bump elastic stack version to 8.11.0-3ae53e7a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11605 [updatecli] Update to elastic/beats@d2bf6872db67
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11613 Add request duration local metrics
  changelogs/head.asciidoc
  docs/monitoring/monitoring-local-collection.asciidoc
  internal/beater/beater.go
  internal/beater/interceptors/metrics.go
  internal/beater/interceptors/metrics_test.go
  internal/beater/middleware/monitoring_middleware.go
  internal/beater/middleware/monitoring_middleware_test.go
  internal/beater/monitoringtest/opentelemetry.go
Labels: backport-skip

#11607 [updatecli] Update to elastic/beats@8d3aa9126c15
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11616 [updatecli] Bump elastic stack version to 8.10.0-f3e0fdd8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11618 [updatecli] Update to elastic/beats@80ed33b8cc69
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11617 [updatecli] Bump elastic stack version to 8.11.0-0d7477b6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11619 [updatecli] Bump Golang version to 1.20.8
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#11621 Create new dev/test certificate for fleet-server
  systemtest/containers.go
  testing/docker/fleet-server/ca.pem
  testing/docker/fleet-server/certificate.pem
  testing/docker/fleet-server/key.pem
Labels: backport-8.10

#11600 Finetune the 16GB and 32GB profiles sizes
  testing/benchmark/system-profiles/16GBx2zone.tfvars
  testing/benchmark/system-profiles/32GBx2zone.tfvars
Labels: backport-skip

#11627 [updatecli] Update to elastic/beats@95be378c22fa
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11625 [updatecli] Bump elastic stack version to 8.10.0-c5be8c13
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11624 [updatecli] Bump elastic stack version to 8.11.0-f8bc4ebc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11623 systemtest: disable fleet ID verification pipeline
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/sampled_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/cmd/genpackage/pipelines.go
  systemtest/approvals/TestAgentConfig.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/ErrorsTxID.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Metricsets.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestIntakeLog/with_faas.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_summary.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/absolute_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/relative_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
  systemtest/approvals/TestServiceTransactionMetricsAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  testing/docker/kibana/kibana.yml
Labels: backport-skip

#11632 Remove `ecs.version` field from mappings
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_logs/fields/ecs.yml
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/app_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/error_logs/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/error_logs/fields/ecs.yml
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/internal_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/rum_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/traces/fields/ecs.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/fields/ecs.yml
  apmpackage/cmd/genpackage/main.go
  apmpackage/cmd/genpackage/pipelines.go
  apmpackage/cmd/genpackage/transform.go
  changelogs/head.asciidoc
  systemtest/approvals/TestAgentConfig.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Metricsets.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_summary.approved.json
  systemtest/approvals/TestProfiling/events.approved.json
  systemtest/approvals/TestProfiling/executables.approved.json
  systemtest/approvals/TestProfiling/metrics.approved.json
  systemtest/approvals/TestProfiling/stackframes.approved.json
  systemtest/approvals/TestProfiling/stacktraces.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
  systemtest/approvals/TestServiceTransactionMetricsAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  systemtest/ingest_test.go
Labels: backport-skip

#11636 [updatecli] Update to elastic/beats@8e7e2065c73b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11628 [updatecli] Update to elastic/beats@a725c7a41183
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11635 [updatecli] Bump elastic stack version to 8.11.0-7dab12da
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11634 [updatecli] Bump elastic stack version to 8.10.0-516050d7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11640 [updatecli] Update to elastic/beats@b7d1f806f6ec
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11638 Minor changes to support running system tests with x-pack-apm
  apmpackage/apm/changelog.yml
  apmpackage/cmd/genpackage/pipelines.go
  systemtest/errorgrouping_test.go
  systemtest/ingest_test.go
Labels: backport-skip

#11642 Fix tail-based sampling discarding low throughput and low sample rate traces
  changelogs/head.asciidoc
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.10

#11647 [updatecli] Bump elastic stack version to 8.11.0-58bca18d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11649 [updatecli] Update to elastic/beats@73774d544927
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11653 [updatecli] Bump elastic stack version to 8.11.0-f9ab12e0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11656 Add 8.10.1 changelog
  changelogs/8.10.asciidoc
Labels: docs, backport-8.10

#11659 Add missing changelog line to 8.10.asciidoc
  changelogs/8.10.asciidoc
Labels: backport-8.10

#11648 [updatecli] Bump elastic stack version to 8.10.1-1dffad09
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11658 [updatecli] Bump elastic stack version to 8.11.0-2b227d89
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11650 [updatecli] Update to elastic/beats@b4f7abe549d9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11646 [updatecli] Bump elastic stack version to 7.17.14-f1d9b80b
  docker-compose.yml
Labels: automation, backport-skip

#11641 [updatecli] Update to elastic/beats@318fdba64ccd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11667 [updatecli] Bump elastic stack version to 8.11.0-f88f1d11
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11668 [updatecli] Update to elastic/beats@ccfa54a3b000
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11670 [updatecli] Update to elastic/beats@fd8fe01a24a9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11666 [updatecli] Bump elastic stack version to 8.10.2-9d743908
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11669 [updatecli] Update to elastic/beats@480bccf4f042
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11532 jjbb: use beats-ci
  .ci/jobs/apm-server-package-mbp.yml
  .ci/jobs/defaults.yml
Labels: backport-skip

#11663 docs: Document sampling behavior on TBS storage limit reached
  docs/configure/sampling.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10

#11677 [updatecli] Update to elastic/beats@3f3f0ce79a7b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11676 [updatecli] Update to elastic/beats@5da74528be00
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11673 [updatecli] Bump elastic stack version to 8.10.2-d38be4c2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11674 [updatecli] Bump elastic stack version to 8.11.0-91824658
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11675 [updatecli] Update to elastic/beats@24c3388ed6d8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11672 [updatecli] Bump elastic stack version to 7.17.14-55a4d733
  docker-compose.yml
Labels: automation, backport-skip

#11691 [updatecli] Bump elastic stack version to 8.10.2-10b341e4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11692 [updatecli] Bump elastic stack version to 8.11.0-6aa5b988
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11693 [updatecli] Update to elastic/beats@513ace48f5f0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11701 [updatecli] Bump elastic stack version to 8.11.0-c47419c4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11706 Added OTel limitation about TBS to the docs
  docs/otel-limitations.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10

#11710 [updatecli] Bump elastic stack version to 8.11.0-abc4d077
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11711 [updatecli] Bump elastic stack version to 8.10.3-aa09190a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11702 [updatecli] Update to elastic/beats@b9a47516c7c4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11699 Adding geolocation attrs to app_logs
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/elasticsearch/ingest_pipeline/default.yml
  changelogs/head.asciidoc
  systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
  systemtest/otlp_test.go
Labels: backport-skip

#11717 changelog: Fix missing PR link
  changelogs/head.asciidoc
Labels: backport-skip

#11720 [updatecli] Update to elastic/beats@90407307dae6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11718 [updatecli] Bump elastic stack version to 8.11.0-6faed5c7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11719 [updatecli] Bump elastic stack version to 8.10.3-345ef27d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11700 [updatecli] Bump elastic stack version to 7.17.14-ca772d6f
  docker-compose.yml
Labels: automation, backport-skip

#11695 [updatecli] Update to elastic/beats@e478d279a0a0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11694 [updatecli] Update to elastic/beats@f111cbc73ec4
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/config/config_test.go
Labels: automation, backport-skip

#11725 [updatecli] Bump elastic stack version to 8.11.0-b2ac6b4d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11724 [updatecli] Bump elastic stack version to 8.10.3-a4520544
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11726 [updatecli] Update to elastic/beats@58db08f2bf76
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11732 [updatecli] Bump elastic stack version to 8.11.0-10db2ffc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11734 [updatecli] Bump elastic stack version to 8.10.3-8e865fb7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11733 [updatecli] Bump elastic stack version to 7.17.14-a1357ca2
  docker-compose.yml
Labels: automation, backport-skip

#11737 [updatecli] Update to elastic/beats@4bd7a25db310
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11744 [updatecli] Bump elastic stack version to 8.10.3-0a467303
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11746 [updatecli] Update to elastic/beats@a5d600652382
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11745 [updatecli] Update to elastic/beats@483d344b0cea
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11736 [updatecli] Update to elastic/beats@49cc14d35d5e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
