Repository elastic/apm-server, pull requests merged in 2023-08, with the labels that each got.

#11322 [updatecli] Bump elastic stack version to 8.9.1-a0629552
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11321 [updatecli] Bump elastic stack version to 8.10.0-ed2e01b4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11320 [updatecli] Bump elastic stack version to 7.17.13-19dc27d2
  docker-compose.yml
Labels: automation, backport-skip

#11323 [updatecli] Update to elastic/beats@e1267beba311
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11318 [updatecli] Update to elastic/beats@8afad2ac70b4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11324 docs: remove breaking change tags
  docs/apm-breaking.asciidoc
Labels: backport-8.9

#11329 [updatecli] Update to elastic/beats@90cd631cabf8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11326 [updatecli] Bump elastic stack version to 7.17.13-7f46ddb9
  docker-compose.yml
Labels: automation, backport-skip

#11327 [updatecli] Bump elastic stack version to 8.9.1-877ad540
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11332 [updatecli] Bump elastic stack version to 8.9.1-40dca293
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11331 [updatecli] Bump elastic stack version to 7.17.13-f0591b59
  docker-compose.yml
Labels: automation, backport-skip

#11334 [updatecli] Update to elastic/beats@4e5806c03a6a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11335 [updatecli] Update to elastic/beats@58176b579b09
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11338 [updatecli] Bump elastic stack version to 8.9.1-762162ce
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11337 [updatecli] Bump elastic stack version to 8.10.0-2619e48b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11341 [updatecli] Update to elastic/beats@325ae699a82f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11340 [updatecli] Update to elastic/beats@5d84cafff95f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11342 [updatecli] Bump Golang version to 1.20.7
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#11343 build: bump apm-data
  NOTICE.txt
  go.mod
  go.sum
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator_test.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-skip

#11347 ci: remove obsoleted Jenkins pipelines
  .ci/Jenkinsfile
  .ci/jobs/apm-server-mbp.yml
  .ci/jobs/apm-server-package-mbp.yml
  .ci/jobs/apm-server-schedule-daily.yml
  .ci/jobs/apm-server-schedule-everyday.yml
  .ci/packaging.groovy
  .ci/schedule-daily.groovy
  .ci/schedule-everyday.groovy
Labels: backport-7.17, backport-8.9

#11357 [updatecli] Bump elastic stack version to 8.10.0-4047f652
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11358 [updatecli] Bump elastic stack version to 8.9.1-6c14de65
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11360 [updatecli] Update to elastic/beats@1f4051f6f715
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11359 [updatecli] Update to elastic/beats@362a2dd9e71a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11361 Grow docappender indexBuilder to desired capacity for performance
  internal/beater/processors.go
Labels: backport-skip

#11363 [updatecli] Bump elastic stack version to 8.9.1-d46182aa
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11364 [updatecli] Update to elastic/beats@1fe462c68f7d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11365 [updatecli] Update to elastic/beats@fa6e633134cf
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11356 action: run microbenchmark on branches
  .github/workflows/microbenchmark.yml
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#11117 LSM-based aggregation
  NOTICE.txt
  changelogs/head.asciidoc
  dev_docs/trace_metrics.md
  docs/data-model.asciidoc
  docs/data/elasticsearch/service_destination_metric.json
  go.mod
  go.sum
  internal/beater/beater.go
  internal/beater/config/aggregation.go
  internal/beater/config/aggregation_test.go
  internal/beater/config/config_test.go
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
  tools/notice/overrides.json
  tools/notice/rules.json
  x-pack/apm-server/aggregation/baseaggregator/aggregator.go
  x-pack/apm-server/aggregation/baseaggregator/space.go
  x-pack/apm-server/aggregation/interval/string.go
  x-pack/apm-server/aggregation/labels/labels.go
  x-pack/apm-server/aggregation/labels/labels_test.go
  x-pack/apm-server/aggregation/lsm.go
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator.go
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator_test.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
Labels: backport-skip

#11370 [updatecli] Update to elastic/beats@604fced40c5b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11376 [updatecli] Bump elastic stack version to 8.9.1-afb401d4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11377 [updatecli] Bump elastic stack version to 8.10.0-46c2dc52
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11375 [updatecli] Bump elastic stack version to 7.17.13-1882ecdc
  docker-compose.yml
Labels: automation, backport-skip

#11379 [updatecli] Update to elastic/beats@3799398872c0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11382 [updatecli] Bump elastic stack version to 8.10.0-22c6ae41
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11383 [updatecli] Bump elastic stack version to 8.9.1-975bdf3e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11384 [updatecli] Update to elastic/beats@4506e55d50f9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11385 [updatecli] Update to elastic/beats@26a1ffe3fa2b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11386 Update apm-data and apm-aggregation
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  internal/agentcfg/reporter.go
  internal/agentcfg/reporter_test.go
  internal/beater/api/mux.go
  internal/beater/api/mux_test.go
  internal/beater/processors.go
  internal/publish/pub.go
  internal/publish/pub_test.go
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions.ndjson
  x-pack/apm-server/aggregation/lsm.go
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor_test.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
Labels: backport-skip, v8.10.0

#11388 [updatecli] Bump elastic stack version to 8.9.1-456ef5ad
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11390 [updatecli] Update to elastic/beats@06760db7494f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11392 Add back aggregation overflow logging
  NOTICE.txt
  go.mod
  go.sum
  x-pack/apm-server/aggregation/lsm.go
Labels: backport-skip

#11395 [updatecli] Bump elastic stack version to 8.10.0-8527fe43
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11396 [updatecli] Bump elastic stack version to 8.9.1-162a595c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11397 [updatecli] Update to elastic/beats@e9fd4b2e4990
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11398 [updatecli] Update to elastic/beats@59529de17b77
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11399 buildkite: package definition
  .buildkite/package.yml
  catalog-info.yaml
Labels: backport-skip

#11401 catalog-info: change BK name
  catalog-info.yaml
Labels: backport-skip

#11409 [updatecli] Update to elastic/beats@138e623c02ed
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11408 [updatecli] Update to elastic/beats@1e0816caae28
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11406 [updatecli] Bump elastic stack version to 8.10.0-bd3f3b15
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11404 changelog: Aggregations share MaxServices
  changelogs/head.asciidoc
Labels: backport-8.10

#11412 add 8.9.1 release notes
  changelogs/8.9.asciidoc
Labels: docs, backport-8.9, backport-8.10

#11252 docs: Update default policies on ILM page
  docs/ilm-how-to.asciidoc
Labels: backport-8.9, backport-8.10

#11424 [updatecli] Bump elastic stack version to 8.10.0-96e4cccf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11431 [updatecli] Update to elastic/beats@84e6affdffe9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11387 [updatecli] Bump elastic stack version to 7.17.13-dde9c3ba
  docker-compose.yml
Labels: automation, backport-skip

#11437 apmpackage: remove `processor.name` field
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
  docs/otel-metrics.asciidoc
  systemtest/approvals/TestAgentConfig.approved.json
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Metricsets.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_summary.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregation.approved.json
  systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
  systemtest/approvals/TestServiceTransactionMetricsAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsMetrics.approved.json
Labels: backport-skip, v8.11.0

#11400 action: support for DRA
  .buildkite/README.md
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/package.yml
  .buildkite/scripts/dra.sh
  .buildkite/scripts/package.sh
  catalog-info.yaml
Labels: automation, Team:Automation, backport-7.17, backport-8.9, backport-8.10

#11447 (docs): Fix commits link for released versions
  changelogs/8.10.asciidoc
  changelogs/8.9.asciidoc
Labels: backport-8.9, backport-8.10

#11443 buildkite: branches are not pull requests
  .buildkite/scripts/dra.sh
Labels: backport-7.17, backport-8.9, backport-8.10

#11426 [updatecli] Bump elastic stack version to 8.9.1-f33bc992
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11425 [updatecli] Bump elastic stack version to 8.10.0-96e4cccf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11454 actions: fix the mergify auto-merge when docs
  .github/workflows/ci-docs.yml
Labels: automation, Team:Automation, backport-7.17, backport-8.9, backport-8.10

#11462 [updatecli] Bump elastic stack version to 8.9.2-f4929e8e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11461 [updatecli] Bump elastic stack version to 7.17.13-9cee84e3
  docker-compose.yml
Labels: automation, backport-skip

#11427 [updatecli] Update to elastic/beats@8903b1f77e7f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11428 [updatecli] Update to elastic/beats@5d1bbbe580e1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11438 Update tf default ec_deployment deployment_template
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
  testing/cloud/variables.tf
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/ec_deployment/variables.tf
  testing/rally-cloud/variables.tf
  testing/smoke/main.tf
  testing/smoke/managed/main.tf
  testing/smoke/supported-os/main.tf
Labels: backport-skip

#11465 [updatecli] Update to elastic/beats@ecc82aa39843
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11466 [updatecli] Update to elastic/beats@c79df0b21c21
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11463 action: run tests on Ubuntu
  .github/workflows/ci.yml
Labels: automation, backport-8.9, backport-8.10

#11473 [updatecli] Bump elastic stack version to 8.10.0-6bf877e8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11472 [updatecli] Bump elastic stack version to 7.17.13-7e207efe
  docker-compose.yml
Labels: automation, backport-skip

#11476 dra: support two workflows in the same context
  .ci/scripts/prepare-release-manager.sh
Labels: backport-skip

#11477 dra: only move if file does not exist
  .ci/scripts/prepare-release-manager.sh
Labels: automation, backport-skip

#11479 [updatecli] Bump elastic stack version to 8.11.0-73e185bf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11478 [updatecli] Bump elastic stack version to 8.9.2-8eb52857
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11480 [updatecli] Bump elastic stack version to 8.10.0-322e3ef7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11482 [updatecli] Update to elastic/beats@c341e06736e3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11481 [updatecli] Update to elastic/beats@eb01e80078fd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11366 [updatecli] Update to elastic/beats@4b615b344207
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11486 Customization for benchmarks manual runs
  .github/workflows/benchmarks.yml
  testing/benchmark/README.md
Labels: backport-skip

#11490 [updatecli] Bump elastic stack version to 8.11.0-76b03348
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11487 [updatecli] Bump elastic stack version to 8.10.0-edf31268
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11488 [updatecli] Bump elastic stack version to 8.9.2-1a569074
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11491 [updatecli] Update to elastic/beats@e57dd305ab0a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11493 [updatecli] Update to elastic/beats@3d4705d7220f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11470 Otel exporter for internal telemetry
  NOTICE.txt
  go.mod
  internal/beater/beater.go
  internal/telemetry/metric_exporter.go
  internal/telemetry/metric_exporter_config.go
  internal/telemetry/metric_exporter_config_test.go
  internal/telemetry/metric_exporter_test.go
Labels: backport-skip

#11494 Don't set `processor.event` for logs
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  systemtest/go.mod
  systemtest/go.sum
  systemtest/intake_log_test.go
  systemtest/otlp_test.go
  tools/go.mod
  tools/go.sum
Labels: backport-skip, v8.11.0

#11464 docs: explain what the CI does
  .github/workflows/README.md
  README.md
Labels: backport-7.17, backport-8.9, backport-8.10

#11498 Allow specifying benchmarks to run
  .github/workflows/benchmarks.yml
Labels: backport-skip

#11501 [updatecli] Bump elastic stack version to 8.10.0-3ddff50a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11502 [updatecli] Bump elastic stack version to 8.11.0-ba1a8c0f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11503 [updatecli] Bump elastic stack version to 8.9.2-fe004c3f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11507 [updatecli] Update to elastic/beats@fd98e2b885a0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11505 [updatecli] Update to elastic/beats@07fd6f9716bc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11508 [updatecli] Update to elastic/beats@a182bafd7c1e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11506 [updatecli] Update to elastic/beats@6c1e6bdf2b14
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#11513 Add 32gb benchmark system profile
  testing/benchmark/system-profiles/32BGx2zone.tfvars
Labels: backport-skip

#11516 [updatecli] Bump elastic stack version to 8.9.2-a804d52d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11517 [updatecli] Bump elastic stack version to 8.11.0-16180d4a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11518 [updatecli] Bump elastic stack version to 8.10.0-b58178d3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11521 [updatecli] Update to elastic/beats@0971da859b06
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11520 [updatecli] Update to elastic/beats@01b87e5accc4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11442 catalog-info: support main, release branches or feature branches
  catalog-info.yaml
Labels: backport-skip

#11526 [updatecli] Update to elastic/beats@aac11fe8f521
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11525 [updatecli] Update to elastic/beats@55edac538c60
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11534 Handle queue.* config for libbeat outputs
  changelogs/8.10.asciidoc
  internal/beater/beater.go
  systemtest/apmservertest/config.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/logstash_test.go
Labels: v8.10.0, backport-8.9, backport-8.10

#11538 docs: fix getting started instructions
  docs/getting-started-apm-server.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10

#11548 [updatecli] Bump elastic stack version to 8.10.0-e6a0cfad
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11547 [updatecli] Bump elastic stack version to 8.11.0-1e5443be
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11550 [updatecli] Update to elastic/beats@64d990d69ee8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11549 [updatecli] Update to elastic/beats@4f6eae0ea385
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11551 [updatecli] Update to elastic/beats@eef9598ea110
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
