Repository elastic/apm-server, pull requests merged in 2023-06, with the labels that each got.

#10924 [updatecli] Bump elastic stack version to 8.8.1-951ef2b6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10925 [updatecli] Bump elastic stack version to 8.9.0-f1fa1d73
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10926 [updatecli] Update to elastic/beats@7eb4a224cc99
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10923 Bump elastic-agent-client to v7.1.2
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.8

#10928 [updatecli] Bump elastic stack version to 8.9.0-45019001
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10929 [updatecli] Bump elastic stack version to 8.8.1-afb32ff1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10932 [updatecli] Bump elastic stack version to 8.8.1-67054589
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10934 [updatecli] Update to elastic/beats@6fddf7cda98f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10939 [updatecli] Bump elastic stack version to 8.8.1-bc8f9ea4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10942 [updatecli] Update to elastic/beats@9edc37365249
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10941 [updatecli] Update to elastic/beats@949d713359fe
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10947 [updatecli] Bump elastic stack version to 8.8.1-e731bb3f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10950 [updatecli] Update to elastic/beats@a8aeb843af85
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10959 [updatecli] Bump elastic stack version to 8.8.1-d9afcd4f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10961 [updatecli] Update to elastic/beats@a1bf8b879792
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10960 [updatecli] Update to elastic/beats@0672e11390f6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10954 docs: Clean up ssl/tls content
  docs/configure/tab-widgets/tls-config-widget.asciidoc
  docs/configure/tab-widgets/tls-config.asciidoc
  docs/legacy/copied-from-beats/docs/shared-ssl-config.asciidoc
  docs/legacy/ssl-input-settings.asciidoc
Labels: docs, backport-8.8

#10964 [updatecli] Update to elastic/beats@0f0599804d83
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10967 [updatecli] Bump Golang version to 1.19.10
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#10966 test: remove metadata fetcher ping test
  internal/sourcemap/metadata_fetcher_test.go
Labels: backport-skip

#10953 feat: update models for apm-data changes and prepare for pb migration
  NOTICE.txt
  go.mod
  go.sum
  internal/r8/deobfuscator_test.go
  internal/sourcemap/mapper.go
  internal/sourcemap/mapper_test.go
  internal/sourcemap/processor_test.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
Labels: backport-skip

#10632 Use local Kibana in Tiltfile if available
  Tiltfile
  script/wait_for_kibana.sh
  systemtest/apmservertest/config.go
  systemtest/kibana.go
Labels: backport-skip

#10971 [updatecli] Bump elastic stack version to 8.9.0-f766627c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10972 [updatecli] Update to elastic/beats@7a59da361983
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10973 Remove `timeseries.instance` in ingest pipeline for pre-8.6 compatibility
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ingest_pipeline/default.yml
  changelogs/head.asciidoc
  systemtest/ingest_test.go
Labels: backport-skip

#10968 Use "dynamic: runtime" instead of strict mapping for internal, TBS, and aggregation indices
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/data_stream/sampled_traces/manifest.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/manifest.yml
  changelogs/head.asciidoc
Labels: backport-skip

#10983 [updatecli] Bump elastic stack version to 8.8.2-009f3608
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10982 [updatecli] Bump elastic stack version to 8.9.0-37a365f9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10985 [updatecli] Update to elastic/beats@e9d8e83d5e01
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10986 ci: Update failed benchmarks Slack notification
  .ci/benchmarks.groovy
Labels: backport-skip

#10987 Setup semaphore for OTLP requests
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  internal/beater/api/intake/handler_test.go
  internal/beater/api/mux.go
  internal/beater/api/mux_test.go
  internal/beater/beater.go
  internal/beater/jaeger/grpc.go
  internal/beater/jaeger/grpc_test.go
  internal/beater/otlp/grpc.go
  internal/beater/otlp/grpc_test.go
  internal/beater/otlp/http.go
  internal/beater/otlp/http_test.go
  internal/beater/server.go
  internal/beater/tracing.go
Labels: backport-skip

#10988 [updatecli] Bump elastic stack version to 8.8.2-157bf445
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10990 [updatecli] Update to elastic/beats@4a16c6a58cfa
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10989 [updatecli] Bump elastic stack version to 8.9.0-f522d185
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10980 Move #6480 changelog entries to be BREAKING
  changelogs/8.0.asciidoc
Labels: backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8

#10992 feat: remove old model usage from sampling package
  x-pack/apm-server/sampling/pubsub/pubsub.go
Labels: backport-skip

#10978 feat: migrate otlp to protobuf models
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/api/mux.go
  internal/beater/jaeger/grpc.go
  internal/beater/jaeger/grpc_test.go
  internal/beater/otlp/grpc.go
  internal/beater/otlp/grpc_test.go
  internal/beater/otlp/http.go
  internal/beater/server.go
Labels: backport-skip

#10981 feat: migrate handler to modelpb and prepare for decoder migration
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/api/intake/handler.go
  internal/beater/api/intake/handler_test.go
  internal/beater/api/mux.go
  internal/model/modelprocessor/nop.go
Labels: backport-skip

#11006 [updatecli] Bump elastic stack version to 8.9.0-fefa3eb8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11009 [updatecli] Update to elastic/beats@67559c1d1bbb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10994 feat: add protobuf codec and migrate tail based sampling to protobuf
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/eventstorage/protobufcodec.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-skip

#11010 [updatecli] Bump elastic stack version to 8.9.0-473a43eb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11007 [updatecli] Bump elastic stack version to 8.8.2-0c8e2646
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11011 [updatecli] Update to elastic/beats@139a8bf9e199
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11012 [updatecli] Update to elastic/beats@8d2283f163f3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11013 feat: migrate decoders to protobuf
  NOTICE.txt
  go.mod
  go.sum
  systemtest/aggregation_test.go
  systemtest/huge_traces_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-skip

#11015 packaging/docker: vendor Mozilla CA certificates
  changelogs/head.asciidoc
  packaging/docker/Dockerfile
  packaging/docker/cacert.pem
Labels: backport-skip, v8.9.0, backport-8.8

#11014 feat: migrate metadata decoding to protobuf
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/api/intake/handler.go
  internal/beater/api/intake/handler_test.go
  internal/beater/api/mux.go
  internal/beater/api/mux_test.go
  internal/sourcemap/processor_test.go
Labels: backport-skip

#11019 feat: migrate r8 deobfuscator to protobuf
  internal/r8/deobfuscator.go
  internal/r8/deobfuscator_test.go
Labels: backport-skip

#11020 feat: bump apm-data for final protobuf cleanup
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/api/mux.go
  internal/beater/beater.go
  internal/beater/server.go
  x-pack/apm-server/main.go
Labels: backport-skip

#11024 [updatecli] Update to elastic/beats@36aa8847c007
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11025 [updatecli] Update to elastic/beats@601ee04b47a5
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11021 docs: describe all aggregated metrics
  docs/data-model.asciidoc
  docs/data/elasticsearch/metricset.json
  docs/data/elasticsearch/service_destination_metric.json
  docs/data/elasticsearch/service_summary_metric.json
  docs/data/elasticsearch/service_transaction_metric.json
  docs/data/elasticsearch/span_breakdown.json
  docs/data/elasticsearch/transaction_metric.json
  docs/exploring-es-data.asciidoc
  docs/metricset-indices.asciidoc
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-8.8

#11029 build: bump apm-data for decoder fix
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11026 dev-docs: add aggregated metrics
  dev_docs/trace_metrics.md
Labels: backport-skip

#11033 [updatecli] Bump elastic stack version to 8.8.2-6bda6fd3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11032 [updatecli] Bump elastic stack version to 8.9.0-27e9c674
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11034 [updatecli] Update to elastic/beats@342ec74bcece
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11035 [updatecli] Update to elastic/beats@bdb67bc10dbb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11036 Fix OTel span type determinism
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
Labels: backport-skip, v8.9.0

#11038 Add span and txn id for logs derived from otel spans
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
Labels: test-plan, backport-skip, v8.9.0

#11041 [updatecli] Bump elastic stack version to 8.9.0-0032a096
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11040 [updatecli] Bump elastic stack version to 8.8.2-c9f8756a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10884 [updatecli] Bump elastic stack version to 7.17.11-57933c35
  docker-compose.yml
Labels: automation, backport-skip

#11044 changelog: update changelog for 8.9 release
  CHANGELOG.asciidoc
  changelogs/8.9.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: backport-skip

#11051 [updatecli] Bump elastic stack version to 8.8.2-363ffebd
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11057 build: manually bump version to 8.10.0
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip

#11058 fix: bump apm-data for structpb conversion
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11061 [updatecli] Bump elastic stack version to 8.9.0-86c33b9d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11062 [updatecli] Bump elastic stack version to 8.8.2-c7e9ae2e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11063 [updatecli] Update to elastic/beats@79563daf8d54
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11064 [updatecli] Update to elastic/beats@7317d97ae71c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11069 [updatecli] Bump elastic stack version to 8.8.2-652417ba
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11050 [updatecli] Bump elastic stack version to 8.10.0-a51cd5d0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11070 [updatecli] Bump elastic stack version to 8.9.0-46e5f4bc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11067 test: update smoke test script to retrieve the correct latest patch version
  testing/smoke/lib.sh
Labels: backport-7.x

#11073 Set max-num-segments to 1 in rally config
  testing/rally/track.json
Labels: backport-skip

#11074 test: strip snapshot suffix and fix supported-os smoke test
  testing/smoke/lib.sh
Labels: backport-skip

#11052 [updatecli] Update to elastic/beats@8ac953185009
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11076 [updatecli] Update to elastic/beats@4b371f988103
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11077 [updatecli] Update to elastic/beats@92c6b2370e46
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11078 [updatecli] Bump elastic stack version to 8.8.2-33f1abe8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11083 [updatecli] Update to elastic/beats@e16de717459e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11081 [updatecli] Update to elastic/beats@36bcc4312e3c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11082 [updatecli] Update to elastic/beats@bef2c2b7c3d7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11084 build: bump apm-data for performance work
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11079 [updatecli] Bump elastic stack version to 8.10.0-aaab0171
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11090 [updatecli] Bump elastic stack version to 8.9.0-efd868fc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11091 [updatecli] Bump elastic stack version to 8.10.0-9fc07504
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11092 [updatecli] Bump elastic stack version to 8.8.2-438a24ff
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11093 [updatecli] Update to elastic/beats@533b3052573d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11099 Add 8.8.2 release notes
  changelogs/8.8.asciidoc
Labels: docs, backport-8.8, backport-8.9

#11097 docs: fix custom image configuration dockerfile
  docs/shared-docker.asciidoc
Labels: backport-8.7, backport-8.8, backport-8.9

#11106 Refactor refreshCache to remove anonymous func
  internal/agentcfg/elasticsearch.go
Labels: backport-skip

#11110 [updatecli] Bump elastic stack version to 8.8.2-41f17f3c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11111 [updatecli] Bump elastic stack version to 8.10.0-759b2cb2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11109 [updatecli] Bump elastic stack version to 8.9.0-bbb2ee5d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11113 [updatecli] Update to elastic/beats@f333d2549ddc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11100 Remove NOTE about port in Cloud ID
  docs/configure/outputs/output-cloud.asciidoc
Labels: docs, backport-8.8, backport-8.9

#11071 Migrate nightly benchmarks to GH Actions
  .ci/benchmarks.groovy
  .ci/jobs/apm-server-benckmarks-mbp.yml
  .ci/scripts/download-png-from-kibana.sh
  .github/workflows/benchmarks.yml
  testing/benchmark/Makefile
Labels: backport-skip

#11122 [updatecli] Bump elastic stack version to 8.10.0-18649b44
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11121 [updatecli] Bump elastic stack version to 8.8.2-ba369b11
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11124 [updatecli] Update to elastic/beats@cf6d82889687
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11125 [updatecli] Update to elastic/beats@e9272adcfcdd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
