Repository elastic/apm-server, pull requests merged in 2023-11, with the labels that each got.

#11882 docs: Clean up OpenTelemetry docs
  docs/otel-direct.asciidoc
  docs/otel-limitations.asciidoc
  docs/otel-metrics.asciidoc
  docs/otel-other.asciidoc
Labels: backport-8.10, backport-8.11

#11983 [updatecli] Update to elastic/beats@4f36168c91dc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11979 [updatecli] Bump elastic stack version to 7.17.15-c46e14f4
  docker-compose.yml
Labels: automation, backport-skip

#11985 [updatecli] Update to elastic/beats@e7703cde97f0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11984 [updatecli] Update to elastic/beats@57df903385a9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11982 [updatecli] Bump elastic stack version to 8.10.5-2cbba330
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11980 [updatecli] Bump elastic stack version to 8.12.0-0fcb9daf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11981 [updatecli] Bump elastic stack version to 8.11.0-2f2c6d79
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11978 feat: unified notification for smoke tests
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-schedule.yml
Labels: backport-skip

#11992 chore: enable dependabot version updates of github-actions yaml files
  .github/dependabot.yml
Labels: backport-skip

#11994 [updatecli] Bump elastic stack version to 8.10.5-d6b719a1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11996 [updatecli] Update to elastic/beats@496457dc0ce3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11995 [updatecli] Update to elastic/beats@b41cd433340f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12002 [updatecli] Bump elastic stack version to 8.10.5-952c31ce
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12004 [updatecli] Update to elastic/beats@d3facc808d2b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12003 [updatecli] Update to elastic/beats@48e0660ff060
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11993 [updatecli] Bump elastic stack version to 8.11.0-d4bb1214
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12001 [updatecli] Bump elastic stack version to 7.17.15-982e299a
  docker-compose.yml
Labels: automation, backport-skip

#12005 [updatecli] Update to elastic/beats@d8a7c7b9c29c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12009 [updatecli] Bump elastic stack version to 8.11.0-c2c48f8b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12008 [updatecli] Bump elastic stack version to 8.10.5-5c458ac8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12007 [updatecli] Bump elastic stack version to 7.17.15-3dc13f24
  docker-compose.yml
Labels: automation, backport-skip

#12010 [updatecli] Update to elastic/beats@1765a9722b39
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12006 smoke: Rename max_primary_shard_size to max_size
  testing/smoke/lib.sh
Labels: test, backport-skip

#12013 docs: Remove references to `processor.event`
  changelogs/8.10.asciidoc
  docs/configure/outputs/logstash.asciidoc
  docs/data-model.asciidoc
  docs/otel-metrics.asciidoc
Labels: backport-8.10, backport-8.11

#12016 [updatecli] Bump elastic stack version to 8.10.5-b9ae0cc2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12019 [updatecli] Update to elastic/beats@2ad905809b7c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12018 [updatecli] Update to elastic/beats@475eaf5784b4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12014 Update shared-docker.asciidoc
  docs/shared-docker.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10, backport-8.11

#12026 docs: Update base image to 22.04
  docs/shared-docker.asciidoc
Labels: backport-skip

#12017 [updatecli] Bump elastic stack version to 7.17.15-82adb10b
  docker-compose.yml
Labels: automation, backport-skip

#12027 [updatecli] Bump elastic stack version to 7.17.15-e209a10a
  docker-compose.yml
Labels: automation, backport-skip

#12032 [updatecli] Bump elastic stack version to 7.17.15-af34bce7
  docker-compose.yml
Labels: automation, backport-skip

#12034 [updatecli] Bump elastic stack version to 7.17.15-0438005b
  docker-compose.yml
Labels: automation, backport-skip

#11940 [updatecli] Update to elastic/beats@a58aeebb0ce6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12033 [updatecli] Bump elastic stack version to 8.11.1-c8848943
  docker-compose.yml
  systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
  systemtest/otlp_test.go
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12043 [updatecli] Bump elastic stack version to 8.11.1-2f6a8ab6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12042 [updatecli] Bump elastic stack version to 7.17.15-aad9f113
  docker-compose.yml
Labels: automation, backport-skip

#12030 [updatecli] Update to elastic/beats@9f93f932e9ae
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12029 [updatecli] Update to elastic/beats@f059c4bebc29
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12028 [updatecli] Bump elastic stack version to 8.12.0-9a986274
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12044 [updatecli] Update to elastic/beats@23df0d210e34
  .go-version
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12012 [updatecli] Update to elastic/beats@0f6417808f30
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12036 [updatecli] Bump Golang version to 1.21.4
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#11977 ubi: remove major version
  packaging.mk
Labels: backport-8.11

#12052 [updatecli] Update to elastic/beats@1d8039decfd0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12050 [updatecli] Update to elastic/beats@921dedec8f7d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12051 [updatecli] Update to elastic/beats@9cf9d4058976
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12055 [updatecli] Bump elastic stack version to 8.11.2-a8fca3bd
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12049 [updatecli] Bump elastic stack version to 8.12.0-82c28a25
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12058 [updatecli] Update to elastic/beats@0b975efb27b1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12056 [updatecli] Update to elastic/beats@0f656292d196
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12057 [updatecli] Update to elastic/beats@473f7197f840
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12061 [updatecli] Bump elastic stack version to 8.11.2-e0eeeb99
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12059 [updatecli] Bump elastic stack version to 7.17.16-95c51018
  docker-compose.yml
Labels: automation, backport-skip

#12060 [updatecli] Bump elastic stack version to 8.12.0-c18d0d89
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12063 [updatecli] Update to elastic/beats@23fc9409c3e3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12062 [updatecli] Update to elastic/beats@7ace47d4cb0d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12064 [updatecli] Update to elastic/beats@1569567660bf
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#12072 [updatecli] Update to elastic/beats@d82b2a0f6c59
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12070 [updatecli] Update to elastic/beats@c686ca76cc2e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12071 [updatecli] Update to elastic/beats@5a65bf6bac47
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12068 [updatecli] Bump elastic stack version to 8.12.0-35e3b343
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12069 [updatecli] Bump elastic stack version to 8.11.2-dc2c1eb6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12067 [updatecli] Bump elastic stack version to 7.17.16-b2590ce9
  docker-compose.yml
Labels: automation, backport-skip

#12074 buildkite: notify the robots team if any failures too
  .buildkite/package.yml
Labels: automation, backport-7.17, backport-8.11

#12083 [updatecli] Update to elastic/beats@97ceb2856ef1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12079 [updatecli] Bump elastic stack version to 8.11.2-b3ae3a61
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12078 [updatecli] Bump elastic stack version to 7.17.16-641039af
  docker-compose.yml
Labels: automation, backport-skip

#12077 ironbank: use ubi:9.3
  packaging/ironbank/Dockerfile
  packaging/ironbank/hardening_manifest.yaml
Labels: automation, backport-7.17, backport-8.11

#12081 [updatecli] Update to elastic/beats@3a79899c43d0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12085 chore: add APM Server in the slack message
  .github/workflows/benchmarks.yml
Labels: backport-skip

#12082 [updatecli] Update to elastic/beats@8e63e2cd1f3e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12091 [updatecli] Update to elastic/beats@886d078ba1f0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12088 [updatecli] Update to elastic/beats@e4be37dff22d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12090 [updatecli] Bump elastic stack version to 8.11.2-01f6d366
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12089 [updatecli] Bump elastic stack version to 7.17.16-1c2c59f9
  docker-compose.yml
Labels: automation, backport-skip

#12095 [updatecli] Update to elastic/beats@0956174a167e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12099 [updatecli] Bump elastic stack version to 7.17.16-03cd24d7
  docker-compose.yml
Labels: automation, backport-skip

#12101 [updatecli] Update to elastic/beats@1d3ac4d87b37
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12084 docs: Remove references to the mutate filter
  docs/configure/outputs/logstash.asciidoc
Labels: backport-8.10, backport-8.11

#12107 [updatecli] Bump elastic stack version to 7.17.16-456fee42
  docker-compose.yml
Labels: automation, backport-skip

#12108 [updatecli] Update to elastic/beats@5ba9f10d5252
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12111 [updatecli] Bump elastic stack version to 7.17.16-ffcb407a
  docker-compose.yml
Labels: automation, backport-skip

#12094 [updatecli] Update to elastic/beats@c1fdb00da13d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12100 [updatecli] Bump elastic stack version to 8.11.2-a6202097
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12102 apmpackage: prepare for move to apm-data plugin
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/apm_data_stream_migration.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  changelogs/head.asciidoc
  systemtest/approvals/TestIngestPipelineDataStreamMigration.approved.json
  systemtest/ingest_test.go
Labels: backport-skip, v8.12.0

#12119 [updatecli] Update to elastic/beats@803307587080
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12118 [updatecli] Update to elastic/beats@07f52c4280e5
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12093 [updatecli] Update to elastic/beats@284683dcc123
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12115 [updatecli] Bump elastic stack version to 7.17.16-36c2b6c2
  docker-compose.yml
Labels: automation, backport-skip

#12116 [updatecli] Bump elastic stack version to 8.11.2-8c8386ee
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12117 [updatecli] Bump elastic stack version to 8.12.0-d6c4164b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11608 docs: Add "Known issues" page
  docs/integrations-index.asciidoc
  docs/known-issues.asciidoc
Labels: docs, backport-8.10

#12125 [updatecli] Bump elastic stack version to 8.12.0-ec4853e4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12124 [updatecli] Bump elastic stack version to 8.11.2-1b4759d3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12128 [updatecli] Update to elastic/beats@b6010c06a733
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12126 [updatecli] Update to elastic/beats@6f32513e5037
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11969 docs: Update performance guide
  docs/processing-performance.asciidoc
Labels: backport-8.10, backport-8.11

#12123 [updatecli] Bump elastic stack version to 7.17.16-922f8875
  docker-compose.yml
Labels: automation, backport-skip

#11997 docs: Document custom field mappings
  docs/custom-index-template.asciidoc
  docs/images/custom-index-template-mapped-fields.png
  docs/images/custom-index-template-runtime-fields.png
Labels: backport-8.8, backport-8.9, backport-8.10, backport-8.11
