Repository elastic/apm-server, pull requests merged in 2023-12, with the labels that each got.

#12138 [updatecli] Update to elastic/beats@f5bd29fce6c7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12131 docs: Update source map documentation
  apm-server.yml
  docs/source-map-how-to.asciidoc
Labels: backport-8.7, backport-8.8, backport-8.9, backport-8.10, backport-8.11

#12137 [updatecli] Update to elastic/beats@b30a5ec82af0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12135 [updatecli] Bump elastic stack version to 8.12.0-9d443b17
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12136 [updatecli] Update to elastic/beats@be42a3369f94
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12150 Revise wait_for_integration ES implementation
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/beatertest/server.go
  internal/beater/checkintegration.go
  internal/beater/server_test.go
  internal/beater/waitready.go
Labels: backport-skip, v8.12.0

#12157 Revert some flattened fields to object type
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/ErrorsTxID.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
Labels: backport-skip, v8.12.0

#12134 [updatecli] Bump elastic stack version to 8.11.2-851afa34
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12161 [updatecli] Bump elastic stack version to 8.12.0-33e8d7e1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12162 [updatecli] Bump elastic stack version to 7.17.16-9916f602
  docker-compose.yml
Labels: automation, backport-skip

#12160 [updatecli] Bump elastic stack version to 8.11.2-9debce77
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12165 [updatecli] Update to elastic/beats@09d10802e53b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12171 backport: Add 8.12 branch
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: Team:Automation, impact:critical, backport-skip, release

#12192 [updatecli] Update to elastic/beats@1490a760f944
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12158 ironbank: enable /usr/bin/tini
  packaging/ironbank/Dockerfile
Labels: backport-7.17, backport-8.11

#12188 [updatecli] Bump elastic stack version to 8.12.0-9bbde39d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12195 [updatecli] Update to elastic/beats@ecdcbcc9d0a0
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#12187 [updatecli] Bump elastic stack version to 7.17.16-cf899701
  docker-compose.yml
Labels: automation, backport-skip

#12207 [Docs][OTel] Fix link to hostmetrics receiver
  docs/otel-direct.asciidoc
Labels: docs, backport-skip

#12168 [updatecli] Bump elastic stack version to 8.11.3-dce3355e
  docker-compose.yml
  systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
  systemtest/otlp_test.go
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12197 Add 8.11.3 release notes
  changelogs/8.11.asciidoc
Labels: backport-8.11, backport-8.12

#12172 docs: Update changelogs for 8.12 release
  CHANGELOG.asciidoc
  changelogs/8.12.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Automation, impact:critical, backport-skip, release

#12163 [updatecli] Update to elastic/beats@5c256faa5821
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12218 [updatecli] Bump elastic stack version to 8.12.0-3faaf80d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12230 [updatecli] Bump elastic stack version to 8.12.0-bde01754
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12169 [updatecli] Bump elastic stack version to 8.13.0-6av99u5d
  docker-compose.yml
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12229 smoke-test: sort latest versions using the semver format
  testing/smoke/lib.sh
Labels: automation, backport-skip

#12235 [updatecli] Bump elastic stack version to 8.13.0-h30gube9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12236 [updatecli] Bump elastic stack version to 8.12.0-0d7c3f79
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12164 [updatecli] Update to elastic/beats@a633696068ed
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12234 ci(release): initial implementation for the automated release steps
  .github/workflows/opentelemetry.yml
  .github/workflows/run-minor-release.yml
  .github/workflows/run-patch-release.yml
Labels: backport-skip, github_actions

#12240 Revert "Revise wait_for_integration ES implementation (#12150)"
  internal/beater/beater.go
  internal/beater/beatertest/server.go
  internal/beater/checkintegration.go
  internal/beater/server_test.go
  internal/beater/waitready.go
Labels: v8.12.0, backport-8.12

#12242 Update apm data
  NOTICE.txt
  changelogs/8.12.asciidoc
  go.mod
  go.sum
  internal/beater/api/intake/handler_test.go
  internal/beater/api/intake/test_approved/BodyReader.approved.json
  internal/beater/api/intake/test_approved/EmptyBody.approved.json
  internal/beater/api/intake/test_approved/FullQueue.approved.json
  internal/beater/api/intake/test_approved/FullQueueLegacy.approved.json
  internal/beater/api/intake/test_approved/integration/rum/TestRUMHandler_KillSwitchMiddleware/On.approved.json
  internal/beater/api/intake/test_approved/integration/rum/TestRUMHandler_NoAuthorizationRequired.approved.json
  internal/beater/api/mux_intake_rum_test.go
  systemtest/rum_test.go
Labels: backport-8.12

#12251 docs: Add tagged regions to changelog
  CHANGELOG.asciidoc
  changelogs/all-breaking-changes.asciidoc
Labels: backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-7.17, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8, backport-8.9, backport-8.10, backport-8.11, backport-8.12

#12269 Remove Nassim Kammah from list of ironbank maintainers
  packaging/ironbank/hardening_manifest.yaml
Labels: backport-7.17, backport-8.11, backport-8.12

#12246 [updatecli] Bump elastic stack version to 8.13.0-yufkxnwm
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12244 [updatecli] Bump elastic stack version to 8.12.0-cf3c9e0f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12245 [updatecli] Bump elastic stack version to 8.11.4-eb79a552
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12203 buildkite: retry docker login
  .buildkite/hooks/pre-command
Labels: backport-7.17, backport-8.12

#12243 [updatecli] Bump elastic stack version to 7.17.17-13e2edc2
  docker-compose.yml
Labels: automation, backport-skip

#12205 [updatecli] Update to elastic/beats@3935d2c3adc8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12247 [updatecli] Update to elastic/beats@b38ef4827c1e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12276 add test for OTLP metrics partial success response
  systemtest/otlp_test.go
Labels: backport-skip

#12281 [updatecli] Bump elastic stack version to 8.13.0-vqaxdghw
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12282 [updatecli] Update to elastic/beats@91d56ecbf5f4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12279 [updatecli] Bump elastic stack version to 8.11.4-8b9cf48f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12283 [updatecli] Update to elastic/beats@2f7ff01798d2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12278 [updatecli] Bump elastic stack version to 8.12.0-67b59f94
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12280 [updatecli] Bump elastic stack version to 7.17.17-6c067840
  docker-compose.yml
Labels: automation, backport-skip

#12277 update-beats: change condition to avoid update if no updates
  .ci/update-beats.yml
Labels: backport-skip

#12292 [updatecli] Bump elastic stack version to 7.17.17-514f2280
  docker-compose.yml
Labels: automation, backport-skip

#12290 [updatecli] Update to elastic/beats@dea4afd59f78
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12289 [updatecli] Update to elastic/beats@7c70c5a3c743
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12288 [updatecli] Update to elastic/beats@8a20bd2b137a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12287 [updatecli] Bump elastic stack version to 8.11.4-4f9102a1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12291 [updatecli] Update to elastic/beats@5663315ed0a3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12285 [updatecli] Bump elastic stack version to 8.13.0-qvykcic3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12286 [updatecli] Bump elastic stack version to 8.12.0-01443900
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12300 [updatecli] Bump elastic stack version to 8.12.0-e8c03076
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12298 [updatecli] Bump elastic stack version to 8.11.4-b057e528
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12299 [updatecli] Bump elastic stack version to 7.17.17-ae5188ce
  docker-compose.yml
Labels: automation, backport-skip

#12297 [updatecli] Bump elastic stack version to 8.13.0-pjcmn9wb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12296 [updatecli] Update to elastic/beats@62b33ef884be
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12293 [updatecli] Update to elastic/beats@f7467f59d14b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12294 [updatecli] Update to elastic/beats@8c4a40fdbfda
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12295 [updatecli] Update to elastic/beats@24ef01141ea2
  NOTICE.txt
  apm-server.docker.yml
  go.mod
  go.sum
Labels: automation, backport-skip

#12305 [updatecli] Bump elastic stack version to 8.12.0-2df616a6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12304 [updatecli] Bump elastic stack version to 8.13.0-4aavtlfc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12302 [updatecli] Bump elastic stack version to 8.11.4-33860d30
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12303 [updatecli] Bump elastic stack version to 7.17.17-2e4b288d
  docker-compose.yml
Labels: automation, backport-skip

#12306 [updatecli] Update to elastic/beats@6f7cd75cd72e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12308 [updatecli] Update to elastic/beats@151dcacde8a1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12307 [updatecli] Update to elastic/beats@ac1e16c327ae
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12319 [updatecli] Update to elastic/beats@62d83c43fc6f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12317 [updatecli] Update to elastic/beats@ea5e055ea1b1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12315 [updatecli] Bump elastic stack version to 8.13.0-4f8l51qr
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12316 [updatecli] Bump elastic stack version to 8.12.0-32d47279
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12314 [updatecli] Bump elastic stack version to 8.11.4-c3b12837
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12313 [updatecli] Bump elastic stack version to 7.17.17-c6804173
  docker-compose.yml
Labels: automation, backport-skip

#12318 [updatecli] Update to elastic/beats@2c25fb8ca824
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
