Repository elastic/apm-server, pull requests merged in 2023-04, with the labels that each got.

#10589 [updatecli] Bump elastic stack version to 8.7.1-8f4cbaed
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10588 [updatecli] Bump elastic stack version to 8.8.0-90aefda5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10592 fix: use dropped spans outcome in spanmetrics aggregation
  changelogs/8.7.asciidoc
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
Labels: backport-8.7

#10601 [updatecli] Update to elastic/beats@91906c9cdc61
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10573 Universal Profiling: Versioned RPC protocol
  systemtest/profiling_test.go
  x-pack/apm-server/profiling/auth.go
  x-pack/apm-server/profiling/collector.go
  x-pack/apm-server/profiling/grpcext.go
Labels: backport-8.7

#10594 metrics: Count context.DeadlineExceeded as timeout
  changelogs/8.7.asciidoc
  internal/beater/middleware/timeout_middleware.go
  internal/beater/middleware/timeout_middleware_test.go
Labels: bug, backport-8.7

#10606 [updatecli] Bump elastic stack version to 8.8.0-32eb4531
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10608 [updatecli] Bump elastic stack version to 8.7.1-f71f9a90
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10611 [updatecli] Update to elastic/beats@7fc0c41013f9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10610 [updatecli] Update to elastic/beats@5e6c8bc1e8f3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10605 metrics: Count GRPC codes.Canceled as timeout
  changelogs/8.7.asciidoc
  internal/beater/interceptors/metrics.go
  internal/beater/interceptors/metrics_test.go
  internal/beater/request/result.go
Labels: test-plan, backport-8.7, v8.7.1

#10615 [updatecli] Update to elastic/beats@be8e3e707bdb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10616 [updatecli] Update to elastic/beats@804e9c521aae
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10591 feat: wait for interval and sends events at once
  systemtest/benchtest/main.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#10624 Remove global labels from agg key for RUM services
  changelogs/8.7.asciidoc
  systemtest/aggregation_test.go
  x-pack/apm-server/aggregation/labels/labels.go
Labels: backport-8.7

#10629 [updatecli] Bump elastic stack version to 8.8.0-e41a7b29
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10614 [updatecli] Bump elastic stack version to 8.7.1-43e3152f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10630 [updatecli] Bump Golang version to 1.19.8
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#10628 Fix recursive statement in docs
  docs/upgrading-to-integration.asciidoc
Labels: backport-skip

#10625 [updatecli] Update to elastic/beats@ca13ce86cf08
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10635 Remove redundant aggregation groups on `faas.coldstart` in transaction metrics
  changelogs/8.7.asciidoc
  systemtest/aggregation_test.go
  systemtest/approvals/TestTransactionAggregation.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-8.7

#10639 [updatecli] Bump elastic stack version to 8.7.1-db61f97d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10644 [updatecli] Bump elastic stack version to 8.7.1-16046737
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10646 docs: move location of included content
  docs/monitor.asciidoc
Labels: backport-skip

#10622 Limit docker compose log max size
  docker-compose.yml
Labels: backport-skip

#10647 Update go-elasticsearch to v8.7.0
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#10652 [updatecli] Bump elastic stack version to 8.7.1-ec562123
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10657 [updatecli] Bump elastic stack version to 8.7.1-75c765d0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10660 [updatecli] Bump elastic stack version to 8.7.1-87dfc35a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10633 [updatecli] Bump elastic stack version to 8.8.0-f9cb2fd1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10661 apmsoak: update configs with new flags
  testing/apmsoak/main.tf
  testing/apmsoak/variables.tf
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/systemd.tpl
  testing/infra/terraform/modules/soaktest_workers/variables.tf
Labels: backport-skip

#10665 [updatecli] Bump elastic stack version to 8.8.0-6c13582a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10666 fix: do not overwrite logging options in containers or systemd environment
  internal/beatcmd/logging.go
Labels: backport-skip

#10673 apmsoak: Add option to rewrite transaction type
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#10674 [Docs] Add 'container.id' to the list of fields used for log correlation
  docs/log-correlation.asciidoc
Labels: backport-skip

#10636 test: retrieve apm-server log during smoke tests and move config to template
  .gitignore
  testing/smoke/supported-os/apm-server.yml.tftpl
  testing/smoke/supported-os/main.tf
Labels: backport-skip

#10682 [updatecli] Bump elastic stack version to 8.8.0-3f572553
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10683 [updatecli] Bump elastic stack version to 8.7.1-152da489
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10685 docs: be more assertive about new ES output
  docs/apm-breaking.asciidoc
Labels: backport-8.7

#10655 Universal Profiling: Improved RPC protocol and code sync
  NOTICE.txt
  go.mod
  go.sum
  systemtest/internal/profiling/collection_agent.pb.go
  systemtest/internal/profiling/collection_agent_grpc.pb.go
  systemtest/profiling_test.go
  x-pack/apm-server/main.go
  x-pack/apm-server/profiling/auth.go
  x-pack/apm-server/profiling/basehash/hash128.go
  x-pack/apm-server/profiling/collection_agent.pb.go
  x-pack/apm-server/profiling/collection_agent_grpc.pb.go
  x-pack/apm-server/profiling/collector.go
  x-pack/apm-server/profiling/collecttraces.go
  x-pack/apm-server/profiling/common/constants.go
  x-pack/apm-server/profiling/common/encode.go
  x-pack/apm-server/profiling/common/encodebody.go
  x-pack/apm-server/profiling/common/encodebody_test.go
  x-pack/apm-server/profiling/common/rle_test.go
  x-pack/apm-server/profiling/libpf/libpf.go
  x-pack/apm-server/profiling/metrics.json
  x-pack/apm-server/profiling/queue.go
Labels: backport-skip

#10692 [updatecli] Bump elastic stack version to 8.8.0-d63208f4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10693 [updatecli] Bump elastic stack version to 8.7.1-02d8313a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10680 Make machine type configurable for soaktest workers
  testing/apmsoak/main.tf
  testing/apmsoak/variables.tf
  testing/infra/terraform/modules/rally_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/variables.tf
Labels: backport-skip

#10695 [updatecli] Bump elastic stack version to 8.7.1-e95716f1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10696 [updatecli] Bump elastic stack version to 8.8.0-2a83168d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10687 systemtest/cmd/sendotlp: support passing a CA cert to verify remote s…
  systemtest/cmd/sendotlp/main.go
Labels: backport-skip

#10702 [updatecli] Bump elastic stack version to 8.8.0-4903e450
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10703 [updatecli] Bump elastic stack version to 8.7.1-1bebafa7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10701 Update changelog for 8.8 release
  CHANGELOG.asciidoc
  changelogs/8.7.asciidoc
  changelogs/8.8.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: backport-skip

#10699 backport: Add 8.8 branch
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: Team:Automation, impact:critical, backport-skip, release

#10709 [updatecli] Bump elastic stack version to 8.8.0-00fd5dad
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10719 Terraform fmt
  .github/workflows/terraform-fmt.yml
  testing/rally-cloud/main.tf
Labels: backport-skip

#10721 [updatecli] Bump elastic stack version to 8.8.0-ebff07ec
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10722 [updatecli] Bump elastic stack version to 8.8.0-ebff07ec
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#10697 Add support for mobile UI filtering
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  changelogs/head.asciidoc
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
Labels: backport-skip
