Repository elastic/apm-server, pull requests merged in 2023-02, with the labels that each got.

#10151 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10153 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10154 [automation] update elastic stack version for testing 8.7.0-87b130b2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10159 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10160 [automation] update libbeat and beats packaging
  go.mod
Labels: automation, backport-skip

#10161 [automation] update elastic stack version for testing 7.17.9-663e90b2
  docker-compose.yml
Labels: dependency, automation, backport-skip

#10148 Update names and comments for aggregations
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/main.go
Labels: backport-skip

#10166 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10167 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10168 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10171 [automation] update elastic stack version for testing 8.7.0-a8bf765b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10169 [automation] update elastic stack version for testing 8.6.2-b5f10a44
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10170 [automation] update elastic stack version for testing 7.17.9-f3ee8926
  docker-compose.yml
Labels: dependency, automation, backport-skip

#10172 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10173 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10176 [automation] update elastic stack version for testing 8.7.0-1ef3b708
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10175 [automation] update elastic stack version for testing 8.6.2-9fa37b7d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10165 Round servicetxmetrics event.success_count.sum
  changelogs/head.asciidoc
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
Labels: backport-skip

#10180 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10181 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10182 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10183 [automation] update elastic stack version for testing 8.7.0-dd1a1621
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10184 [automation] update elastic stack version for testing 8.6.2-74b1938c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10178 Pool histograms for reuse between active and inactive
  changelogs/head.asciidoc
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-skip

#10163 Add apmbench case for many aggregation groups
  systemtest/cmd/apmbench/main.go
Labels: backport-skip

#10140 docs: Remove txmetrics config
  docs/legacy/configuring.asciidoc
  docs/legacy/transaction-metrics.asciidoc
Labels: backport-7.17, backport-8.6

#10157 Adjust aggregations max_groups autosizing const
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/config/aggregation.go
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
Labels: backport-skip

#10190 Fix txmetrics space make size
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
Labels: backport-skip

#10195 testdata: remove client.ip from unknown-span-type
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  testdata/intake-v2/unknown-span-type.ndjson
Labels: backport-skip

#10193 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10185 Fix incorrect `transaction.duration.summary.sum` calculation
  changelogs/head.asciidoc
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-skip

#10192 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10198 [automation] update elastic stack version for testing 8.6.2-7c4539d9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: dependency, automation, backport-skip

#10197 Bump versions for 8.7.0 release
  .mergify.yml
  apmpackage/apm/changelog.yml
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip

#10186 Update changelog for 8.7 release
  CHANGELOG.asciidoc
  changelogs/8.7.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: backport-skip

#10201 profiling: do not store obsolete SourceType in frame metadata
  systemtest/approvals/TestProfiling/stackframes.approved.json
  x-pack/apm-server/profiling/collector.go
Labels: backport-skip

#10210 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10211 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10216 Fix servicetxmetrics histogram storing wrong values
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
Labels: backport-8.7

#10219 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10220 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10217 fix: improve smoke testing flexibility and resolve deployment issues
  testing/smoke/basic-upgrade/test.sh
  testing/smoke/legacy-managed/test.sh
  testing/smoke/legacy-standalone-major-managed/test.sh
  testing/smoke/lib.sh
  testing/smoke/supported-os/test.sh
Labels: backport-skip

#10230 [automation] update libbeat and beats packaging
  go.mod
  go.sum
Labels: automation, backport-skip

#10231 [automation] update libbeat and beats packaging
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10179 Migrate update-beats pipeline to updatecli and GH actions workflow
  .ci/jobs/update-beats-mbp.yml
  .ci/scripts/check-beats-version.sh
  .ci/scripts/update-beats.sh
  .ci/update-beats.groovy
  .ci/update-beats.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/update-beats.yml
Labels: backport-7.17, backport-8.6

#10222 action: bump elastic-stack
  .ci/bump-elastic-stack-snapshot.yml
  .ci/bump-stack-version.sh
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#10239 action: avoid fail fast and checkout branch
  .github/workflows/bump-elastic-stack.yml
Labels: automation, Team:Automation, backport-skip

#10240 updatecli: use automation label
  .ci/bump-elastic-stack-snapshot.yml
Labels: backport-8.6

#10187 Delete update-json-schema automation
  .ci/.jenkins-schema.yml
  .ci/jobs/update-json-schema.yml
  .ci/scripts/prepare-spec-changes.sh
  .ci/update-json-schema.groovy
Labels: backport-skip

#10251 action: use composite updatecli
  .github/workflows/bump-elastic-stack.yml
Labels: automation, backport-7.17, backport-8.6, backport-8.7

#10214 Use result from histogram instead of separate count and sum
  changelogs/8.7.asciidoc
  systemtest/approvals/TestServiceTransactionMetricsAggregation.approved.json
  systemtest/approvals/TestTransactionAggregation.approved.json
  systemtest/approvals/TestTransactionAggregationShutdown.approved.json
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-8.7

#10257 Universal Profiling: Tags for stateless elasticsearch impact
  x-pack/apm-server/profiling/ilm.go
Labels: backport-skip

#10270 [updatecli] Bump elastic stack version to 8.7.0-52171374
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10273 [updatecli] Bump elastic stack version to 8.7.0-35c038b9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10274 [updatecli] Bump elastic stack version to 8.6.2-8caa8b27
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10271 test: fix system test panic on compile error and avoid double close
  systemtest/aggregation_test.go
  systemtest/apmservertest/server.go
  systemtest/apmservertest/server_test.go
  systemtest/jaeger_test.go
  systemtest/logging_test.go
Labels: backport-skip

#10247 fix: close pipeline when stopping final batch processor
  internal/beater/beater.go
Labels: backport-8.6, backport-8.7

#10249 test: fix most goroutine leaks in unit tests
  internal/beater/otlp/http_test.go
  internal/publish/pub_test.go
  internal/sourcemap/body_caching_test.go
  internal/sourcemap/processor_test.go
Labels: backport-skip

#10280 [updatecli] Bump elastic stack version to 8.8.0-56b80d12
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10279 [updatecli] Bump elastic stack version to 8.6.2-03dd602a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10248 docs: Add Kibana endpoint config to non-ES outputs
  docs/legacy/copied-from-beats/outputs/console/docs/console.asciidoc
  docs/legacy/copied-from-beats/outputs/fileout/docs/fileout.asciidoc
  docs/legacy/copied-from-beats/outputs/kafka/docs/kafka.asciidoc
  docs/legacy/copied-from-beats/outputs/logstash/docs/logstash.asciidoc
  docs/legacy/copied-from-beats/outputs/redis/docs/redis.asciidoc
  docs/legacy/shared-kibana-endpoint.asciidoc
Labels: Team:Docs, backport-8.6, backport-8.7

#10260 docs: OTEL updates
  docs/diagrams/apm-otel-architecture.asciidoc
  docs/open-telemetry.asciidoc
  docs/otel-with-elastic.asciidoc
Labels: Team:Docs, backport-8.6, backport-8.7

#10226 docs: improve tbs config descriptions
  docs/apm-input-settings.asciidoc
Labels: Team:Docs, backport-8.6, backport-8.7

#10294 CI: only notify Slack of update-beats on failure
  .github/workflows/update-beats.yml
Labels: backport-skip

#10250 fix: accept --environment macos_service and udpate testcase to avoid race condition
  NOTICE.txt
  go.mod
  go.sum
  systemtest/cmdflags_test.go
Labels: backport-skip

#10278 Use composite action for updatecli workflow
  .github/workflows/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10244 Use elastic-stack-snapshot-branches action for update-beats workflow
  .ci/update-beats.yml
  .github/workflows/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10306 test: close tracer in logging test and avoid goroutine leak
  systemtest/logging_test.go
Labels: backport-skip

#10302 Fix service summary overflow bucket regression
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ingest_pipeline/default.yml
  systemtest/aggregation_test.go
  systemtest/apmservertest/config.go
  systemtest/approvals.go
  systemtest/approvals/TestServiceSummaryMetricsAggregationOverflow.approved.json
Labels: backport-8.7

#10196 Update release checklist
  dev_docs/RELEASES.md
Labels: backport-skip

#10296 test: close response body in TestServerRoot and fix goroutine leak
  internal/beater/server_test.go
Labels: backport-skip

#10311 [updatecli] Bump elastic stack version to 8.7.0-4412a58d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#9624 ci: enable smoke tests for supported OS
  .ci/schedule-daily.groovy
  .ci/smoke-tests-os.groovy
  testing/smoke/supported-os/main.tf
  testing/smoke/supported-os/test.sh
Labels: backport-8.6, backport-8.7

#10314 .github: unrevert notification change
  .github/workflows/update-beats.yml
Labels: backport-skip

#10298 benchtest: break out of infinite loop and fix goroutine leak
  systemtest/benchtest/expvar/metrics.go
Labels: backport-skip

#10316 benchmark: Run 2-3h after stack bump is run
  .ci/schedule-everyday.groovy
Labels: backport-skip

#10243 golang: bump automation with updatecli and GH actions
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#10317 feat: add support for rhel 9
  testing/smoke/supported-os/main.tf
  testing/smoke/supported-os/test.sh
Labels: backport-skip, backport-8.7

#10319 ci: remove update-beats daily from Jenkins
  .ci/schedule-daily.groovy
Labels: backport-skip

#10323 [updatecli] Bump elastic stack version to 8.7.0-91bd3c0f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10322 [updatecli] Bump elastic stack version to 8.8.0-4c33ca65
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10259 docs: Update standalone index docs
  docs/data-streams.asciidoc
  docs/legacy/exploring-es-data.asciidoc
Labels: Team:Docs, backport-8.5, backport-8.6, backport-8.7

#10325 feat: add macOS Catalina deprecation notice
  internal/beatcmd/beat.go
Labels: backport-skip

#10258 test: fix io.pipe locking the goroutine forever while writing
  systemtest/apmservertest/server.go
Labels: backport-skip

#10329 fix: invert args order for prefix check in deprecation notice
  internal/beatcmd/beat.go
Labels: backport-skip

#10297 Fix service destination labels regression
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
  docs/data-model.asciidoc
  systemtest/aggregation_test.go
  systemtest/approvals/TestServiceDestinationAggregation.approved.json
Labels: backport-8.7

#10130 Fix aggregations make batch size
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
Labels: backport-8.7

#10335 [updatecli] Bump elastic stack version to 8.8.0-4671daa2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10336 [updatecli] Bump elastic stack version to 8.7.0-b97ae348
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10334 test: always close agent container, even if the test did not fail
  systemtest/fleet_test.go
Labels: backport-skip

#10232 [automation] update libbeat and beats packaging
  .go-version
  Dockerfile
  NOTICE.txt
  docs/version.asciidoc
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#10330 Collect monitoring for the overflow metrics for all aggregations
  changelogs/8.7.asciidoc
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator.go
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator_test.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/main.go
Labels: test-plan, backport-8.7

#10228 test: remove cleanup hook for sourcemaps
  systemtest/elasticsearch.go
  systemtest/fleet_test.go
  systemtest/kibana.go
  systemtest/sourcemap_test.go
Labels: backport-skip

#10343 lint: solve linter issues
  systemtest/elasticsearch.go
Labels: backport-skip

#10344 [updatecli] Bump elastic stack version to 8.7.0-ec872331
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10345 [updatecli] Bump elastic stack version to 8.8.0-5d46a537
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10346 [updatecli] Bump elastic stack version to 7.17.10-d6610e36
  docker-compose.yml
Labels: automation, backport-skip

#10339 Relocate most modelprocessors to apm-data
  Makefile
  NOTICE.txt
  cmd/check-internal-metrics/main.go
  go.mod
  go.sum
  internal/beater/api/mux.go
  internal/beater/beater.go
  internal/beater/server.go
  internal/model/modelprocessor/chained.go
  internal/model/modelprocessor/culprit.go
  internal/model/modelprocessor/culprit_test.go
  internal/model/modelprocessor/datastream.go
  internal/model/modelprocessor/datastream_test.go
  internal/model/modelprocessor/dropped_spans_stats.go
  internal/model/modelprocessor/dropunsampled.go
  internal/model/modelprocessor/dropunsampled_test.go
  internal/model/modelprocessor/environment.go
  internal/model/modelprocessor/environment_test.go
  internal/model/modelprocessor/errormessage.go
  internal/model/modelprocessor/errormessage_test.go
  internal/model/modelprocessor/groupingkey.go
  internal/model/modelprocessor/groupingkey_test.go
  internal/model/modelprocessor/hostname.go
  internal/model/modelprocessor/hostname_test.go
  internal/model/modelprocessor/internal_metrics.go
  internal/model/modelprocessor/metricsetname.go
  internal/model/modelprocessor/metricsetname_test.go
  internal/model/modelprocessor/nodename.go
  internal/model/modelprocessor/nodename_test.go
  internal/model/modelprocessor/spantype.go
  internal/model/modelprocessor/spantype_test.go
  x-pack/apm-server/main.go
Labels: backport-skip

#10348 build: bump honnef.co/go/tools to v0.4.2
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#10347 test: close auth assertions response body
  systemtest/apikeycmd_test.go
Labels: backport-skip

#10355 [updatecli] Bump elastic stack version to 8.7.0-c05d21f2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10357 [updatecli] Bump elastic stack version to 8.8.0-ad6ea1d3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10358 [updatecli] Bump Golang version to 1.19.6
  .ci/packer_cache.sh
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: backport-skip

#10365 [updatecli] Bump elastic stack version to 8.7.0-0cf05406
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10366 [updatecli] Bump elastic stack version to 8.8.0-95622f9e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10364 [updatecli] Bump elastic stack version to 7.17.10-72c5bb9c
  docker-compose.yml
Labels: automation, backport-skip

#10362 Fixes issues with transaction metrics aggregation.
  changelogs/8.7.asciidoc
  x-pack/apm-server/aggregation/baseaggregator/space.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
Labels: backport-8.7

#10369 .ci: fix update-beats branch condition
  .ci/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10373 .ci: fix update-beats branch condition, take 2
  .ci/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10378 .ci: fix update-beats branch condition, take 3
  .ci/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10352 idxmgmt: don't return error from BuildSelector
  internal/idxmgmt/supporter_factory.go
  internal/idxmgmt/supporter_factory_test.go
Labels: test-plan, v8.7.0, backport-8.7

#10359 ci: update packer cache during bump golang action
  .ci/packer_cache.sh
  script/update_go_version.sh
Labels: backport-skip

#10360 fix: reset metadata fetcher init error after successful sync
  internal/sourcemap/metadata_fetcher.go
Labels: backport-skip

#10389 [updatecli] Bump elastic stack version to 8.7.0-8c4f161e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip
