Repository elastic/apm-server, pull requests merged in 2023-07, with the labels that each got.

#11128 ci: improve debuggability of benchmarks
  .github/workflows/benchmarks.yml
  testing/benchmark/outputs.tf
Labels: backport-skip

#11116 Add sourcemap periodic refresh tracing
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/beater_test.go
  internal/sourcemap/metadata_fetcher.go
  internal/sourcemap/metadata_fetcher_test.go
Labels: backport-skip

#11129 Add transaction for agent config periodic refresh
  changelogs/head.asciidoc
  internal/agentcfg/elasticsearch.go
  internal/agentcfg/elasticsearch_test.go
  internal/beater/beater.go
  internal/beater/server.go
Labels: backport-skip

#11130 Improve docs for running locally
  README.md
  docker-compose.yml
Labels: backport-skip

#11123 [updatecli] Bump elastic stack version to 8.9.0-024bad78
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11132 [updatecli] Bump elastic stack version to 8.8.3-1f4ea904
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11095 [updatecli] Update to elastic/beats@4efc7de24d41
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11135 Update to Go 1.20.x
  .go-version
  README.md
  cmd/intake-receiver/go.mod
  docs/version.asciidoc
  go.mod
  internal/beatcmd/init.go
  internal/glog/go.mod
  packaging/docker/Dockerfile
  systemtest/go.mod
  tools/go.mod
Labels: backport-skip

#11136 Fix benchmark notification
  .github/workflows/benchmarks.yml
Labels: backport-skip

#11089 Stop dropping metadata fields in span documents
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  changelogs/head.asciidoc
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
Labels: backport-skip

#11141 [updatecli] Update to elastic/beats@f7fa407aff97
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11140 [updatecli] Bump elastic stack version to 8.8.3-dcc440f7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11142 [updatecli] Update to elastic/beats@cbfc78da4595
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11133 [updatecli] Update to elastic/beats@e20a8d447b63
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11143 Update apm-data
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/beater.go
  internal/beater/processors.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_bench_test.go
Labels: backport-8.9

#11120 Correct license text for Elastic License 2.0
  changelogs/8.9.asciidoc
  licenses/ELASTIC-LICENSE-2.0.txt
Labels: backport-8.9

#11145 systemtest: fix TestMonitoring flakiness
  systemtest/go.mod
  systemtest/go.sum
  systemtest/monitoring_test.go
  systemtest/sampling_test.go
Labels: backport-skip

#11146 agentcfg: fix TestRun flakiness
  internal/agentcfg/elasticsearch.go
  internal/agentcfg/elasticsearch_test.go
Labels: backport-skip

#11119 Add ability to trigger benchmarks manually
  .ci/benchmarks.groovy
  .github/workflows/benchmarks.yml
Labels: backport-skip

#11150 [updatecli] Bump elastic stack version to 8.10.0-0d099cfb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11149 [updatecli] Bump elastic stack version to 8.8.3-9428e7c2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11151 [updatecli] Update to elastic/beats@8597ca78aba6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11153 [updatecli] Update to elastic/beats@06990e3e8821
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11137 sampling: use Marshal/UnmarshalVT
  NOTICE.txt
  go.mod
  x-pack/apm-server/sampling/eventstorage/jsoncodec.go
  x-pack/apm-server/sampling/eventstorage/protobufcodec.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
Labels: backport-skip

#11156 Setup tracer processor
  internal/beater/beater.go
  internal/model/modelprocessor/tracer.go
  internal/model/modelprocessor/tracer_test.go
Labels: backport-skip

#11152 [updatecli] Update to elastic/beats@3a044718ce36
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11157 [updatecli] Update to elastic/beats@f75a2ed898bc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11158 [updatecli] Update to elastic/beats@2b2623c88db4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11148 [doc] fix broken link to opentelemetry-collector/Memory Limiter Processor in the Otel Integration doc
  docs/otel-direct.asciidoc
Labels: backport-8.8, backport-8.9

#11163 Upgrade go-docappender to 0.2.0
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11164 [updatecli] Update to elastic/beats@e6f2d4dd1854
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11174 [updatecli] Update to elastic/beats@843206971c7e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11178 build: bump go-docappender for allocation improvements
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11169 fix incorrect "same-kind" strategy default
  docs/span-compression.asciidoc
Labels: backport-skip

#11180 [updatecli] Bump elastic stack version to 8.10.0-89405a28
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11181 [updatecli] Bump elastic stack version to 8.8.3-193fc993
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11139 [updatecli] Bump elastic stack version to 8.9.0-0f1ee255
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11182 [updatecli] Update to elastic/beats@89f73e8044f1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11054 [updatecli] Update to elastic/beats@7dfbf89356ab
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11184 test: use atomic values to resolve race condition in systemtests
  systemtest/benchtest/main_test.go
  systemtest/loadgen/eventhandler/handler_test.go
Labels: backport-skip

#11189 Update opentelemetry & jaeger Go modules
  NOTICE.txt
  go.mod
  go.sum
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_summary.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/cmd/sendotlp/main.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/otlp_test.go
Labels: backport-skip

#11166 systemtest: Use `elastic/apm-tools`
  Makefile
  go.mk
  systemtest/agentconfig_test.go
  systemtest/aggregation_test.go
  systemtest/apikeycmd_test.go
  systemtest/approvals.go
  systemtest/elasticsearch.go
  systemtest/environment_test.go
  systemtest/errorgrouping_test.go
  systemtest/errors_test.go
  systemtest/estest/client.go
  systemtest/estest/query.go
  systemtest/estest/request.go
  systemtest/estest/search.go
  systemtest/go.mod
  systemtest/go.sum
  systemtest/huge_traces_test.go
  systemtest/ingest_test.go
  systemtest/instrumentation_test.go
  systemtest/intake_async_test.go
  systemtest/intake_log_test.go
  systemtest/intake_test.go
  systemtest/internal/approvaltest/approvals.go
  systemtest/internal/approvaltest/cmd/check-approvals/main.go
  systemtest/jaeger_test.go
  systemtest/kibana.go
  systemtest/metrics_test.go
  systemtest/monitoring_test.go
  systemtest/otlp_test.go
  systemtest/profiling_test.go
  systemtest/rum_test.go
  systemtest/sampling_test.go
  systemtest/sourcemap_test.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: backport-skip

#11195 [updatecli] Bump elastic stack version to 8.10.0-daadfd9e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11196 [updatecli] Bump elastic stack version to 8.9.0-a302929e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11197 [updatecli] Bump elastic stack version to 8.8.3-b2365b79
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11198 [updatecli] Update to elastic/beats@0dbf0eb8e165
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11199 [updatecli] Update to elastic/beats@2dc3f675c783
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11168 Allow dynamic datasets and namespaces
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/manifest.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  apmpackage/apm/data_stream/error_logs/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/data_stream/rum_traces/manifest.yml
  apmpackage/apm/data_stream/sampled_traces/manifest.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/traces/manifest.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/manifest.yml
  changelogs/head.asciidoc
Labels: backport-skip

#11205 Configure metrics provider to send data to the elastic agent
  NOTICE.txt
  go.mod
  internal/beater/beater.go
Labels: backport-skip

#11206 [updatecli] Bump elastic stack version to 8.10.0-84ebde23
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11209 [updatecli] Update to elastic/beats@e705f6998746
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11210 [updatecli] Update to elastic/beats@5d974fd64425
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11211 [updatecli] Update to elastic/beats@56b6aebf766e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11177 docs: Add Otel logs preview badge and limitation
  docs/otel-direct.asciidoc
  docs/otel-limitations.asciidoc
Labels: backport-8.8, backport-8.9

#11162 docs: Install the APM integration without internet
  docs/configure/index.asciidoc
  docs/getting-started-apm-server.asciidoc
Labels: backport-8.8, backport-8.9

#11202 Set processor.* fields in mappings and ingest
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/rum_traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/traces/elasticsearch/ingest_pipeline/default.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
Labels: backport-skip

#11218 [updatecli] Bump elastic stack version to 8.10.0-464beb1d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11219 [updatecli] Bump elastic stack version to 8.9.0-905e99b1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11220 [updatecli] Bump elastic stack version to 8.8.3-40270fd0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11221 [updatecli] Update to elastic/beats@ebe6846ea448
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11222 [updatecli] Update to elastic/beats@b701377c9b12
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11223 [updatecli] Update to elastic/beats@58759691549d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11224 [updatecli] Bump Golang version to 1.20.6
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#11072 Universal Profiling: Remove all UP-related code and tests
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/config/config.go
  internal/beater/config/config_test.go
  internal/beater/config/profiling.go
  systemtest/apmservertest/config.go
  systemtest/internal/profiling/collection_agent.pb.go
  systemtest/internal/profiling/collection_agent_grpc.pb.go
  systemtest/profiling_test.go
  testing/docker/kibana/kibana.yml
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
  x-pack/apm-server/profiling/auth.go
  x-pack/apm-server/profiling/basehash/basehash.go
  x-pack/apm-server/profiling/basehash/hash128.go
  x-pack/apm-server/profiling/basehash/hash128_test.go
  x-pack/apm-server/profiling/basehash/hash64.go
  x-pack/apm-server/profiling/basehash/hash64_test.go
  x-pack/apm-server/profiling/collection_agent.pb.go
  x-pack/apm-server/profiling/collection_agent_grpc.pb.go
  x-pack/apm-server/profiling/collector.go
  x-pack/apm-server/profiling/collecttraces.go
  x-pack/apm-server/profiling/common/constants.go
  x-pack/apm-server/profiling/common/ecs.go
  x-pack/apm-server/profiling/common/encode.go
  x-pack/apm-server/profiling/common/encodebody.go
  x-pack/apm-server/profiling/common/encodebody_test.go
  x-pack/apm-server/profiling/common/rle.go
  x-pack/apm-server/profiling/common/rle_test.go
  x-pack/apm-server/profiling/common/timestamp.go
  x-pack/apm-server/profiling/grpcext.go
  x-pack/apm-server/profiling/ilm.go
  x-pack/apm-server/profiling/ilm_test.go
  x-pack/apm-server/profiling/libpf/libpf.go
  x-pack/apm-server/profiling/metrics.json
  x-pack/apm-server/profiling/monitoring.go
  x-pack/apm-server/profiling/queue.go
Labels: backport-skip, v8.9.0

#11194 [updatecli] Bump elastic stack version to 7.17.12-c78d45be
  docker-compose.yml
Labels: automation, backport-skip

#11200 [updatecli] Update to elastic/beats@fbd3ff8bd4ed
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11228 [updatecli] Bump elastic stack version to 7.17.12-08fbe972
  docker-compose.yml
Labels: automation, backport-skip

#11227 [updatecli] Bump elastic stack version to 8.8.3-a6972ae1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11231 [updatecli] Update to elastic/beats@061cb88e68e2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11234 [updatecli] Bump elastic stack version to 8.8.3-91900d44
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11235 [updatecli] Bump elastic stack version to 8.10.0-c2848ab2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11236 [updatecli] Bump elastic stack version to 8.9.0-446d2070
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11237 Update apm-data, use modelpb.IP
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/api/mux.go
  internal/beater/api/mux_test.go
  internal/beater/otlp/clientmetadata.go
  internal/beater/otlp/clientmetadata_test.go
Labels: backport-skip

#11238 Add CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip

#11028 Set processor.* fields in mappings and ingest
  NOTICE.txt
  go.mod
  go.sum
  internal/agentcfg/reporter.go
  internal/agentcfg/reporter_test.go
  internal/beater/server_test.go
  internal/model/modelprocessor/eventcounter.go
  internal/model/modelprocessor/eventcounter_test.go
  internal/model/modelprocessor/tracer_test.go
  internal/publish/pub_test.go
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/ErrorsTxID.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestIntakeLog/with_faas.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/absolute_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/relative_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  systemtest/go.mod
  systemtest/go.sum
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator.go
  x-pack/apm-server/aggregation/servicesummarymetrics/aggregator_test.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator.go
  x-pack/apm-server/aggregation/servicetxmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator.go
  x-pack/apm-server/aggregation/spanmetrics/aggregator_test.go
  x-pack/apm-server/aggregation/txmetrics/aggregator.go
  x-pack/apm-server/aggregation/txmetrics/aggregator_test.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/groups_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-skip, v8.10.0

#11242 Upgrade apm-data for the 8.9 branch
  NOTICE.txt
  go.mod
  go.sum
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
Labels: backport-skip

#11244 [updatecli] Update to elastic/beats@f52d38ac56a7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11232 [updatecli] Update to elastic/beats@195e58ee00a9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11246 [updatecli] Update to elastic/beats@97e8feb645ef
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11241 Upgrade apm-data for the main branch
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11248 [updatecli] Bump elastic stack version to 8.9.0-164e5e60
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11251 [updatecli] Update to elastic/beats@50d7b818d676
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11250 [updatecli] Update to elastic/beats@38e7b021cad7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11249 [updatecli] Update to elastic/beats@dd50d49baeb9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11254 [updatecli] Bump elastic stack version to 8.10.0-506cd98d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11256 [updatecli] Update to elastic/beats@c94ae741ccca
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11257 [updatecli] Update to elastic/beats@8a9d6f6c8a68
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11260 [updatecli] Bump elastic stack version to 8.9.0-4b9e2fa6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11263 [updatecli] Update to elastic/beats@b6c377c88447
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11261 [updatecli] Update to elastic/beats@04bd93334b34
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11258 test: enable pprof and expvar in tilt config
  testing/infra/k8s/base/stack/apm-server.yaml
Labels: backport-skip

#11271 [updatecli] Bump elastic stack version to 8.10.0-1f4b0cd0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11270 [updatecli] Bump elastic stack version to 7.17.12-624c085e
  docker-compose.yml
Labels: automation, backport-skip

#11275 [updatecli] Update to elastic/beats@53438292c5f6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11165 docs: update Logstash output docs
  docs/configure/outputs/logstash.asciidoc
  docs/shared-kibana-endpoint.asciidoc
Labels: backport-8.8, backport-8.9

#11279 [main] docs: redirects for removed pages (#10894)
  docs/redirects.asciidoc
Labels: backport-skip

#11268 build: bump go-docappender for heap usage fix
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-skip

#11287 [updatecli] Bump elastic stack version to 8.10.0-235feca2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11286 [updatecli] Bump elastic stack version to 7.17.12-7c1d40f1
  docker-compose.yml
Labels: automation, backport-skip

#11288 [updatecli] Update to elastic/beats@b1b4d8b7858c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11289 [updatecli] Update to elastic/beats@ecceadd8c8e2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11290 [updatecli] Update to elastic/beats@3f30e5ed2594
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11292 smoketest: install the specific apm-server and elastic-agent version instead of latest
  testing/infra/terraform/modules/standalone_apm_server/latest_apm_server.sh
  testing/infra/terraform/modules/standalone_apm_server/latest_elastic_agent.sh
  testing/infra/terraform/modules/standalone_apm_server/main.tf
Labels: backport-8.8, backport-8.9

#11299 [updatecli] Bump elastic stack version to 8.9.0-6b15bb32
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11255 [updatecli] Bump elastic stack version to 8.8.3-3c98aafb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11300 [updatecli] Update to elastic/beats@f60c665d6476
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11301 [updatecli] Update to elastic/beats@630c11fd72c7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11304 ci: migrate away from jenkins
  .ci/Jenkinsfile
  .ci/scripts/bench.sh
  .github/workflows/microbenchmark.yml
Labels: backport-skip

#11306 [updatecli] Bump elastic stack version to 8.10.0-439345ab
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11307 [updatecli] Update to elastic/beats@7fd27bf1f6c4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11204 Add link for .NET OTel bridge
  docs/otel-with-elastic.asciidoc
Labels: backport-skip

#11296 ci: Only notify benchmarks failure via Slack on Nightly scheduled run
  .github/workflows/benchmarks.yml
Labels: backport-skip

#10993 apmbench: Re-enable OTLP traces benchmark
  systemtest/cmd/apmbench/main.go
Labels: backport-skip

#11311 build: bump apm-data
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/processors.go
  internal/publish/pub.go
  systemtest/approvals/TestCompressedSpans.approved.json
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestErrorIngest.approved.json
  systemtest/approvals/TestFleetIntegration.approved.json
  systemtest/approvals/TestFleetIntegrationSourcemap.approved.json
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/ErrorsTxID.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/MinimalEvents.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestIntake/UnknownSpanType.approved.json
  systemtest/approvals/TestIntakeLog/with_faas.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/absolute_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMErrorSourcemapping/relative_bundle_filepath/standalone.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/approvals/TestRUMSpanSourcemapping.approved.json
  systemtest/approvals/TestRUMXForwardedFor.approved.json
  systemtest/approvals/TestTransactionDroppedSpansStatsTransaction.approved.json
  systemtest/huge_traces_test.go
  systemtest/sampling_test.go
  x-pack/apm-server/sampling/pubsub/pubsub.go
  x-pack/apm-server/sampling/pubsub/pubsub_test.go
Labels: backport-skip

#11313 [updatecli] Bump elastic stack version to 8.10.0-ec4cafa5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11305 [updatecli] Bump elastic stack version to 8.8.3-e0b5ba55
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11314 [updatecli] Update to elastic/beats@b2d501789fc1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11316 [updatecli] Bump elastic stack version to 8.9.1-44a814f0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11319 Fix benchmark tf OTEL_EXPORTER_OTLP_ENDPOINT to run OTLP bench
  testing/infra/terraform/modules/benchmark_executor/apmbench.tf
Labels: backport-skip
