Repository elastic/apm-server, pull requests merged in 2023-10, with the labels that each got.

#11739 Scale service destination based on available memory
  changelogs/head.asciidoc
  docs/data-model.asciidoc
  internal/beater/beater.go
Labels: backport-skip

#11764 systemtest: Fix geoip changes
  systemtest/approvals/TestIntake/Errors.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
Labels: backport-8.10

#11761 docs: Update changelogs for 8.11 release
  CHANGELOG.asciidoc
  changelogs/8.11.asciidoc
  changelogs/head.asciidoc
  docs/release-notes.asciidoc
Labels: Team:Automation, impact:critical, backport-skip, release

#11755 [updatecli] Bump elastic stack version to 7.17.14-78860399
  docker-compose.yml
Labels: automation, backport-skip

#11769 tools: update elastic-package to v0.88.0
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#11763 [updatecli] Update to elastic/beats@c1918b0509c8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11749 [updatecli] Update to elastic/beats@ea73410c20ec
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11748 [updatecli] Bump elastic stack version to 8.11.0-4e7ff248
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11747 [updatecli] Bump elastic stack version to 8.10.3-75e0d7cb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11776 [updatecli] Update to elastic/beats@b301d3278d75
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11775 [updatecli] Update to elastic/beats@2988148e3ea5
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11777 [updatecli] Update to elastic/beats@37113021c2d2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11773 [updatecli] Bump elastic stack version to 8.11.0-867cd584
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11729 Switch built-in ILM rollover policies from max_size to max_primary_shard_size
  apmpackage/apm/data_stream/app_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/app_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/error_logs/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/internal_metrics/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/rum_traces/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.1m.json
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.1m.json
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.1m.json
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/traces/elasticsearch/ilm/default_policy.json
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.1m.json
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  changelogs/head.asciidoc
  testing/smoke/lib.sh
Labels: backport-skip

#11780 ironbank: bump version to 8.8
  packaging/ironbank/Dockerfile
Labels: backport-7.17, backport-8.10, backport-8.11

#11788 ironbank: update hardening to 8.8
  packaging/ironbank/hardening_manifest.yaml
Labels: backport-7.17, backport-8.10, backport-8.11

#11794 [updatecli] Bump elastic stack version to 7.17.14-a522fb9c
  docker-compose.yml
Labels: automation, backport-skip

#11796 [updatecli] Update to elastic/beats@e4bb7549a25c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11795 [updatecli] Update to elastic/beats@7877074cc606
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11792 [updatecli] Bump elastic stack version to 8.11.0-dfefa400
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11793 [updatecli] Bump elastic stack version to 8.10.3-17f9519a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11801 [updatecli] Update to elastic/beats@b25934a799d9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11803 [updatecli] Update to elastic/beats@a4f8aa1ae6af
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11816 [updatecli] Update to elastic/beats@04a0022641d9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11817 [updatecli] Update to elastic/beats@332917dbd4c8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11821 build: bump go version to 1.21.3
  .go-version
  NOTICE.txt
  cmd/intake-receiver/go.mod
  docs/version.asciidoc
  go.mod
  go.sum
  internal/glog/go.mod
  packaging/docker/Dockerfile
  script/update_go_version.sh
  systemtest/go.mod
  tools/go.mod
Labels: backport-8.10, backport-8.11

#11833 [updatecli] Update to elastic/beats@73303ae8c759
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11829 [updatecli] Bump elastic stack version to 8.10.3-35c43be1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11832 [updatecli] Bump elastic stack version to 8.11.0-4acbdbb1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11831 [updatecli] Bump elastic stack version to 8.12.0-3a221f77
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11834 [updatecli] Update to elastic/beats@093757b9eca6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11839 [updatecli] Bump elastic stack version to 8.11.0-60b804d4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11838 [updatecli] Bump elastic stack version to 8.10.4-b2fddf0a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11837 [updatecli] Bump elastic stack version to 8.12.0-1a1295ff
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11840 [updatecli] Update to elastic/beats@e322104a8cc2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11841 [updatecli] Update to elastic/beats@276935866238
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11842 [updatecli] Update to elastic/beats@10b198c985eb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11853 [updatecli] Update to elastic/beats@89030c0055c9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11852 [updatecli] Update to elastic/beats@8a707127fb2b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11850 [updatecli] Bump elastic stack version to 8.10.4-df8d75ce
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11851 [updatecli] Bump elastic stack version to 8.12.0-cb808527
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11849 [updatecli] Bump elastic stack version to 8.11.0-820fdcd6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11855 action: free disk space in python-system-tests
  .github/workflows/ci.yml
Labels: backport-skip

#11830 [updatecli] Bump elastic stack version to 7.17.15-a0c3fd00
  docker-compose.yml
Labels: automation, backport-skip

#11756 [updatecli] Update to elastic/beats@69b29de7c115
  NOTICE.txt
  beater/server_test.go
  go.mod
  go.sum
Labels: automation, backport-skip

#11864 Add 8.10.4 release notes
  changelogs/8.10.asciidoc
  changelogs/head.asciidoc
Labels: backport-8.10, backport-8.11

#11863 [updatecli] Update to elastic/beats@6be0d18448bb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11862 [updatecli] Update to elastic/beats@f17aa541281a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11860 [updatecli] Bump elastic stack version to 8.12.0-1359bda9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11858 [updatecli] Bump elastic stack version to 8.10.4-945697b8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11859 [updatecli] Bump elastic stack version to 8.11.0-48d7ee6d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11868 Remove unused 386 file
  x-pack/apm-server/aggregation_386.go
Labels: backport-skip

#11878 [updatecli] Update to elastic/beats@29482b585059
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11877 [updatecli] Bump elastic stack version to 8.11.0-6b5c9b80
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11879 [updatecli] Update to elastic/beats@54416d5c7908
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11876 [updatecli] Bump elastic stack version to 8.10.4-ba5798e3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11886 [updatecli] Bump elastic stack version to 7.17.15-310ac563
  docker-compose.yml
Labels: automation, backport-skip

#11885 [updatecli] Bump elastic stack version to 8.10.5-fede41a8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11884 [updatecli] Bump elastic stack version to 8.11.0-50f754c3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11889 [updatecli] Update to elastic/beats@d3c42ef75b93
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11888 [updatecli] Update to elastic/beats@79ea0204fbb0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11890 [updatecli] Update to elastic/beats@98d5be29b3cb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11854 docs: Fix Go distributed tracing example
  docs/tab-widgets/distributed-trace-receive.asciidoc
  docs/tab-widgets/distributed-trace-send.asciidoc
Labels: backport-7.17, backport-8.10, backport-8.11

#11741 docs: Document privileges to read RUM source maps; Update examples
  docs/access-api-keys.asciidoc
  docs/configure/rum.asciidoc
  docs/feature-roles.asciidoc
Labels: backport-8.7, backport-8.8, backport-8.9, backport-8.10, backport-8.11

#11887 [updatecli] Update to elastic/beats@63af3b695af1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11902 [updatecli] Bump elastic stack version to 8.11.0-64ca6348
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11900 [updatecli] Bump elastic stack version to 7.17.15-ae1f480c
  docker-compose.yml
Labels: automation, backport-skip

#11901 [updatecli] Bump elastic stack version to 8.10.5-69d64a75
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11903 [updatecli] Update to elastic/beats@67699c399860
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11904 [updatecli] Update to elastic/beats@bf4aa9e7dc27
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11905 Fix service destination max group scaling based on memory
  internal/beater/beater.go
  internal/beater/config/aggregation.go
  internal/beater/config/config_test.go
Labels: test-plan, v8.11.0, backport-8.11

#11907 [updatecli] Bump elastic stack version to 8.10.5-0028f476
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11908 [updatecli] Bump elastic stack version to 8.12.0-129ce746
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11909 [updatecli] Bump elastic stack version to 7.17.15-3f916b1e
  docker-compose.yml
Labels: automation, backport-skip

#11911 [updatecli] Update to elastic/beats@a0e7f5d7b830
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11913 [updatecli] Update to elastic/beats@450302fbee29
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11910 [updatecli] Update to elastic/beats@74c241a959eb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11914 changelog: add entry for datastream changes in 8.10
  changelogs/8.10.asciidoc
Labels: backport-8.10, backport-8.11

#11922 [updatecli] Bump elastic stack version to 8.10.5-b919c0d9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11920 [updatecli] Bump elastic stack version to 8.11.0-f8ea8c6e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11921 [updatecli] Bump elastic stack version to 8.12.0-0f0dbad4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11923 [updatecli] Update to elastic/beats@455461486c59
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11924 [updatecli] Update to elastic/beats@127703245317
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11925 [updatecli] Update to elastic/beats@2c109f0093f1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11881 docs: clarify the usage of the server information endpoint
  docs/api-info.asciidoc
Labels: docs, Team:Docs, backport-skip

#11883 Make OTLP input return partial success response
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  internal/beater/otlp/grpc.go
  internal/beater/otlp/http.go
Labels: backport-skip

#11926 fix: correct base Docker image names
  packaging/ironbank/Dockerfile
  packaging/ironbank/hardening_manifest.yaml
Labels: bug, backport-7.17, backport-8.10, backport-8.11

#11927 ubi9: update the reference as done with the ironbank
  packaging.mk
  tools/notice/dependencies.csv.tmpl
Labels: backport-7.17, backport-8.10, backport-8.11

#11937 [updatecli] Bump elastic stack version to 8.11.0-26e5e008
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11936 [updatecli] Bump elastic stack version to 7.17.15-75139b44
  docker-compose.yml
Labels: automation, backport-skip

#11939 [updatecli] Update to elastic/beats@fe32436b2e80
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11938 [updatecli] Update to elastic/beats@703ecffa54dd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11931 mergify: add backport label for the 7.17 backports
  .mergify.yml
Labels: backport-skip

#11943 [updatecli] Update to elastic/beats@fd0446ff94e9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11912 [updatecli] Update to elastic/beats@bbf0111c1d50
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/beatertest/output.go
  internal/elasticsearch/config_test.go
Labels: automation, backport-skip

#11941 docs: Remove remaining uses of "legacy" from the docs
  docs/apm-breaking.asciidoc
  docs/common-problems.asciidoc
  docs/integrations-index.asciidoc
  docs/upgrading-to-8.x.asciidoc
  docs/upgrading-to-integration.asciidoc
Labels: backport-8.10, backport-8.11

#11942 docs: Update include file path
  docs/apm-quick-start.asciidoc
Labels: backport-8.11

#11947 [updatecli] Bump elastic stack version to 8.11.0-6c3c780b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11946 [updatecli] Bump elastic stack version to 8.12.0-f9668451
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11949 [updatecli] Update to elastic/beats@88d866bae9fd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11948 [updatecli] Update to elastic/beats@d792f05bb5b0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11950 [updatecli] Update to elastic/beats@ee864b52d115
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11955 [updatecli] Bump elastic stack version to 8.12.0-fa958a90
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11957 [updatecli] Update to elastic/beats@bb2793eab632
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11958 [updatecli] Update to elastic/beats@27792cfd5166
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11959 Update OTel head-based sampling limitation
  docs/sampling.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10, backport-8.11

#11963 [updatecli] Bump elastic stack version to 8.10.5-4e5678b2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11964 [updatecli] Bump elastic stack version to 8.12.0-bb5042c3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11966 [updatecli] Update to elastic/beats@1e80ba2dcdbc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11965 [updatecli] Update to elastic/beats@edde82d12e28
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11967 [updatecli] Update to elastic/beats@adcd4b0c7cc2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#11961 ci(action): minor changes in the smoke tests
  .github/workflows/generate-smoke-tests-list/action.yml
  .github/workflows/setup-cluster-env/action.yml
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
Labels: backport-skip

#11962 [updatecli] Bump elastic stack version to 8.11.0-052083ba
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#11975 8.11 release note updates
  changelogs/8.11.asciidoc
  docs/apm-breaking.asciidoc
Labels: backport-8.11
