Repository elastic/apm-server, pull requests merged in 2023-03, with the labels that each got.

#10380 [updatecli] Update to elastic/beats@26153f4e61c09f3776bdd20a0c6cc239540a64d8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10381 [updatecli] Update to elastic/beats@0569e9710f428e229a73347182a1aa120fbb31ea
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10390 [updatecli] Update to elastic/beats@507243683f672a5546a9e7c2ffc38d234d043a9a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10391 [updatecli] Update to elastic/beats@7d27bf4a2a79ed99763a7f0963e47cf0b1092e30
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10393 [updatecli] Update to elastic/beats@3dbd8fb05a1ef477e18f169d8922cc500582bbd6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10396 [updatecli] Bump elastic stack version to 8.8.0-431cc5c2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10397 [updatecli] Bump elastic stack version to 8.7.0-0e27acda
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10394 mage: set safe.directory for crossbuild
  magefile.go
Labels: backport-skip

#10356 [updatecli] Bump elastic stack version to 8.6.3-05dd8895
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10395 [updatecli] Bump elastic stack version to 7.17.10-d54c5387
  docker-compose.yml
Labels: automation, backport-skip

#10392 [updatecli] Update to elastic/beats@bd1487f37b3b9e62279c1dfe7da05159cc559baf
  NOTICE.txt
  go.mod
  go.sum
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#10384 updatecli: set branch where PRs are created from, update PR title and description
  .ci/bump-elastic-stack-snapshot.yml
  .ci/bump-golang.yml
  .ci/update-beats.yml
  .mergify.yml
Labels: backport-skip

#10367 fix: remove hardcoded timeout and don't block when fetching sourcemaps
  internal/beater/beater_test.go
  internal/sourcemap/chained.go
  internal/sourcemap/metadata_fetcher.go
  internal/sourcemap/sourcemap_fetcher.go
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/elasticsearch.go
  systemtest/kibana.go
  systemtest/sourcemap_test.go
Labels: test-plan, v8.7.0, backport-8.7

#10402 [updatecli] Update to elastic/beats@3bf1c0ee503119b5ccdc2d625a1f58bf87698f9f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10401 [updatecli] Update to elastic/beats@90a92f753dfeb6947060f367ceb14d4972aa96e6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10400 [updatecli] Update to elastic/beats@bd1487f37b3b9e62279c1dfe7da05159cc559baf
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10377 chore: bring up to date `apm-server.yml`
  apm-server.docker.yml
  apm-server.yml
  docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
Labels: backport-8.7

#10403 Terraform: Pin version to `0.5.1` for now
  testing/benchmark/main.tf
  testing/cloud/main.tf
  testing/infra/terraform/modules/ec_deployment/terraform.tf
  testing/rally-cloud/main.tf
  testing/smoke/main.tf
  testing/smoke/supported-os/main.tf
Labels: backport-8.7

#10407 fix: re-add max-procs to config options
  apm-server.docker.yml
  apm-server.yml
Labels: backport-8.7

#10410 [updatecli] Bump elastic stack version to 8.7.0-b02b23e7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10411 [updatecli] Bump elastic stack version to 8.8.0-3648efbb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10409 [updatecli] Bump elastic stack version to 8.6.3-70d2e959
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10414 [updatecli] Update to elastic/beats@3dbd8fb05a1ef477e18f169d8922cc500582bbd6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10418 [updatecli] Bump elastic stack version to 8.7.0-a77bb5f1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10419 [updatecli] Bump elastic stack version to 8.8.0-4dc109f9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10412 [updatecli] Update to elastic/beats@64f0ddf2c914c0d7664896b0296f094d46599fd7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10421 [updatecli] Update to elastic/beats@3bf1c0ee503119b5ccdc2d625a1f58bf87698f9f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10416 [updatecli] Bump elastic stack version to 7.17.10-274f22a3
  docker-compose.yml
Labels: automation, backport-skip

#10417 [updatecli] Bump elastic stack version to 8.6.3-3395a806
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10420 [updatecli] Update to elastic/beats@caea0abd4636dbfe2b0dabcb9ae30cde398c1a84
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10422 10m,60m metrics: Update delete phase to 180d, 390d
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_destination_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_summary_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/service_transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.10m.json
  apmpackage/apm/data_stream/transaction_interval_metrics/elasticsearch/ilm/default_policy.60m.json
Labels: backport-8.7

#10424 Rename organisation label to obs as per guidelines
  testing/infra/terraform/modules/tags/output.tf
Labels: backport-skip

#10426 [updatecli] Update to elastic/beats@3bf1c0ee503119b5ccdc2d625a1f58bf87698f9f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10428 [updatecli] Update to elastic/beats@caea0abd4636dbfe2b0dabcb9ae30cde398c1a84
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10431 [updatecli] Bump elastic stack version to 8.7.0-07a35681
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10432 [updatecli] Bump elastic stack version to 8.6.3-a99e7a4f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10433 [updatecli] Bump elastic stack version to 8.8.0-424dfdb7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10430 [updatecli] Bump elastic stack version to 7.17.10-26a8527c
  docker-compose.yml
Labels: automation, backport-skip

#10439 [updatecli] Bump elastic stack version to 8.8.0-ba3f07b2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10440 [updatecli] Update to elastic/beats@6938716440bee408f89e293f2b6d972bb08d45b2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10434 [updatecli] Update to elastic/beats@a8ab071c4ac09e99891af05595294a8473b86473
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10441 [updatecli] Update to elastic/beats@45c5190e4d369b11074abe9549dd0bfe82f3d08c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10436 Fix updatecli update-beats pipeline
  .ci/update-beats.yml
Labels: backport-7.17, backport-8.6, backport-8.7

#10452 [updatecli] Update to elastic/beats@c0e86bac6055
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10450 [updatecli] Update to elastic/beats@88b1cacdb103
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10453 [updatecli] Update to elastic/beats@b850575c9095
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10451 [updatecli] Update to elastic/beats@ae7cd86bad7a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10353 test: update testcontainer library and remove reaper code
  systemtest/cmd/buildapm/main.go
  systemtest/containers.go
  systemtest/go.mod
  systemtest/go.sum
Labels: backport-skip

#10455 [updatecli] Bump elastic stack version to 8.6.3-fdab5f2a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10457 update-beats: only update beats module
  Makefile
Labels: backport-7.17, backport-8.6, backport-8.7

#10435 test: fix sourcemap flaky tests and related issues
  systemtest/apmservertest/config.go
  systemtest/approvals/TestNoMatchingSourcemap.approved.json
  systemtest/approvals/TestRUMRoutingIntegration.approved.json
  systemtest/estest/search.go
  systemtest/fleet_test.go
  systemtest/rum_test.go
  systemtest/sourcemap_test.go
Labels: backport-8.7

#10456 feat: stores app logs in service-specific data stream
  NOTICE.txt
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/manifest.yml
  changelogs/head.asciidoc
  docs/data-streams.asciidoc
  go.mod
  go.sum
  systemtest/approvals/TestIntakeLog/with_faas.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestOTLPGRPCLogs.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/intake_log_test.go
Labels: backport-skip

#10464 [updatecli] Update to elastic/beats@9b3fda48fcf6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10466 [updatecli] Update to elastic/beats@1cffca14510b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10462 feat: add APIKey for apmsoak
  systemtest/benchtest/clients.go
  systemtest/gencorpora/gencorpora.go
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/loadgen/eventhandler/replay_transport.go
  systemtest/soaktest/soaktest.go
  testing/apmsoak/main.tf
  testing/apmsoak/terraform.tfvars.example
  testing/apmsoak/variables.tf
  testing/infra/terraform/modules/benchmark_executor/README.md
  testing/infra/terraform/modules/ec_deployment/README.md
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/systemd.tpl
  testing/infra/terraform/modules/soaktest_workers/variables.tf
Labels: backport-skip

#10469 [updatecli] Update to elastic/beats@e7e6dacfca20
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10472 [updatecli] Bump Golang version to 1.19.7
  .go-version
  docs/version.asciidoc
  packaging/docker/Dockerfile
Labels: automation, backport-skip

#10474 [updatecli] Bump elastic stack version to 8.7.0-a1ea0fcc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10476 [updatecli] Update to elastic/beats@710bcfb4727e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10477 [updatecli] Update to elastic/beats@d91a27e6bdb8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10473 [updatecli] Bump elastic stack version to 7.17.10-58141e3d
  docker-compose.yml
Labels: automation, backport-skip

#10470 [updatecli] Update to elastic/beats@a03fb15c2429
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10479 [updatecli] Bump elastic stack version to 8.6.3-677cac11
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10478 [updatecli] Bump elastic stack version to 7.17.10-61c4df0d
  docker-compose.yml
Labels: automation, backport-skip

#10484 [updatecli] Update to elastic/beats@280c44829c72
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10483 [updatecli] Update to elastic/beats@6b3d63e85df8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10487 [updatecli] Update to elastic/beats@b86912dbdd66
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10490 [updatecli] Bump elastic stack version to 8.7.0-b1c1f67f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10489 [updatecli] Bump elastic stack version to 8.6.3-e2404ee6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10488 [updatecli] Bump elastic stack version to 7.17.10-fb2882fc
  docker-compose.yml
Labels: automation, backport-skip

#10481 [updatecli] Update to elastic/beats@e0f6e17e7d8b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10499 [updatecli] Update to elastic/beats@0587bb0d175a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10496 [updatecli] Bump elastic stack version to 8.6.3-43bbf105
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10497 [updatecli] Update to elastic/beats@37939bdc756f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10500 [updatecli] Update to elastic/beats@815bd88fecf3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10498 [updatecli] Update to elastic/beats@106833bb6aff
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10503 [updatecli] Bump elastic stack version to 8.6.3-a3787e40
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10505 [updatecli] Update to elastic/beats@6c073556615f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10506 [updatecli] Update to elastic/beats@43c78fbf35bd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10504 [updatecli] Update to elastic/beats@ba67aa8fed61
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10493 [updatecli] Bump elastic stack version to 7.17.10-40fdd3ef
  docker-compose.yml
Labels: automation, backport-skip

#10501 systemtest/loadgen: don't pre-compress batches
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
Labels: backport-skip

#10508 benchmarks: run benchmarks 6 times, for 95% CI
  .ci/benchmarks.groovy
  .ci/scripts/bench.sh
  testing/benchmark/Makefile
Labels: backport-skip

#10512 [updatecli] Update to elastic/beats@a0feb39f68d7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10514 [updatecli] Update to elastic/beats@a0c6bb637057
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10511 [updatecli] Update to elastic/beats@584276707f2a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10509 loadgen: add support for timestamp rewriting
  systemtest/benchtest/clients.go
  systemtest/benchtest/main.go
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/loadgen/eventhandler/transport.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#10517 [updatecli] Update to elastic/beats@a8dbc6c06381
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10227 docs: Clarify anonymous authentication details
  docs/empty.yml
  docs/legacy/configuration-anonymous.asciidoc
  docs/legacy/configuration-rum.asciidoc
  docs/legacy/secure-communication-agents.asciidoc
  docs/secure-agent-communication.asciidoc
Labels: Team:Docs, backport-8.5, backport-8.6, backport-8.7

#10454 Document service log correlation
  docs/empty2.yml
  docs/log-correlation.asciidoc
Labels: docs, backport-8.7

#10471 docs: APM agent config
  apm-server.docker.yml
  apm-server.yml
  docs/empty.yml
  docs/empty2.yml
  docs/legacy/configuration-agent-config.asciidoc
  docs/legacy/configure-kibana-endpoint.asciidoc
  docs/legacy/configuring.asciidoc
  docs/legacy/copied-from-beats/outputs/elasticsearch/docs/elasticsearch.asciidoc
  docs/legacy/tab-widgets/jaeger-sampling.asciidoc
Labels: docs, backport-8.7

#10518 [updatecli] Update to elastic/beats@b8e0449d12b1
  NOTICE.txt
  go.mod
  go.sum
  internal/beatcmd/beat.go
Labels: automation, backport-skip

#10515 ci: remove all the stages that run in GH actions
  .ci/Jenkinsfile
Labels: backport-7.17, backport-8.7

#10528 [updatecli] Update to elastic/beats@66755e6b5833
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10536 [updatecli] Update to elastic/beats@caac39a97eb8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10527 [updatecli] Bump elastic stack version to 8.6.3-05478f37
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/base/stack/kibana.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: automation, backport-skip

#10530 systemtest/loadgen: support ID randomisation
  systemtest/benchtest/clients.go
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#10526 [updatecli] Bump elastic stack version to 7.17.10-319f366a
  docker-compose.yml
Labels: automation, backport-skip

#10516 feat: support standalone APM Server with Tilt
  .ci/bump-elastic-stack-snapshot.yml
  Tiltfile
  dev_docs/TESTING.md
  testing/infra/k8s/base/kustomization.yaml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/fleet-server.yaml
  testing/infra/k8s/overlays/local/kustomization.yaml
Labels: backport-skip

#10537 [updatecli] Update to elastic/beats@2d32a6e6b541
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10529 changelog: tidy up 8.7 changelog
  apmpackage/apm/changelog.yml
  changelogs/8.7.asciidoc
Labels: backport-8.7

#10547 [updatecli] Update to elastic/beats@94d2ab78c973
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10548 [updatecli] Update to elastic/beats@192be249d121
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10549 [updatecli] Update to elastic/beats@7c362043d981
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10550 apmsoak: Support arbitrary headers via `-header`
  systemtest/benchtest/clients.go
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/loadgen/eventhandler/transport.go
  systemtest/soaktest/soaktest.go
Labels: enhancement, backport-skip

#10554 [updatecli] Bump elastic stack version to 7.17.10-5423f09a
  docker-compose.yml
Labels: automation, backport-skip

#10555 [updatecli] Update to elastic/beats@a9d6766c8bb3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10558 [updatecli] Update to elastic/beats@fcc91c7169a4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10556 [updatecli] Update to elastic/beats@56c96583bccd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#10559 docs: duplicate breaking changes
  docs/a.yml
  docs/apm-breaking.asciidoc
Labels: Team:Docs, backport-8.7

#10564 action: lint is mandatory but doc changes don't need it
  .github/workflows/ci-docs.yml
Labels: backport-skip

#10552 Add missing `agent.activation_method` mapping
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  changelogs/8.7.asciidoc
  systemtest/approvals/TestApprovedMetrics.approved.json
  systemtest/approvals/TestIntake/Events.approved.json
  systemtest/approvals/TestIntake/Metricsets.approved.json
  systemtest/approvals/TestIntake/Spans.approved.json
  systemtest/approvals/TestIntake/Transactions.approved.json
  systemtest/approvals/TestIntake/TransactionsHugeTraces.approved.json
  systemtest/approvals/TestIntakeLog/with_faas.approved.json
  systemtest/approvals/TestIntakeLog/with_flat_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_nested_ecs_fields_overrides_flat_fields.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp.approved.json
  systemtest/approvals/TestIntakeLog/with_timestamp_as_str.approved.json
  systemtest/approvals/TestIntakeLog/without_timestamp.approved.json
  testdata/intake-v2/events.ndjson
  testdata/intake-v2/logs.ndjson
  testdata/intake-v2/metricsets.ndjson
  testdata/intake-v2/spans.ndjson
  testdata/intake-v2/transactions-huge_traces.ndjson
  testdata/intake-v2/transactions.ndjson
Labels: backport-8.7

#10563 feat: steady rate load generation for loadgen
  dev_docs/TESTING.md
  systemtest/benchtest/main.go
  systemtest/gencorpora/gencorpora.go
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/loadgen/limiter.go
  systemtest/soaktest/soaktest.go
  testing/apmsoak/main.tf
  testing/apmsoak/terraform.tfvars.example
  testing/apmsoak/variables.tf
  testing/benchmark/Makefile
  testing/infra/terraform/modules/soaktest_workers/README.md
  testing/infra/terraform/modules/soaktest_workers/main.tf
  testing/infra/terraform/modules/soaktest_workers/systemd.tpl
  testing/infra/terraform/modules/soaktest_workers/variables.tf
Labels: backport-skip

#10570 [updatecli] Update to elastic/beats@bc8e1c567ed4
  NOTICE.txt
  go.mod
  go.sum
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
Labels: automation, backport-skip

#10574 systemtest/loadgen: add `-rewrite-*-names` flags
  systemtest/loadgen/config/config.go
  systemtest/loadgen/eventhandler.go
  systemtest/loadgen/eventhandler/handler.go
  systemtest/loadgen/eventhandler/handler_test.go
  systemtest/soaktest/soaktest.go
Labels: backport-skip

#10577 mergify: auto-merge backports from mergify
  .mergify.yml
Labels: backport-skip

#10578 mergify: cannot create and auto-approve the same user
  .mergify.yml
Labels: backport-skip

#10567 docs: Group aggregation metric changes into subsections
  changelogs/8.7.asciidoc
Labels: backport, backport-8.7

#10584 [updatecli] Update to elastic/beats@1c93cd6fe3e1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
