Repository elastic/apm-server, pull requests merged in 2024-01, with the labels that each got.

#12329 [updatecli] Update to elastic/beats@5e4852920fb9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12328 [updatecli] Update to elastic/beats@5043c444b12f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12327 [updatecli] Update to elastic/beats@a1ef36366d21
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12326 [updatecli] Bump elastic stack version to 8.11.4-41fcbc39
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12324 [updatecli] Bump elastic stack version to 7.17.17-224d8e33
  docker-compose.yml
Labels: automation, backport-skip

#12323 [updatecli] Bump elastic stack version to 8.12.0-9947ebf0
  apm-server.docker.yml
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12333 Update NOTICE.txt year
  NOTICE.txt
Labels: backport-skip

#12337 [updatecli] Update to elastic/beats@6f192c01ef19
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12338 [updatecli] Update to elastic/beats@246adc20a0f9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12340 [updatecli] Update to elastic/beats@6bc34f578d0e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12339 [updatecli] Update to elastic/beats@09baa1b9bac9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12343 docs: fix incorrect filenames in a document for Windows
  docs/getting-started-apm-server.asciidoc
Labels: backport-8.8, backport-8.9, backport-8.10, backport-8.11, backport-8.12

#12335 [updatecli] Bump elastic stack version to 8.11.4-c8acd73b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12336 [updatecli] Bump elastic stack version to 8.12.0-2335225c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12325 [updatecli] Bump elastic stack version to 8.13.0-toucn398
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12351 [updatecli] Bump elastic stack version to 8.12.0-a87bc5c4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12350 [updatecli] Bump elastic stack version to 8.11.4-02032cc3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12352 [updatecli] Update to elastic/beats@81ebafc4c2da
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12349 [updatecli] Bump elastic stack version to 8.13.0-ybxdr713
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12362 [updatecli] Update to elastic/beats@d1b32774aef4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12363 [updatecli] Update to elastic/beats@7d5284a232dc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12364 [updatecli] Update to elastic/beats@38ba816ecc6c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12361 [updatecli] Bump elastic stack version to 8.11.4-25ab7bee
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12369 [updatecli] Bump elastic stack version to 8.11.4-8881462e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12370 [updatecli] Update to elastic/beats@95f0f85a3edd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12372 [updatecli] Update to elastic/beats@61337102fc51
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12371 [updatecli] Update to elastic/beats@4ed62e67b8a1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12373 [updatecli] Update to elastic/beats@32d2ba068c31
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12368 [updatecli] Bump elastic stack version to 7.17.17-95dddbc3
  docker-compose.yml
Labels: automation, backport-skip

#12381 [updatecli] Update to elastic/beats@57f0435123e0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12382 [updatecli] Update to elastic/beats@e9372ad9ab1f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12380 [updatecli] Bump elastic stack version to 8.13.0-8upz6ftd
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12379 [updatecli] Bump elastic stack version to 8.11.4-3f013fd4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12391 docs: update docs versions 8.11.5
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: in progress, docs, Team:Automation, release

#12273 ci(release): automate release steps for the patch
  .github/workflows/run-patch-release.yml
  release.mk
Labels: backport-7.17, backport-8.12

#11822 apmpackage: use package spec v3
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/app_logs/fields/fields.yml
  apmpackage/apm/data_stream/app_logs/manifest.yml
  apmpackage/apm/data_stream/app_metrics/fields/fields.yml
  apmpackage/apm/data_stream/app_metrics/manifest.yml
  apmpackage/apm/data_stream/error_logs/fields/fields.yml
  apmpackage/apm/data_stream/error_logs/manifest.yml
  apmpackage/apm/data_stream/internal_metrics/fields/fields.yml
  apmpackage/apm/data_stream/internal_metrics/manifest.yml
  apmpackage/apm/data_stream/rum_traces/manifest.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/ecs.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/manifest.yml
  apmpackage/apm/data_stream/traces/fields/fields.yml
  apmpackage/apm/data_stream/traces/manifest.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/manifest.yml
  apmpackage/apm/manifest.yml
  apmpackage/cmd/genpackage/transform.go
  tools/go.mod
  tools/go.sum
Labels: backport-skip

#12390 Add 8.11.4 release notes
  changelogs/8.11.asciidoc
Labels: backport-8.11, backport-8.12

#12417 [updatecli] Update to elastic/beats@2f45bbdd4f1f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12419 [updatecli] Update to elastic/beats@10b1f7a03aa0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12420 [updatecli] Update to elastic/beats@40722051b23b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12418 [updatecli] Update to elastic/beats@a10ace565d03
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12387 [updatecli] Bump elastic stack version to 7.17.17-1107dfdb
  docker-compose.yml
Labels: automation, backport-skip

#12388 [updatecli] Bump elastic stack version to 8.13.0-07re5v7e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12421 Remove Jenkins related files
  .ci/jobs/apm-server-package-mbp.yml
  .ci/jobs/apm-server.yml
  .ci/jobs/defaults.yml
  .ci/packaging.groovy
Labels: backport-7.17, backport-8.12

#12426 [updatecli] Bump elastic stack version to 8.13.0-sq0d327c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12425 [updatecli] Bump elastic stack version to 8.12.0-k08v7bga
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12429 [updatecli] Update to elastic/beats@a1cb25125664
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12424 [updatecli] Bump elastic stack version to 7.17.17-f603656b
  docker-compose.yml
Labels: automation, backport-skip

#12428 [updatecli] Update to elastic/beats@4b75f99ec4dc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12427 [updatecli] Update to elastic/beats@b3a03e99baf5
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12432 auto-bump: docs/version.asciidoc does not exist
  script/update_go_version.sh
Labels: backport-7.17, backport-8.12

#12437 [updatecli] Update to elastic/beats@5d5afee8546c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12436 [updatecli] Update to elastic/beats@c34f3dbde57c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12440 [updatecli] Bump elastic stack version to 8.12.0-aarirsc2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12441 [updatecli] Bump elastic stack version to 7.17.17-66d75d96
  docker-compose.yml
Labels: automation, backport-skip

#12445 ci(patch-release): use current version
  release.mk
Labels: backport-7.17, backport-8.12

#12438 [updatecli] Update to elastic/beats@7a2441915532
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12451 Log number of bytes read from HTTP request body
  changelogs/head.asciidoc
  internal/beater/middleware/log_middleware.go
  internal/beater/middleware/log_middleware_test.go
  internal/beater/request/context.go
  internal/beater/request/context_test.go
Labels: backport-skip, v8.13.0

#12453 TBS: Fix missing TTL after badger.ErrTxnTooBig
  x-pack/apm-server/sampling/eventstorage/storage.go
Labels: backport-8.12

#12456 [updatecli] Bump elastic stack version to 8.12.0-08mvpdoi
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12459 [updatecli] Update to elastic/beats@4bc27d26ea69
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12455 [updatecli] Bump elastic stack version to 8.13.0-knq1zsti
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12460 [updatecli] Update to elastic/beats@af0928f86fb2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12466 [updatecli] Bump elastic stack version to 8.12.0-pitatttq
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12465 [updatecli] Update to elastic/beats@74945355f943
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12467 [updatecli] Bump elastic stack version to 7.17.17-36eb4463
  docker-compose.yml
Labels: automation, backport-skip

#12469 [updatecli] Update to elastic/beats@49f905d02542
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12468 [updatecli] Bump elastic stack version to 8.13.0-l534sdis
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12470 [updatecli] Update to elastic/beats@1fe4e40f1e75
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12475 [updatecli] Update to elastic/beats@0a722beac809
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12476 [updatecli] Update to elastic/beats@d92327c262ea
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12474 [updatecli] Update to elastic/beats@c23411acc04b
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/middleware/timeout_middleware_test.go
Labels: automation, backport-skip

#12483 release(patch): use the makefile defined in the release branch
  .github/workflows/run-patch-release.yml
Labels: backport-7.17, backport-8.12

#12489 [updatecli] Update to elastic/beats@630f62b55799
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12490 [updatecli] Update to elastic/beats@2c5f738ef890
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12488 [updatecli] Update to elastic/beats@b2e2ecc36c54
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12228 Disable sending local collection metrics to batch processor
  internal/beater/beater.go
Labels: backport-8.12

#12480 release: remove call to the deleted make goal
  release.mk
Labels: backport-skip

#12219 Define value for all constant_keyword fields in apmpackage
  apmpackage/apm/changelog.yml
  apmpackage/apm/data_stream/sampled_traces/fields/base-fields.yml
  apmpackage/apm/data_stream/service_destination_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_summary_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/service_transaction_interval_metrics/fields/fields.yml
  apmpackage/apm/data_stream/transaction_interval_metrics/fields/fields.yml
Labels: backport-skip

#12495 [updatecli] Update to elastic/beats@4e4f2d3839e3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12494 [updatecli] Update to elastic/beats@90228e66040f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12496 [updatecli] Update to elastic/beats@5cece738e346
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12497 backstage: add tags and consumesApi
  catalog-info.yaml
Labels: backport-skip

#12499 Revert "backstage: add tags and consumesApi"
  catalog-info.yaml
Labels: backport-skip

#12505 [updatecli] Bump elastic stack version to 8.12.1-viuu0igj
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12504 [updatecli] Bump elastic stack version to 8.13.0-l5snflwr
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12501 [updatecli] Update to elastic/beats@51f5cb4e4d23
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12506 Bump apm-data to detect OTel messaging.{system,operation} for transactions
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
Labels: backport-skip

#12513 [updatecli] Update to elastic/beats@cf731e633992
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12516 [updatecli] Bump elastic stack version to 7.17.18-1cc388da
  docker-compose.yml
Labels: automation, backport-skip

#12514 [updatecli] Bump elastic stack version to 8.12.1-mg2y3klg
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12515 [updatecli] Bump elastic stack version to 8.13.0-yil7wib0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#12517 [updatecli] Update to elastic/beats@374c05da46f7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12518 github-action: use wildcards for discovering all the workflows
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#12520 sendotlp: Add support for api key auth
  systemtest/cmd/sendotlp/main.go
Labels: backport-skip

#12521 [updatecli] Bump elastic stack version to 7.17.18-8136c1b9
  docker-compose.yml
Labels: automation, backport-skip

#12500 [updatecli] Update to elastic/beats@9f58fef62910
  NOTICE.txt
  go.mod
  go.sum
  internal/beater/config/config_test.go
Labels: automation, backport-skip

#12523 [updatecli] Update to elastic/beats@343847a093b9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#12522 [updatecli] Bump elastic stack version to 8.12.1-lipljxnp
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip
