Repository elastic/apm-server, pull requests merged in 2024-07, with the labels that each got.

#13526 ci(buildkite): use shared secrets
  .buildkite/hooks/pre-command
Labels: backport-7.17, backport-8.14

#13529 ci(release): update descriptions and use oblt-actions@v1
  .github/workflows/prepare-release/action.yml
  .github/workflows/run-minor-release.yml
  .github/workflows/run-patch-release.yml
  dev_docs/RELEASES.md
Labels: backport-7.17, backport-8.14

#13538 [updatecli] Update to elastic/beats@e5bb44934c11
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13537 [updatecli] Update to elastic/beats@cb0900496952
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13534 [updatecli] Bump elastic stack version to 8.14.2-770d7914
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13535 [updatecli] Bump elastic stack version to 8.15.0-5d6d1bc4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13533 [updatecli] Bump elastic stack version to 7.17.23-e4b694b2
  docker-compose.yml
Labels: automation, backport-skip

#13530 TBS: perf: Reduce allocs slightly in write and delete
  x-pack/apm-server/sampling/eventstorage/storage.go
Labels: backport-skip

#13539 TBS: perf: Pool APMEvent in sampling decision handler
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-skip

#13514 feat: add reload listener for apm tracing config
  changelogs/head.asciidoc
  internal/beatcmd/beat_test.go
  internal/beatcmd/reloader.go
  internal/beatcmd/reloader_test.go
Labels: backport-skip

#13546 [updatecli] Bump elastic stack version to 8.15.0-2088c97b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13543 [updatecli] Bump elastic stack version to 7.17.23-9786b1ff
  docker-compose.yml
Labels: automation, backport-skip

#13542 [updatecli] Bump elastic stack version to 8.14.2-09792e49
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13545 [updatecli] Update to elastic/beats@76a62ebf8946
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13544 [updatecli] Update to elastic/beats@e9455e203842
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13549 benchmarks: increase role-duration-seconds in aws/auth
  .github/workflows/benchmarks.yml
Labels: backport-skip

#13554 CHANGELOG: add entry for OTEL attribute `messaging.destination.name` change
  changelogs/head.asciidoc
Labels: backport-skip

#13559 udpatecli: support bump golang for 7.17
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
Labels: backport-7.17, github_actions, backport-8.14

#13565 [updatecli] Bump elastic stack version to 7.17.23-3e9e1611
  docker-compose.yml
Labels: automation, backport-skip

#13566 [updatecli] Bump elastic stack version to 8.14.2-0fc498d7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13564 [updatecli] Bump elastic stack version to 8.15.0-63a0c3c8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13568 [updatecli] Update to elastic/beats@48e4af47abf7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13567 [updatecli] Update to elastic/beats@548560de0c86
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13576 fix: Update `FlushBytes` parsing/defaults
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/beater_test.go
Labels: bug, backport-8.14

#13515 8.14.3: update versions
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: release

#13555 8.14.2: add missing changelog entry
  changelogs/8.14.asciidoc
Labels: backport-8.14

#13571 updatecli: add backport labels
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
Labels: backport-7.17, backport-8.14

#13582 updatecli(golang): update go.mod files to be bumped
  .ci/bump-golang.yml
Labels: dependency, backport-skip

#13583 [updatecli] Bump Golang version to 1.21.12
  .go-version
  approvaltest/go.mod
  internal/glog/go.mod
  systemtest/go.mod
  tools/go.mod
Labels: automation, backport-skip

#13590 [updatecli] Update to elastic/beats@c111789e3c61
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13591 [updatecli] Update to elastic/beats@6517ed811b0e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13587 [updatecli] Bump elastic stack version to 7.17.23-1d1cdcd0
  docker-compose.yml
Labels: automation, backport-skip

#13588 [updatecli] Bump elastic stack version to 8.15.0-90bfa704
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13589 [updatecli] Bump elastic stack version to 8.14.2-d682129b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13586 [updatecli] Bump elastic stack version to 8.15.0-90bfa704
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13592 [updatecli] Update to elastic/beats@5a379fc1f3e0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13593 Bump up apm-data to v1.7.0
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.15

#13553 8.15: update docs
  CHANGELOG.asciidoc
  changelogs/8.15.asciidoc
Labels: release

#13598 benchmarks: Increase AWS token duration to `5h`
  .github/workflows/benchmarks.yml
Labels: benchmarking, backport-skip

#13552 8.15: update docs, mergify, versions and changelogs
  CHANGELOG.asciidoc
  changelogs/8.15.asciidoc
  changelogs/head.asciidoc
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip, release

#13599 Add 8.14.3 Release Notes
  changelogs/8.14.asciidoc
Labels: backport-8.14, backport-8.15

#13605 Bump up apm-data version to v1.8.0
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.15

#13612 [updatecli] Update to elastic/beats@31d3abd490ec
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13609 [updatecli] Bump elastic stack version to 8.14.2-af63ff6e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13608 [updatecli] Bump elastic stack version to 7.17.23-010ec319
  docker-compose.yml
Labels: automation, backport-skip

#13610 [updatecli] Bump elastic stack version to 8.15.0-474afc1d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13613 [updatecli] Update to elastic/beats@9d3b98dd17fb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13614 Bump up apm-data to v1.8.1
  NOTICE.txt
  changelogs/8.15.asciidoc
  go.mod
  go.sum
Labels: test-plan, v8.15.0, backport-8.15

#13618 [updatecli] Update to elastic/beats@6e97683404dd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13620 output: Retry document-level `429`s by default
  changelogs/head.asciidoc
  internal/beater/beater.go
  internal/beater/beater_test.go
Labels: enhancement, backport-8.15

#13631 [updatecli] Update to elastic/beats@e40a406e6c42
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13630 [updatecli] Update to elastic/beats@85dbd4e62ba1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13627 [updatecli] Bump elastic stack version to 7.17.23-8d3160b2
  docker-compose.yml
Labels: automation, backport-skip

#13629 [updatecli] Update to elastic/beats@0c41eb73d556
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13628 [updatecli] Bump elastic stack version to 8.14.2-9ba1255f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13623 Bump up apm-data to v1.8.2
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.15

#13626 [updatecli] Bump elastic stack version to 8.15.0-dd63864e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13639 fix: specify correct path for tools/go.mod when running benchmark
  testing/benchmark/Makefile
Labels: backport-skip

#13641 Bump up apm-data to v1.8.3
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.15

#13647 [updatecli] Bump elastic stack version to 7.17.23-f9f83972
  docker-compose.yml
Labels: automation, backport-skip

#13646 [updatecli] Update to elastic/beats@718199610453
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13648 [updatecli] Update to elastic/beats@e1b593ffe820
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13649 [updatecli] Update to elastic/beats@032a4cfd5f3b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13644 [updatecli] Bump elastic stack version to 8.14.3-33f59ad2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13645 [updatecli] Bump elastic stack version to 8.15.0-e9b4a2f9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13654 Bump up apm-data to v1.8.4
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-8.15

#13660 [updatecli] Bump elastic stack version to 8.15.0-1a386dd5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13659 [updatecli] Bump elastic stack version to 8.16.0-a9f3d4e7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13658 [updatecli] Bump elastic stack version to 8.14.3-95e002dd
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13656 [updatecli] Update to elastic/beats@84836ea25463
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13657 [updatecli] Update to elastic/beats@fda578f25ee8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13652 Rename APM Server APIs
  docs/spec/openapi/bundled.yaml
Labels: backport-skip

#13665 Fix 8.14 broken changelog
  changelogs/8.14.asciidoc
Labels: backport-8.14, backport-8.15

#13674 [updatecli] Update to elastic/beats@c3712b5956a8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13673 [updatecli] Update to elastic/beats@7b35a7a5de93
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13671 [updatecli] Bump elastic stack version to 8.16.0-8e262a3b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13672 [updatecli] Bump elastic stack version to 8.14.3-7222297b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13653 fix: Add wrapper around libbeat instrumentation to propagate missing tracer config
  changelogs/8.15.asciidoc
  internal/beater/beater.go
  internal/beater/beater_test.go
Labels: backport-8.15

#13670 [updatecli] Bump elastic stack version to 7.17.23-0493bc2f
  docker-compose.yml
Labels: automation, backport-skip

#13669 [updatecli] Bump elastic stack version to 8.15.0-9bb1fcab
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13678 Don't check ILM policies on 8.15+
  testing/smoke/lib.sh
Labels: backport-skip

#13687 [updatecli] Update to elastic/beats@ab1fdd368655
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13685 [updatecli] Bump elastic stack version to 8.15.0-9cf398b8
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13680 Update 8.15 changelog diff link
  changelogs/8.15.asciidoc
Labels: backport-8.14, backport-8.15

#13684 [updatecli] Bump elastic stack version to 7.17.23-14c86b06
  docker-compose.yml
Labels: automation, backport-skip

#13683 [updatecli] Bump elastic stack version to 8.14.4-5d9afc5f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13682 [updatecli] Update to elastic/beats@aa5ec880ee71
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13686 [updatecli] Update to elastic/beats@5671cff8d143
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13681 [updatecli] Bump elastic stack version to 8.16.0-892b6545
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13692 [updatecli] Update to elastic/beats@b3d0f3a78e5f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13695 [updatecli] Bump elastic stack version to 7.17.23-e3a177e8
  docker-compose.yml
Labels: automation, backport-skip

#13694 [updatecli] Update to elastic/beats@269d31935ea6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13698 [updatecli] Bump elastic stack version to 8.16.0-a89b9a37
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13691 Add additional config remapping for "api_key" and "secret_token" for libbeat instrumentation wrapper
  changelogs/8.15.asciidoc
  internal/beater/beater.go
  internal/beater/beater_test.go
Labels: backport-8.15

#13697 [updatecli] Bump elastic stack version to 8.15.0-70355f19
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13696 [updatecli] Bump elastic stack version to 8.14.4-ddd05c32
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13693 [updatecli] Update to elastic/beats@d6a8214de877
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13709 [updatecli] Update to elastic/beats@9ada51321919
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13707 [updatecli] Update to elastic/beats@d40a9e372858
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13704 [updatecli] Bump elastic stack version to 8.16.0-d7bef85f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13706 [updatecli] Bump elastic stack version to 8.15.0-bc431a00
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13708 [updatecli] Update to elastic/beats@cf49dc686fd0
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13711 [updatecli] Update to elastic/beats@f057bbdc1c9b
  Dockerfile
  NOTICE.txt
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#13715 [updatecli] Bump elastic stack version to 7.17.23-3619a002
  docker-compose.yml
Labels: automation, backport-skip

#13717 [updatecli] Bump elastic stack version to 8.14.4-cf4f2f99
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13716 [updatecli] Update to elastic/beats@4301c0a260aa
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13714 [updatecli] Update to elastic/beats@8af2d57dac1c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13718 [updatecli] Update to elastic/beats@d7449ebc87c2
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13721 [updatecli] Update to elastic/beats@4e040097aa02
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13722 [updatecli] Update to elastic/beats@942f8c78573d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13727 docs: Tidy up 8.14 changelog
  changelogs/8.14.asciidoc
Labels: backport-8.14, backport-8.15

#13733 DRA: fix permissions of build artifacts
  .buildkite/scripts/dra.sh
  .buildkite/scripts/package.sh
Labels: backport-skip

#13723 [updatecli] Update to elastic/beats@1067b6c812cc
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13735 [updatecli] Update to elastic/beats@b8494160f941
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13734 [updatecli] Update to elastic/beats@f3f772f6fe47
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13720 [updatecli] Bump elastic stack version to 7.17.23-81381180
  docker-compose.yml
Labels: automation, backport-skip

#13737 DRA: Remove custom chmod
  .buildkite/scripts/dra.sh
Labels: backport-skip

#13749 [updatecli] Bump elastic stack version to 8.14.4-d0f2f673
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13748 [updatecli] Bump elastic stack version to 8.16.0-bc7f8bf6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13747 [updatecli] Bump elastic stack version to 8.15.0-b31336e2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13745 [updatecli] Bump elastic stack version to 7.17.23-45566d1b
  docker-compose.yml
Labels: automation, backport-skip

#13744 [updatecli] Update to elastic/beats@dd671a6bcefb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13746 [updatecli] Update to elastic/beats@dedfdc679e5b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13755 [updatecli] Bump elastic stack version to 8.14.4-83a5d94e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13752 [updatecli] Bump elastic stack version to 7.17.23-81e2e343
  docker-compose.yml
Labels: automation, backport-skip

#13753 [updatecli] Bump elastic stack version to 8.16.0-38912362
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13754 [updatecli] Bump elastic stack version to 8.15.0-bc3d3719
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13756 [updatecli] Update to elastic/beats@a9b85ce4631c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13759 [updatecli] Update to elastic/beats@bce3b66cc8d9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13758 [updatecli] Update to elastic/beats@ae524ab14a41
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13757 [updatecli] Update to elastic/beats@5541971cc328
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13761 [updatecli] Bump elastic stack version to 8.16.0-9f5437f6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13767 [updatecli] Update to elastic/beats@bd0ffc1af3bb
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13763 [updatecli] Bump elastic stack version to 7.17.23-684633f9
  docker-compose.yml
Labels: automation, backport-skip

#13764 [updatecli] Bump elastic stack version to 8.14.4-6e08fc48
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13766 [updatecli] Update to elastic/beats@e132ee9bdcfe
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13769 [updatecli] Bump elastic stack version to 8.15.0-b3f8815c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13770 [updatecli] Bump elastic stack version to 8.14.4-0a05d857
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13771 [updatecli] Bump elastic stack version to 8.16.0-e485f1da
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13768 [updatecli] Bump elastic stack version to 7.17.23-fdd97b45
  docker-compose.yml
Labels: automation, backport-skip

#13773 [updatecli] Update to elastic/beats@ad46ac5a34f6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13775 [updatecli] Update to elastic/beats@786f4ad0b0fa
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13774 [updatecli] Update to elastic/beats@8d3e96db92c8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13785 [updatecli] Update to elastic/beats@4944196a346f
  .go-version
  Dockerfile
  NOTICE.txt
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#13783 [updatecli] Bump elastic stack version to 8.16.0-4647f73c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13781 [updatecli] Bump elastic stack version to 8.15.0-4b70dfd2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13784 [updatecli] Update to elastic/beats@083f1dd3bc73
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13788 dependbot: fix diff script
  .github/workflows/update-dependabot-pr.yml
Labels: backport-skip

#13789 dependabot: fix diff script pt2
  .github/workflows/update-dependabot-pr.yml
Labels: backport-skip

#13780 [updatecli] Update to elastic/beats@a4b0924467d3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip
