Repository elastic/apm-server, pull requests merged in 2024-06, with the labels that each got.

#13287 Bump go-docappender to v2.1.3
  NOTICE.txt
  changelogs/8.14.asciidoc
  go.mod
  go.sum
Labels: backport-8.14

#13295 [updatecli] Update to elastic/beats@8cc85a2d59b6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13294 [updatecli] Bump elastic stack version to 8.14.0-5dfd9f77
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13291 [updatecli] Bump elastic stack version to 7.17.22-0ffa86c5
  docker-compose.yml
Labels: automation, backport-skip

#13292 [updatecli] Bump elastic stack version to 8.13.5-aadf4dc6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13293 [updatecli] Bump elastic stack version to 8.15.0-9180a854
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13290 [updatecli] Update to elastic/beats@de52d1434ea3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13147 Test SNAPSHOT in smoketests
  testing/smoke/legacy-managed/test.sh
  testing/smoke/legacy-standalone-major-managed/test.sh
  testing/smoke/lib.sh
Labels: backport-skip

#13305 [updatecli] Update to elastic/beats@4d4f1ced13fe
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13303 [updatecli] Update to elastic/beats@217f5a626498
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13299 [updatecli] Bump elastic stack version to 7.17.22-fc4e6ec2
  docker-compose.yml
Labels: automation, backport-skip

#13301 [updatecli] Bump elastic stack version to 8.13.5-20996be4
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13302 [updatecli] Bump elastic stack version to 8.14.0-0eb8d6bf
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13304 [updatecli] Update to elastic/beats@c46512f95b45
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13329 ci: exclude github secret access if dependabot
  .github/workflows/ci.yml
Labels: backport-7.17, backport-8.14

#13338 [updatecli] Update to elastic/beats@d23413676ebd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13334 [updatecli] Bump elastic stack version to 8.13.5-dd711047
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13333 [updatecli] Bump elastic stack version to 8.14.0-81c97bc2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13335 [updatecli] Bump elastic stack version to 8.15.0-8dbc9634
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13336 [updatecli] Update to elastic/beats@592ea5bb128d
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13327 ubi: use ubi:9.4
  packaging/ironbank/Dockerfile
  packaging/ironbank/hardening_manifest.yaml
Labels: backport-7.17, backport-8.14

#13347 buildkite: create link with the DRA html report
  .buildkite/scripts/dra.sh
Labels: backport-7.17, backport-8.14

#13351 [updatecli] Bump elastic stack version to 8.13.5-50954ab2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13354 [updatecli] Update to elastic/beats@90f9e8f6e48e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13352 [updatecli] Bump elastic stack version to 8.15.0-aa0ade8a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13350 [updatecli] Bump elastic stack version to 8.14.0-f18b4b35
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13196 Update apm-data and remap for OTel hostmetrics to elastic metrics
  .gitignore
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  internal/beater/otlp/grpc.go
  internal/beater/otlp/http.go
  systemtest/approvals/TestDropUnsampled.approved.json
  systemtest/approvals/TestJaeger/batch_0.approved.json
  systemtest/approvals/TestJaeger/batch_1.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_counter.approved.json
  systemtest/approvals/TestOTLPGRPCMetrics_histogram.approved.json
  systemtest/approvals/TestOTLPGRPCTraces.approved.json
  systemtest/go.mod
  systemtest/go.sum
  systemtest/jaeger_test.go
Labels: backport-skip

#13358 Add Amazon Linux 2023 to the smoke tests
  testing/infra/terraform/modules/standalone_apm_server/main.tf
  testing/smoke/os_matrix.sh
Labels: backport-skip

#13364 [updatecli] Update to elastic/beats@ff4b518ddcea
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13360 [updatecli] Bump elastic stack version to 8.14.0-a753d549
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13363 [updatecli] Bump elastic stack version to 8.15.0-725cdb43
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13367 [updatecli] Bump Golang version to 1.22.4
  .go-version
Labels: automation, backport-skip

#13369 ci: set GH_TOKEN to remove warnings
  .buildkite/hooks/pre-command
  .github/workflows/ci.yml
Labels: backport-7.17, backport-8.14

#13377 [updatecli] Bump elastic stack version to 8.14.1-99e97402
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13378 [updatecli] Update to elastic/beats@b6f4a46a06f5
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13375 [updatecli] Update to elastic/beats@de256b88f101
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13382 ci: fix type of release
  .github/workflows/prepare-release/action.yml
  .github/workflows/run-minor-release.yml
  .github/workflows/run-patch-release.yml
Labels: backport-7.17, backport-8.14

#13359 smoketest: fix healthcheck to wait for the resource to be ready
  testing/smoke/lib.sh
Labels: backport-skip

#13380 Add 7.17.22 release notes and bump version to 7.17.23
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  changelogs/7.17.asciidoc
  cmd/version.go
Labels: release

#13390 [updatecli] Bump elastic stack version to 8.15.0-fd647d58
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13389 [updatecli] Bump elastic stack version to 8.14.1-8b8a5a33
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13392 [updatecli] Update to elastic/beats@1b59d076f25c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13397 Create empty changelog for 8.14.1
  changelogs/8.14.asciidoc
Labels: backport-8.14

#13407 [updatecli] Update to elastic/beats@821ae189c19b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13406 [updatecli] Update to elastic/beats@60ba7bb46d03
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13405 [updatecli] Bump elastic stack version to 8.14.1-49676bee
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13404 [updatecli] Bump elastic stack version to 8.15.0-d2070ed2
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13408 github-actions: slack bot and kibana benchmark
  .github/workflows/benchmarks.yml
  .github/workflows/check-docker-compose.yml
Labels: backport-7.17, backport-8.14

#13413 [updatecli] Update to elastic/beats@20fea92709ea
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13414 [updatecli] Update to elastic/beats@18d20572de18
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13412 [updatecli] Update to elastic/beats@f9fec1e4ff85
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13419 [updatecli] Update to elastic/beats@522cf448075a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13418 [updatecli] Bump elastic stack version to 8.15.0-d4efed09
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13417 [updatecli] Bump elastic stack version to 8.14.2-0ba21de0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13424 [updatecli] Update to elastic/beats@39a018c8c64b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13425 [updatecli] Bump elastic stack version to 8.15.0-0d7d4ba9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13423 [updatecli] Update to elastic/beats@b398af8ccc99
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13426 [updatecli] Bump elastic stack version to 8.14.2-0ad1343e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13436 [updatecli] Update to elastic/beats@8b197c8f1594
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13437 [updatecli] Update to elastic/beats@090ec6b342e7
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13438 [updatecli] Update to elastic/beats@b0de1c742275
  .go-version
  Dockerfile
  NOTICE.txt
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#13434 [updatecli] Bump elastic stack version to 8.14.2-85d68b3b
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13445 [updatecli] Bump elastic stack version to 8.15.0-72200925
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13449 [updatecli] Update to elastic/beats@b1518d057809
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13448 [updatecli] Update to elastic/beats@2f10d0840326
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13446 [updatecli] Bump elastic stack version to 7.17.23-dc0072d1
  docker-compose.yml
Labels: automation, backport-skip

#13450 [updatecli] Update to elastic/beats@b5f78874c8a4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13447 [updatecli] Bump elastic stack version to 8.14.2-b877ca2d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13454 github-actions: set AWS_PROFILE
  .github/workflows/setup-cluster-env/action.yml
Labels: backport-7.17, backport-8.14

#13459 [updatecli] Bump elastic stack version to 7.17.23-d780a0f6
  docker-compose.yml
Labels: automation, backport-skip

#13458 [updatecli] Bump elastic stack version to 8.15.0-ee48b214
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13457 [updatecli] Bump elastic stack version to 8.14.2-d9e02e11
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13461 [updatecli] Update to elastic/beats@ffdb3c91c700
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13462 [updatecli] Update to elastic/beats@5a16c8f74ec9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13460 [updatecli] Update to elastic/beats@44aeabb36206
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13469 [updatecli] Bump elastic stack version to 8.15.0-93475c89
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13471 [updatecli] Update to elastic/beats@ee2a561d73fd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13470 [updatecli] Bump elastic stack version to 8.14.2-36e48dc3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13466 [updatecli] Update to elastic/beats@cd8ed8a6d543
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13467 [updatecli] Update to elastic/beats@99a6e8cf71e4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13468 [updatecli] Bump elastic stack version to 7.17.23-a4b11e4b
  docker-compose.yml
Labels: automation, backport-skip

#13464 TBS: Optimize for ReadTraceEvents miss
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
Labels: backport-8.14

#13479 [updatecli] Update to elastic/beats@4cc14a17f3c3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13477 [updatecli] Bump elastic stack version to 8.14.2-802f0e3c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13478 [updatecli] Update to elastic/beats@40bfa06b9d60
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13476 [updatecli] Update to elastic/beats@d2c4c2d7150c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13465 feat(oidc): google secret source of truth
  .github/workflows/benchmarks.yml
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
Labels: backport-7.17, backport-8.14

#13488 [updatecli] Bump elastic stack version to 8.15.0-021a3fba
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13490 [updatecli] Update to elastic/beats@5f64f090eea6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13491 [updatecli] Update to elastic/beats@1d7f24db2d06
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13487 [updatecli] Update to elastic/beats@14caf11a3a4e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13489 [updatecli] Bump elastic stack version to 8.14.2-d49753ad
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13497 ci(smoke-tests): set id-token when running other workflows
  .github/workflows/smoke-tests-schedule.yml
Labels: backport-7.17, backport-8.14

#13501 [updatecli] Update to elastic/beats@c2b2983c1825
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13500 [updatecli] Update to elastic/beats@38b62b265182
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13504 [updatecli] Update to elastic/beats@f9260909ff38
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13503 [updatecli] Bump elastic stack version to 8.15.0-c0e0d013
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13502 [updatecli] Bump elastic stack version to 8.14.2-d7169439
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13492 ci(oidc): use AWS access
  .github/workflows/benchmarks.yml
  .github/workflows/generate-smoke-tests-list/action.yml
  .github/workflows/setup-cluster-env/action.yml
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
Labels: backport-7.17, github_actions, backport-8.14

#13507 [updatecli] Bump elastic stack version to 7.17.23-4ea59487
  docker-compose.yml
Labels: automation, backport-skip

#13508 [updatecli] Bump elastic stack version to 8.15.0-af44b0a5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13509 [updatecli] Bump elastic stack version to 8.14.2-5c99b6cc
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13511 [updatecli] Update to elastic/beats@e1641ce57740
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13510 [updatecli] Update to elastic/beats@8448a509433f
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13520 [updatecli] Update to elastic/beats@5323dc625833
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13521 [updatecli] Update to elastic/beats@d2f40a717dac
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13522 [updatecli] Update to elastic/beats@e16b5e2f429a
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13518 [updatecli] Bump elastic stack version to 7.17.23-56c486b8
  docker-compose.yml
Labels: automation, backport-skip
