Repository elastic/apm-server, pull requests merged in 2024-08, with the labels that each got.

#13816 [updatecli] Update to elastic/beats@c60e553a99e6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13815 [updatecli] Update to elastic/beats@a70fd7dd87ef
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13813 [updatecli] Bump elastic stack version to 8.16.0-73e9a660
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13814 [updatecli] Update to elastic/beats@640f2de34ef6
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13811 [updatecli] Bump elastic stack version to 8.15.0-65c16a2f
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13823 Migrate docker-compose to docker compose
  .github/workflows/ci.yml
  systemtest/containers.go
  testing/stack-monitoring.sh
Labels: backport-8.14, backport-8.15

#13819 [updatecli] Update to elastic/beats@cd7285b6b8ae
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13817 [updatecli] Bump elastic stack version to 8.16.0-f9f84acb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13812 [updatecli] Bump elastic stack version to 8.14.4-fc0488b9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13818 [updatecli] Bump elastic stack version to 8.15.0-697eb961
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13829 [updatecli] Update to elastic/beats@5d591f644b08
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13828 [updatecli] Update to elastic/beats@744485afb15b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13832 dependabot: fix command to determine the diff
  .github/workflows/update-dependabot-pr.yml
Labels: backport-skip

#13833 [updatecli] Update to elastic/beats@07c6c949be84
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13834 changelog: correct feature backported to 8.15
  changelogs/8.15.asciidoc
  changelogs/head.asciidoc
Labels: backport-skip

#13839 changelog: apm-aggregation labels bug
  changelogs/8.15.asciidoc
Labels: backport-8.15

#13842 dependabot: compare to actual output value and add debug step
  .github/workflows/update-dependabot-pr.yml
Labels: backport-skip

#13846 dependabot: use git-status instead of git-diff
  .github/workflows/update-dependabot-pr.yml
Labels: backport-skip

#13848 Bump up version to 8.15.1
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip

#13849 [updatecli] Update to elastic/beats@fada07251b70
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13852 [8.15] Bump apm-data to v1.9.1
  NOTICE.txt
  go.mod
  go.sum
Labels: v8.15.1

#13853 [8.15] Bump go-docappender to v2.2.1
  NOTICE.txt
  go.mod
  go.sum
Labels: v8.15.1

#13857 [updatecli] Bump elastic stack version to 8.16.0-47fa2a49
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13856 [updatecli] Bump elastic stack version to 8.15.0-5b8c47c1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13855 [updatecli] Bump elastic stack version to 8.14.4-3a06015a
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13854 [updatecli] Update to elastic/beats@f170d884096e
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13861 [updatecli] Bump Golang version to 1.22.6
  .go-version
Labels: automation, backport-8.15

#13868 [updatecli] Bump elastic stack version to 8.14.4-41737d57
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13866 [updatecli] Bump elastic stack version to 8.16.0-3a9f65a3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13864 [updatecli] Update to elastic/beats@cebcf1bbfeac
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13865 [updatecli] Update to elastic/beats@94081ab34a69
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13875 [updatecli] Bump elastic stack version to 8.15.1-95cb44ee
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13873 [updatecli] Update to elastic/beats@79206dd8c1cd
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13838 Fix memory limit check bytes to GB conversion
  internal/beater/beater.go
  internal/beater/beater_test.go
  internal/beater/memlimit_cgroup.go
  internal/beater/memlimit_cgroup_test.go
  internal/beater/memlimit_system.go
Labels: backport-8.15

#13883 [updatecli] Update to elastic/beats@85d1ec816568
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13881 [updatecli] Bump elastic stack version to 8.15.1-292be5eb
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13882 [updatecli] Bump elastic stack version to 8.16.0-da6628ae
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13888 [updatecli] Update to elastic/beats@f9a9369bc972
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13886 [updatecli] Bump elastic stack version to 8.16.0-fe676ba3
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13887 [updatecli] Bump elastic stack version to 8.15.1-ce14508c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13892 [updatecli] Update to elastic/beats@531a97acfaf9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13895 [updatecli] Update to elastic/beats@b9bfe1a7fbb3
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13894 [updatecli] Bump elastic stack version to 8.15.1-d2032aa6
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13899 [updatecli] Bump elastic stack version to 8.15.1-2c141eda
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13900 [updatecli] Bump elastic stack version to 8.16.0-233f996e
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13860 [updatecli] Bump Golang version to 1.22.6
  .go-version
  approvaltest/go.mod
  internal/glog/go.mod
  systemtest/go.mod
  tools/go.mod
Labels: automation, backport-skip

#13820 [updatecli] Update to elastic/beats@ecddbc127623
  Dockerfile
  NOTICE.txt
  go.mod
  go.sum
  tests/Dockerfile
Labels: automation, backport-skip

#13800 [updatecli] Bump elastic stack version to 7.17.24-93497d42
  docker-compose.yml
Labels: automation, backport-skip

#13906 [updatecli] Bump elastic stack version to 8.15.1-379d17a0
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13905 [updatecli] Bump elastic stack version to 7.17.24-e0c98212
  docker-compose.yml
Labels: automation, backport-skip

#13908 [updatecli] Update to elastic/beats@60a2462c109c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13907 [updatecli] Bump elastic stack version to 8.16.0-0c16574c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13916 [updatecli] Update to elastic/beats@8c37b92c40e8
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13914 [updatecli] Bump elastic stack version to 8.15.1-18f0c058
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13915 [updatecli] Bump elastic stack version to 8.16.0-368aa682
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13913 [updatecli] Bump elastic stack version to 7.17.24-7d0436f8
  docker-compose.yml
Labels: automation, backport-skip

#13911 [updatecli] Update to elastic/beats@88c39ef43407
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13912 [updatecli] Update to elastic/beats@e09627fb5672
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13922 [updatecli] Update to elastic/beats@e64ea44140d4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13920 [updatecli] Bump elastic stack version to 8.15.1-aba8b96c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13923 [updatecli] Bump elastic stack version to 7.17.24-b1f4ff18
  docker-compose.yml
Labels: automation, backport-skip

#13921 [updatecli] Update to elastic/beats@35a23d167b03
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13919 [updatecli] Bump elastic stack version to 8.16.0-07587139
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13924 [updatecli] Update to elastic/beats@dff664d0f0e1
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13931 [updatecli] Bump elastic stack version to 8.16.0-c5bcaeae
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13929 [updatecli] Bump elastic stack version to 7.17.24-e395ff83
  docker-compose.yml
Labels: automation, backport-skip

#13928 [updatecli] Update to elastic/beats@96b136a54066
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13927 [updatecli] Update to elastic/beats@af33fad4d50b
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13930 [updatecli] Bump elastic stack version to 8.15.1-16cafb68
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13940 [updatecli] Update to elastic/beats@dae00eaa4107
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13937 [updatecli] Bump elastic stack version to 8.16.0-e5ab468c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13935 [updatecli] Bump elastic stack version to 7.17.24-05a7d6ca
  docker-compose.yml
Labels: automation, backport-skip

#13944 [updatecli] Bump elastic stack version to 8.15.1-35befaba
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13942 [updatecli] Bump elastic stack version to 8.16.0-32bc94b7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13943 [updatecli] Bump elastic stack version to 7.17.24-5417cd4d
  docker-compose.yml
Labels: automation, backport-skip

#13948 deps(updatecli): bump all policies
  updatecli-compose.yaml
Labels: backport-skip

#13954 [updatecli] Bump elastic stack version to 8.15.1-6ed69fc1
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13953 [updatecli] Bump elastic stack version to 7.17.24-2d3bfa51
  docker-compose.yml
Labels: automation, backport-skip

#13945 [updatecli] Update to elastic/beats@1c48c95af7e4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13960 [updatecli] Bump elastic stack version to 7.17.24-f6cb7d65
  docker-compose.yml
Labels: automation, backport-skip
