Repository elastic/apm-server, pull requests merged in 2024-09, with the labels that each got.

#13966 changelog: add 8.15.1 entry
  changelogs/8.15.asciidoc
Labels: backport-8.15

#13971 [updatecli] Bump elastic stack version to 8.15.1-e010ad04
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13970 [updatecli] Bump elastic stack version to 8.16.0-a3caaa65
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13969 [updatecli] Bump elastic stack version to 7.17.24-bb129799
  docker-compose.yml
Labels: automation, backport-skip

#13975 github-actions: replace apm-pipeline-library actions for oblt-actions
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/bump-golang.yml
  .github/workflows/check-docker-compose.yml
  .github/workflows/smoke-tests-schedule.yml
  .github/workflows/update-beats.yml
Labels: backport-7.17, backport-8.15

#13918 Add changelog for fallback to ILM if DSL not present
  changelogs/8.15.asciidoc
Labels: backport-8.15

#13958 Fix ScrollID used for retrieval of APM Agents configuration
  internal/agentcfg/elasticsearch.go
Labels: backport-8.15

#13982 [updatecli] Bump elastic stack version to 7.17.24-5ffd9a45
  docker-compose.yml
Labels: automation, backport-skip

#13983 [updatecli] Bump elastic stack version to 8.15.1-67154674
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#13959 Test agentcfg es fetcher scroll id
  internal/agentcfg/elasticsearch_test.go
Labels: backport-8.15

#13986 changelog: add entries for apm-data and go-docappender upgrades
  changelogs/8.15.asciidoc
Labels: docs, backport-8.15

#13985 [updatecli] Update to elastic/beats@bc2cbf4b71ba
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#13997 8.15.2: update versions
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: release

#13990 deps(updatecli): bump all policies
  .ci/updatecli/values.d/scm.yml
  updatecli-compose.yaml
Labels: backport-skip

#13998 [updatecli] Bump elastic stack version to 7.17.24-f8a360d9
  docker-compose.yml
Labels: automation, backport-skip

#14008 [updatecli] Bump Golang version to 1.23.1
  .go-version
Labels: automation, backport-8.15

#14019 [updatecli] Update to elastic/beats@a7455dc9d4a9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14017 [updatecli] Bump elastic stack version to 8.15.2-e26b3970
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14015 [updatecli] Bump elastic stack version to 7.17.24-2a15a0bd
  docker-compose.yml
Labels: automation, backport-skip

#14032 [updatecli] Update to elastic/beats@6abec5038a08
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14031 [updatecli] Bump elastic stack version to 8.15.2-72deec01
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14030 [updatecli] Bump elastic stack version to 7.17.24-2ea99796
  docker-compose.yml
Labels: automation, backport-skip

#14033 changelod: add release notes for 7.17.24
  changelogs/7.17.asciidoc
Labels: docs

#14027 ci(microbenchmark): add 8.x branch
  .github/workflows/microbenchmark.yml
Labels: backport-8.x

#14028 ci(release): support for releases from 8.x
  release.mk
Labels: backport-7.17, backport-8.15, backport-8.x

#14044 mergify: replace queue action for queue_rules
  .mergify.yml
Labels: backport-8.x

#14047 [updatecli] Bump elastic stack version to 7.17.25-84dcbf3c
  docker-compose.yml
Labels: automation, backport-skip

#14049 [updatecli] Bump elastic stack version to 8.15.2-c56c9001
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14036 deps(updatecli): bump all policies
  .ci/updatecli/values.d/scm.yml
  updatecli-compose.yaml
Labels: backport-8.x

#14048 [updatecli] Bump elastic stack version to 8.16.0-2156c99d
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-8.x

#14056 mergify: backport-skip and backport-8.x are mutually exclusive
  .mergify.yml
Labels: backport-8.x

#14063 changelog: 8.15 removes support for integration custom ingest pipelines
  changelogs/8.15.asciidoc
Labels: backport-8.15, backport-8.x

#14070 [updatecli] Bump elastic stack version to 8.16.0-bff94f3c
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14068 [updatecli] Bump elastic stack version to 7.17.25-2af1904e
  docker-compose.yml
Labels: automation, backport-skip

#14069 [updatecli] Bump elastic stack version to 8.15.2-eb081dc9
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14071 [updatecli] Update to elastic/beats@37d26eeb8cf4
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14081 [updatecli] Update to elastic/beats@ef04f1c58bf9
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14079 [updatecli] Bump elastic stack version to 9.0.0-5fdca544
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14078 [updatecli] Bump elastic stack version to 8.16.0-c6f183db
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14076 [updatecli] Bump elastic stack version to 7.17.25-0a21543d
  docker-compose.yml
Labels: automation, backport-skip

#14080 [updatecli] Bump elastic stack version to 8.15.2-964527b7
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14094 [updatecli] Update to elastic/beats@6af7f8294656
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14091 [updatecli] Bump elastic stack version to 8.15.2-7f2cd899
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14089 [updatecli] Update to elastic/beats@29ccd4834f6c
  NOTICE.txt
  go.mod
  go.sum
Labels: automation, backport-skip

#14093 [updatecli] Bump elastic stack version to 9.0.0-d56464e5
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14092 [updatecli] Bump elastic stack version to 8.16.0-874a7f05
  docker-compose.yml
  testing/infra/k8s/base/stack/apm-server.yaml
  testing/infra/k8s/base/stack/elasticsearch.yaml
  testing/infra/k8s/base/stack/kibana.yaml
Labels: automation, backport-skip

#14090 [updatecli] Bump elastic stack version to 7.17.25-09a2826c
  docker-compose.yml
Labels: automation, backport-skip

#14010 github-action: use ephemeral tokens with the required permissions
  .github/workflows/bump-elastic-stack.yml
  .github/workflows/bump-golang.yml
  .github/workflows/update-beats.yml
  .github/workflows/update-compose.yml
Labels: backport-7.17, backport-8.15, backport-8.x

#14025 ci(release minor): add tag::list entry for minor release in the changelog
  release.mk
Labels: backport-7.17, backport-8.15, backport-8.x

#14156 ci: support running smoke tests using the GitHub UI
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
Labels: backport-7.17, backport-8.15, backport-8.x

#14176 smoke tests: Ignore version 9.0.0
  testing/infra/terraform/modules/standalone_apm_server/latest_apm_server.sh
  testing/infra/terraform/modules/standalone_apm_server/latest_elastic_agent.sh
  testing/smoke/legacy-standalone-major-managed/test.sh
  testing/smoke/supported-os/test.sh
  testing/smoke/test_supported_os.sh
Labels: backport-8.x

#14187 8.15.3: update versions
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: release

#14186 changelog: 8.15.2 release
  changelogs/8.15.asciidoc
Labels: backport-8.15, backport-8.x
