Repository elastic/apm-server, pull requests merged in 2025-04, with the labels that each got.

#16373 ci(bump golang): use make update-go-version
  .ci/updatecli/bump-golang.yml
  script/update_go_version.sh
Labels: backport-skip

#16499 [docs] Add missing mapped pages
  docs/release-notes/breaking-changes.md
Labels: docs, Team:Docs

#16500 functionaltests: exclude more error logs
  functionaltests/internal/esclient/client.go
  functionaltests/single_upgrade_test.go
Labels: backport-skip

#15512 Replace okta-awscli with okta-aws-cli in testing/benchmark
  testing/benchmark/Makefile
  testing/benchmark/README.md
Labels: backport-8.x

#16520 functionaltests: Add Kibana Upgrade Assistant APIs to resolve migration deprecations
  functionaltests/internal/kbclient/client_test.go
  functionaltests/internal/kbclient/testdata/fixtures/TestClient_ResolveMigrationDeprecations.yaml
  functionaltests/internal/kbclient/upgrade_assist.go
  functionaltests/internal/kbclient/upgrade_assist_test.go
Labels: backport-skip

#16537 functionaltests: Minor refactor
  .github/workflows/functional-tests.yml
  functionaltests/8_16_test.go
  functionaltests/8_17_test.go
  functionaltests/8_18_test.go
  functionaltests/8_19_test.go
  functionaltests/9_0_test.go
  functionaltests/9_1_test.go
  functionaltests/basic_upgrade_test.go
  functionaltests/internal/asserts/data_streams.go
  functionaltests/internal/asserts/doc_count.go
  functionaltests/internal/asserts/doc_count_v7.go
  functionaltests/internal/esclient/client.go
  functionaltests/internal/esclient/client_v7.go
  functionaltests/internal/gen/generator.go
  functionaltests/internal/kbclient/client.go
  functionaltests/logs_filters.go
  functionaltests/steps_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16605 deps(gh-actions): use main for the elastic gh actions
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: backport-active-all

#16598 [docs] Update APM, Synthetics, Uptime links
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: docs, Team:Docs

#16503 functionaltests: Add 7x to 8x standalone to managed test
  .github/workflows/functional-tests.yml
  functionaltests/8_x_test.go
  functionaltests/9_1_test.go
  functionaltests/README.md
  functionaltests/internal/esclient/client_v7.go
  functionaltests/internal/kbclient/upgrade_assist_test.go
  functionaltests/logs_filters.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/steps_test.go
  functionaltests/steps_v7_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16650 mergify: support 8.19 and remove support 8.x
  .mergify.yml
  release.mk
Labels: backport-skip

#16637 Fix ec_deployment local exec provisioner error
  testing/infra/terraform/modules/ec_deployment/deployment.tf
Labels: backport-skip

#16582 functionaltests: Add test for 7x to 8x to 9x
  .github/workflows/functional-tests.yml
  functionaltests/9_x_test.go
  functionaltests/internal/gen/generator.go
  functionaltests/internal/kbclient/client.go
  functionaltests/internal/kbclient/upgrade_assist.go
  functionaltests/main_test.go
  functionaltests/steps_test.go
  functionaltests/steps_v7_test.go
Labels: backport-skip

#16686 functionaltests: Add upgradable to stack version
  functionaltests/8_16_test.go
  functionaltests/8_17_test.go
  functionaltests/8_18_test.go
  functionaltests/8_19_test.go
  functionaltests/8_x_test.go
  functionaltests/9_0_test.go
  functionaltests/9_1_test.go
  functionaltests/9_x_test.go
  functionaltests/internal/ecclient/client.go
  functionaltests/internal/ecclient/client_test.go
  functionaltests/internal/ecclient/stack_version.go
  functionaltests/internal/ecclient/stack_version_test.go
  functionaltests/main_test.go
  functionaltests/steps_test.go
Labels: backport-skip

#16645 Revert "release: support 8.x releases (#14392)"
  release.mk
Labels: backport-8.x

#16694 catalog-info: run 7.17 DRA weekly
  catalog-info.yaml
Labels: backport-skip

#16742 chore: minor refactor of TestReadSubscriberPositionFile
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-active-9

#16695 functionaltests: Move and rename tests
  .github/workflows/functional-tests.yml
  functionaltests/8_x_test.go
  functionaltests/README.md
  functionaltests/basic_upgrade.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/standalone_test.go
  functionaltests/steps.go
  functionaltests/steps_v7.go
  functionaltests/utils.go
Labels: backport-skip
