Repository elastic/apm-server, pull requests merged in 2025-07, with the labels that each got.

#17329 integration-server-test: Add BC testing
  .github/workflows/generate-bc-upgrade-paths/action.yml
  .github/workflows/generate-bc-upgrade-paths/bc.sh
  .github/workflows/integration-server-test.yml
  Makefile
  integrationservertest/internal/ech/versions_cache.go
  integrationservertest/main_test.go
  integrationservertest/upgrade_test.go
Labels: backport-skip

#17500 iserver-test: Fix upgrade config lazy rollover
  integrationservertest/upgrade-config.yaml
Labels: backport-skip

#17512 monitoring: update apm-server metrics collection to avoid conflicts
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
Labels: test-plan, backport-9.0, backport-8.19, backport-9.1, v9.0.4

#17572 docs: Fix known issues unintended nested entries
  docs/release-notes/known-issues.md
Labels: backport-skip

#17643 Add 8.17.9 changelog entry
  changelogs/8.17.asciidoc
Labels: backport-skip

#17709 iserver-test: Add 9.2 test and some improvements
  .github/workflows/integration-server-test.yml
  integrationservertest/internal/gen/generator.go
Labels: backport-skip

#17754 iserver-test: Remove 9.1 from 9.2 lazy rollover exception
  integrationservertest/upgrade-config.yaml
Labels: backport-skip

#17586 changelog: Add 9.0.4 release notes
  docs/release-notes/index.md
Labels: backport-skip

#17291 updatecli: pass the branch instead
  .ci/scripts/update-beats.sh
  .ci/updatecli/update-beats.yml
  Makefile
Labels: backport-active-all

#17100 docs: Add integrations.md to provide steps for testing APM integratio…
  dev_docs/integrations.md
Labels: backport-skip

#17871 updatecli: use the new gh token action, and remove experimental
  .github/workflows/update-compose.yml
Labels: Team:Automation, backport-skip
