Repository elastic/apm-server, pull requests merged in 2025-03, with the labels that each got.

#15953 Remove tf module for running soaktest and update readme
  testing/apmsoak/Makefile
  testing/apmsoak/README.md
  testing/apmsoak/main.tf
  testing/apmsoak/terraform.tfvars.example
  testing/apmsoak/variables.tf
Labels: backport-active-all

#15983 changelog: add 8.16.5 entry
  changelogs/8.16.asciidoc
Labels: backport-8.x

#15984 changelog: add 8.17.3 changelog entry
  changelogs/8.17.asciidoc
Labels: backport-8.x

#15993 fix: Wrong source in newly added Terraform tags
  testing/smoke/main.tf
Labels: backport-active-9, backport-active-8

#15901 smoke: Fix smoke test Terraform issue
  functionaltests/8_15_test.go
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/outputs.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/outputs.tf
  functionaltests/utils_test.go
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-skip

#15976 Change server information endpoint `/` to only accept GET and HEAD requests
  docs/spec/openapi/paths/server_info.yaml
  internal/beater/api/mux_root_test.go
  internal/beater/api/root/handler.go
Labels: test-plan, backport-active-9, v9.0.0

#16038 benchmark: Align 8GB profiles worker size
  testing/benchmark/system-profiles/8GB_NVMe-x1zone.tfvars
  testing/benchmark/system-profiles/8GB_io2_6000iops-x1zone.tfvars
Labels: backport-8.18, backport-9.0

#16061 fix: Add locks for unsupported metric registration
  internal/beater/otlp/grpc.go
  internal/beater/otlp/http.go
Labels: backport-8.x, backport-9.0

#15992 systemtest: Fix flaky tests
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
  systemtest/otlp_test.go
Labels: backport-skip

#16063 feat: bump go to 1.24.1
  cmd/intake-receiver/go.mod
  functionaltests/go.mod
  go.mod
  systemtest/go.mod
Labels: backport-8.x, backport-8.18, backport-9.0

#16035 smoke: Use APM Server version to get Stack version
  testing/smoke/managed/test.sh
  testing/smoke/supported-os/test.sh
  testing/smoke/test_supported_os.sh
Labels: backport-active-9, backport-active-8

#15932 test: Enable race detector
  .github/workflows/ci.yml
  Makefile
  docker-compose.yml
Labels: backport-skip

#16124 bench: Don't return error for agents SendBatchesInLoop
  docker-compose.yml
  systemtest/benchtest/main.go
Labels: backport-active-9, backport-active-8

#16145 docs: Document smoke test scenarios
  testing/smoke/README.md
Labels: backport-skip

#16081 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: docs, Team:Docs, backport-active-9

#16155 Fix apmsoak cmd to use the latest apm-perf
  systemtest/soaktest/soaktest.go
Labels: backport-8.x, backport-8.18, backport-9.0

#16082 [docs] Migrate docs from AsciiDoc to Markdown
  CHANGELOG.asciidoc
  CHANGELOG.md
  changelogs/6.1.asciidoc
  changelogs/6.2.asciidoc
  changelogs/6.3.asciidoc
  changelogs/6.4.asciidoc
  changelogs/6.5.asciidoc
  changelogs/6.6.asciidoc
  changelogs/6.7.asciidoc
  changelogs/6.8.asciidoc
  changelogs/7.0.asciidoc
  changelogs/7.1.asciidoc
  changelogs/7.10.asciidoc
  changelogs/7.11.asciidoc
  changelogs/7.12.asciidoc
  changelogs/7.13.asciidoc
  changelogs/7.14.asciidoc
  changelogs/7.15.asciidoc
  changelogs/7.16.asciidoc
  changelogs/7.2.asciidoc
  changelogs/7.3.asciidoc
  changelogs/7.4.asciidoc
  changelogs/7.5.asciidoc
  changelogs/7.6.asciidoc
  changelogs/7.7.asciidoc
  changelogs/7.8.asciidoc
  changelogs/7.9.asciidoc
  changelogs/8.0.asciidoc
  changelogs/8.1.asciidoc
  changelogs/8.10.asciidoc
  changelogs/8.11.asciidoc
  changelogs/8.12.asciidoc
  changelogs/8.13.asciidoc
  changelogs/8.14.asciidoc
  changelogs/8.15.asciidoc
  changelogs/8.16.asciidoc
  changelogs/8.17.asciidoc
  changelogs/8.18.asciidoc
  changelogs/8.2.asciidoc
  changelogs/8.3.asciidoc
  changelogs/8.4.asciidoc
  changelogs/8.5.asciidoc
  changelogs/8.6.asciidoc
  changelogs/8.7.asciidoc
  changelogs/8.8.asciidoc
  changelogs/8.9.asciidoc
  changelogs/9.0.asciidoc
  changelogs/all-breaking-changes.asciidoc
  changelogs/head.asciidoc
  docs/docset.yml
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
  docs/release-notes/toc.yml
Labels: docs, Team:Docs

#15960 functionaltest: Add one re-route processor test
  functionaltests/8_16_test.go
  functionaltests/TestUpgrade_8_13_4_to_8_16_0_Reroute/main.tf
  functionaltests/TestUpgrade_8_13_4_to_8_16_0_Reroute/outputs.tf
  functionaltests/TestUpgrade_8_13_4_to_8_16_0_Reroute/tags.tf
  functionaltests/TestUpgrade_8_13_4_to_8_16_0_Reroute/terraform.tf
  functionaltests/TestUpgrade_8_13_4_to_8_16_0_Reroute/vars.tf
  functionaltests/internal/esclient/client.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16062 functionaltests: Copy terraform files at start of each test
  functionaltests/.gitignore
  functionaltests/README.md
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/main.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/outputs.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/tags.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/terraform.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/vars.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/main.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/outputs.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/tags.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/terraform.tf
  functionaltests/TestUpgrade_8_18_0_to_9_0_0/vars.tf
  functionaltests/infra/terraform/main.tf
  functionaltests/infra/terraform/outputs.tf
  functionaltests/infra/terraform/tags.tf
  functionaltests/infra/terraform/terraform.tf
  functionaltests/infra/terraform/vars.tf
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16198 smoke: Add missing patch in legacy major test
  testing/smoke/legacy-standalone-major-managed/test.sh
  testing/smoke/lib.sh
Labels: backport-skip

#16222 disable validate-wolfi-docker-image workflow
  .github/workflows/ci.yml
Labels: backport-8.0, backport-8.3, backport-8.1, backport-8.2, backport-8.4, backport-8.5, backport-8.6, backport-8.7, backport-8.8, backport-8.9, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#16182 fix: metrics interceptor concurrent map read write
  internal/beater/interceptors/metrics.go
  internal/beater/interceptors/metrics_test.go
  internal/beater/middleware/monitoring_middleware.go
Labels: backport-active-9, backport-active-8

#16202 smoke: Temporarily disable failing 9.0 smoke test upgrade in legacy major
  testing/smoke/legacy-standalone-major-managed/test.sh
Labels: backport-skip

#16252 functionaltests: Fix terraform source being wrong after copy
  functionaltests/infra/terraform/main.tf
  functionaltests/infra/terraform/tags.tf
Labels: backport-skip

#16273 functionaltests: Rename ecc to esc to make way for ecclient
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16276 smoke: Fix 9.0.0 assertion fail and legacy major typo
  testing/smoke/basic-upgrade/test.sh
  testing/smoke/legacy-standalone-major-managed/test.sh
Labels: backport-skip

#15903 smoke: Add note in smoke-tests about checkout ref
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
  .github/workflows/smoke-tests-schedule.yml
Labels: backport-skip

#16304 [docs] Copy recent release note edits
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: docs, Team:Docs

#16324 functionaltests: Disable QA env in functional tests
  .github/workflows/functional-tests.yml
Labels: backport-skip

#16319 docs: add breaking changes for 9.0
  docs/release-notes/breaking-changes.md
Labels: backport-skip

#16295 functionaltests: Use stack version fetching for tests
  .github/workflows/functional-tests.yml
  functionaltests/8_16_test.go
  functionaltests/9_0_test.go
  functionaltests/README.md
  functionaltests/internal/ecclient/client.go
  functionaltests/internal/ecclient/stack_version.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16177 smoke: Add legacy smoke-test-ess to simplify test matrix
  .github/workflows/generate-smoke-tests-list/action.yml
  .github/workflows/smoke-test-ess-action/action.yml
  .github/workflows/smoke-tests-ess.yml
  Makefile
Labels: backport-skip

#16341 functionaltests: Add BC tests
  functionaltests/8_16_test.go
  functionaltests/9_0_test.go
  functionaltests/basic_upgrade_test.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip

#16361 Remove goja replace
  go.mod
Labels: backport-8.x

#16342 functionaltests: Add reroute tests
  functionaltests/8_16_test.go
  functionaltests/basic_upgrade_test.go
Labels: backport-skip

#16362 functionaltests: Refactor TouchPackagePolicyByID
  .github/workflows/ci.yml
  functionaltests/go.mod
  functionaltests/go.sum
  functionaltests/internal/gen/generator.go
  functionaltests/internal/kbclient/client.go
  functionaltests/internal/kbclient/client_test.go
  functionaltests/internal/kbclient/testdata/fixtures/TestClient_GetPackagePolicyByID.yaml
  functionaltests/internal/kbclient/testdata/fixtures/TestClient_UpdatePackagePolicyByID.yaml
  functionaltests/internal/kbclient/testdata/fixtures/TestGetPackagePolicy.yaml
  functionaltests/internal/kbclient/testdata/fixtures/TestUpdatePackagePolicy.yaml
  functionaltests/single_upgrade_test.go
Labels: backport-skip

#16385 TBS: Fix edge case where storage limit is exceeded but missed by drop loop check
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_manager.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.17, backport-8.18

#16375 functionaltests: Fix error logs query
  functionaltests/internal/esclient/client.go
Labels: backport-skip

#16395 functionaltests: Use matrix to split test runs
  .github/workflows/functional-tests.yml
  functionaltests/basic_upgrade_test.go
  functionaltests/main_test.go
Labels: backport-skip

#16393 docs: TBS: Add known issue for small events in LSM
  docs/release-notes/known-issues.md
Labels: docs, backport-8.x, backport-8.16, backport-8.17, backport-8.18

#16402 functionaltests: Fix post-upgrade assertion
  functionaltests/basic_upgrade_test.go
  functionaltests/internal/esclient/client.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
Labels: backport-skip

#16456 smoke: Remove temp hack
  testing/smoke/basic-upgrade/test.sh
Labels: backport-skip

#16359 functionaltests: Move assertDocCount and assertDatastreams to asserts package
  functionaltests/basic_upgrade_test.go
  functionaltests/internal/asserts/data_streams.go
  functionaltests/internal/asserts/data_streams_test.go
  functionaltests/internal/asserts/doc_count.go
  functionaltests/internal/asserts/doc_count_test.go
  functionaltests/internal/esclient/client.go
  functionaltests/main_test.go
  functionaltests/single_upgrade_test.go
  functionaltests/utils_test.go
Labels: backport-skip
