Repository elastic/apm-server, pull requests merged in 2025-09, with the labels that each got.

#18485 github-actions: support backport labels after being merged
  .github/workflows/backport-active.yml
Labels: backport-skip

#18402 Add applies_to statements
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: docs

#18551 Fix secrets google project
  .github/workflows/benchmarks.yml
  .github/workflows/setup-integration-server-test/action.yml
  .github/workflows/smoke-tests-os.yml
Labels: backport-active-9, backport-8.19

#18614 Update gobench
  go.mod
  go.sum
Labels: backport-skip

#18524 iserver-test: Add panic logs check if ingest fails
  integrationservertest/.gitignore
  integrationservertest/README.md
  integrationservertest/docker-image-override.yaml.example
  integrationservertest/infra/terraform/main.tf
  integrationservertest/infra/terraform/vars.tf
  integrationservertest/internal/elasticsearch/client.go
  integrationservertest/setup.go
  integrationservertest/standalone_test.go
  integrationservertest/steps.go
  integrationservertest/upgrade_test.go
Labels: backport-skip
