Repository elastic/apm-server, pull requests merged in 2025-01, with the labels that each got.

#15078 benchmarking: moxy use default tags only
  testing/benchmark/main.tf
  testing/infra/terraform/modules/moxy/main.tf
  testing/infra/terraform/modules/moxy/variables.tf
  testing/infra/terraform/modules/standalone_apm_server/main.tf
  testing/infra/terraform/modules/standalone_apm_server/variables.tf
Labels: backport-8.x

#15112 TBS: refactor to encapsulate badger DB
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/eventstorage/storage_manager.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.x, backport-8.16, backport-8.17

#15136 test: Fix failing TestOTLPGRPCLogsClientIP due to geoip
  docs/spec/v2/span.json
  systemtest/approvals/TestOTLPGRPCLogsClientIP.approved.json
Labels: backport-8.x, backport-8.16, backport-8.17

#15135 test: Fix missing assertions for default result IDs in monitoringtest
  internal/beater/monitoringtest/monitoring.go
Labels: backport-8.x, backport-8.16, backport-8.17

#14905 Win: install APM Server in Program Files directory
  packaging/files/windows/install-service.ps1
Labels: backport-8.x, backport-8.16, backport-8.17

#15123 Instrumentation: fix log trace inconsistent status code with timeout check when writing the response
  internal/beater/api/mux.go
  internal/beater/middleware/timeout_middleware.go
  internal/beater/middleware/timeout_middleware_test.go
  internal/beater/request/context.go
  internal/beater/server_test.go
Labels: backport-8.x, backport-8.16, backport-8.17

#15106 TBS: drop and recreate badger db after exceeding storage limit for TTL time
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_manager.go
  x-pack/apm-server/sampling/eventstorage/storage_manager_test.go
  x-pack/apm-server/sampling/eventstorage/storage_whitebox_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.x, backport-8.16, backport-8.17

#15159 TBS: Add `sampling.tail.discard_on_write_failure` config
  internal/beater/config/sampling.go
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.x, backport-8.16, backport-8.17

#15173 [8.17] Fix CI failure due to docs/spec/v2/span.json
  docs/spec/v2/span.json
Labels: backport-8.16

#15190 github-actions: support for copying the backport labels
  .github/workflows/mergify-labels-copier.yml
Labels: automation, Team:Automation, backport-8.x

#15198 benchmarks: clean up infra logs
  testing/infra/terraform/modules/ec_deployment/scripts/enable_features.tftpl
Labels: backport-8.x

#15216 internal/beater/config: fix 32-bit arch overflow
  changelogs/head.asciidoc
  internal/beater/config/agentconfig.go
Labels: backport-8.x

#14959 apm-server: remove ubi support for main (9.0)
  packaging.mk
Labels: backport-skip

#15218 ci: clean up infra logs II
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/infra/terraform/modules/ec_deployment/outputs.tf
  testing/infra/terraform/modules/ec_deployment/scripts/secret_token.tftpl
Labels: backport-8.x

#15217 ci(dra): support qualifier for the main branch
  .buildkite/scripts/dra.sh
  Makefile
  go.mk
  internal/beatcmd/beat.go
  internal/beatcmd/beat_test.go
  internal/beatcmd/version.go
  internal/beater/api/mux.go
  internal/beater/api/mux_root_test.go
  internal/beater/beater.go
  internal/beater/processors.go
  internal/elasticsearch/client.go
  internal/kibana/client.go
  internal/version/settings.go
Labels: automation, Team:Automation, backport-8.x

#15274 ci(dra): skip snapshots with qualifier and run in parallel
  .buildkite/package.yml
  .buildkite/scripts/dra.sh
Labels: backport-8.x

#15276 ci(dra): fix Vault variables
  .buildkite/scripts/dra.sh
Labels: backport-8.x

#15278 ci(dra): version should not include the qualifier
  .buildkite/scripts/dra.sh
  Makefile
Labels: automation, backport-8.x

#14935 functionaltests: add first test case
  .github/workflows/functional-tests.yml
  functionaltests/8_15_test.go
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/main.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/outputs.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/tags.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/terraform.tf
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/vars.tf
  functionaltests/go.mod
  functionaltests/go.sum
  functionaltests/internal/esclient/client.go
  functionaltests/internal/esclient/config.go
  functionaltests/internal/gen/generator.go
  functionaltests/internal/terraform/logger.go
  functionaltests/internal/terraform/runner.go
  functionaltests/internal/terraform/var.go
  functionaltests/main_test.go
  functionaltests/utils_test.go
Labels: backport-8.x

#15288 ci(release): run DRA for main/staging only if `ELASTIC_QUALIFIER` is set
  .buildkite/scripts/dra.sh
Labels: backport-8.x

#15303 terraform: add tags module
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/main.tf
  testing/cloud/main.tf
Labels: backport-8.x

#15296 ci(benchmarks): increase role-duration AWS
  .github/workflows/benchmarks.yml
Labels: backport-8.x

#15319 github-actions(pre-commit): detect merge conflicts and shebangs
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: automation, backport-7.17, backport-8.x, backport-8.17

#15338 benchmarks: chopm apm_secret_token
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-8.x

#15337 terraform: support TBS in standalone_apm_server
  testing/benchmark/main.tf
  testing/benchmark/terraform.tfvars.example
  testing/benchmark/variables.tf
  testing/infra/terraform/modules/standalone_apm_server/README.md
  testing/infra/terraform/modules/standalone_apm_server/apm-server.yml.tftpl
  testing/infra/terraform/modules/standalone_apm_server/elastic-agent.yml.tftpl
  testing/infra/terraform/modules/standalone_apm_server/main.tf
  testing/infra/terraform/modules/standalone_apm_server/variables.tf
Labels: backport-8.x

#15349 smoke tests: setup tf action explicitly
  .github/workflows/benchmarks.yml
  .github/workflows/smoke-tests-ess.yml
  .github/workflows/smoke-tests-os.yml
  testing/infra/terraform/modules/ec_deployment/deployment.tf
  testing/smoke/managed/main.tf
  testing/smoke/supported-os/main.tf
Labels: backport-8.x

#15353 tf: fix ec_deployment terraform module
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-8.x

#15357 TF: restore explicit tags for apm_standalone module
  testing/benchmark/main.tf
  testing/infra/terraform/modules/moxy/main.tf
  testing/infra/terraform/modules/moxy/variables.tf
  testing/infra/terraform/modules/standalone_apm_server/main.tf
  testing/infra/terraform/modules/standalone_apm_server/variables.tf
  testing/smoke/managed/main.tf
  testing/smoke/supported-os/main.tf
Labels: backport-8.x

#15328 pre-commit: fix check failures
  .pre-commit-config.yaml
  packaging/files/linux/apm-server.sh
  packaging/files/linux/postinstall.sh
  packaging/files/linux/preinstall.sh
  script/build_apm_docs.sh
  script/intake-receiver-version.sh
  testing/docker/elastic-agent/build.sh
  testing/smoke/lib.sh
  testing/smoke/os_matrix.sh
  testing/smoke/test_supported_os.sh
Labels: backport-7.x, backport-8.x, backport-8.17

#15342 ci(terraform): add `expiration_date` tags to currentime+1day
  testing/infra/terraform/modules/tags/output.tf
Labels: backport-8.x

#15356 functionaltests: restart Integrations Server after ingestion
  functionaltests/8_15_test.go
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/outputs.tf
  functionaltests/go.mod
  functionaltests/go.sum
  functionaltests/internal/ecclient/client.go
  functionaltests/internal/gen/generator.go
  functionaltests/main_test.go
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-8.x

#15380 Always rewrite timestamps and IDs in run-benchmark
  testing/benchmark/Makefile
Labels: backport-8.x

#15378 [apmbench] Report intake events per second
  systemtest/benchtest/expvar/expvar.go
  systemtest/benchtest/expvar/metrics.go
  systemtest/benchtest/main.go
  systemtest/benchtest/main_test.go
Labels: backport-8.x

#15350 dra: use a google bucket that contains the elastic qualifier
  .buildkite/hooks/pre-command
  .buildkite/scripts/dra.sh
  .buildkite/scripts/package.sh
  .buildkite/scripts/utils.sh
Labels: backport-8.x

#15383 Fix typo in TBS sample rate in standalone_apm_server
  testing/infra/terraform/modules/standalone_apm_server/apm-server.yml.tftpl
  testing/infra/terraform/modules/standalone_apm_server/elastic-agent.yml.tftpl
Labels: backport-8.x

#15329 ci(major-release): support run major release `[0-9]+.0.0`
  .github/workflows/prepare-release/action.yml
  .github/workflows/run-major-release.yml
  dev_docs/RELEASES.md
  release.mk
Labels: backport-8.x

#15404 tf: larger default volume size if TBS is enabled
  testing/benchmark/main.tf
Labels: backport-8.x

#15410 tf: default volume type to gp3
  testing/benchmark/variables.tf
Labels: backport-8.x

#15416 Fix clearscroll request fmt string
  internal/agentcfg/elasticsearch.go
  internal/sourcemap/metadata_fetcher.go
Labels: backport-8.x

#15447 pgo: export only explictly and reduce pgo cadence
  .github/workflows/benchmarks.yml
Labels: backport-8.x

#15235 TBS: Replace badger with pebble
  NOTICE.txt
  changelogs/head.asciidoc
  go.mod
  go.sum
  internal/beater/config/config_test.go
  internal/beater/config/sampling.go
  internal/beater/monitoringtest/opentelemetry.go
  x-pack/apm-server/main.go
  x-pack/apm-server/main_test.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/eventstorage/badger.go
  x-pack/apm-server/sampling/eventstorage/doc.go
  x-pack/apm-server/sampling/eventstorage/logger.go
  x-pack/apm-server/sampling/eventstorage/partition_rw.go
  x-pack/apm-server/sampling/eventstorage/partitioner.go
  x-pack/apm-server/sampling/eventstorage/partitioner_test.go
  x-pack/apm-server/sampling/eventstorage/pebble.go
  x-pack/apm-server/sampling/eventstorage/pebble_test.go
  x-pack/apm-server/sampling/eventstorage/prefix.go
  x-pack/apm-server/sampling/eventstorage/prefix_test.go
  x-pack/apm-server/sampling/eventstorage/rw.go
  x-pack/apm-server/sampling/eventstorage/rw_test.go
  x-pack/apm-server/sampling/eventstorage/sharded.go
  x-pack/apm-server/sampling/eventstorage/sharded_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_manager.go
  x-pack/apm-server/sampling/eventstorage/storage_manager_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_manager_test.go
  x-pack/apm-server/sampling/eventstorage/storage_test.go
  x-pack/apm-server/sampling/eventstorage/storage_whitebox_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_bench_test.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.x

#15451 TBS: fix race condition in dynamic trace group removal
  x-pack/apm-server/sampling/groups.go
  x-pack/apm-server/sampling/groups_test.go
Labels: backport-8.x

#15485 mergify: remove backport-8.x enforcement
  .mergify.yml
Labels: backport-skip

#15488 TBS: make storage_limit follow processor lifecycle; update TBS processor config
  x-pack/apm-server/main.go
  x-pack/apm-server/sampling/config.go
  x-pack/apm-server/sampling/config_test.go
  x-pack/apm-server/sampling/eventstorage/rw.go
  x-pack/apm-server/sampling/eventstorage/rw_test.go
  x-pack/apm-server/sampling/eventstorage/storage_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_manager.go
  x-pack/apm-server/sampling/eventstorage/storage_manager_bench_test.go
  x-pack/apm-server/sampling/eventstorage/storage_manager_test.go
  x-pack/apm-server/sampling/processor.go
  x-pack/apm-server/sampling/processor_test.go
Labels: backport-8.x, backport-9.0

#15492 TBS: log a warning with error field on processing trace failed
  x-pack/apm-server/sampling/processor.go
Labels: backport-8.x, backport-8.18, backport-9.0

#15496 TBS: fix log formatting
  x-pack/apm-server/sampling/eventstorage/rw.go
Labels: backport-8.x, backport-9.0
