Repository elastic/apm-server, pull requests merged in 2025-08, with the labels that each got.

#17948 refactor: replace NewRegistry with safer GetOrCreateRegistry
  internal/beatcmd/beat.go
  internal/beater/beater.go
  internal/beater/beater_test.go
Labels: backport-8.19, backport-9.1

#18000 iserver-test: Revert temp fix for fleet server issue
  integrationservertest/internal/gen/generator.go
Labels: backport-skip

#18105 changelog: Update 8.19.1 entry
  changelogs/8.19.asciidoc
Labels: backport-skip

#18088 Changelog: Add notes for 9.1.2 release
  docs/release-notes/index.md
Labels: backport-9.1

#17753 iserver-test: Auto generate upgrade path
  .github/workflows/generate-bc-upgrade-paths/action.yml
  .github/workflows/generate-bc-upgrade-paths/bc.sh
  .github/workflows/generate-upgrade-paths/action.yml
  .github/workflows/integration-server-test.yml
  .github/workflows/setup-integration-server-test/action.yml
  Makefile
  integrationservertest/README.md
  integrationservertest/internal/ech/client.go
  integrationservertest/internal/ech/client_test.go
  integrationservertest/internal/ech/version.go
  integrationservertest/internal/ech/version_test.go
  integrationservertest/internal/ech/versions_cache.go
  integrationservertest/internal/gen/generator.go
  integrationservertest/main_test.go
  integrationservertest/scripts/genpath/main.go
  integrationservertest/scripts/genpath/versions_bc.go
  integrationservertest/scripts/genpath/versions_snapshot.go
  integrationservertest/setup.go
  integrationservertest/standalone_test.go
  integrationservertest/upgrade-config.yaml
  integrationservertest/upgrade_test.go
Labels: backport-skip

#18278 iserver-test: Increase timeout
  Makefile
Labels: backport-skip

#18304 add release notes 9.0.6
  docs/release-notes/index.md
Labels: backport-9.0

#18311 Add 9.1.3 changelog
  docs/release-notes/index.md
Labels: backport-9.1

#18371 9.1: Update version
  cmd/intake-receiver/version.go
  internal/version/version.go
Labels: backport-skip, release
