Repository elastic/apm-server, pull requests merged in 2025-02, with the labels that each got.

#15544 docs: Add back changelog for missing metrics
  changelogs/8.15.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#15497 functionaltests: filter unwanted logs
  functionaltests/8_15_test.go
  functionaltests/internal/asserts/doc.go
  functionaltests/internal/asserts/es_logs.go
  functionaltests/internal/asserts/es_logs_test.go
Labels: backport-8.x

#15571 docs: Remove incorrect entry in 8.18 changelog
  changelogs/8.18.asciidoc
Labels: backport-skip

#15551 kibana: add x-elastic-product-origin header to the client
  internal/kibana/client.go
  internal/kibana/client_test.go
Labels: backport-8.x

#15379 Bump apm-perf in systemtest and tools
  systemtest/benchtest/clients.go
  systemtest/benchtest/main.go
  systemtest/cmd/apmbench/main.go
  systemtest/go.mod
  systemtest/go.sum
  tools/go.mod
  tools/go.sum
Labels: backport-8.x, backport-8.18, backport-9.0

#15654 tf: fix benchmarking standalone apm to use x86_64 AMI by default
  testing/benchmark/main.tf
  testing/infra/terraform/modules/standalone_apm_server/main.tf
Labels: backport-9.0

#15197 changelog: document apm_user role removal breaking change
  changelogs/head.asciidoc
Labels: backport-skip

#15339 Update benchmark warmup time
  .github/workflows/benchmarks.yml
  testing/benchmark/README.md
Labels: backport-8.x

#15664 TBS: update pebble options for performance
  x-pack/apm-server/sampling/eventstorage/pebble.go
Labels: backport-9.0

#15733 benchmark: increase worker instance size
  testing/benchmark/system-profiles/8GBx1zone.tfvars
Labels: backport-8.18, backport-9.0

#15426 github-action: Add AsciiDoc freeze warning
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: backport-8.x, backport-9.0

#15805 functionaltests: disable scheduled run
  .github/workflows/functional-tests.yml
Labels: backport-skip

#15820 CI(smoketest): fetch previous version on first minor
  testing/smoke/basic-upgrade/test.sh
  testing/smoke/lib.sh
Labels: backport-skip

#15882 docs: update docs versions to 7.17.29
  apmpackage/apm/changelog.yml
  apmpackage/apm/manifest.yml
  cmd/version.go
Labels: backport-skip

#15818 functionaltests: replace flush metric mechanism
  .github/workflows/ci.yml
  .github/workflows/functional-tests.yml
  functionaltests/8_15_test.go
  functionaltests/TestUpgrade_8_15_4_to_8_16_0/outputs.tf
  functionaltests/go.mod
  functionaltests/go.sum
  functionaltests/internal/gen/generator.go
  functionaltests/internal/kbclient/client.go
  functionaltests/internal/kbclient/client_test.go
  functionaltests/internal/kbclient/testdata/fixtures/TestGetPackagePolicy.yaml
  functionaltests/internal/kbclient/testdata/fixtures/TestUpdatePackagePolicy.yaml
  testing/infra/terraform/modules/ec_deployment/outputs.tf
Labels: backport-skip

#15883 feat: purge more noisy kerberos libs from docker image
  packaging/docker/Dockerfile
Labels: backport-8.16, backport-8.17, backport-8.18

#15885 Run smoke-tests-ess for 8.16 and 8.17
  .github/workflows/smoke-tests-ess.yml
Labels: backport-skip

#15902 functionaltest: Fix ignored error
  functionaltests/8_15_test.go
  functionaltests/internal/esclient/client.go
  functionaltests/internal/kbclient/client.go
  functionaltests/utils_test.go
Labels: backport-skip

#15884 fix: label terraform ECH deployments
  testing/smoke/main.tf
  testing/smoke/managed/main.tf
  testing/smoke/supported-os/main.tf
Labels: backport-active-9, backport-active-8
